- data/factorio/mod/LICENSE.md
- data/factorio/mod/info.json
- data/factorio/mod_template/control.lua
- Adds buffering of received free-samples items.
- Players with a full inventory will receive new items as space becomes
available.
- Players who do not yet exist in the world will receive all free samples
upon joining.
- When receiving new technologies, announce the technology BEFORE marking
it as researched so that it appears before its free samples in the log.
- If receiving a half-stack of free samples, use math.ceil on the division
in case a mod uses an odd number as a stack size... or a stack size of 1
- Handle free_samples logic in the Lua side rather than as part of a Jinja
template.  This makes this hopefully more adaptable to a future setup
where all the rando information is shipped as startup settings.
> Overhauls control.lua template

- test/minecraft/TestMinecraft.py
- worlds/minecraft/Items.py
- worlds/minecraft/Options.py
- worlds/minecraft/__init__.py
> Added option for MC bee traps

- Options.py
- data/factorio/mod_template/data.lua
- playerSettings.yaml
- requirements.txt
- worlds/factorio/Options.py
- worlds/factorio/__init__.py
- worlds/factorio/requirements.txt
generate_early: split world_gen into basic and advanced map settings for mod generation
> Factorio: use schema for world_gen, allow setting pollution values

- LttPClient.py
Adds LttP client support for multiple SNES devices (actual consoles or emulators) being connected to a single QUsb2Snes instance.
If more than one SNES is present, lists the connected SNESes as e.g.:
```
[SNES]: Found 2 SNES devices; connect to one with /snes <address> <device number>:
1 - <device name>
2 - <device name>
```
Retains current default behavior of automatically connecting if a single SNES device is present (at the default SNES address, or a specific address given by the `--snes` command line switch).
> LttP: support multiple connected SNESes

- WebHostLib/templates/genericTracker.html
- WebHostLib/tracker.py
Adding an order received column for the generic tracker so you can sort by it and see the most recent items received. Progressive items will have the number of the last one acquired. Handles new games where item list doesn't exist yet, and tested with multiple games.
> New column for generic tracker

- WebHostLib/static/styles/ootTracker.css
- WebHostLib/templates/ootTracker.html
- WebHostLib/tracker.py
- worlds/oot/__init__.py
Adds a web tracker for Ocarina of Time based on the Minecraft tracker. The first commit was a change required to make those items correctly show up on the webtracker, as those two locations are deleted when the setting is turned on.
> Ocarina of Time web tracker

- worlds/alttp/Rom.py
- worlds/alttp/Rules.py
- Fixed a bug where the Swamp Palace Big Key would not be allowed in the first chest of Swamp.
- Fixed a bug where HMG dungeon exits would not be fixed in crossed/crossed-dungeons entrance shuffle.
> Hybrid Major Glitches fixes

- worlds/oot/Options.py
- worlds/oot/__init__.py
- Fixed a bug where shopsanity + closed forest would cause frequent generation failures due to inaccessible Deku Shield
- Reenabled Master Quest dungeon option (requires updated Lua script from Z5Client repo)
> Ocarina of Time fixes

- worlds/ror2/Items.py
- worlds/ror2/Options.py
- worlds/ror2/Rules.py
- worlds/ror2/__init__.py
Fixed lunartic so it will still generate all lunar items even if the player disables lunar items. Added all scraps to the logical requirements pool and brought back the scraps only preset. Adjusted a few preset weights.
> Risk of Rain 2: logic updates

- worlds/generic/Rules.py
This fixes an issue raised by the inclusion of Master Quest dungeons. Since MQ dungeons causes some locations to not always be present in an OoT game, location exclusion may fail if the relevant location does not exist due to being located in the wrong dungeon type. This change prevents that error from occurring while still producing an error message for invalid exclusion settings, including if the player tries to exclude a location without an ID value.
> Exclusion bugfix

- MultiServer.py
As part of the aliased names, marks players with a pair of asterisks if they have completed their goal to make it clear who has and hasn't beaten their goal at all times.
> Marks player names with a pair of asterisks if they have completed their goal

- test/minecraft/TestAdvancements.py
- worlds/minecraft/Locations.py
- worlds/minecraft/Rules.py
- worlds/minecraft/__init__.py
- Egg shards will no longer require more than are placed
- The Overpowered advancement now logically requires access to a bastion remnant and the ability to mine the gold blocks found there. It is consequently no longer a hard-pool advancement.
> Minecraft fixes

- worlds/oot/__init__.py
Was relying on self.nonadvancement_items, now checks if that attribute is present
> Fix get_item command in OOTWorld

- SNIClient.py
Causes reliability issues when relative path is used, see [subprocess doc](https://docs.python.org/3/library/subprocess.html#subprocess.Popen)
In my case, it did not start SNI at all.
> Use absolute path when starting SNI

- worlds/timespinner/Locations.py
- worlds/timespinner/Regions.py
- worlds/timespinner/__init__.py
Fixed some placement logics regarding gyre archives & military fortress
Renamed 'Transition chest #' to 'Gyre chest #'
> [Timespinner] Fixed some placement logics

- worlds/timespinner/Locations.py
LoreChecks was missing double-jump checks on "Memory - Way Up There (Final Circle)" and "Journal - Near Bottom Struggle Juggle (Mission Findings)"
> Timespinner: Fix missing double-jump checks for LoreChecks locations

- worlds/alttp/Options.py
I think quadrupled prices will be plenty expensive, and this will stop people who pick "random" from getting 9999 priced items and potentially locking their multiworld behind absurd rupee grinds
> LTTP - Cap item prices at 4x

- WebHostLib/static/styles/supermetroidTracker.css
Improve accessibility by changing text to white and page background to black.
Original contrast ratio was 3.88, and new contrast ratio is 5.4
> Increase contrast of SM tracker

- CommonClient.py
- MultiServer.py
- WebHostLib/tracker.py
- docs/network protocol.md
* Tracker tag will receive all items via server (including local)
* TextOnly tag will receive no items
* TextClient sends TextOnly tag
* precollected items / start_inventory does not get an "Order received" number anymore
* local items do always get an "Order received" number now
* multisave changed, includes version number now, upgrade works for games (not trackers)
> Add per-client remote_item settings + TextOnly Tag

- Fill.py
- WebHostLib/static/assets/tutorial/archipelago/plando_en.md
Add True option for item count to place the number of that item that is in the item pool.
Prioritize plando blocks by location count minus item count, so that the least flexible blocks are handled first to increase likelihood of success.
True and False for Force option are coming in as bools instead of strings, so that had to be accounted for.
Several other bug fixes.
> Item Plando updates

- CommonClient.py
- FF1Client.py
- FactorioClient.py
- MultiServer.py
- SNIClient.py
- docs/network protocol.md
* adds new Connect and ConnectUpdate argument `items_handling: int`. Passing `null` or not sending it loads them from multidata, which is set by world for backwards-compatibility, but is deprecated.
* adds new ConnectionRefused reason `InvalidItemsHandling`
> Move remote_items and _start_inventory from world to client

- WebHostLib/static/assets/gameInfo/Super Mario 64 EX.md
- WebHostLib/static/assets/tutorial/sm64ex/setup_en.md
- WebHostLib/static/assets/tutorial/tutorials.json
- worlds/sm64ex/Items.py
- worlds/sm64ex/Locations.py
- worlds/sm64ex/Options.py
- worlds/sm64ex/Regions.py
- worlds/sm64ex/Rules.py
- worlds/sm64ex/__init__.py
I wanted some variation from just testing V6 the whole time...
This uses [my fork of sm64ex](https://github.com/N00byKing/sm64ex), branch `archipelago`, which is just [sm64ex](https://github.com/sm64pc/sm64ex) and the Archipelago Integration. It communicates the same way as the V6 Integration does.
Stars and Caps are randomized
Due to copyright restrictions, I can't provide finished builds of the client.
However, there exist launchers which compile everything for you.
I've modified one of them to work with my AP build of sm64ex: [sm64pclauncher](https://github.com/N00byKing/sm64pclauncher). Builds available. MSYS still needs to be installed manually.
Compiling on Linux:
- Required packages: `cmake`, `sdl2`, `glew`, `python`
- Clone Repo recursively, checkout branch `archipelago`
- Put …
> Add Super Mario 64 (PC Port) to Archipelago

- Fill.py
- test/general/TestFill.py
While troubleshooting the v6 generation problems, I ran into an issue where runs with the same seed produced different results. I tracked this down to v6 adding items to the item pool in a random way (iterating over a set). This change makes makes the fill algorithm more robust to how worlds add locations and items to the pool.
> Sort before distribute to preserve seed integrity

- Fill.py
- test/general/TestFill.py
This attempts to make the item swapping logic smarter by not allowing it to swap out important early progression items. If removing an item from a location will reduce the number locations that are currently accessible, it will no longer perform that swap.
> Don't swap items that reduce access

- MultiServer.py
from doubling received_items that happened when moving from world-based to client-based remote_items
Basing this solely on received_items gives the most accurate message regarding what was in the save (ignoring what was in multidata).
>  Fix wrong message when loading apsave

- worlds/oot/EntranceShuffle.py
- worlds/oot/Items.py
- worlds/oot/__init__.py
- ER options now affect closed forest correctly
- ER generation rate improved when spawn positions are randomized
- Ice traps now considered trap items internally
- Hints now consider regions containing nonexcluded items to be not barren
- Farore's Wind made a nonexcluded item if the relevant trick is off (instead of always progression)
> Ocarina of Time updates

- MultiServer.py
I've started many an async game with my siblings after forgetting to go over my host.yaml settings and started with unwanted settings, and find after the server shuts down due to inactivity every night (or I restart after fixing bugs with other things I'm working on) the options are reset to the initial host.yaml settings.
This will save any changes to game options so that they will not reset after restarting.
> Save game options with server save data

- Options.py
Options: change "random" prevention to assert, so it doesn't get checked in compiled version, as it's a source-code-time issue.
> Options: implement additional assert checking for duplicate option ID

- .github/workflows/build.yml
- Generate.py
- Launcher.py
- LttPAdjuster.py
- Patch.py
- SNIClient.py
- Utils.py
- WebHost.py
- WebHostLib/lttpsprites.py
- setup.py
- worlds/alttp/Rom.py
- worlds/oot/Rom.py
- worlds/sm/Rom.py
- worlds/smz3/Rom.py
- worlds/soe/Patch.py
* Launcher.py - a launcher for the various components
* setup.py rewrite
* build_exe: added linux compatibility
* use command classes
* added bdist_appimage command
* imports data from Launcher.py
* github build action for Linux (AppImage and .tar.gz)
* most stuff can be run from a read-only dir on linux by using ~/Archipelago - windows-support still missing and will fall back to old behaviour
* SNIClient shows an error if launching it fails (we don't capture the message yet)
> Setup, Launcher, Linux Support

- Generate.py
Makes absolute paths for yamls work
This breaks downloads of http:// and ftp://, but nobody should use that
Sorry for breaking that. Someone tested on windows, but i guess not Generate.exe :S
> Generate: fix windows support

- Generate.py
utf-8-sig will fallback to non-sig automatically
> Generate: don't fail on marked utf-8 files

- CommonClient.py
Don't run the `console_loop` task when steam overlay is being used because it would freeze steam on Linux (and possibly Mac).
Explanation: steam uses the LD_PRELOAD environment variable to force-load DLLs that overwrite OpenGL functions, so that as soon as an OpenGL context is created steam can activate its overlay. This seems to be broken when a a thread waits on stdin, so we detect that "gameoverlayrenderer" (the name of the DLL) was preloaded and disable said task.
> Clients: don't use stdin when loading steam overlay

- BaseClasses.py
- Options.py
use `NumericOption` class inheriting from `numbers.Integral` instead of `int`
also `Range` can sometimes take text like:
"high": high end of range
"low": low end of range
~"true", "on": default if it exists, otherwise high end of range~
~"false", "off": zero if zero is the low end~
These are the typing changes I made to deal with issues in https://github.com/ArchipelagoMW/Archipelago/pull/356
> Options.py typing

- CommonClient.py
- Main.py
- MultiServer.py
- docs/api.md
- docs/network protocol.md
- worlds/AutoWorld.py
- worlds/alttp/__init__.py
- worlds/factorio/__init__.py
- worlds/meritous/__init__.py
- worlds/raft/__init__.py
- worlds/rogue-legacy/__init__.py
- worlds/sm/__init__.py
- worlds/smz3/__init__.py
- worlds/soe/__init__.py
- worlds/subnautica/__init__.py
* `AutoWorld.World`s can set required_server_version and required_client_version properties. Drop `get_required_client_version()`.
* `MultiServer` will set an absolute minimum client version based on its capability (protocol level).
* `IgnoreVersion` tag is replaced by using `Tracker` or `TextOnly` with empty or null `game`.
* Ignoring game will also ignore game's required_client_version (and fall back to server capability).
> Core: change how required versions work, deprecate IgnoreGame

- worlds/hk/__init__.py
items are marked as advancement if they have an additional effect, so instead of a lookup we can just refer to a bool that's already local as a quick pre-check
> HK: slight optimization

- WebHostLib/templates/supportedGames.html
- docs/api.md
- worlds/AutoWorld.py
- worlds/minecraft/__init__.py
added option for a World to supply a bug report URL to the user, most likely a GitHub issue page, but can be any URL.
Added the actual link to the `/games` endpoint. but I am open to suggestions on other places to put it.
> Add bug report link to WebWorld

- WebHostLib/static/assets/tutorial/Archipelago/advanced_settings_en.md
- WebHostLib/static/assets/tutorial/Archipelago/triggers_en.md
- WebHostLib/static/assets/tutorial/ChecksFinder/checksfinder_en.md
- WebHostLib/static/assets/tutorial/Final Fantasy/multiworld_en.md
- WebHostLib/static/assets/tutorial/Minecraft/minecraft_en.md
- WebHostLib/static/assets/tutorial/SMZ3/multiworld_en.md
- WebHostLib/static/assets/tutorial/Secret of Evermore/multiworld_en.md
- WebHostLib/static/assets/tutorial/Super Metroid/multiworld_en.md
The lowercase `a` in the link in this Markdown file leads to a 404.  This fixes the link.  Thanks to CelestialPanda for the heads up.
> Fix lowercase letter in link leading to 404

- WebHostLib/generate.py
Fixed two distinct bugs.
* remaining_mode was not disabled in race mode like it should have been.
* remaining_mode was derived from the forfeit_mode setting, with the form entered value for remaining_mode being ignored entirely.
> Fix remaining_mode on webhost.

- worlds/timespinner/Options.py
This PR is to give Timespinner's option selection parity with the local randomizer. This does not affect AP item placement, but these settings can be used by Timespinner players during AP runs without conflict. (changing local filler drops which are not in logic)
Companion to https://github.com/JarnoWesthof/TsRandomizer/pull/67 , requested by @JarnoWesthof
> Timespinner: Options to Support Loot Randomization

- test/programs/TestGenerate.py
fixes a warning on some systems
> Test: add missing cleanup in TestGenerate

- BaseClasses.py
- Utils.py
- docs/api.md
- worlds/AutoWorld.py
typing, mostly in `AutoWorld.py`
includes a bug fix (that was found by static type checking)
in `get_filler_item_name`
> typing, mostly in AutoWorld.py

- worlds/witness/WitnessItems.txt
- worlds/witness/locations.py
1. Junk items weren't generating correctly due to a naming discrepancy. This is now fixed.
2. Small oversight: A difficult optional panel was in the "general" category, which is supposed to only include required and/or easy puzzles.
3. Jarno made a major addition to the client which needs a change in generation to not break things. Specifically, it requires that the location list includes no panels where using multiple solutions on that same panel is *required* in some way.
> Witness Hotfixes

- worlds/factorio/Options.py
* With `width` and `height` all keys for 'basic' map gen should be defined now. (No reason to allow arbitrary keys.)
* Remove all limitations from `property_expression_names` because it has a lot of "sub keys" that could could also be extended through other mods.
As a side-note, setting `basic.cliff_settings.cliff_elevation_0 = 99` seems to already (mostly?) disable cliffs; no need to go into property expressions.
> Factorio: mapgen update

- MultiServer.py
- WebHostLib/api/generate.py
- WebHostLib/check.py
- WebHostLib/generate.py
- WebHostLib/static/styles/generate.css
- WebHostLib/templates/generate.html
* Add item_cheat control instead of being always enabled.
* add server_password to allow for !admin /server_commands from any text client, therefore allowing server console hand-off to another person.
* Clearly indicate that item_cheat and remaining_mode are disabled in Race mode.
> Add options to generate page

- worlds/smz3/TotalSMZ3/Regions/Zelda/PalaceOfDarkness.py
Per discussion in #bug-reports
Original logic from SMZ3 is:
`
items.KeyPD >= (GetLocation("Palace of Darkness - Harmless Hellway").ItemIs(KeyPD, World) ?
(items.Hammer && items.Bow && items.Lamp) || config.Keysanity ? 4 : 3 :
(items.Hammer && items.Bow && items.Lamp) || config.Keysanity ? 6 : 5))
`
I believe these parentheses are needed to correctly replicate this logic
@lordlou
> [SMZ3] Fix Harmless Hellway logic

- worlds/timespinner/Options.py
- Added a new Option toggle for Timespinner damage rando -- instead of just on/off there are presets and also "Manual"
- If "Manual" is chosen it reads from the new DamageRandoOverrides attribute, allowing for granular setting of probabilities for each orb to be buffed, nerfed, or unaffected
> Adding damage rando v2 options to timespinner rando

- Main.py
From: 
```
Found World Types:
A Link to the Past      : 144 Items | 287 Locations
Item IDs:        2 -      180 | Location IDs:    59758 -  4194341
ArchipIDLE              : 300 Items | 100 Locations
Item IDs:     9000 -     9299 | Location IDs:     9000 -     9099
ChecksFinder            :   3 Items |  25 Locations
Item IDs:    80000 -    80002 | Location IDs:    81000 -    81024
Factorio                : 222 Items | 183 Locations
Item IDs:   131070 -   131292 | Location IDs:   131072 -   131254
Final Fantasy           : 192 Items | 255 Locations
Item IDs:      256 -      498 | Location IDs:      257 -      767
Hollow Knight           : 249 Items | 740 Locations
Item IDs: 16777216 - 16777464 | Location IDs: 16777216 - 16777955
Meritous                :  23 Items | 104 Locations
Item IDs: …
```
> Main: compress world type output log

- Options.py
This is an amendment to PR https://github.com/ArchipelagoMW/Archipelago/pull/504
---
"false" only makes sense if:
- the bottom of the range is 0
- "true" also makes sense
---
"true" only makes sense if:
- there is a default that isn't 0
- "false" also makes sense
---
so the conditions for both "true" and "false" are:
- the bottom of the range is 0
- there is a default that isn't 0
---
Since PR https://github.com/ArchipelagoMW/Archipelago/pull/504 was specifically to address variable progression balancing, both of those conditions hold, so this shouldn't affect anything else unless someone threw something in in the short time since 504 was accepted.
> only accept true and false for a range if they make sense

- Utils.py
and can be skipped in certain cases for speed of startup
> Core: tkinter import may only be needed for type-info

- worlds/alttp/__init__.py
- worlds/archipidle/__init__.py
- worlds/ff1/__init__.py
- worlds/hk/__init__.py
- worlds/minecraft/__init__.py
- worlds/oot/__init__.py
- worlds/rogue-legacy/__init__.py
- worlds/sm/__init__.py
- worlds/sm64ex/__init__.py
- worlds/soe/__init__.py
- worlds/spire/__init__.py
Implements the get_filler_item_name function for various games. Junk items are determined with the following methods:
ALTTP: From the "extras" lists for the specified item pool difficulty
ArchipIDLE: Any random item
FF1: 50% Heal, 25% Pure, 25% Soft
Hollow Knight: Geo Rock-Default
Minecraft: pulls from the junk weights used to normally fill out the item pool with junk
OoT: results of get_junk_item()
Rogue Legacy: random item from misc_items_table
Super Metroid: Nothing
Super Mario 64: 1Up Mushroom
Secret of Evermore: random item from the Ingredients item name group
Slay the Spire: 60% Card Draw, 40% Relic
I'd be happy to make any adjustments / remove sections if any maintainers, etc do not like these methods
> Implement get_filler_item_name for various games

- Starcraft2Client.py
Added functionality to switch between and'ing and or'ing mission requirements. Not as useful in Wings of Liberty since only All In requires multiple missions, but will be used down the line when Heart of the Swarm and Legacy of the Void gets added.
> SC2: Changed All In to require either previous mission instead of both

- FF1Client.py
Specifically check for an empty string and give a helpful error message
> Adding in error message for FF1 if player name is empty in the ROM

- SNIClient.py
Since it is impossible to determine which dungeon to reveal, like it is impossible to determine which prize to auto-collect if the boss itself was collected, without reading the rom,  I have to block collection of Sahasrahlah like I do with blocking of boss items.
> Block collection of Sahasrahlah.

- WebHostLib/templates/generate.html
Just a simple, "this is what it does, go see this guide for more info." basically for those not familiar with it, but are curious what it does.
> WebHost: Add tooltip for Plando Options on the Generate page.

- worlds/sm64ex/Options.py
- worlds/sm64ex/__init__.py
- worlds/v6/Options.py
- worlds/v6/__init__.py
I was asked a while ago whether or not I was OK with this change, but I guess whoever asked never implemented it.
> v6,sm64ex: Use standard Death Link option name

- worlds/sc2wol/docs/en_Starcraft 2 Wings of Liberty.md
Removed some Timespinner copy-pasta in the webhost page and added details on what has been changed in the campaign.
> SC2: Updated webhost details page

- MultiServer.py
- test/general/TestItems.py
- worlds/factorio/__init__.py
Factorio: item *name* group was pointing to IDs instead.
Server: prevent crash when using Event-filled item name group
> Tests: add test to check for typo'd item name group definitions

- Launcher.py
- MinecraftClient.py
- MultiServer.py
- Utils.py
- kvui.py
- setup.py
Sorry to merge 3 things into one PR
* cx_Freeze 6.11 requires changes to the build commands. Because of the `>=6.10` we had previously this will break current setup.py, which is required to use/test the AppImage. Commit# 1e28a3d replaces commit# f9b12b5
* Better AppImage compatibility:
* the start script did not work for Linux flavours with a shell that is strictly posix compliant
* we now package one more library, that may be too different between build and user OS
* Better UX for Launcher.py and MultiServer.py:
* kvui.MessageBox: this is required to show errors in Launcher.py. I also added a messagebox function to Utils.py that either uses kivy or falls back to tkinter, so we can use a single function call and get nice UX
* Utils.open_filename: tk does not look native on Linux, so we …
> Better UX, AppImage and setup.py

- CommonClient.py
- FactorioClient.py
- kvui.py
* Fix Factorio spamming the console with slot errors
* Implement message boxes for connect errors (applies to all CommonClient-based clients) which may look like
I'm open for more places to add such message boxes. Please let me know.
Currently the text output is unchanged, but I'm for for cutting down the clutter in the text output: it would stop hiding previous messages from users by scrolling the text, and it would force users to posts more complete logs rather than the screenshots we get now. I'd like some feedback on that though.
> Clients: UX improvements

- worlds/alttp/docs/multiworld_de.md
- worlds/alttp/docs/multiworld_en.md
- worlds/alttp/docs/multiworld_es.md
- worlds/alttp/docs/multiworld_fr.md
Docs reference `.bmbp` or `.apbp` instead of `.aplttp`. Updated those references.
Also remove references to Z3 and SNC in English doc, thanks @alwaysintreble 
~~Best of luck with the other langs~~
> ALTTP: Updates to setup documents

- worlds/oot/docs/setup_en.md
More and more people have issues with connecting with OoT because fresh installs of newer versions of Bizhawk show having "Lua+LuaInterface" selected when it actually loads "Nlua+KopiLua" instead until you toggle between the two options. Hopefully adding this bolded note will help new users avoid this problem in the future.
> OOT: Add note about common issue with lua option in the configuration step

- worlds/timespinner/Options.py
Companion to https://github.com/JarnoWesthof/TsRandomizer/pull/81
Adds settings to support Boss Randomization for Timespinner
- BossRando: shuffles the location of bosses
- BossScaling: scales replaced boss stats to match the vanilla locations
- BossHealing: enables/disables heals after random bosses
@Berserker66 @JarnoWesthof
> [Timespinner] Add Boss Randomization Settings

- WebHostLib/options.py
- WebHostLib/templates/options.yaml
- worlds/rogue-legacy/Options.py
Makes some changes to the WebHost to allow game implementations to define `"random"` as the default value for Choice-derived or Toggle-derived options and sets it as the default on Game Settings pages. Also adds it as the default option in the template files.
Example from Rogue Legacy Options.py:
```py
class StartingGender(Choice):
"""
Determines the gender of your initial 'Sir Lee' character.
"""
display_name = "Starting Gender"
option_sir = 0
option_lady = 1
alias_male = 0
alias_female = 1
default = "random"
```
What the default option looks like on the Settings Page:
What the default options look like in the Template file:
```yaml
Rogue Legacy:
starting_gender: # 
sir: 0
lady: 0
random: 50
```
Also works on the weighted settings page:
> WebHost: Allow "random" to be default option for toggles and choices.

- worlds/hk/Items.py
- worlds/hk/Options.py
- worlds/hk/__init__.py
I don't know AP internals very well and haven't extensively tested this yet.  Posting as-is to request feedback.
This all assumes the client behavior if a location isn't randomized is to simply leave it alone.  I _think_ this is the case, but haven't checked yet.
This makes the following changes under `worlds/hk`:
- Add configurable goals (Any, THK, Siblings, Radiance)
- Change base logic to require Opened_Black_Egg_Temple instead of requiring 3 dreamers.  This is future-proof for transition rando, where Black Egg might not have been located yet.
- Add combat logic for THK and Radiance on par with Rando4's boss logic, so itemless HK shouldn't be required.
- Completing a goal different than your assigned one is allowed, provided you meet the combat and item requirements.
- This means you …
> Hollow Knight updates (goals, WP/POP, etc.)

- MinecraftClient.py
* show file open dialog if MinecraftClient is run without arguments
* get rid of `shell=` remains; we don't use strings anymore
* use user_path for forge_dir. This may spam a bit more text, but should behave identical to the old code on windows and from code while allowing to use forge_dir relative to home for read-only installations. Putting an absolute path into host.yaml also still works.
> MinecraftClient: Linux fixes

- worlds/hk/Rules.py
- worlds/hk/templates/RulesTemplate.pyt
This was causing off-by-one errors, which were problematic if e.g. a Grubfather slot wanted all 46 grubs.
> HK: Bugfix shop requirements to be >= rather than >.

- NetUtils.py
This saves between 7 and 15% where compression is unavailable.
> Server: minify cmd json

- Utils.py
format_SI_prefix would break trying to find the next label after Yotta. Any such weakness is now removed. Also converted to use of Decimal to unify float and int handling for convenience.
> remove limit of 1000 Yotta-Joule in EnergyLink

- worlds/sc2wol/docs/setup_en.md
With SC2 only being supported in Windows and macOS, it's unclear that it is actually also able to run with Archipelago in Linux. This PR documents the necessary setup needed to properly run the StarCraft 2 client in Linux through a Wine installation.
> SC2: add Linux setup to tutorial

- worlds/alttp/docs/multiworld_en.md
- worlds/sm/docs/multiworld_en.md
- worlds/smz3/docs/multiworld_en.md
Removed remaining references to SNC in guides. Changed SM and SMZ3 patch file extension references to `.apsm` and `.apsmz3`, respectively
> Updates to ALTTP, SM, and SMZ3 guides

- worlds/sm64ex/Rules.py
I brought this up in #super-mario-64, and the minor consensus is that 100 Coins is "possible", the same way Red Coins is possible.
According to a FAQ online, DDD has 106 coins. That means you are still required to get at least 5 of the red coins in order to get the 100 coin star. If we already have a rule stating the Red Coins require the sub to be removed (by reaching Bowser in the Fire Sea), it should apply to the 100 coins as well.
The consensus on it being "possible" was that it requires a very specific triple jump. There is no "Strict" category for this since it isn't caps/cannons-based, but it is extremely unreasonable to casual play. If you want to sequence break it, go for it, but I don't think it should be expected.
> DDD 100 Coins in Entrance Rando should expect sub removal

- MultiServer.py
literally just a new command to act as a new call for forfeit. Changed the output text when someone releases and collects from/to the multiworld to be more clear.
> multiserver: allow `!release` as an alias for `!forfeit`

- worlds/hk/Options.py
When enabled, choose how incoming deathlinks are handled:
**vanilla**: DeathLink kills you and is just like any other death.  RIP your previous shade and geo.
**shadeless**: DeathLink kills you, but no shade spawns and no geo is lost.  Your previous shade, if any, is untouched.
**shade**: DeathLink functions like a normal death if you do not already have a shade, shadeless otherwise.
Requires an updated client, PR to that repo is also coming.
> HK: Add options for Deathlink.

- worlds/sc2wol/Items.py
ItemClassification commit changed all SC2 never_exclude items into filler items, and all filler items into useful items (except the plus resources items). I am assuming this was in error.
> Revert SC2 item classifications

- worlds/factorio/__init__.py
Managed to find a seed where the non-stackable spidertron remote ended up in the rocket-part recipe, resulting in that seed being impossible to complete.
> Factorio: Fix impossible seeds for rocket-part recipes as well.

- LttPAdjuster.py
- Patch.py
- worlds/alttp/Rom.py
- worlds/sm/Rom.py
- worlds/smz3/Rom.py
Removes term considered offensive from error messages & variable names.
Tested rolling a SM+Z3+SMZ3 multi & genning world roms by running SNIClient on the resulting world patchfiles.
> SNES games: use JPN as abbreviation for Japan/Japanese

- BaseClasses.py
```py
test = ItemClassification.progression_skip_balancing
import timeit
print(timeit.timeit("ItemClassification.progression in test", globals=globals()))
print(timeit.timeit("bool(test & ItemClassification.progression)", globals=globals()))
```
```
0.3143199998885393
1.2014224999584258
```
> BaseClasses: make ItemClassification properties faster

- Fill.py
fill_restrictive pops out one item per player, then goes into a loop trying to place them. If the locations sent into fill_restrictive are exhausted, it will continue trying to fill all the remaining items popped out, and will start trying to swap out previously placed items.
I don't think this was an issue before priority_locations was introduced, as fill_restrictive was expected to never run out of locations. But this can be expected to be a regular occurrence now.
I observed this loop going on for quite some time for a multiworld of just 30 games. I imagine generating an async of 400+ games could lose a lot of time over this.
> Break out of fill loop if locations is empty

- worlds/alttp/docs/multiworld_es.md
- worlds/smz3/docs/multiworld_en.md
The path of the image embedded in LTTP ES language setup guide was not changed when both files were moved in #455 . If any other non-English docs have embeds, those might be worth checking over.
By convenient opportunity I've also removed the mention of RetroArch nightly builds from the SMZ3 setup guide, because RA 1.10.3 was released with the fix for AP SMZ3.
> docs: fix 2 URLs

- worlds/generic/docs/advanced_settings_en.md
some reformatting and cleanup to make advanced settings guide look a bit better. add priority_locations example and fix typos
> advanced guide cleanup

- worlds/sm64ex/Regions.py
- worlds/sm64ex/Rules.py
- worlds/sm64ex/__init__.py
Required to fix THI behaviour.
New Behaviour: THI Tiny / Huge are treated as seperate paintings. When randomized, this also means that two seperate painting can lead to each THI instance, and the two original THI paintings can lead to different courses
> sm64ex: Adapt area_connections slotdata Format

- worlds/factorio/requirements.txt
Addresses bug https://github.com/mark9064/factorio-rcon-py/issues/2 by  specifying working version for now.
> Factorio: specify rcon version

- ChecksFinderClient.py
Found ChecksFinder works easily on Linux as long as the client has the correct path.
Existing exe is fine, just run `wine ChecksFinder.exe`
> ChecksFinder: Linux support via wine

- WebHostLib/static/assets/tutorialLanding.js
- WebHostLib/templates/supportedGames.html
Adds an anchor tag to each "Game" entry in Setup Guides and scrolls to it from the Games page when clicked. Should help reduce the amount of "How do I set up this game?" questions.
> WebHost: Add links to "Setup Guides" in Supported Games page

- worlds/factorio/__init__.py
Encountered a bug earlier where the crafting category can be incorrectly set to crafting, if the recipe gets two fluid ingredients, and it tries to roll in a third one.
> Fixed a crafting category bug related to fluids.

- worlds/witness/WitnessLogic.txt
An unbeatable seed was reported where because of faulty region connections/definitions, the logic (in door randomizer) thought you could go backwards through the mountain all the way up to Same Solution Set & Light Bridge Controller 3, which is impossible (you can only go up to Elevator Discard). 
This is the fix for it
> The Witness: Logic fix (unbeatable seed)

- WebHostLib/options.py
- WebHostLib/static/assets/weighted-settings.js
Now it doesn't output anything... just like all the other `OptionDict`s. Also some more explicit checking of types rather than if they just contain an attribute.
> WebHost: Fix `OptionDict`s that define `valid_keys` from outputting as `[]` on Weighted Settings export.

- MultiServer.py
- Utils.py
- WebHost.py
- WebHostLib/__init__.py
- WebHostLib/autolauncher.py
- WebHostLib/customserver.py
- WebHostLib/misc.py
- WebHostLib/tracker.py
- worlds/meritous/__init__.py
- worlds/sm64ex/__init__.py
- worlds/v6/__init__.py
customserver now has the process host import and collect the static server data, it then gets passed into the Process() call, resulting in pickling and transfer of the required data. As a result, the Process should no longer import and retain memory of all the world objects.
Have not yet looked into the actual memory impact that it has the desired effect.
Have done a bit of !hinting and picking up items on both servers.
Tries to address https://github.com/ArchipelagoMW/Archipelago/issues/856
> WebHost: allow customserver to skip importing worlds subsystem for hosting a Room

- Starcraft2Client.py
Simple command to the client override the difficulty of a missions in a certain seed.  Is not persistent and is local only, will only have the override until the client is closed
> SC2: Added Difficulty Override to Client

- MultiServer.py
That way the forfeit for items for players that are still playing appear last in the log, which is the visible text in at least the py clients.
> MultiServer: swap auto-forfeit with auto-collect order

- Main.py
Double-clicking in terminal may select the period, resulting in a bad filename in clipboard.
Also fixing quotes.
> Generate: remove period for easy copy&paste

- worlds/witness/WitnessLogic.txt
- worlds/witness/player_logic.py
Getting inside the Treehouse Laser Room no longer fails to check for Stars & Same Colored Symbol in remote doors modes
> Witness: Logic fix for Treehouse in Doors

- Utils.py
* fix import order
* lazy import shutil
* lazy import jellyfish (also speed-up by 0.8%, probably because of inlining)
* yaml:
* explicitely call Loader UnsafeLoader
* use CDumper, twice as fast
* stop leaking leak imported names load and load_all
* open_file: use absolute path
* replace quotes in touched code
* add some typing in touched code
* stringify type hinting for non-imports
* %s/.format -> f
* freeze safe_builtins
* remove double-caching in get_options()
* get rid of some warnings
> Core: clean up Utils.py

- Utils.py
decimal is kinda big, there is no noticable difference in performance and the import is unused by webhost's customserver
decimal.pyc - 342 bytes - imports either _decimal.so or _pydecimal.pyc
_decimal.*.so - 307KB - actually loaded
making a difference in idle malloc of ~300K just to hold the module ready.
to be clear:
the 300KB are not what we actually save, it's the upper bound of the potential. We import enough other stuff, that the real savings are ~~40KB~~ 160KB per process from what I can tell.
> Utils: lazy decimal import

- worlds/sm/__init__.py
The old code relied on item.type being unique across all worlds.
In the Item rework we removed item.type from BaseClasses.Item, so this bug finally crashed.
> SM: correctly check if items are SM items

- BaseClasses.py
- worlds/dark_souls_3/__init__.py
- worlds/ff1/__init__.py
PR #840 didn't validate that item.location had parent_region, and parent_region having world, and just blindly assumed that the entire chain of self.location.parent_region.world would be valid if self.location itself was valid.
As a consequence, I looked to see what games were broken by #840.
> Fix generation failure for Final Fantasy 1 and Dark Souls 3.

- CommonClient.py
When running client without a gui, ctx.ui is None
> Fix CommonClient.server_loop with nogui

- WebHostLib/templates/islandFooter.html
GitHub wiki is hardly updated and we prefer developers/users to use the markdown documentation in the docs/ directory anyway, so removed link in footer.
Before:
After:
> WebHost: Remove "Wiki" link from footer

- worlds/ror2/docs/setup_en.md
It now points to the RoR2 player-settings page instead of HK
> Fixed the link to the game settings page for RoR2

- worlds/witness/__init__.py
- worlds/witness/locations.py
- worlds/witness/player_logic.py
- worlds/witness/settings/Disable_Unrandomized.txt
- Fixed logic for disable_non_randomized (It previously thought you could still use the original activation triggers for lasers)
- Changed Exception for no progression items to a Warning
- Made it so the Mountaintop Box Long solution does not logically require access to the stairs below the box *if* the requirement is set to 7 lasers or lower
- Other small changes
> Witness: More bug fixes

- worlds/AutoWorld.py
Make webworld attributes docstrings instead of comments for nice IDE hinting features.
> core: webworld attribute descriptions as docstrings

- worlds/sc2wol/Locations.py
People seem to be on the mission long enough to get attacked by Mutalisks, so Victory should require anti air.
Optional Objectives are doable quite comfortably before Mutalisks show up, allowing the anti-air to be on them for later in the mission.
> SC2: add anti air to Devil's Playground Victory

- worlds/sc2wol/Items.py
Some of the "Beat Mission" items defined in Items.py were incorrectly named (and they were all manually entered), so they are replaced with a list comprehension that pulls mission names from MissionTables.py.  This fixes a generation error where certain missions could never be recognized as complete, preventing generation from accessing large portions of the campaign.
Ran ~100 generations on a generic mission shuffle yaml.
> SC2: Switched mission item group to a list comprehension

- worlds/factorio/data/mod_template/settings.lua
Rather than having to wait for the client to load up all the way to the first time it attempts to reach control phase to find out that it borked because more than one factorio AP mod attempted to define the exact same command functions,  best catch this during the earliest phase possible.
This is what that looks like in the factorio client.
If at least one of the mod instances has this change, it will catch all the instances whether or not the change is present. (as shown in the following image.)
And no error if one and only one factorio AP mod is loaded.
> Factorio: Detect if more than one AP factorio mod is loaded.

- Utils.py
- WebHost.py
- WebHostLib/templates/supportedGames.html
- Case-insensitive sort of the game list on some webpages was broken by #883. Reason being that Jinja, unlike python, has default case insensitive sort, which we were using prior to that PR. Case sensitivity was accidentally introduced to Jinja's sorting of the **Supported Games** list by writing a custom sort function
- Fix preserves title sort while bringing back case insensitive sort.
- Also made the Supported Games page `<title>` more relevant to its content and match how you navigate there.
- Diffed the webpage text of `/games` and `/tutorial` before and after. The only effect was sorting SMZ3 correctly again in `/games`.
> WebHost: sort game list case-insensitively again

- LttPAdjuster.py
- worlds/alttp/Rom.py
Extend the original "ignore invalid sprite files" PR to use sprite.valid (instead of blind Exception catching), showing a message to the user and logging more.
This code is run when opening the "Sprite" window in AlttPAdjuster and would originally crash by placing a blank .apsprite in data/sprites/custom/ or a bad utf16 string in a .zspr in data/sprites/alttpr/.
> LttpAdjuster: Exception handling, error logging and messagebox for zspr and apsprite

- worlds/factorio/data/mod_template/control.lua
Found a bug where if a recipe gives 0 of an item, then the mod can crash, if the recipe was unlocked in single craft mode.  (it dies at can_insert(stack)).
Found this bug while testing a standalone version of free samples, and of course, I needed to back port this bug fix here.
> Factorio: Fix a bug with single craft free samples.

- WebHost.py
`__file__` is relative in 3.8, so `os.path.dirname(__file__)` ends up being an empty string breaking calls to `local_path()` (without arguments)
(an alternative solution would be to do `dirname(abspath(__file__))`, but I think this fix is simpler (and not required once we drop 3.8))
> WebHost: fix local_path on python 3.8

- .github/workflows/lint.yml
- .github/workflows/unittests.yml
- docs/running from source.md
Running pytest without the subtests plugin will hide the "game=..." from `subTest`, e.g. for #985. This makes the unittest output more useful.
Looking at the output of #985.
> CI/Doc: Use pytest subtests

- worlds/oot/__init__.py
It turns out that glitched logic and MQ dungeons are not compatible. This is something that I missed when adding MQ functionality originally, so this never actually worked anyway. On ootrandomizer this is also forbidden, so we'll forbid it here too.
A big rewrite for glitched logic is in the works, so once that's done I'll port it over and we should get glitched+MQ with it.
> OoT: prevent glitched + mq dungeons

- .github/workflows/build.yml
- .github/workflows/release.yml
- Launcher.py
* Launcher.py always running ModuleUpdate breaks setup.py build --yes
* Use env variables in github workflows
* Update SNI and Enemizer versions in github workflows
* Minor cleanup in workflows
* Silence pycharm warning in Launcher.py
https://github.com/black-sliver/Archipelago/runs/8179743619
> CI: fix automated builds, update SNI and Enemizer

- test/general/TestItems.py
This was an implementation requirement that wasn't quite clear to me starting out. Adding a test makes it extremely clear - generation breaks when games don't have enough items in the pool.
Also trying to get a feel for how PRs work around here before my big one.
```
python -m pytest .\test\general\TestItems.py
```
First normally, and second, removing a single filler item from my game on my dev branch.
> Tests: Check for Holes in the Item Pool

- LttPAdjuster.py
- worlds/alttp/Options.py
- worlds/alttp/__init__.py
The `link_palettes` option is disabled because it doesn't work and is also incompatible with `random_sprite_on_event`. However, it's still exposed on the settings page. This simply removes the option from view so that we do not have a nonfunctional setting.
> ALttP: remove link_palettes option

- FF1Client.py
Corrects the issue causing the client and lua messaging not displaying properly after the printjson changes
Corrects the issue where no messages were being displayed in the FF1Client and still keeps the scoping of only relevant information displaying in the lua messages in the emulator.
Tested locally against several multiworlds with other games, hinting, item send/receiving, forfeit/collects, etc. up to seed completion, behaves as expected similar to prior to the printjson changes but also with the scoped lua messages now.
> FF1: fix FF1Client messaging and scoped lua messaging with printjson

- worlds/ff1/__init__.py
Adds an exception when Noverworld seeds are attempted to be rolled. The workaround is to generate them on an old version of the FFR site.
Tested generation on normal seeds successfully, exception is thown on the Noverworld seeds successfully
> FF1: Throw exception for Noverworld

- MultiServer.py
MultiServer.py would show exceptions instead of clear messages to the user when cancelling file open dialog or when running headless.
The cancel message was tested by cancelling, the no-tkinter was tested by manually raising exceptions in Utils.open_filename
> MultiServer: nicer output in terminal

- worlds/__init__.py
The imports fail if the folder has a '.' in the name, with a somewhat obscure error, and adding a '.' in front of it is what a linux user might expect to use when disabling a world temporarily.
This change makes AutoWorld's automatic imports ignore files and folders that start with ".".
ran Generate.py
> autoworld: don't load files/folders starting with '.'

- Starcraft2Client.py
- The client now knows what to do and say if `ExecuteInfo.txt` exists, but is empty.
- If `ExecuteInfo.txt` is missing or empty, the user is now instructed to run SC2 through the Blizzard launcher, then try again.
Manually edited/deleted `ExecuteInfo.txt`, then ran `Starcraft2Client.py` on Windows 10 and tried to connect.
Originally, I was going to have the client raise a RuntimeError when `ExecuteInfo.txt` is empty, but that would have been inconsistent with how it handles other cases (like the file being missing, or being unable to find the executable it points to). I preferred raising the error, personally, because it's louder, puts the proposed solution front-and-center on the user's screen, forces the connection to fail so the user can retry as suggested without closing the client, …
> SC2: Add helpful feedback when failing to locate SC2

- docs/world api.md
Clarify that requirements.txt will be picked up automatically. In reference to a question in discord.
> Doc: clarify requirements.txt in world api.md

- docs/world api.md
- test/general/TestNames.py
In order to differentiate between IDs and names (i.e. for !hint), names must not be numeric.
Renamed an item and a location and watched ~~the world burn~~ tests fail.
> Doc/Tests: item and location names must not be numeric

- MultiServer.py
This
* allows using `!hint <id>` and `!hint_location <id>` in addition to `!hint <name>` and `!hint_location <name>`
* gives a useful error for !hint and !hint_location if the game is unknown (datapackage for a game is missing)
* allows hinting for an unknown game with IDs only
* as above for `/hint` and `/hint_location`
Additionally fixed a typing error by using `full_name: str ` in _cmd_hint and _cmd_hint_location
```
BatBoy:
!hint Test -> unknown game warning
!hint 123 -> no hints found
!hint 696969 -> returned hints
!hint_location Test -> unknown game warning
!hint_location 123 -> no hints found
!hint_location 696969 -> returned a hint
Timespinner:
!hint Test -> did you mean...?
!hint 123 -> no hints found
!hint Tablet -> returned hints
!hint 1337124 -> returned hints
!hint_location …
```
> MultiServer: allow using IDs for hints

- worlds/factorio/Mod.py
- worlds/factorio/data/mod/info.json
- worlds/factorio/data/mod_template/data-final-fixes.lua
[Factory Levels](https://mods.factorio.com/mod/factory-levels) allows for some of the machines to level up and get faster and more productive, based on the number of products crafted by the machines.  If a machine levels up enough, it may even upgrade to the next tier automatically, in the cases where the machine can be upgraded in place.
The main thing here is that the fluid box and crafting categories needed to be copied to ALL 25 levels of assembling-machine-1.
> Factorio: Add explicit support for factory-levels mod.

- docs/world api.md
- worlds/soe/Logic.py
- worlds/soe/__init__.py
Conventionally, we added a leading underscore to logic mixins' function
names. This is noisy in the warning section of IDEs. Leading underscores
should only be used for private/protected functions.
In addition, the use of self.world and/or requirement to (no) pass in stuff
was not made clear earlier.
\+ changed naming "public" SoE mixin
It's just docs.
> Doc, SoE: Logic mixin: no underscore for public members

- worlds/alttp/docs/multiworld_de.md
- worlds/alttp/docs/multiworld_en.md
- worlds/alttp/docs/multiworld_es.md
- worlds/alttp/docs/multiworld_fr.md
- worlds/dkc3/docs/setup_en.md
- worlds/sm/docs/multiworld_en.md
- worlds/smz3/docs/multiworld_en.md
This PR Removes all remaining references to Multitroid from the docs.
By reading it.
Someone who speaks the relevant languages should update the `snes9x` sections of the `es`, `de`, and `fr` ALttP setup docs to include the information about the `socket.dll` file.
> Core: Update snes9x Links

- WebHostLib/templates/timespinnerTracker.html
Oculus ring didnt show up on web tracker anymore even if the flag was enabled, the flag was called 'FacebookMode' is now called 'EyeSpy'
Poorly
> Fixed Oculus Ring from showing up on tracker

- worlds/subnautica/docs/setup_en.md
- Added sections for console commands and known issues.
- Updated "Resuming" section to reflect current functionality.
- Removed implication that one might have to create the QMods folder. (If it's missing, then you've already messed up step 1.)
- Renamed "Connect Menu" to "connect form" to be less confusing. Generally fixed word capitalization to conform to standard English. Minor wording changes.
> Docs: updated Subnautica setup guide

- worlds/sc2wol/Locations.py
Victory and Beat conditions diverged in some instances due to needing to be updated in two places, despite them being the same "check".
running Generate a few times and peeking at spoiler.
@TheCondor07
> SC2: dynamically create Beat <mission_name> Events, preventing copy-paste errors

- ModuleUpdate.py
ModuleUpdate.py would scan requirements for worlds that are deliberately excluded from AutoWorld system.
By renaming sc2wol to .sc2wol and running ModuleUpdate.py
> ModuleUpdate: skip disabled/hidden folders

- WebHostLib/static/assets/tutorial.js
- WebHostLib/templates/check.html
- WebHostLib/templates/generate.html
- WebHostLib/templates/hostGame.html
- WebHostLib/templates/startPlaying.html
I noticed many pages used the default document title of "Archipelago", for example:
- https://archipelago.gg/start-playing
- https://archipelago.gg/tutorial/Archipelago/plando/en
- https://archipelago.gg/tutorial/Factorio/setup/en
These changes fix some obvious mistakes where multiple `<title>` tags are being set and extends the tutorial loading JavaScript to attempt to take a title from the loaded markdown.
I ran a local web host, opened these URLs in my browser and confirmed the document title to be better than before:
- http://localhost/start-playing
- http://localhost/generate
- http://localhost/uploads
- http://localhost/check
- http://localhost/tutorial/Archipelago/advanced_settings/en
- http://localhost/tutorial/Factorio/setup/en
- etc
> WebHost: Fixed some document titles

- setup.py
this fixes libssl1.1 not being found on Linux distributions that only have libssl3 - we include libssl1.1.x, but it's not being picked up by the _ssl module without changing environment variables.
> AppImage: provide LD_LIBRARY_PATH

- FactorioClient.py
> FactorioClient: Prevent pipes from breaking on invalid UTF-8

- worlds/hk/__init__.py
This changes Dreamers to no longer be affected by progression balancing due to it providing very early dreamers in games leading to early infected crossroads and much shorter games in some cases.
3 successful generation attempts
> HK: changes dreamers to skip prog balance

- test/general/TestReachability.py
- worlds/sm/Regions.py
- worlds/sm/Rules.py
- by adding exclusion for Regions used only when corresponding Starting Location is used
- by removing unnecessary VARIA Regions used only for EscapeRando (not supported in AP anyway)
> [SM] Fixed failing testAllStateCanReachEverything

- worlds/generic/docs/plando_en.md
- worlds/generic/docs/triggers_en.md
A pass of polish for the trigger and plando guides.
The changes in roughly descending order of severity are:
- Hopefully improved the clarity of the trigger part explanation
- Fixed the last trigger example (indents were messed up)
- Minor nomenclature changes, that someone should review in context
- "root category" -> "category"
- "root option" -> "category"
- "imaginary names" -> "imaginary values"
- Moved some links to be inline
- Added commas
- Fixed some capitalization
- Misc homogenization
> Docs: Polished Trigger and Plando guides

- BaseClasses.py
In `sweep_for_events`, removes locations from the location set after they are reachable, so that we don't run `can_reach` on already-reachable locations unnecessarily
Generated a 10 world HK multiworld with 6200 items, on main and on this branch, with a set seed. Generation time was cut from around 450 seconds to 253 seconds, and the .archipelago files output matched exactly.
> [Core] improve sweep_for_events efficiency

- worlds/pokemon_rb/__init__.py
- worlds/pokemon_rb/options.py
- worlds/pokemon_rb/rom.py
Fixes non-deterministic generation.
If legendaries are set to be shuffled into static locations, prevents them from being shuffled into the "restless soul" encounter at the top of the Pokémon Tower, as the Pokémon encountered here cannot be captured
Also prevents wild pokemon in Pokemon Tower 6F from being the same pokemon as the restless soul encounter, as the game will load the restless soul encounter scripts for them in this case.
Compared spoiler logs of same seed generations to confirm deterministic generation has been achieved.
For restless soul fixes: generated games, used breakpoints to confirm intended behavior was occurring.
> [Pokémon  R/B] Fixes

- WebHostLib/static/assets/faq.js
- WebHostLib/static/assets/gameInfo.js
- WebHostLib/static/assets/glossary.js
- WebHostLib/static/assets/tutorial.js
- WebHostLib/static/styles/themes/base.css
Anchors are used to mark a specific spot in a longer page as part of the URL. Consider the following URL:
> [https://archipelago.gg/faq/en/#what-happens-if-a-person-has-to-leave-early?](https://archipelago.gg/faq/en/#what-happens-if-a-person-has-to-leave-early?)
Opening the page using that URL should automatically jump to the section specified by the anchor. However, currently sometimes it doesn't work, and when it does, the start of the section is obscured by the clouds of the header. The same problem occurs when clicking on a heading, which updates the anchor in your URL bar and scrolls it so far to the top that it is obscured by the clouds.
This PR fixes these problems. It also modernizes the code a little bit (for-each loops, `window.location.hash` instead of character juggling with …
> WebHost: Fixed scrolling to anchors

- docs/network protocol.md
I had to look in the code to find out what happens when I `Get` a key that doesn't exist on the server.
This puts it in the documentation.
> Docs: Retrieved packet when information doesn't exist

- Fill.py
Adds parenthesis to forbid_important_item_rule so that the two things are evaluated together instead of `not` only applying to the first
generated same seed with and without and determined item placement was different, confirming the intended effect of the old statement was not being achieved
> [Core] Fix forbid_important_item_rule

- Fill.py
The current swap algorithm fails in certain scenarios. This change makes the swap assume it can place the
item-to-be-swapped-out in an earlier location so that it attempts the swap even if the swap itself does not improve
accessibility.
By running ap-roller on a bunch of yamls.
ItemLink was not tested.
Per-player priority/excluded was not tested.
Random options, no local/non-local items, accessibility: items or location (not minimal).
| Game     | Seeds | Main | PR |
|:-------- | -----:| ----:| --:|
| Alttp    |   400 |   [^1] 9% | unchanged |
| Raft[^2] |   400 |        0% | unchanged |
| SA2B     |   400 |        1% | 0% |
| SM       |   400 |  [^3] 37% | 27% |
| SMZ3     |   600 | [^3] high | unchanged |
| SoE.41   |  1400 |        0% | unchanged |
| SoE.42   |  1400 |   [^4] 4% | 0% | …
> Main: Fill: more opportunities for swapping

- worlds/raft/Rules.py
The Raft generator currently allows items required for the Receiver to work to spawn on story islands. This is an impossible scenario to complete.
I manually generated multiple Raft worlds and verified that the required Receiver-related items were not locked behind story islands.
> Raft: Update rules to account for navigation

- worlds/witness/Options.py
- worlds/witness/WitnessItems.txt
- worlds/witness/WitnessLogic.txt
- worlds/witness/WitnessLogicExpert.txt
**Changes:**
Allow for more Puzzle Skips and also raise the default.
Puzzle Skips have been rebalanced client-side to be more consistent in value across the board, making me feel like it's now fine to allow more of them.
(Examples: Instead of one Puzzle Skip bypassing the entirety of Metapuzzle, you can now individually skip the small puzzles of Metapuzzle, which will show you the correct shape to use. And then only if all 4 small puzzles are skipped, you can use a 5th skip to fully skip Metapuzzle. On the flipside, it is now possible to use 2 Puzzle Skips to skip the Quarry Laser panel even if you haven't beaten either side of the Quarry. I plan to do more interesting things with PSs in the future)
-
Also made the Elevator Start panel logically require shortbox (usually 7) lasers in …
> The Witness: More Puzzle Skips, Softlock Fix

- worlds/AutoWorld.py
- worlds/dkc3/__init__.py
- worlds/oribf/__init__.py
- worlds/rogue_legacy/__init__.py
- worlds/sa2b/__init__.py
- worlds/smw/__init__.py
- worlds/witness/__init__.py
Pushing multiple references of the same item to the item pool, instead of creating multiple copies, possibly breaks when accessing item.location, so we test for that now.
The assert loop has no influence on the release build, and on a server that run's it with `-O`, because it's hidden behind `__debug__`.
Additional testing in `/tests/` may be good, for example to validate that two players of the same world do not get each others items, and maybe to validate apworlds pre-installation? The assert however gives insight into real world generation during development.
> Core: assert that items have a single reference

- WebHostLib/static/assets/weighted-settings.js
This change fixes a bug on the weighted settings page caused by range options with hundreds of thousands of possibilities. Now, only the min, max, and default are stored and displayed on the UI. Adding and removing range options now also adds and removes them from localStorage.
I tested this locally.
> Fix weighted-settings to not save full set of range options to localStorage

- Generate.py
Fixes that filler gets included as player, regardless if filler is needed or not. Even if filler is needed, earlier behaviour would have one random filler slot within the group of non-filler slots.
Running Generate with 3 and 0 players, with templates posted to discord. Problem was found as Player142 of the Async gen was another copy of the filler.
> Generate: don't try to include meta or filler weights file as player

- Fill.py
Fixes an issue where inaccessible items placed during main prog item fill could make items placed into priority locations inaccessible. Accomplishes this by waiting until after prog item fill to lock priority locations. 
Other changes:
* Put priority fill into an `if` block as I noticed `accessibillity corrections` wasting a few seconds on a small multiworld when there were no priority locations
* Since inaccessible locations may be emptied after prog item fill, I sort locations to move priority locations to the front of the line before re-filling in `accessibility_corrections`. I first tried pulling out priority locations and running `fill_restrictive` with just them, but that function will put out warnings that items failed to place if it ends with items and locations left over. We …
> [Core] Fix priority location handling in accessibility corrections

- CommonClient.py
- FactorioClient.py
- Utils.py
- host.yaml
- worlds/factorio/data/mod_template/control.lua
- worlds/factorio/docs/setup_en.md
In light of the pain caused by the in-game spam in the big async, this PR adds a toggle to filter the item sends being displayed in-game down to only those involving the local factory (items sent from or to that factory). It defaults to off, but can be enabled by any of a `host.yaml` setting, a FactorioClient command and a Factorio client in-game command.
Note that this filter does not affect what is displayed in FactorioClient.
I tested this locally using a modded MultiServer.py to send randomly generated ItemSend messages to a FactorioClient & Factorio client instance.
This feature is technically independent of #1068, but the toggling commands and settings are implemented in exactly the same way. Minor merge conflict resolving will be required if both PRs are approved.
> Factorio: Add optional filtering for item sends displayed in-game

- worlds/zillion/docs/setup_en.md
- worlds/zillion/options.py
I found that the RetroArch core I have been using has not been updated in more than 10 years, and the author is telling people to go to a different one instead. So I did a game with that one and it works.
Also, since `early_items` is implemented, I wanted to include a recommendation to use it in the setup guide.
> Docs: Zillion: RetroArch core and `early_items` recommendation.

- worlds/sm64ex/Options.py
- worlds/sm64ex/Rules.py
* Adds an option to split courses and secret areas into separate pools for randomization
* If MIPS1Cost is greater than MIPS2Cost, swap the costs instead of setting MIPS2Cost to MIPS1Cost
Generating and observing intended effects in the spoiler logs
@N00byKing
> [SM64] Separate Entrance Shuffle pools option and MIPS cost option improvement

- MultiServer.py
Changes the way the hint system works, so that if there is a hint cost, a player can no longer right at the start of the game do for example,  !hint master sword,  !hint power glove, !hint mirror shield,  in order to find out if their items are progressive or not, in the case where the player decided to use grouped random.  If you can't afford to pay for the hint,  then the only messages a player will get besides not being able to pay,  is general error messages, like "did you mean x (69% sure)"
The following screenshot shows an example, in the case of zillion, I have a random starting character, so a player might do !hint JJ, !hint Apple, !hint Champ,  to find out what their starting character is before the game has started.  By giving the same can't afford the hint message in all cases, …
> MultiServer: Don't leak info about what exists or not if player can't afford the hint

- docs/network protocol.md
Adding a new library to the Network Protocol docs, as suggested on the discord
> Docs: Add ArchipelagoRS to the Network Protocol docs

- .github/workflows/build.yml
`build` changed on Windows a while back, breaking the automated build. Fixing by switching to `build_exe` instead.
https://github.com/ArchipelagoMW/Archipelago/actions/runs/3347236556
> CI: use build_exe in automated build

- Utils.py
- worlds/factorio/Locations.py
- worlds/factorio/Mod.py
- worlds/factorio/Options.py
- worlds/factorio/Shapes.py
- worlds/factorio/Technologies.py
- worlds/factorio/__init__.py
- worlds/factorio/data/mod_template/data-final-fixes.lua
- worlds/factorio/data/mod_template/locale/en/locale.cfg
- worlds/factorio/data/mod_template/macros.lua
Changes Factorio's locations from being filtered, scaled and shuffled vanilla ones to entirely newly created ones controlled by new yaml options.
Associated changes:
* instead of 4 total traps replacing the 4 useless technologies, one can now have individually 25 traps each
* new locations are searchable by name ingame
* previously static nodes can now be part of the tech tree layouts, will however be placed reasonably (automation and logistic will always be at the start and rocket silo always be at the end)
This is also the required base changes I need for future plans (tm)
It also updates the …
> Factorio: revamped location system

- MultiServer.py
- test/programs/TestMultiServer.py
Once upon a time, there was a multiworld seed with a player named "buxnq" and another player named "buxnQ", and some other players. And the host needed to forfeit the items from buxnq's world. So the host used the command `/forfeit buxnq`, and it forfeited buxnQ's items. The host was unable to forfeit buxnq's items.
The server commands first try to match the player name case sensitively.
If there's no case-sensitive match, then they will try to match without matching case (only if it's unamibguous).
new unit tests added
generated a game with those names again and tested a few server commands
> MultiServer: fix case sensitivity in server commands

- worlds/factorio/__init__.py
Factorio would
* generate different location pool order (and thus different locations)
* generate "automated" events in different order
for the same seed. Fixing this by sorting.
```python
from hashlib import md5
print(md5(str(nauvis.locations).encode("utf-8")).hexdigest())
```
> Factorio: deterministic locations

- Generate.py
- MultiServer.py
Make player names case insensitive from Generator's point of view.
Note: this also makes Player{NUMBER} and Player{number} use the same counter, which was not the case previously.
Bunch of yamls with the same name in different variations.
> Core: make player name case-insensitive

- Fill.py
Fixes bug where unfilled early_priority_locations is added to  fill_locations twice
generating games with early items and early priority locations and ensuring it does not explode
> [Core] fix early items bug

- CommonClient.py
- data/client.kv
- kvui.py
A bunch of small fixes and improvements for CommonClient:
- Focus the text field when requesting input.
- Store and prefill the last server address. It is stored in `_persistent_storage.yaml` and is thus global to all CommonClient derivatives in the install. It is only stored upon a successful connect.
- Focus the address bar upon start and select the port portion. (If the last server address does not have a port component, the entire address is selected.) This means, if the last address is correct, you can simply hit Enter after starting the client to reconnect.
- Don't allow editing of the address while connected.
- Don't make pressing Enter in the address bar disconnect you.
- Use `TextInput.text_validate_unfocus` over the current jank workaround.
- Fixed the ~10 second hang when …
> CommonClient: Some GUI polish

- worlds/zillion/requirements.txt
License of zilliandomizer package is changed to LAGPL
> Zillion: license

- worlds/overcooked2/Overcooked2Levels.py
- worlds/overcooked2/__init__.py
Revert an accidental change from the Multiworld rename and optimize the slot_data location scouting. Can this be done with client side scouting instead? Another suggested change is that location IDs currently range from 1-44 and it'd be much better to have a base offset in that dictionary definition, but likely requires client change. @toasterparty :)
Generated and played some OC2
> Overcooked 2: Revert OC2Level world references to be named correctly, optimize location scouting.

- WebHostLib/lttpsprites.py
Fixed the warning ".gitignore dropped, as it has no valid sprite data." that is logged when starting up the WebHost
Just starting the WebHost with the line changed
> WebHost: Fixed warning ".gitignore dropped, as it has no valid sprite data."

- worlds/witness/WitnessLogic.txt
A broken seed was reported where Colored Squares was on a panel locked by Colored Squares. This PR fixes this problem.
> The Witness: Logic fix

- worlds/bk_sudoku/docs/setup_en.md
Updated the docs to nolonger require .net6 to be installed, as BK sudoku switched to a standalone executable
Poorly
> Docs: Updated Sudoku docs now we use standalone deployment

- worlds/oot/__init__.py
oops
If these aren't locked then progression balancing can swap an item into them, which causes problems.
> OoT: lock fast-filled shop locations

- worlds/pokemon_rb/rules.py
A late change to location names was made, and one was missed in rules.py. I had tested these changes by generating a default yaml, and failed to realize this would not include hidden items 
Describing this code change to Figment who made this change and reported that generation was able to proceed past the rule setting phase without error
> [Pokémon Red and Blue] Fix location name in rules

- worlds/sc2wol/PoolFilter.py
The original line incorrectly added an Item to a List[Item] rather than appending.
Generating on a seed that ran into this rare if branch (30253513828953847490)
> SC2: Bugfix for duplicate item handling

- worlds/subnautica/Creatures.py
- worlds/subnautica/Options.py
This bug was reported by Oneup#7856 on Discord on October 27th.
The setting `creature_scan_logic: removed` erroneously put the Cuddlefish in the creature scan pool.
Generated a few seeds with `creature_scan_logic: removed` and checked the spoiler logs.
> Subnautica: Fix `creature_scan_logic: removed` allowing Cuddlefish

- Fill.py
- test/general/TestFill.py
There were concerns about the performance of early items (removing things from lists).
makes 1 pass through the list for everything that needs to be removed,
instead of searching through the list and rebuilding it for each removal
added a unit test for early items
> Core: optimize early items and add unit test

- CommonClient.py
- FactorioClient.py
- worlds/factorio/data/mod_template/control.lua
The amount of energy stored in the energy link is only visible in the FactorioClient GUI. This means that players running FactorioClient without GUI and players connecting to a remote AP Factorio server have no way of seeing this value.
Two commands that print the current status of the energy link:
- `/energy_link` in FactorioClient
- `/energy-link` in game
- Energy link seems to be mostly implemented in a way that would allow sharing energy between different games, not just Factorio, but I implemented `/energy_link` as part of FactorioClient, rather than baking it into CommonClient. My main reasons are:
- It's currently tricky to have a CommonClient command appear in the `/help` listing only for certain games. I deemed showing `/energy_link` in all CommonClient based clients to sow more …
> Factorio: Added commands for checking energy link from CLI and in game

- FactorioClient.py
On Windows, whether your input to the console window is interpreted by FactorioClient or the Factorio server itself alternates with every line you enter.
This doesn't solve the problem, but it prints a warning before and after the start-up sequence, `if Utils.is_windows and sys.stdin`. This simultaneously serves as documentation. I hope this saves someone else from wasting time chasing this bug.
Yes.
> FactorioClient: Document/warn about Windows console input

- worlds/smw/docs/setup_en.md
Adding a link to the SMW Tracker to the SMW Setup Guide.
I clicked the link.
> SMW: Add link to Tracker in setup guide

- worlds/witness/WitnessLogic.txt
- worlds/witness/locations.py
1. Two panels in Tutorial Outpost were missing their Full Dots requirement
2. Fixed error where 2+ expert players would break on generation
> The Witness: Logic Fix & Generation Fix

- worlds/factorio/Mod.py
- worlds/factorio/data/mod_template/control.lua
in normal AP play, nothing.
This sets vanilla technologies that are useless to be hidden and researched, so if any user installed mods happen to refer to these technologies, it will not break those changes.
By loading up Factorio and seeing if it gave the desired result.
The technologies are completely hidden from the user, so no.
> Factorio: set useless technologies to be researched from the start

- WebHostLib/static/assets/tracker.js
- WebHostLib/templates/checkResult.html
- WebHostLib/templates/genericTracker.html
- WebHostLib/templates/tracker.html
This PR should put the other PR (#1145) in go mode. It adds DOM IDs to all relevant tables and adds the discussed snippet for unifying the settings of all tracker pages.
Mildly. On localhost with all the different tracker pages, checking the local storage display of the browser.
> WebHost: Fix DataTables local storage keys

- worlds/sc2wol/PoolFilter.py
- worlds/sc2wol/__init__.py
Early Unit:  Now respects Excluded Items when selecting a random unit.
Units Always Have Upgrades:  Changed removal cascade behavior; now additionally checks to see if an associated item is already locked when attempting to remove, and locks associated items if so.  Occasionally caused issues with starter items in the past, frequently caused issues with yaml-defined Locked Items.
Five test generations on five different YAMLs, four of which used reduced settings and one of which used full settings.
> SC2: Bugfixes for YAML Option Interactions

- data/lua/PKMN_RB/pkmn_rb.lua
Re-adds erroneously-removed frame increment. Checks for items from client every 5 frames now instead of every frame. Also makes sure item received value is zeroed out before sending another item, just to be safe.
I am hoping these changes fix an issue I've encountered twice where items have failed to be received by the game despite showing up in /received in the client
Generating a multiworld, running `/collect` for the Pokémon player, connecting to the slot with this lua and observing all items correctly being received, with the stutter of the "item received" sound effect slightly less dramatic as items are being received 5 times slower now.
> Pokemon Red and Blue: lua updates

- test/general/TestItems.py
- worlds/oot/Rules.py
- worlds/oot/__init__.py
in title. Fixes longstanding issue of bottles not being hintable, and adds a new set because I realized it could be useful for those who randomize it. 
generate game, server hint for the two groups, returns items correctly
> OoT: make Bottles and Adult Trade Item hintable groups

- worlds/smw/Regions.py
- worlds/smw/Rom.py
Two unintended behaviors are fixed in this PR:
- If you kick a Baby Yoshi into an item that would fill his stomach, he would still grow into adult Yoshi even without you having the `Yoshi` item. (Most easily reproduced in Star World 2)
- You could jump off of moving ropes without the `Climb` item. (Allowed skipping the Climb requirement in Cheese Bridge Area)
Also one logic fix is addressed in this PR:
- `Forest of Illusion 3 - Secret Exit` was set to require `Swim` instead of `Spin Jump` due to a copy/paste error.
I generated a seed and got to the two above-mentioned levels without the specified items, and observed that the behavior went away. The changes are unrelated to the existing `Climb` and `Yoshi` behavior, but those were also tested anyway.
Ran a few generations to verify the …
> SMW: Fix Baby Yoshi and Rope Jump Exploits

- worlds/witness/WitnessItems.txt
"Treehouse Drawbridge (Panel)" gave access to the Laser House door timer, "Treehouse Door Timer (Panel)" gave access to the Back of the Shadows Door Timer. This corrects that
> The Witness: Fix "doors: panels" items referring to the wrong panels

- worlds/oot/docs/en_Ocarina of Time.md
- worlds/oot/docs/setup_en.md
Adds to the OoT docs:
- How to make savestates work
- A link to https://wiki.ootrandomizer.com/index.php?title=Bizhawk
- A link to https://wiki.ootrandomizer.com/index.php?title=Logic
Local webhost instance.
> Docs/OoT: Add savestate fix and links to Bizhawk and Logic wiki pages

- worlds/sc2wol/PoolFilter.py
- worlds/sc2wol/__init__.py
Vestigial fields were removed from slot data, so old clients always crash.  Incremented the required version to 0.3.6.
Generated one SC2 world, hosted it on source, and connected to it with a source client.
> SC2:  Increment required client version

- Utils.py
> **BlackSilver**: sni is not being started from sniclient in the 0.3.6 appimage when you upgrade. reason seems to be that the option was renamed in host.yaml, but the new option does not have a default in Utils.py that's working (it has the wrong name there).
>
> **PoryGone**: Changing the field in Utils.py to match should resolve it
Did not test directly (I used a suggested workaround of deleting `host.yaml` instead, which worked)
> Fix SNI not launching on upgrade to 0.3.6

- BaseClasses.py
- WebHostLib/upload.py
There is a method in BaseClasses.py: `MultiWorld.get_out_file_name_base` that does not append the player name to the final patch output file if the player name matches the format: `Player{slot_number}`. This does cause any issues in Generation or even when running the Server, but during upload in WebHost, WebHost tries to search for the player name in the file name and fails to do so, causing a 500 error.
```
File "C:\Users\Phar\Projects\Archipelago\.venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\Phar\Projects\Archipelago\.venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
rv = self.handle_user_exception(e)
File …
```
> WebHost/Core: Defer creating slots that have patch files until after multidata is loaded and remove redundant code.

- MultiServer.py
- worlds/generic/docs/commands_en.md
I've definitely found in development that there were times I wished I could check a specific location from the server, in order to test various game behaviors. This is now possible.
Ex:
```
/send_location Pory_SMW Donut Plains 4 - Normal Exit
```
I spun up `MultiServer.py` hosting a seed with a few games, and checked locations in each of several games. Also attempted intentional typos to verify the typo detection.
I'm not attached to the name of the command or any of the messaging returned to the players in fail states, please suggest if you have better wording
> Core: Add MultiServer command to check a specific location

- worlds/pokemon_rb/docs/setup_en.md
The setup_en.md file had an un-escaped URL that was breaking a link; this fixes the link by escaping the spaces in the URL.
> Docs: Fix broken link in Pokemon setup instructions

- worlds/witness/WitnessLogicExpert.txt
Expert Jungle Discard requires Arrows, not Triangles
> The Witness: Logic Fix (Broken Seed reported)

- worlds/factorio/Options.py
- worlds/factorio/docs/setup_en.md
* Fleshed out lacking option descriptions.
* Added instructions on peaceful mode to the setup guide.
* Added subheadings for each "other setting" in the setup guide.
Locally, in Firefox.
> Docs/Factorio: Option descriptions, peaceful mode setup

- worlds/bk_sudoku/docs/en_Sudoku.md
Updating the Sudoku docs to specify it will nolonger hint the same location multiple times
Just checked the .md file in github for style and spelling mistakes
> Sudoku, Docs: Updated text about duplicated hints

- CommonClient.py
- MultiServer.py
- Utils.py
- docs/network protocol.md
implements _read prefixed datastore keys that can dynamically answer.
This implements  
* `_read_hints_{team}_{slot}` to get hints of that player
* `_read_slot_data_{slot}` to get slot_data of that slot
slot_data is now optional. In practice I've seen it be used sometimes only for a client or only for a tracker.
TextClient now skips slot_data download.
A bit, with stuff like `asyncio.create_task(self.send_msgs([{"cmd": "Get", "keys": [f"_read_hints_{self.team}_{self.slot}"]}]))` in an on_package callback.
Which returned:
`{'cmd': 'Retrieved', 'keys': {'_read_hints_0_1': [{'receiving_player': 8, 'finding_player': 3, 'location': 91948, 'item': 1604, 'found': False, 'entrance': '', 'item_flags': 2, 'class': 'Hint'}, {'receiving_player': 9, 'finding_player': 1, 'location': 2202, 'item': 1604, …
> Network: implement read_only datastore keys: hints and slot_data

- worlds/hylics2/__init__.py
Fixes a generation issue found by @ThePhar where Hylics 2 worlds would not be recognized as beatable because the victory event was created too late, in `generate_basic` rather than `create_regions`. This resulted in the location not being cached, and therefore not retrieved by `get_locations` during `check_accessibility`.
> Hylics 2: fix beatability failures

- WebHostLib/api/generate.py
- WebHostLib/check.py
- WebHostLib/generate.py
- WebHostLib/static/styles/globalStyles.css
- WebHostLib/upload.py
The website accepts two different kinds of zip files on two not entirely dissimilar pages, both part of common workflows for setting up a game:
- A *settings zip* serves to bundle a set of player settings YAML files for upload to `/generate` (or `/check`).
- A *seed zip* serves to bundle the various output files of a seed generation, which may be uploaded to `/uploads` to host a room on the web host.
When you accidentally upload a seed zip to the `/generate` or `/check` pages you get a cryptic error message, because the spoiler log is parsed as a settings file. I have observed one instance of this causing a newbie to seek tech support in the Discord.
Example:
This adds rudimentary checks to `/generate` and `/check` to reject seed zips, and to `/uploads` to reject settings zips. A helpful …
> WebHost: Detect confusion of settings zip and seed zip

- Generate.py
Removed a not that stopped game specific overrides from being applied correctly.
With SoE's custom progression balancing
> Core: fix bug that caused world option overrides to fail

- .gitignore
- inno_setup.iss
- setup.py
distribute Factorio and Subnautica as .apworld
on py 3.10 win10 through to launching an inno installed AP
> Core: default distribute Factorio and Subnautica as .apworld

- worlds/oot/docs/setup_en.md
- worlds/pokemon_rb/docs/setup_en.md
- Pokemon guide was missing a point about changing the Lua option in Bizhawk.
- The same point in the OoT guide was missing a step about restarting Bizhawk after changing the Lua option, so updated that as well.
no need. just updated text in docs.
> Docs: Update Pokemon and OoT setup guides

- ZillionClient.py
- worlds/AutoWorld.py
- worlds/zillion/__init__.py
fixes issues reported
https://discord.com/channels/731205301247803413/1050191303863963778
and
https://discord.com/channels/731205301247803413/1048803229250633808
In some generated games, some location checks weren't reported because they didn't have the information they needed from slot data.
generated a game with `Generate.py`, uploaded to archipelago.gg to make a room, and play through the game connected to that room, getting all the location checks
> Zillion: fix invalid slot data from race condition

- worlds/rogue_legacy/__init__.py
Early vendors and Early architect do the exact opposite of what I wanted. They don't get added to pool. Wups.
Generated. They are back.
> Rogue Legacy: Fix early vendors and architect not being added to pool.

- Starcraft2Client.py
- worlds/sc2wol/Items.py
- worlds/sc2wol/Locations.py
- worlds/sc2wol/LogicMixin.py
- worlds/sc2wol/MissionTables.py
- worlds/sc2wol/Options.py
- worlds/sc2wol/PoolFilter.py
- worlds/sc2wol/Regions.py
- worlds/sc2wol/__init__.py
- Seeds were nondeterministic when `early_unit` was enabled due to pulling from a set, now sorts set before picking
- Renamed "world" arguments in various methods to "multiworld", in keeping with #931 
- Fixed All-In Ground including anti-air in its logic, fixed method call without arguments
- Fixed No-Logic pulling from original logic for Beat events after iterator was changed to an enumeration
Several generations on affected settings after each commit.
> SC2: Various bugfixes

- PokemonClient.py
- worlds/pokemon_rb/__init__.py
- worlds/pokemon_rb/options.py
- worlds/pokemon_rb/rom.py
Verify rom checksum during client patching process.
Moves type chart randomization from `generate_output` to `generate_early` so that the data exists before trying to place it into slot data.
Adds trap weight options at request of players.
Adds missing `display_name` for `master_ball_price`
Running debug with breakpoints and ensuring the type chart was correctly placing into `slot_data`, and that trap weights were being set up correctly. Observed correct trap weights in spoiler log.
Swapped titles of Red and Blue roms to verify client would refuse to patch due to incorrect checksum. Verified patching process works when roms are correct.
> [Pokemon R/B] Bug fixes and add trap weights

- worlds/oot/Hints.py
- worlds/oot/__init__.py
Fixes a bug where the region_has_shortcuts function would crash during evaluation if the relevant boss room was not yet connected to a dungeon (e.g. in boss shuffle). Now returns False if unconnected, which is the logically-safe assumption. 
Bug reported at https://discord.com/channels/731205301247803413/1051691924085543003
> Fix region_has_shortcuts crash when boss shuffle is on

- worlds/lufia2ac/docs/en_Lufia II Ancient Cave.md
Adds a new section to the Lufia II Ancient Cave game page,
describing the various ways in which the AP experience differs from the original game.
Proofread.
> Docs: lufia2ac: document changes from the vanilla game

- worlds/oot/Options.py
- worlds/oot/Patches.py
- worlds/oot/__init__.py
- Since multiprocessing and exceptions apparently don't interact well, any exceptions in `generate_output` are handled more gracefully now. The event is always set as well, so the process will no longer hang on an exception there.
- The triforce object file was renamed in 7.0. I didn't change the filename in the code, so it would crash on non-Windows systems.
- Some hint distributions just crash, so I'm temporarily removing them. It will take a while to port the relevant functionality and I'd rather not hold up the next version release.
> Ocarina of Time 0.3.7 hotfixes

- worlds/pokemon_rb/logic.py
- worlds/pokemon_rb/options.py
- worlds/pokemon_rb/regions.py
Allow setting exp modifier to 0%, and add logic rules to Cinnabar Gym and Fighting Dojo to ensure higher level Pokémon are catchable
Generating with plando and set seeds with logic rules in place and without, to ensure it would not force you to fly to Cinnabar Gym and fight Blaine or to Saffron and fight in the Dojo before being able to reach any catchable Pokémon beyond sphere 1
> [Pokemon R/B] Allow 0 exp setting and add logic rule to Cinnabar Gym

- setup.py
- worlds/__init__.py
pl3453 f0rm47 y0ur 717l3 w17h wh47 p0r710n 0f 7h3 pr0j3c7 7h15 pull r3qu357 15
74r6371n6 4nd wh47 17'5 ch4n61n6.
3x. "my64m34: 1mpl3m3n7 n3w 64m3" 0r "d0c5: 4dd n3w 6u1d3 f0r cu570m1z1n6 my64m33"
m4k35 4pw0rld5 l04d4bl3 1n 3.8 4nd 3.9 py7h0n, 45 l0n6 45 7h3y d0n'7 d3f1n3 4 l061cm1x1n
runn1n6 b07h fr0z3n 4nd 50urc3 v3r510n 0f 4p 4641n57 3.8 4nd 3.10
```
Makes APWorlds loadable in 3.8 and 3.9 Python, as long as they don't define a LogicMixin
running both frozen and source version of AP against 3.8 and 3.10
```
> Core: Make apworlds function mostly before Python 3.10

- worlds/pokemon_rb/rom.py
Adds revives to the shops modified by the better_shops option, left out by an oversight
Generating, checking shops to make sure Revive is present and there are no apparent issues with shops.
> Pokémon R/B: Add Revive to better_shops

- WebHostLib/misc.py
- WebHostLib/templates/siteMap.html
Game lists should now be sorted by title everywhere, and no-longer be sorted by world folder name
locally running the webhost with trail & error
> WebHost: Fixed game order by title

- WebHostLib/static/assets/player-settings.js
See title and images below.
Compared webpages between current site and this branch. Verified that template files and exported setting files were not affected by change, purely just a visual change on website.
Before:
After:
> WebHost: Capitalize `SpecialRange` choices in keep consistency with other `Choice` options on settings pages.

- worlds/rogue_legacy/Rules.py
Early vendors and early architect can place items anywhere instead of the first local sphere, because some math was terrible in a rule (basically always returned `True`).
This fixes that.
Ran before:
Ran after:
N/A
> Rogue Legacy: Fix early vendors and architect... again.

- MultiServer.py
- WebHostLib/generate.py
- WebHostLib/templates/generate.html
- host.yaml
Renamed all the host options to use `release_mode` instead
Generated and tested all of the commands locally on webhost and on multiserver both as client and as server
> Multiserver: rename all references to forfeit and deprecate it

- worlds/generic/docs/advanced_settings_en.md
Adds information on special values a user can add to their `name` in their YAML to have it replaced with a slot number or name count number.
I looked at the markdown and thought, "Yeah, that looks good enough." Then created a pull request.
N/A
> Docs: Add special name keywords to docs.

- MultiServer.py
- WebHostLib/customserver.py
- worlds/AutoWorld.py
- worlds/ror2/__init__.py
- worlds/spire/__init__.py
Completely remove `forced_auto_forfeit` as the only 2 worlds that used it, "Risk of Rain 2" and "Slay the Spire", no longer depend on it.
Ran tests and removed all references to `forced_auto_forfeit`.
N/A
> MultiServer: Remove `forced_auto_forfeit`

- worlds/overcooked2/Logic.py
- Fixes an issue where generation frequently fails when horde levels/items are excluded from location pool
- I stake my reputation as a developer that this fix works as intended and will never regress
> [OC2] Logic Blunder

- playerSettings.yaml
moves prog balancing and accessibility into game section, and adds the rest of the universal AP options to the template yaml
ran a couple test gens to make sure i didn't break anything with the defaults
n/a
> [LTTP] update template to add all universal AP options

- worlds/bk_sudoku/docs/en_Sudoku.md
Updated docs to match latest release of client where hints no-longer yield duplicated results due to the implementation of the hints api
just here in the github ui
> Docs, Sudoku: Hints will no-longer duplicate

- ZillionClient.py
ZillionClient was auto-reconnecting after a manual disconnect.
With this fix, it does not auto-reconnect after a manual disconnect.
a single-player web-generated seed, manually disconnecting and reconnecting
> ZillionClient: fix manual disconnect

- worlds/oot/__init__.py
If the bridge or ganon bosskey required more hearts than were in the pool, generation crashed.
This forces the item pool to contain sufficiently many hearts to satisfy the logic.
Fixes the bug reported at https://discordapp.com/channels/731205301247803413/1063244398411927564.
> OoT: heart logic fix

- Fill.py
- worlds/alttp/Rules.py
- worlds/alttp/test/items/TestPrizes.py
Originally reported in https://discord.com/channels/731205301247803413/1061996715625947256:
When using items plando without specifying an explicit list of target locations, all locations in the target world will be considered (this seems to be a bit of a semi-hidden feature in itself). However, a problem arises when any item ends up being placed in an ALttP dungeon prize location, as this causes a crash during ROM output. (And wouldn't be supported by the ALttP ASM anyway.)
~~The proposed solution is to ignore all ALttP dungeon prizes when going through plando location candidates.~~
The proposed solution is to add item rules that allow only crystals/pendants for ALttP dungeon prize locations.
~~This PR also tries to fix an existing, similar exclusion, where the present code was faulty …
> alttp: add item rules for prize locations

- worlds/sa2b/Regions.py
`King Boom Boo` boss can lock progress to subsequent gates, by requiring `Knuckles - Shovel Claws`. The region connections were not accounting for gates past the immediate one locked by said boss, so the `Knuckles - Shovel Claws` could be locked in a later gate, with no means of access.
Many generations, verifying access to `Knuckles - Shovel Claws` before `King Boom Boo` in all cases
> SA2B: Fix Gate Region Connections

- worlds/pokemon_rb/rom.py
Fixes a bug where if you select "vanilla" tm/hm compatibility, evolved Pokémon are copying the tm/hm compatibility of their pre-evolved form if the mons' types are the same. This changes it to only do this if you select `prefer_types` or `completely_random`. I will be trying to come up with a better solution for this but this quick fix should suffice for now.
Running debugger w/ breakpoints and observing what appeared to be expected behavior.
> Pokémon R/B: Fix TM/HM compatibility bug

- worlds/subnautica/docs/setup_en.md
* The steps required to enable/open the console in Subnautica have changed in the recent big update. This updates the instructions.
* Added example for how to use `!hint`.
* Misc rewording for clarification.
* I don't know whether we are supporting the old Subnautica version at all. If we are, we should probably keep the old console enabling instructions, and also add a remark somewhere that we support both.
* I haven't added the upcoming `tracker` command. If Berserker wants, he or I can roll it into this PR.
> Docs/Subnautica: Updated console instructions, misc clarifications

- BaseClasses.py
- Generate.py
- Main.py
- Options.py
- WebHostLib/check.py
- WebHostLib/generate.py
- worlds/alttp/test/options/TestPlandoBosses.py
- worlds/sm/variaRandomizer/rando/RandoSettings.py
- worlds/sm/variaRandomizer/randomizer.py
convert mixture of Plando Options and Settings into just Options
also this
running generation on webhost and generate.py
> Core: convert mixture of Plando Options and Settings into just Options

- worlds/pokemon_rb/__init__.py
- worlds/pokemon_rb/options.py
Added `cerulean_cave_condition` to the `fill_slot_data` function to allow poptracker to auto-update the number required
Moved `option_disabled = 0` to the TrapWeight class to allow any trap in Red and Blue to be disabled
Added a contingency to traps such that if all are disabled, it won't give traps,
Running `Generate.py` to create a seed with all traps disabled but a `trap_percentage` greater than 0. Then posting the seed onto the online branch to check poptracker sees the new tag
> Pokemon Red and Blue: Updates to trap weights and tracker support

- kvui.py
In #1139 I added a QoL feature that makes CommonClient pre-select the port portion of the address on startup. I simply used `str.find(":")` to determine the port portion, which fails when the address contains other colons than the one separating the port.
This PR ensures the following cases are now handled correctly:
* The address has a username&password component (such as `Berserker:hunter2@archipelago.gg:50695`).
* An IPv6 address is specified (such as `[2001:4860:4860::8888]:38281`).
Additionally, the logic is extended to select the host portion if no port is present.
With various strings of all combinations of username&password component present ⨯ IPv6 address ⨯ port present.
> CommonClient: Fix address pre-selection

- worlds/factorio/__init__.py
prevents automation-1 and logistics-1 costing more than 10 red science, which just becomes tedious without them
Factory without Factory
> Factorio: fix automation-level tech costs before automation

- data/client.kv
- kvui.py
always display all tab headers
looking at it, mostly SC2 client as it has the Mission Launcher, which is not a logger.
From
to
> kvui: always display all tab headers

- Starcraft2Client.py
Old users who have never run the /download_data command in SC2Client do not have a version number for the maps on their system. This PR warns these users that their maps are probably outdated, and that they should run `/download_data`. This should cut back on people having issues with the Safe Haven and Haven's Fall missions.
Also, `/download_data` no longer accepts a parameter called `force`, and will now *always* force a download when run. This is to simplify the user interface; we did have an issue already where someone needed to force a download but didn't understand how to do it.
- Deleted version number file on a Windows 10 machine that already had the most recent map files
- Tried to connect to a server (the correct feedback appeared)
- Ran `/download_data` twice with no arguments …
> SC2Client: Changes to /download_data and feedback

- Main.py
Fixes a bug where locality rules would not be set properly on some locations (first discovered in Hollow Knight) due to no recache being triggered between their creation and `locality_rules` being called.
> Core: recache all locations before locality rules

- worlds/oot/EntranceShuffle.py
NL used to be unrestricted in its entrance shuffling, which would cause issues with items becoming unreachable -- in particular, Temple of Time could be unreachable which would render the game very definitely incompletable. It no longer gets to be special and cause problems, so now it has the same shuffling as glitchless.
> oot: remove special NL exceptions in entrance randomization

- worlds/factorio/Options.py
- worlds/factorio/__init__.py
adds ramping tech cost as an option
By loading it up in Factorio
Taken from 1-10000 cost with ramping on.
> Factorio: add option "ramping tech cost"

- worlds/subnautica/Rules.py
fix swim_rule 0 (easy) always considers items
`0 == False -> True`
also fix considers items actually working, as 3 or 4 or `5 == True -> False`
Basically this behaviour matrix was by accident in effect:
```
easy -> easy_items
normal -> normal
hard -> hard
easy_items -> easy
normal_items -> normal
hard_items -> hard
```
a quick look at a spoiler
> Subnautica: fix considers items firing wrong

- setup.py
import error on .build if cx-freeze is missing or outdated
running the script
> Setup: don't use dependency before it's installed

- Options.py
Currently the method `from_any` is declared as an abstract classmethod on the class `AssembleOptions`, but this is incorrect.
`AssembleOptions` itself is not an ABC to begin with (it actually is a metaclass for defining ABCs).
Instead, this PR moves the declaration of the abstract classmethod to the ABC whose metaclass is `AssembleOptions`, i.e., the class `Option`.
Honestly, the main reason this PR exists is because it ensures that PyCharm no longer points out that *subclasses* of `AssembleOptions` are incomplete because they do not implement `from_any`.
(We actually want to enforce this for *instances* of `AssembleOptions`, which is what this PR does.)
Before:
After:
```python
class OptionWithoutFromAny(Option[str]):
pass
OptionWithoutFromAny()
```
Before: Nothing
After: "TypeError: …
> core: properly declare from_any as an abstract classmethod

- BaseClasses.py
- LttPAdjuster.py
- Main.py
- OoTAdjuster.py
- worlds/alttp/Rom.py
- worlds/checksfinder/__init__.py
- worlds/dkc3/Rom.py
- worlds/factorio/Mod.py
- worlds/factorio/__init__.py
- worlds/hk/__init__.py
- worlds/minecraft/__init__.py
- worlds/oot/Cosmetics.py
- worlds/oot/Patches.py
- worlds/oot/__init__.py
- worlds/pokemon_rb/rom.py
- worlds/ror2/__init__.py
- worlds/smw/Rom.py
- worlds/spire/__init__.py
It'll probably lead to new errors, which in this case is good.
Global random source is yeeted before multithreaded stage, to prevent accidental non-determinism from this source.
It kind of tests itself.
> Core: replace global random state with descriptive error

- WebHostLib/templates/tracker.html
- WebHostLib/tracker.py
Add a column to the general tracker to display a percentage of checks completed in each seed. In response to games having different numbers of total checks, this allows players to see a normalized value to compare progress between them.
Ran webhost from source. Created seed with two different games. Completed different amounts of progress in each game. Verified percentage column displayed correct style formatting and correct values. Created second seed with two copies of same game. Forfeited one seed to confirm 100 percent completion displayed correctly.
> WebHost: add checks percent done column to tracker

- worlds/zillion/requirements.txt
This fixes a bug where putting too many player names for remote items in the rom would overflow to corrupt other data in the rom.
(This bug was discovered with the recent 1200 world async. 100 names was enough to make it overflow.)
generated a game with 120 player names for remote items and verified it was playable
completed a 3-player multiworld
> Zillion: fix name data overflow

- .github/workflows/build.yml
- .github/workflows/release.yml
Re build fix: this will now install more stuff in the venv, and then later downgrade `charset-normalizer` for `aiohttp`. Not sure if the fix is updating the venv ahead of time, or "priming" then venv with a good charset-normalizer, but it definitely works now.
As a side note: the linux build currently does not work because dkc3 and smw do relative imports outside of their root, but that's unrelated to this change.
> CI: sni update to v0.0.88 and fix build

- worlds/overcooked2/Logic.py
Horde logic used to be blanketed over all horde levels, but these two levels are significantly harder without the horde specific items. Require both horde items before logical access to these levels.
`python -m pytest ./worlds/overcooked2/test/TestOvercooked2.py`
> [OC2] Relax Horde Logic for Horde H-8 and Winter H-4

- worlds/lufia2ac/__init__.py
Fixes an entrance whose parent region did not coincide with the region that it was an exit from.
https://github.com/ArchipelagoMW/Archipelago/pull/1442
> lufia2ac: fix mismatched exits/parent region

- .gitignore
- data/client.kv
- kvui.py
allow user-defined text colors in data/client.kv
> kivy: allow user-defined text colors in data/client.kv

- test/general/TestImplemented.py
- test/general/TestReachability.py
> Tests: test that exits to `Regions` are the parents of the `Entrance`

- data/client.kv
- kvui.py
limit UI side logs to by default 1000 messages
by setting it to 1 and watching every message on the async delete the last one.
> kvui: limit UI side logs to by default 1000 messages

- worlds/AutoWorld.py
- worlds/alttp/Rom.py
- worlds/alttp/__init__.py
Moved lttp's enemizer check to stage_assert_generate and made the `LTTPWorld.use_enemizer` check a property and have it break once it finds the first lttp player that needs enemizer and checks for it, both giving a slight performance boost.
Generated with every world except zillion and lufia2. Generated with boss shuffle both with and without enemizer in AP
> LTTP: make the enemizer check a property and only check for it once instead of per world

- worlds/overcooked2/Options.py
- worlds/overcooked2/__init__.py
Discussion thread: https://discord.com/channels/731205301247803413/1060293978953621504/1060293981168214066
In short, my game gets the short end of the stick when paired against games with high amounts of filler. I've implemented a stop gap solution that uses location prioritization to prevent overcooked games from obsolescence. I recommend other games with high progression check density to take inspiration from this to insulate against the consequences of other worlds.
I've set `Compromise` as the default to ensure that this balancing never goes too far. Overcooked games on this default setting will *trend* towards fairness without ever surpassing it.
Generate and evaluate the spoiler log of several multiworld configurations containing Overcooked! 2
> [OC2] Location Balancing

- worlds/overcooked2/Items.py
- worlds/overcooked2/Logic.py
- worlds/overcooked2/__init__.py
- worlds/overcooked2/docs/en_Overcooked! 2.md
- worlds/overcooked2/test/TestOvercooked2.py
Before: 1 item activates all 4
After: 7 items activate 7 buttons, creating more divergent routes
Also, I consolidated the 6 filler emotes into a single "Emote Wheel" item to make space in the item pool.
I bumped my data version and min AP version to indicate this change.
The corresponding oc2-modding update is **v1.6.0**
Played a few local seeds. If I add more features in this version, then I'll probably ping for a beta test to clear the cumulative changes from any regression doubt.
> [OC2] Colored Ramp Button Items

- Utils.py
- WebHostLib/misc.py
- WebHostLib/templates/siteMap.html
* Sitemap game settings list, nolonger has links to games that dont have a setting page
* Added tutorials to the sitemap for easy access
Locally running the webhost
> WebHost: Add tutorials to sitemap and hide settings link for games without settings

- worlds/dkc3/Rules.py
- worlds/dkc3/__init__.py
- worlds/smw/Regions.py
- worlds/smw/Rules.py
- worlds/smw/__init__.py
No longer use out-of-world relative imports in SMW or DKC3 worlds, to prevent runtime errors with `.apworld`s.
- Generated several seeds of each game, with varying settings which would interact with the relative imports.
- Run `setup.py` and test generating and opening clients for multiple games, verifying there are no errors with at any point.
N/A
> SMW & DKC3: Remove relative imports

- worlds/timespinner/Options.py
Allowing yamls like
```yaml
RisingTidesOverrides:
Xarion: 
Dry: 50
Flooded: 450
CastleMoat: Flooded
CastleBasement:
#Dry: 20
Flooded: 450
```
Doing some generations locally
> Timespinner: Made keys optional

- worlds/timespinner/Options.py
- worlds/timespinner/PreCalculatedWeights.py
Allow different ways of specifying RisingTidesOverrides.
In the case of dictionary specification, verify that at least one of the weighted options is greater than zero for each of the options.
Rolling different yamls, and verifying that I get the expected errors for bad input.
> Timespinner: Make RisingTidesOverrides consistent with normal yaml behaviour.

- WebHostLib/tracker.py
https://discord.com/channels/731205301247803413/731214280439103580/1075228226399502366
ran webhost locally and opened the multitracker
> Tracker: get game names from slot_info instead of `multidata["games"]` and render custom game names on generic tracker

- worlds/dkc3/Rom.py
- worlds/smw/Rom.py
Same as for other games, this will resolve to ~/Archipelago on Linux, if the install folder is read-only
> DKC3, SMW: use user_path for file

- worlds/subnautica/Items.py
- worlds/subnautica/__init__.py
Vanilla Subnautica gives "Large Room" alongside "Multipurpose Room" always. New client is now released that breaks this bond and makes them independently shuffleable
locally so far, posted client and apworld to Subnautica channel.
> Subnautica: Allow either utility room for progression

- BaseClasses.py
#1467 removed all checks for `show_in_spoiler` and it is ignored. This adds a check back in so that locations with this flag are not written to the spoiler log.
Generating and observing the spoiler
> Core: Check for show_in_spoiler

- .github/workflows/unittests.yml
Adding macos to the unittest matrix to see if all dependencies work on macos (they should.)
We'll see once this fails or succeeds
> CI: run unittests on macos

- worlds/timespinner/Options.py
- worlds/timespinner/PreCalculatedWeights.py
- worlds/timespinner/__init__.py
The `RisingTidesOverrides` for `LakeSerene` was an oddity as rolling `Flooded` caused it to be `Dry` and vice versa
Also refactored the `PreCalculatedWeights` to reduce code duplication
Local generations + loaded up a few tests seed for confirmation
> Timespinner: Fixed Dry lake serene oddity

- Fill.py
item plando that selects from multiple worlds uses a set, which may return in different order when rolling the same seed twice
by running the new code once and checking if it still gives the same locations as before
> Item Plando: make world selection deterministic

- worlds/zillion/__init__.py
- worlds/zillion/logic.py
- worlds/zillion/options.py
- worlds/zillion/region.py
use `Option.current_key` instead of `Option.get_current_option_name()`
and other minor fixes (typing and docstrings)
a few generations, a single-player playthrough, and unit tests
> Zillion: use `Option.current_key`

- worlds/tloz/ItemPool.py
- worlds/tloz/Locations.py
- worlds/tloz/Options.py
- worlds/tloz/Rules.py
- worlds/tloz/__init__.py
Addressed some of the comments left by @alwaysintreble in the original PR, and a few things I came across
- consolidated declaration and population of level location lists
- moved floor_location_game_ids_late declaration for consistency
- moved generate_itempool to create_items, where it belongs
- mention that expanded pool includes take any caves in the option description again
- removed unnecessary StartingPosition check regarding Take Any Caves (leftover from older StartingPosition behavior I believe)
- use proper comparisons to option keys instead of hardcoded ints
some test generations and some debugging stepthroughs to make sure behaviors still worked as intended and items are being placed as they should
N/A
> TLOZ: Code Cleanup

- worlds/timespinner/Items.py
- worlds/timespinner/__init__.py
After community feedback, the method to guarantee at least one local progression item to be placed in the first 4 chests in lake desolation. has been restored. it was previously removed in a refactoring due to is overly complexity. but starting with only 4 checks strait into bk is no fun
local generations + debugging each path flow of the code
> Timespinner: Bring back starter progression item

- BaseClasses.py
Title
Generated and looked at the spoiler. Since I override Accessibility in The Messenger it was double printing
> Spoiler: Don't double print if world overrides common options

- Utils.py
- WebHost.py
- WebHostLib/__init__.py
- WebHostLib/autolauncher.py
- WebHostLib/customserver.py
- WebHostLib/downloads.py
- WebHostLib/templates/hostRoom.html
- WebHostLib/templates/macros.html
- docs/webhost configuration sample.yaml
automatically fill PATCH_TARGET -> HOST_ADDRESS and re-use it for rooms
sets timeout for retrieving public IP as well
Hopefully fixes broken rooms
with and without HOST_ADDRESS set on local windows machine.
> WebHost: automatically fill PATCH_TARGET -> HOST_ADDRESS and re-use it for rooms

- worlds/witness/Options.py
- worlds/witness/WitnessLogic.txt
- worlds/witness/WitnessLogicExpert.txt
- worlds/witness/WitnessLogicVanilla.txt
- worlds/witness/__init__.py
- worlds/witness/docs/setup_en.md
- worlds/witness/locations.py
- worlds/witness/static_logic.py
Death Link option has been added.
To facilitate the client showing the "cause" of death, slot_data now contains a dict from all entity IDs to their canonical AP names, rather than just EP names.
A new beta client has been released accordingly.
(I accidentally named one of the commits after the changes to the client, that's why the commit names are weird, oops)
> The Witness: Death Link + Small bug fixes

- worlds/alttp/__init__.py
- worlds/oot/HintList.py
https://discord.com/channels/731205301247803413/1082180010128965652
- OoT:
`getHint` was narrowly checking whether the type of a variable was equal to `str`, which did not correctly cover the case where the variable is an instance of a *subclass* of `str`. 
- ALttP:
The code around `build_shop_info` introduced by #1467 was bogus.
Successfully generating a game from the yamls posted in https://discord.com/channels/731205301247803413/1082180010128965652 with seed 0 using this PR merged with MMBN3
> oot/alttp: fix bugs found through MMBN3 testing

- worlds/alttp/ItemPool.py
bug that @Alchav found
Generated with and without plando with ice rod hunt as goal to make sure it output correctly.
> LTTP: fix ice rod hunt boss shuffle

- worlds/sm64ex/docs/setup_en.md
Added several sections in regards to opening the completed SM64 build with batch files instead of SM64PCLauncher.
> Docs: SM64 Guide update to explain how to launch the game with batch files

- worlds/pokemon_rb/__init__.py
- worlds/pokemon_rb/locations.py
If early_parcel is chosen and Dexsanity is on, do not allow the Parcel on dexsanity locations. There are no repeatable sources of income to fund Pokéball purchases before getting the Parcel and you could have to catch 20 Pokémon before finding the one that gives the Parcel.
Items added to pool when Dexsanity is enabled are changed from "any random filler" to Poké Balls, Great Balls, and Ultra Balls, as it can end up being quite expensive to purchase all the balls needed to catch every Pokémon.
Generated a seed on main where Oak's Parcel was at a Dexsanity location, used same seed number with this branch and Oak's Parcel moved to the Route 1 Free Sample Man. Also observed many Poké Ball items in the pool.
> Pokemon R/B: Version 3 final touches

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/lint.yml
- .github/workflows/unittests.yml
* the previous change had a typo, not always triggering build
* skipping of unittests is a bit more greedy now
* skip lint if no py changed
* skip CodeQL if no py and no js changed (probably good since it's our slowest workflow).
* update CodeQL since `@v1` is unsupported now
With what feels like a million branches on my fork :sweat_smile:
> CI: more filters, update CodeQL

- worlds/messenger/docs/en_The Messenger.md
- worlds/messenger/docs/setup_en.md
Made the tutorial a bit clearer and added file path for linux users. Removed an issue that was fixed in a newer courier release. Fixed a bad link.
Reading and clicking the links
> The Messenger: docs improvement

- MinecraftClient.py
add support for direct URL mod downloads which will allow better control over which APMC data version use which mod.
also make a nice error message if the chosen release channel is empty, rather than a hard crash.
> [Minecraft] Update MinecraftClient.py

- MultiServer.py
Fixes a bug where Archipelago was missing from datapackage_versions and datapackage_checksums.
Also includes "Archipelago" in games, so it gets picked up by clients instead of having to hard-code it in clients.
while updating apclientpp
> MultiServer: include 'Archipelago' in games, versions and checksums

- inno_setup.iss
The `inno_setup` had two separate entries for Link's Awakening. One was erroneous, and has been removed.
There aren't two anymore.
> Remove duplicate Link's Awakening setup

- worlds/pokemon_rb/rules.py
Had a random moment of realization that I forgot access rules on Pokemon Tower wild Pokémon, which is far more likely to be an issue now with Dexsanity as an option
Adds logical requirement for Silph Scope to catch wild Pokémon in the Pokémon Tower.
Generating and following code with breakpoints
> Pokémon R/B: Pokémon Tower Wild Pokemon logic fix

- WebHostLib/static/styles/landing.css
- WebHostLib/static/styles/themes/base.css
- Mobile view works properly on mobile Chrome and Firefox
- Added thin-window view for desktop browsers that have been reduced in size
- Tested in Chrome and Firefox on mobile and desktop
Tested on Chrome and Firefox, both on mobile and desktop
As seen on a mobile phone:
As seen on a desktop browser when the window is resized to be less than 960px:
> [WebHost] Improve mobile styles for WebHost

- worlds/ladx/LADXR/generator.py
- worlds/ladx/LADXR/patches/titleScreen.py
- worlds/ladx/__init__.py
Auth: we now generate a new random value for the auth value in `pre_fill`
Seed Name: Can now be anything. Truncated to 20 bytes, I can add back in the code to handle two lines and double that if people wanna go nuts.
This has the side effect of eliminating a lot of bytes<->hex conversions 👍
Locally - new auth works, the menu displays the custom seed_name. Custom seed_name tested by modifying `Generate.py`
> LADX: Pass in seed_name and auth separately

- MultiServer.py
- kvui.py
if there is a hint cost, don't make it 0
This fixes Clique being able to hint for all its items and locations if hint cost is lower than 50%
I didn't, sorry.
> MultiServer: if there is a hint cost, don't make it 0

- WebHostLib/customserver.py
give active rooms a chance to reclaim their port
on my local copy of a webhost so far, but I have little reason to suspect it shouldn't work on the main one.
> WebHost: give active rooms a chance to reclaim their port

- worlds/messenger/__init__.py
- worlds/messenger/docs/en_The Messenger.md
- worlds/messenger/docs/setup_en.md
While I wanted the release to be managed completely on a singular fork, Minous doesn't have the time to devote to this, so changing all the links to point to my fork to manage it. The mod is still completely backwards compatible and noted as such.
> The Messenger, Docs: Change links for the release

- worlds/ladx/docs/en_Links Awakening DX.md
Adding proper credits for the creators of the sprite sheets included in the LADX implementation, with links as requested by the creators.
> LADX: Added credits for included sprite sheets

- setup.py
A wrong indentation in setup.py made it stop working if cx_freeze was already installed.
https://discord.com/channels/731205301247803413/731214280439103580/1089325393330311199
> Setup: fix broken cx_freeze import

- worlds/dkc3/docs/setup_en.md
- worlds/sm/docs/multiworld_en.md
- worlds/smw/docs/setup_en.md
- worlds/smz3/docs/multiworld_en.md
- worlds/soe/docs/multiworld_en.md
The wording on the BizHawk steps to setup was unclear here:
https://archipelago.gg/tutorial/Super%20Mario%20World/setup/en#bizhawk
> 4. Click the button to open a new Lua script.
This is unclear because opening a "new Lua script" overwrites whichever one you choose.
It's a content change.
> Docs: Making steps for BizHawk setup clearer.

- worlds/dark_souls_3/data/locations_data.py
removed duplicate location for "PW: Vilhelm's Leggings"
removing a duplicate location i noticed while editing the map tracker
wasnt, just removed it.
> DS3: removed duplicate location

- worlds/pokemon_rb/rom.py
Fixes a crash during a sort when trying to fill out the number of available Pokémon if attempting to match types. Also changes to look at the original Pokémons' stats instead of whatever has been placed there already.
Generating with failures, using same seed # with changes successfully
> Pokémon R/B: Sort fix

- WebHostLib/static/assets/weighted-settings.js
Fix a bug causing weighted-settings UI to incorrectly display range values with no default as having a value of 25.
Tested locally on my development machine.
Using OoT as an example, the weighted-settings option `ganon_bosskey_rewards` configuration is:
```json
"ganon_bosskey_rewards": {
"type": "range",
"displayName": "Dungeon Rewards Required for Ganon's BK",
"description": "Set how many dungeon rewards are required to receive Ganon BK.",
"defaultValue": 9,
"min": 1,
"max": 9
},
```
This causes weigeted-settings to create a localStorage setting of:
And because options with a value of `0` are skipped during `.yaml` generation, the resulting file would contain:
localStorage settings are generated and saved before the UI for weighted-settings is generated. localStorage is used to populate …
> [WebHost] Fix weighted-settings UI incorrectly populating range values

- kvui.py
On kivy UI the default F1 keybind opens a settings menu, that seems to break the layout engine once closed
pressed F1 and nothing happened
> kvui: block settings menu

- worlds/ladx/LADXR/locations/shop.py
* Fixes gen failures due to trying to encode bad characters as ascii or otherwise
* Adds hints for the real item given for non LADX players
Locally
> LADX: Fix gen failures with non-ascii player names, fix missing custom

- worlds/ladx/LADXR/generator.py
- worlds/ladx/Options.py
* Adds option to enable nag messages when touching rocks (default off, as before)
* Adds option to always have the post "you got a sword" music (default on, a change in behavior)
Locally, to test the defaults, and then to invert them
> LADX: Add options for sword music and nag messages

- OoTClient.py
- Utils.py
- kvui.py
- worlds/pokemon_rb/rom.py
- worlds/tloz/Rom.py
* OoTClient did not allow absolute paths in host.yaml
* OoTClient used local_path instead of user_path for the ROM
* TLoZ used local_path instead of user_path for the ROM
* Pokemon R/B used local_path instead of user_path for the ROM
* kvui used local_path instead of user_path for user overrides
What is user_path? On a regular windows install user_path and local_path is the same. When running from a read-only directory, such as an AppImage (i.e. the user can't install ROMs into local_path), user_path points to the user's home folder instead.
It wasn't for the most part. I don't have the required ROMs. Would be good if people could verify i did not add typos.
> worlds,clients,kvui: use user_path

- WebHostLib/options.py
- WebHostLib/static/assets/weighted-settings.js
- WebHostLib/static/styles/weighted-settings.css
This PR adds support for `item-list`, `location-list`, and `custom-list` option types to the Weighted Settings page.
Tested locally on my development machine.
All three list types look the same, but here's a screenshot of each type anyway.
Locations List (Timespinner):
Items List (Kingdom Hearts 2):
Custom List (Timespinner):
> [WebHost] Add support for items-list, locations-list, and custom-list option types to weighted-settings

- worlds/tloz/Rules.py
Was informed that Pols Voice require certain weapons to kill that might not be guaranteed by the starting weapon. This is the only regular enemy in the game that cannot be killed by either any of the starting weapons or bombs which can be bought, so adding this rule should prevent any issues.
passed unit tests and ran about a dozen test generations
> [TLOZ] Pols Voice Logic Fix

- worlds/pokemon_rb/rom.py
- worlds/pokemon_rb/text.py
Fixes a crash that could occur during generation, or possibly worse, a crash that could occur *in-game* as the result of special characters in players' names.
Also fixes a possible incorrect quiz answer solution.
Generating games with special characters on main, observing crashes, using same seed to generate on this branch and observing text in game.
> Pokémon R/B: Another quiz fix

- worlds/factorio/docs/en_Factorio.md
Energy Bridges were changed to a 10MW throughput but this change was not reflected in the game page.
> [Factorio/Doc] Fixed outdated Energy Link troughput in Game Page

- WebHostLib/options.py
- WebHostLib/static/assets/weighted-settings.js
Restore "random" options to weighted-settings (as proposed by @alwaysintreble) and adjust capitalization of hard-coded settings
Tested locally on my dev machine.
> Restore "random" option to weighted-settings

- host.yaml
- worlds/adventure/docs/setup_en.md
Added an example for automatically loading adventure_connector.lua to setup.md and host.yaml
Viewed in PyCharm markdown viewer
> AdventureDocs: Added example for automatically loading adventure_connector.lua

- WebHostLib/templates/multiTrackerNavigation.html
Fixes the styling of the multitracker navigation element.
Specifically, this ~~reverts~~ *fixes* a refactoring of the code that resulted in the class of the selected button becoming `tracker-navigation-buttonselected`.
Accessing the multitracker
Broken:
Fixed: (different game)
> WebHost: Fix broken styling of multitracker navigation

- worlds/overcooked2/__init__.py
- The location balancing option for overcooked was accidentally generating 44 sets of priority locations instead just one set
pytest
> [OC2] Only Calculate Priority Locations Once

- AdventureClient.py
I'm fairly sure this is more correct, and the user_path way may actually have been broken if installed in a location without write access.  
Built exe and ran from outside home directory.
> AdventureClient: Change user_path to local_path for locating basepatch file

- worlds/blasphemous/Rules.py
Fixing some small mistakes in logic related to not having enough fervour to use Aubade of the Nameless Guardian or Tirana of the Celestial Bastion.
> Blasphemous: Small logic fixes

- .github/workflows/build.yml
- .github/workflows/release.yml
18.04 will not be supported starting 2023-04-01
Merge as late as possible. Getting the old libc into the next release would be nice.
> CI: update ubuntu to 20.04

- CommonClient.py
- MultiServer.py
```
/missing <Text>
!missing <Text>
!checked <Text>
```
```
/missing AP-1 in FactorioClient
!missing AP-1 in FactorioClient
!checked AP-1 in FactorioClient
/missing in FactorioClient
!missing in FactorioClient
!checked in FactorioClient
```
> Network: allow filtering checked and missing by text fragment

- worlds/AutoWorld.py
- worlds/blasphemous/__init__.py
This allows new (ap-)worlds to function with old clients without having to define a version.
> Core: default data_version to 0

- worlds/stardew_valley/docs/setup_en.md
The link from the Stardew Setup Guide to the Stardew Settings page was broken and was leading to an error 404
Now it works properly
> Fix broken link in Stardew Setup Guide

- worlds/sm64ex/__init__.py
- worlds/v6/__init__.py
For #1460 
Only modify itempool in `create_items` for V6, sm64ex.
sm64ex was only doing item creation in `generate_basic` anyway, so it was just renamed.
v6 also did music randomization. This was kept in `generate_basic`, while itempool mods were moved to their own `create_items` function.
Tested normal generation.
> sm64ex,v6: Use create_items for itempool modification

- worlds/blasphemous/Rules.py
- worlds/blasphemous/__init__.py
- worlds/blasphemous/docs/setup_en.md
Updating setup docs to include a link to the poptracker pack for Blasphemous, changing items to be created during `create_items` instead of `generate_basic`, and fixing a typo in the rules.
> Blasphemous: Update docs, item creation

- MultiServer.py
Makes server save on more changes than just location checks, as we have more state than that nowadays.
Firing up a local webhost, seeing the Disconnected in the Tracker change to Connected by only connecting with TextClient and waiting a moment.
> MultiServer: Flag for saving on datastore, create_as_hint scout and client state change

- MultiServer.py
remove remaining forfeit compat from network layer
all the remaining compat is in loaded an old server savegame, which might have to stay forever if we want to still load those.
I technically tested that back when we first tried to remove forfeit and had to put this back for compat. Haven't tested this in isolation, let me know if I should.
> MultiServer: remove remaining forfeit compat from network layer

- docs/running from source.md
Makes it more obvious that build tools is entirely optional. Also updates the link directly to a very well hidden version of just build tools. Also describes *which* part of build tools is necessary.
Just re-installed windows so i had to go through this process.
> Docs: Add some more details to running from source doc

- worlds/factorio/Locations.py
- worlds/factorio/Mod.py
- worlds/factorio/Shapes.py
- worlds/factorio/Technologies.py
- worlds/factorio/__init__.py
instead of 255, 127, 85 etc. Locations for the respective science packs, the pools are now a clean 255, 255, 255 etc. 
When selecting Locations for the generation, this means a roughly equal amount of Locations per highest pack.
Raising min Client version to 0.4.0, while technically not required, it does prevent a confused client if:
0.3.8 Client connects to 0.4.1 Multiworld, then connects to a 0.4.0 or 0.3.8 Multiworld where IDs are changed but checksum is not yet in place.
I looked at a spoiler log.
> Factorio: flatten science pack curve

- Options.py
allows using a list or tuple or such to provide allowed keys for Options in an ordered way, so that UI can use that ordering.
By posting this to discord and having others do it.
> Core: ordered valid keys

- WebHostLib/options.py
- WebHostLib/static/assets/weighted-settings.js
Sets the default values for `OptionSet`/`OptionList` with `valid_keys` and defined defaults.
I opened my browser, cleared the localStorage and looked at a couple games with defined defaults, like Rogue Legacy.
> WebHost: Set defaults for lists/sets on Weighted Settings page

- BaseClasses.py
- Main.py
See title.
Ran a generation with an ALTTP (which uses it) and StS (which does not) and it successfully generated.
N/A
> Core: Band-aid fixes `start_inventory_from_pool` causing generation failures if any world doesn't utilize it.

- worlds/tloz/__init__.py
Adds proper handling of FileNotFoundError for if the program cant find the TLOZ base rom (i.e. someone forgot to put their base rom into the folder)
Ran a local generation and a webhost generation and got the proper error message.
> [TLOZ] Add FileNotFoundError handling for base rom

- worlds/ladx/LADXR/generator.py
- worlds/ladx/__init__.py
Gfxmods that used a full graphics file (ported from LADX, all our included sprites are bsdiff4 only) would overwrite the egg tiles. Instead of applying the patch first, I now apply it last
Locally. Used `Rosa.bin` from LADXR, noted large pink egg, even with title screen patch on. After this fix, the egg looks correct.
> LADX: fix egg sprite in non-patched gfx mode

- MultiServer.py
Ping argument seems to have changed in an update of websockets. This uses the lib's default of 20s now.
Wasn't
> MultiServer: fix broken ping

- data/lua/connector_adventure.lua
Fixes a connector_adventure.lua script bug that throws in BizHawk 2.9, breaking the connection, when a local item is touched by the player.  This is the fix I mentioned I'd need to make when discussing PR#1685
Added logging to verify local item location state.  Collected a local item using 2.8 to create a save that allowed for quick access.  Checked that this broke in 2.9.  Applied fix and verified that it works properly in 2.8 and 2.9.  Removed logging that was used to verify the local item location state.
> Adventure: Fix error in connector lua that was fairly harmless in BizHawk 2.8 but throws in 2.9

- worlds/sm/__init__.py
- worlds/sm/variaRandomizer/graph/graph.py
- worlds/sm/variaRandomizer/graph/location.py
- worlds/sm/variaRandomizer/logic/smboolmanager.py
- worlds/sm/variaRandomizer/rom/rompatcher.py
- worlds/sm/variaRandomizer/utils/objectives.py
fixed bad comeback check logic:
- fixed wrong condition in Collect to assign lastAP
- ~~limited comeback check to filling stage~~
- ~~now excludes items that can open doors from progression balancing if Area or Door Rando is used~~
- fixed possible infinite loop in generating output when many SM worlds are present
- fixed new VARIA code that changed a list used for every SM worlds and would throw if many SM worlds uses Aea rando and not AreaLayout
edit: 
fixed failing unit test that put to light a destructive collection state that could happen in can_comeback, allowing for a unified comeback check solution that doesnt limit it to filling stage and doesnt need to exclude items that can open doors from progression balancing.
I generated a lot of multiwords with 20 SM worlds having random …
> SM: failing generation fixes

- worlds/alttp/Client.py
had the parens around the sets incorrect.
Rolled a seed and did two checks. First one without connecting and second after connecting.
> LTTP: Fix bad parens in new check logging

- kvui.py
sizing for kivy is wrong on macOS
ran commonclient.py on both windows and macOS
> [kivy] change the sizing for macOS

- worlds/messenger/__init__.py
Players are unable to connect to the multiworld if their names are invalid so going to straight up prevent it from generating.
Did a few test generations with `_` ` ` and some invalid characters
> The Messenger: Throw error for invalid names and replace `_` with ` `

- worlds/stardew_valley/options.py
During the development of 3.x.x, we renamed an option in fishsanity from random_selection to randomized
This adds an alias so that older yamls don't break on it
Ran the automated tests
> Stardew Valley - Add alias for renamed Fishsanity option

- MultiServer.py
A few days ago we upgraded WebSockets, what I didn't notice then is that there is now a proper close method, so we can use that instead.
Ran /exit and it did indeed exit.
> Multiserver cleaner exit

- worlds/alttp/Rules.py
- worlds/generic/Rules.py
Core: correct typing info for item_in_locations
Core: rename item_in_locations to item_name_in_location_names
Core: add actual item_name_in_locations
The current state of it seems to have lead to confusion in https://github.com/ArchipelagoMW/Archipelago/pull/1757, where a single Location was passed but it expects pairs of item names and player number, however neither the naming scheme nor the typing info pointed this out correctly.
unittests
> Core: correct typing info for item_in_locations

- worlds/zillion/__init__.py
There was a low probability that the Zillion 1st sphere could be empty.
It caused this test failure: https://github.com/ArchipelagoMW/Archipelago/actions/runs/4791795268/jobs/8522615992
unit tests
a few generations
and some test code (now commented out) to force the rare event and see the new log message
> Zillion: fix empty 1st sphere

- data/lua/common.lua
URange wasn't moved to common.lua (and no longer exists in connector_ff1.lua) when the lua files were changed for Bizhawk 2.9 socket change.
(This could also be added to the connector_ff1.lua instead if preferred since I believe it's the only one that leverages it but this is where those functions were centralized)
The socket change/lua changes broke functionality for FF1Client when they were restructured since the URange function was removed.
Tested vs Bizhawk 2.8 and 2.9, works for both. (Otherwise they failed to connect since they couldn't read the slot name/location/item names in the rom)
The original lua fix corrected the main socket issue this function just got forgotten in the move.
> FF1: Added URange fix for Bizhawk 2.9 support

- worlds/subnautica/Options.py
- worlds/subnautica/__init__.py
adds free_samples to Subnautica, very similar to Factorio
With various item types at least once (vehicles, compound items, regular items, fragments etc.)
Did not test the whole range of items, but in testing I noticed that the game just creates dummy items for BS, so should be easy enough to fix if it comes up and not be fatal.
> Subnautica: add free samples option

- docs/options api.md
Noticed that the option documentation missed defining aliases. Moved where sub option definition is since it's a longer section and not always necessary.
Read it.
> Docs: document option alias in the options doc

- worlds/ror2/Rules.py
If the locations were less then 50 it wouldn't run any rules on locations and just put everything in sphere 1
Generated multiple times
> [RoR2] Classic mode logic fix

- WebHostLib/__init__.py
- WebHostLib/autolauncher.py
A few days ago we noticed slowly increasing memory use on processes that generate worlds. This change should reclaim that memory again and by default no longer use the webthreads to gen, leaving them out of the problem.
Finding the root cause would still be nice, but this at least treats the symptom.
by setting maxtasksperchild to 1 and seeing python.exe processes appear and disappear.
> WebHost: recycle generator processes

- NetUtils.py
- Utils.py
Python 3.11 changed to pickle/store enums by name rather than by value. This breaks our safe unpickle, it produces bigger pickles and it makes it impossible to rename keys in enums after the fact.
Changing it back to ByValue produces the same output as py<=3.10.
Change in python is here: https://github.com/python/cpython/pull/26658
```
$ python --version
Python 3.11.3
$ Generate.py
$ MultiServer.py ...
/send Player1 A Shrubbery
/save
$ MultiServer.py ...
Loaded save file with 1 received items for 1 players
```
> Core: store multidata/multisave enums by value on py3.11

- Main.py
Core: fix start_inventory_from_pool breaking if it's removing the last instance of an item from pool.
Core: fix start_inventory_from_pool removing arbitrary items from pool if quick abort branch is entered.
https://discord.com/channels/731205301247803413/1103404853654470706
> Core: fix start_inventory_from_pool 

- Launcher.py
This fixes multiprocessing in the Launcher when frozen.
On local build, with a func Component spawning a process with multiprocessing.
> Launcher: allow multiprocessing

- WebHostLib/options.py
Thanks HK.
Fix for bug introduced in #1614. Just needed to ensure we ignore `OptionDict`-derived objects/classes since we aren't rendering them anyway.
Fixes this:
Ran WebHost.py and checked to see if error reappeared. 
It did not, nor did it get outputted in exported yaml.
> WebHost: Prevent `dict` type options with `valid_keys` from exporting with `[]` on weighted settings.

- worlds/tloz/ItemPool.py
Makes a fresh copy of starting weapon locations when get_pool_core is ran
Should fix the issue of dangerous_weapon_locations getting appended to the list for other worlds past the first world that has dangerous StartingPosition, as well as running into the error if ExpandedPool was different between players
Credit for fix goes to @Silvris in the AP Discord
(also apologies for stupid commit history. sleepy Figment accidentally committed to my main at first instead of making a new branch)
Ran a few gens with a weights yaml for 100 TLOZ worlds
> [TLOZ] Fix start weapon locations

- KH2Client.py
When reconnecting and getting a 0 packet it doesnt reset the inventory slot so it starts from where it left off instead of at the beginning.
I connected to the server, got a ability from the server then disconnected then reconnected and it didnt overwrite/duplicate the ability
> KH2: Ability Sync Fix

- worlds/alttp/Dungeons.py
If dungeon items from minimal worlds were to be filled during `fill_dungeons_restrictive`, the completion condition would not be cleared from `all_state_base` before filling, which caused the accessibility checks to never trigger. This removes the condition to ensure that the fill proceeds correctly.
https://discord.com/channels/731205301247803413/731214280439103580/1104724505806524457 yamls no longer fail to roll.
> ALttP: fix minimal + dungeon item fill interaction

- worlds/witness/WitnessLogicExpert.txt
The Swamp Cyan Underwater Sliding Bridge EP check requires using the Swamp Cyan Underwater Sliding Bridge Control.
Both the upstairs control and the underwater control require Shapers & Black/White Squares on Expert, but the underwater one only has the vanilla/normal requirement in the Expert logic file.
ExemptMedic showed that it is possible to plando Black/White Squares onto Swamp Cyan Underwater Sliding Bridge EP in an Expert seed, which means this creates broken seeds.
> The Witness: Logic fix in response to broken seed (Expert Swamp)

- worlds/alttp/__init__.py
use local_early_items for Small Key HC in Standard Keyshuffle
Fixes LttP creating an extra Small Key in that mode combo, correcting the item pool counts.
with and without the conditions for this item placement met.
> LttP: use local_early_items for Small Key HC in Standard Keyshuffle

- KH2Client.py
When getting a drive form normally sora's anti points reset to 0. However, when writing the form into sora's inventory doesn't trigger the game to do this so I do it manually. 
I had 1 anti point and gave sora a drive form then it reset to 0.
> KH2-AntipointReset

- worlds/blasphemous/Rules.py
Fixing logic errors in WotHP where keys and relics that should have been required were not.
Going to the rooms in question and comparing AP's logic with the non-AP rando's logic
> Blasphemous: Fixed logic errors in WotHP

- Utils.py
For whatever reason, running SNIClient from source may run websockets at DEBUG log level. Make sure it's correctly set.
Running SNIClient before and after the change and looking at logging output.
> Logging: make sure level is applied for websockets

- docs/world api.md
Changed the description of excluded and priority locations to match how they appear in other places such as the options api doc
> Docs: Update world api excluded/priority locations description

- worlds/messenger/Options.py
Updates the description and display name to properly represent how start_inventory works in my game.
Looked at the generated yaml template. Does not get properly represented on the website and changes nothing there.
> The Messenger: override start_inventory description

- WebHostLib/models.py
```
[2023-05-19 19:11:01,203] GET NEW CONNECTION
[2023-05-19 19:11:01,205] SELECT COUNT(*)
FROM `room` `room`
WHERE `room`.`creation_time` >= %s
[datetime.datetime(2023, 5, 12, 19, 11, 1, 203309)]
[2023-05-19 19:11:11,214] SELECT COUNT(*)
FROM `seed` `seed`
WHERE `seed`.`creation_time` >= %s
[datetime.datetime(2023, 5, 12, 19, 11, 11, 214101)]
[2023-05-19 19:11:27,055] COMMIT
[2023-05-19 19:11:27,056] RELEASE CONNECTION
```
Gets turned into:
```
[2023-05-19 19:16:47,013] GET NEW CONNECTION
[2023-05-19 19:16:47,014] SELECT COUNT(*)
FROM `room` `room`
WHERE `room`.`creation_time` >= %s
[datetime.datetime(2023, 5, 12, 19, 16, 47, 12650)]
[2023-05-19 19:16:47,015] SELECT COUNT(*)
FROM `seed` `seed`
WHERE `seed`.`creation_time` >= %s
[datetime.datetime(2023, 5, 12, 19, 16, 47, 15504)] …
```
> WebHost: index columns used by landing page.

- Generate.py
Logs that race mode is enabled.
Also does a bit of cleanup
Once
> Core: log race mode enabled

- worlds/blasphemous/Rules.py
This makes a few changes to logic to better match the 1.3 rando's logic. This fixes instances where the wrong items were expected, fixes a typo of "Lorqiana", moves the expert logic on "PotSS: Second area ledge" to only apply if on expert, and adds a new route to "DC: Mea Culpa altar" via Linen of Golden Thread + Three Gnarled Tongues
By comparing the AP logic to the rando 1.3 logic. The Mea Culpa route was tested manually, in-game.
> [Blasphemous] Various logic fixes

- WebHostLib/requirements.txt
Makes WebHost work in Python 3.11
running webhost generation and hosting of a Factorio world locally.
> WebHost: use Py3.11 compatible ponyorm

- test/worlds/__init__.py
Sorts tests by folder, resulting in less categories created from our custom loader. Possibly only visible in PyCharm?
turns
into
> Tests: sort custom loaded tests

- test/general/TestReachability.py
makes Reachability tests' names a bit more unique and slightly improves them
> Tests: make names more unique

- worlds/blasphemous/Rules.py
Logic fixes for WotBC Cherub with Dawn _or_ Wheel and "Jondo upper west tree root" with Wheel + Ranged on expert.
Comparing to 1.3 logic and in-game testing.
> Blasphemous: Two small logic updates

- worlds/generic/docs/advanced_settings_en.md
Changed wording for items accessibility to describe how it actually works. Changed "none" accessibility to "minimal". Added description for `priority_locations`. Reordered settings such as `local_items` and `start_location_hints` to match their order in templates. Removed negative connotation from sentence about editing YAMLs.  Fixed some grammatical errors.
Reading
> Docs: Update YAML planning guide

- inno_setup.iss
- worlds/alttp/__init__.py
- worlds/alttp/docs/multiworld_en.md
Cleans out /SNI/lua and /EnemizerCLI/ on install/update
watched outdated lua files in SNI poof during setup.
As I was using current cx-Freeze, AP itself didn't work, but that should not be related.
> Setup: delete outdated Enemizer and SNI files

- SNIClient.py
Auto launches SNI if it isn't already running, before opening the browser, if the `.apsoe` is patched through SNIClient.
> Secret of Evermore: auto launch SNI before browser when SNIClient patched

- setup.py
worlds being just their init and nothing else.
Upstream bug: https://github.com/marcelotduarte/cx_Freeze/issues/1907
> Setup: pin cx-Freeze to latest working version

- Launcher.py
- Utils.py
- worlds/LauncherComponents.py
removes that any callable is always FUNC, instead of say CLIENT
running Launcher.py
> Launcher: deprecate FUNC Component type

- WebHostLib/api/generate.py
- WebHostLib/check.py
- WebHostLib/requirements.txt
- WebHostLib/upload.py
DeprecationWarning: 'flask.Markup' is deprecated and will be removed in Flask 2.4. Import 'markupsafe.Markup' instead.
I started the webhost.
> WebHost: import Markup from markupsafe

- worlds/raft/__init__.py
Raft is prefilling frequencies incorrectly when multiple Raft worlds with different frequencies are used in the same multiworld. This makes Raft worlds use their own items instead of any Raft world's items.
Currently, what Raft's prefilling is doing is it's looking for the first item with a given name in the item pool. When every Raft player in a multiworld has similar settings (in this case, everyone either has prefilled items or does not have prefilled items), this is not a problem -- players' items are inserted into the item pool and removed from the item pool in (hopefully) the same order, so their generations are correct. However, when there are different settings in different Raft worlds, problems arise. Now, the Raft worlds that prefill items are at risk of using _other_ Raft …
> Raft: Fix item prefilling

- worlds/dlcquest/data/__init__.py
- worlds/witness/WitnessLogic.txt
- worlds/witness/WitnessLogicExpert.txt
- worlds/witness/WitnessLogicVanilla.txt
- worlds/witness/__init__.py
- worlds/witness/hints.py
- worlds/witness/items.py
- worlds/witness/locations.py
- worlds/witness/player_logic.py
- worlds/witness/rules.py
- worlds/witness/settings/Disable_Unrandomized.txt
- worlds/witness/static_logic.py
- worlds/witness/utils.py
Changes:
- Hints should feel a lot less same-y now ("Priority hints" are no longer always hints in disguise)
- Keep Hedge Mazes 1-3 and Pressure Plates 1-3 are added as locations in all settings
- Desert Final Room Hexagonal & Desert Final Room Bent 3 are added as locations
- Entries in exclude_locations that are referring to panels are now sent through slot data. This means they can be pre-skipped on the client side.
Fixes:
- Logic error in the Stoneworks that led to more restrictive seeds than necessary
- Logic error for Theater Flowers EP that led to more restrictive seeds than necessary
- Fixed crash in plando when "item" is a dict with weights
- Spoiler log locations were in random order per region, now they are consistent
> The Witness: Hint distribution changes, added locations, misc fixes

- worlds/ladx/Items.py
- worlds/ladx/Locations.py
- worlds/ladx/__init__.py
https://github.com/ArchipelagoMW/Archipelago/issues/1840
use custom collect/remove to keep track of logical rupee counts instead of LogixMixin
Didn't test, but it should be marginally faster
May contain some pep8, sorry
only once so far
@zig-for
> LADX: use custom collect/remove to keep track of logical rupee counts instead of LogixMixin

- CommonClient.py
- requirements.txt
On Windows, the local cert store might be outdated and refuse connection to some servers.
Certifi bundles its own cert store. The only real downside is that outdated AP installations will always have outdated certificates since we bundle the certificates with the installer.
Connecting to a ws:// and a wss:// room.
> Clients: use certifi

- docs/adding games.md
- docs/contributing.md
- docs/world maintainer.md
Adds responsibilities of world maintainers/authors to the docs and proposes some rules how to fairly vote in and out maintainers.
Who should we ping?
> Docs: add info about maintaining worlds

- WebHostLib/static/assets/player-settings.js
Discord Bug Report: https://discord.com/channels/731205301247803413/1113657616397246544
> **Exempt-Medic**: If you go to any game's settings page and set progression balancing to Custom and then click the die to randomize it and then click the die again to unrandomize it, the progression balancing gets given a value of "custom" and attempting to generate gives the error:
> > Something went wrong and your game could not be generated. {'player': 'Failed to generate mystery in player: Error generating option progression_balancing in The Witness'}
---
When toggling randomization off on any "Special Range" type option on a player settings page, it would update the "value" of the option to: `custom`, causing a generation issue as its not a valid option.
This fixes that issue by preventing an …
> WebHost: Fix special-range value setting to `custom` when randomization is toggled off

- worlds/witness/locations.py
All Keep Pressure Plates puzzles are now always locations.
This makes a line where a Pressure Plates location gets conditionally added and a different one removed cause incorrect behavior.
> Witness: Fix missing location

- docs/running from source.md
GIt is required to install the Zilliandomizer package.
Also, this is probably just nice to have.
> Docs: Mention Git in the "Optional" section of "Running from Source"

- worlds/dlcquest/Options.py
- worlds/dlcquest/Rules.py
Re-write documentation for the settings page so it reads better and is more clear.
It's documentation. I ran the test suite.
> DLC Quest - Documentation improvements

- Launcher.py
- Utils.py
- use "spawn" to launch multiprocessing from Launcher - this is default on Windows, but has to be set explicitly on Linux and mac since the default "fork" breaks kivy
- implement the windows-exclusive freeze_support fix for non-windows to allow "spawn" to work on non-windows - this is a very old bug in upstream python
by launching bfbb client and factorio client on Linux via multiprocessing in a frozen build
> Linux: add freeze_support, Launcher: use spawn

- setup.py
- worlds/hk/__init__.py
- worlds/oribf/Rules.py
- worlds/oribf/__init__.py
technically, makes Ori BF an apworld.
The goal however is to have a list of worlds that have yet to convert to apworld compatible and I'd also like to mandate going forward that no worlds are ever added to this list.
Running Launcher and TextClient and looking into the log for exceptions.
> Setup: flip apworld list

- setup.py
- worlds/witness/__init__.py
- worlds/witness/rules.py
Removed relative imports from outside the Witness package. Then, removed Witness from the apworld exclusion list in setup.py
Tested: python setup.py build_exe, go to the build, confirm that a witness .apworld was created, generate a seed with a Witness world. It worked, although I got some errors from oribf and stardew valley which I thought I'd mention
(Python 3.9)
> Witness: APworld compatibility, but for real this time

- worlds/oribf/__init__.py
Fixes oribf apworld failing to load on py3.8 and minor import cleanup.
`python3.8 setup.py build_exe` on Linux and then generating any game (not oribf). It would show an error loading the world before the commit and not complain after the commit
> OriBF: fix py3.8 apworld compatibility

- Generate.py
- Main.py
Adds a command line argument for `Generate.py` to skip progression balancing step, regardless of individual player `progression_balancing` settings. Argument is called `--skip_prog_balancing`.
Run with command line: `python Generate.py` (No changes)
```
Archipelago (0.4.1) logging initialized on Windows-10-10.0.22621-SP0 running Python 3.10.8
P1 Weights: Test1.yaml >> Generated by https://archipelago.gg/
P2 Weights: Test2.yaml >> Generated by https://archipelago.gg/
Generating for 2 players, 48891933062538200934 Seed 99530657785344493820 with plando: bosses
Archipelago Version 0.4.1  -  Seed: 99530657785344493820
[...Worlds Info...]
Creating World.
Creating Items.
Calculating Access Rules.
Running Item Plando
Running Pre Main Fill.
Filling the world with 145 items.
Balancing multiworld …
```
> Generate: Add skip progression balancing argument.

- Launcher.py
- worlds/LauncherComponents.py
Alternative to https://github.com/ArchipelagoMW/Archipelago/pull/1892, that makes each window closable independently.
Only with TextClient on Windows
> Launcher: keep alive

- WebHostLib/templates/multiTracker.html
Aligns the status column head in the multitracker to the left, to align with the column's content. Consistent with the rest of the design.
Accessing the multitracker
Before:
Now:
> WebHost: Align multitracker status column to the left

- LinksAwakeningClient.py
:(
Little endian so that old saves don't break. Probably.
Tested by loading up RiversDX in the big async. It had more than 256 items queued up because of abuse of start items.
> LADX: 16 bits for the check ID

- WebHostLib/templates/multiTracker.html
Checks sorting should sort by checks completed not the formatted string displayed.
Uses [orthogonal data](https://datatables.net/manual/data/orthogonal-data#HTML-5)
Using dummy data for a generated game in multi-tracker
[Before]:https://github.com/ArchipelagoMW/Archipelago/assets/1796312/e317a1dd-6d6c-4475-8b72-0ca5984e9ae1
[After]:https://github.com/ArchipelagoMW/Archipelago/assets/1796312/6b29900b-31bc-4233-8e18-8016ca2e2983
| Before | After |
| ------ | ------ |
| ![Before] | ![After] |
> WebHost: Fixes multi-tracker checks sorting.

- worlds/messenger/__init__.py
- worlds/messenger/test/TestShop.py
I added a unit test that tests the shop costs with the minimum amount of generated locations. With the settings in that test only 6 items can possibly be currency and if none of those have a value over 100, then all of the shop locations are immediately accessible. There's still settings where a player can have even 0 possible currency items but that's their own fault, which is fine. This change is primarily so the unit test doesn't fail by slicing the filler dictionary before filler is created if the amount of items that still need to be generated is sufficiently small.
Ran the unit test about 100 times. There's still a very slim chance it can fail if the random object generates 6 "Time Shard (50)". Only way to fully prevent that is to slice the dictionary an additional value. Will do if …
> The Messenger: strip generated filler items for a sufficiently small pool

- worlds/factorio/data/mod_template/control.lua
/resync or general resume currently ignored indexes where anything is stored, rather than matching content is stored, skipping awarding of that item in rare cases.
Killing the MultiServer savegame and reshuffling receive order in a new savegame. Traps trigger again, but that's a minor price to pay.
> Factorio: fix resync not reconciling divergent history

- worlds/lufia2ac/Options.py
- worlds/lufia2ac/__init__.py
When the `boss` option is used to change the encounter on the final floor, a matching dungeon sprite will now be loaded instead of the Master's sprite. The music during the fight will also match the battle theme used for that boss during the main game.
Aside from being visually consistent, this has the additional advantage that players who selected mystery bosses can now see which kind of foe they are about to encounter, and can thus change their equipment accordingly before starting to fight. 
See screenshots.
> lufia2ac: use an appropriate dungeon sprite and battle theme for each boss

- worlds/sa2b/docs/setup_en.md
Add note about known issue wherein the Mod Loader option `Skip Intro` prevents Cutscene Traps from playing.
I read it.
> SA2: Add troubleshooting note about Skip Intro and Cutscene Traps

- data/lua/connector_mmbn3.lua
Fixes the Lua code for determining which index a program should use for color to properly set Press Program (and the starting programs of BlkMind, EnrgyChng, and Alpha, in case they are ever randomized in the future).
Manually toggled bits to find the proper index for these programs, rewrote the lua script to include them properly in their group, and ran a local seed to test if `!getitem` gave the program with the right index. Memory viewing confirmed proper bit was set, and item was properly accessible in inventory.
> MMBN3: Press program now has proper color index when received remotely

- worlds/hylics2/Items.py
- worlds/hylics2/Locations.py
- worlds/hylics2/Rules.py
- worlds/hylics2/__init__.py
I thought I found everything in this game while I was first working on it but it turns out I missed this one spot.
> Hylics 2: Add missing location

- worlds/musedash/test/TestPlandoSettings.py
This fixes a rare test failure where the one of the included songs actually ended up chosen as the goal song.
Confirmed that the test pass when one song was a goal song.
> Muse Dash: Fix Rare Test Failure

- worlds/AutoWorld.py
#1649 added self.random with a correct type hint, but didn't import random, which caused the hint to be interpreted as `Any` (at least in VS Code for me)
Seeing VS Code pick up the type hint in other files and running `Generate.py`
N/A
> Core: Import `random` for type hint on World.random

- worlds/sc2wol/__init__.py
Fix SC2 for added unit test in #1460 
Making itempool only modified during create_items
Generated a game and ran the affected
> SC2: Move itempool generation logic from `generate_basic` to `create_items`.

- worlds/raft/__init__.py
Making itempool only modified during create_items, rather than in prefill.
Generated Raft worlds with different configurations that generated different items/prefills to make sure they still worked. Ran unit tests, including the one in [PR 1460](https://github.com/ArchipelagoMW/Archipelago/pull/1460/files) (modified so it only ran for Raft). Everything passed and worked as expected.
> Raft: Only modify itempool during create_items

- worlds/dark_souls_3/docs/setup_en.md
Added instructions for downpatching Dark Souls III, which is required by the archipelago mod
I have tested that the mod works using the linked downpatching method
> DS3, Docs: Add downpatching instructions to Dark Souls III setup guide

- WebHost.py
`zfile.filename` is the full path within the archive, so by default `zf.extract` will maintain that directory structure when extracting.
This causes the docs to be placed in the wrong place, as the Javascript code expects them to be placed directly in the game folder.
Added `mmbn3.apworld` to my `worlds/` folder and ran `WebHost.py`. Prior to my change, this created `WebHostLib/static/generated/docs/MegaMan\ Battle\ Network\ 3/mmbn3/docs/` and copied `en_MegaMan Battle Network 3.md` and `setup_en.md` there, which is incorrect (note the extra `/mmbn3/docs` in that path). Trying to open either of these pages from the link in `/games` leads to a 404.
After my change, `mmb3/docs/` folders are not created. Instead the two .md files are copied into `WebHostLib/static/generated/docs/MegaMan\ …
> WebHost: Fix docs generation from a .apworld

- worlds/smz3/TotalSMZ3/Patch.py
SMZ3's Ganon Sign previously erroneously told the user how many crystals the "ganon_vulnerable" config option rolled, regardless of if it chose the AllDungeonsDefeatMotherBrain goal.
A game was generated with the problematic settings and the sign was read to confirm the text change. A second game was generated with normal settings to confirm the text does not change on other goals.
Last note: I would appreciate if anyone would like to suggest alternate wording for the all dungeons goal sign text. The current text is 4 lines long in game, and i'm not sure what total's smz3 uses for all dungeons …
> SMZ3: Fixed Ganon sign text on AllDungeonsDefeatMotherBrain goal

- BaseClasses.py
- docs/world api.md
`Region.connect` and `Region.create_exit`. latter returns an entrance that can be used for other things (?) and former allows easy connection between two regions without needing the full structure of `add_exits`. Also added deprecation warning to creating Entrance elsewhere, since there's a ton of duplicated code from people doing so. Made it a separate commit so it can be easily dropped if desired.
unit tests and checking that the logs print the warning correctly
> Core: Region connection helpers

- MultiServer.py
> MultiServer: fix loading of default hintcost

- worlds/sm64ex/docs/setup_en.md
Docs: verbosify the manual build sections for SM64
Many users have struggled with manually building SM64, or building SM64 at all. This seeks to minimize the amount of Tech Support issues opened with regards to SM64.
See [1118719784461279242](https://discord.com/channels/731205301247803413/1118719784461279242)
> SM64: Verbosify SM64 documentation

- worlds/smw/__init__.py
Move Generate Basic earlier to pass tests
A few generations
> SMW: Move item creation earlier

- inno_setup.iss
The installer now generates a desktop shortcut and start menu shortcut for the Launcher and the LADX client
Ran setup.py build_exe, then compiled the inno_setup and installed Archipelago. Confirmed that the new shortcuts were created and correctly opened their respective exes.
> Installer: Add desktop and start menu shortcuts for Launcher and LADX Client

- Main.py
Moves conversion of server options to dict to avoid causing an AttributeError when `baked_server_options` is not `None`. Introduced in 827444f5a4e065bc310c889892580eb1f97c73cb
Running the webhost locally and generating a couple seeds.
> WebHost: Fix as_dict attribute error

- worlds/witness/WitnessLogicExpert.txt
...for Quarry Lower Row 1 in Expert. This panel has Triangles & Eraser, not Dots & Eraser
Doesn't currently lead to any broken seeds or anything as it is an additional requirement, it just makes seeds unnecessarily restrictive.
> Witness: Logic Fix (Incorrect Symbols expected)

- worlds/witness/__init__.py
One of the recent PRs accidentally removed all ability for the client to see which EPs are precompleted due to settings.
This is pretty bad, as the client now thinks these EPs need to be completed for "Obelisk Side" locations, when the generator does not. This would lead to **impossible seeds.**
> Witness: Fix unsolvable EPs not being precompleted (Impossible seeds)

- worlds/sa2b/docs/en_Sonic Adventure 2 Battle.md
A link to location guide into Game Page for SA2.
I clicked the link.
> SA2B: Add link to location guide into Game Page

- worlds/tloz/Rom.py
TLoZ implementation is importing APDeltaPatch from Patch, rather than worlds.Files where it is implemented.
I genned and played a seed with the change.
> TLoZ: Fix Incorrect Import

- test/general/TestReachability.py
also tests the reverse case of reachable regions
yes
> Tests: ensure unreachable_regions is correctly set

- settings.py
* implements dict support for Group.dump allowing to add/remove APWorlds (it would crash for unknown Groups otherwise)
* implements sequence support for Group.dump allowing to save/load scalar sequences (no upcasting)
* this is future proofing to not break when downgrading from something like \
`plando_options: Set[PlandoEnum] = {PlandoEnum.Bosses}`
* skip invalid values when loading a dict/Group from host.yaml. This might still crash later, but the error might be more appropriate
* keep the old file when crashing during save
* adding dicts of dicts to SoE
* adding sets, tuples and list of lists as well as lists of dicts to SoE
* generating a fresh host.yaml
* loading a "destroyed" host.yaml
> Settings: implement saving of dict and sequence, add graceful crashing

- worlds/messenger/SubClasses.py
The Money Wrench location needs to actually be interacted with in order to access the area of the shop that has the figurine. The client is smart enough to not allow the player into the area until they have the actual item but I had the oversight that they still require to interact with the location first and the logic wasn't accounting for that.
Was looking through generated playthroughs and noticed this 😬
> The Messenger: Fix location access for Figurine Shop Locations

- UndertaleClient.py
- worlds/undertale/docs/undertale_en.md
Adds a new command to the client, named /savepath.  This lets you target the path where your save data is stored.  Normally the client automatically finds the correct place, due to the Windows platform; however Linux platforms for example would have to utilize Wine in order to play what is currently implement and would thus utilize a wine prefix.  Doing this allows the user to redirect the client to the correct folder on launch.  Its a rough solution but should make the game playable for Linux until something more sophisticated is made.
- Ran the client, connected, used the command, did !getitem Spider Donut, received it.
- Ran the client, used the command, connected, did !getitem Spider Donut, received it.
> Undertale: Change Save Data Folder Location

- worlds/witness/__init__.py
Think things got messed up a bit when we resolved a merge conflict in https://github.com/ArchipelagoMW/Archipelago/pull/1953
Right now, no Witness seeds generate at all under any version
Python 3.8 support issue will be fixed in another PR very soon
> Witness: (Fatal) Fix incorrect reference due to a faulty merge conflict

- worlds/clique/Items.py
- worlds/clique/Locations.py
- worlds/clique/Options.py
- worlds/clique/Regions.py
- worlds/clique/Rules.py
- worlds/clique/__init__.py
- worlds/clique/docs/en_Clique.md
- worlds/clique/docs/guide_en.md
Refactors, implementation of `get_filler_item_name`, and new color option.
Also sidesteps a possible generation issue with larger Clique-only games because of how restricted the "viable location pool" is by preventing Button Activation from being on The Button.
Ran a mostly Clique test game, with minimal issues.
N/A
> Clique: Refactors and Additional Features supported by v1.5

- worlds/stardew_valley/logic.py
- worlds/stardew_valley/regions.py
- worlds/stardew_valley/rules.py
- worlds/stardew_valley/test/TestRegions.py
Leo's TreeHouse is an entrance that only opens after unlocking Ginger Island, meeting Leo, and earning 6 hearts with him. Therefore, in the randomizer, this entrance requires progression items.
This change fixes a bug where the entrance was randomized under the "Non-progression" setting. It is now correctly under the "Buildings" setting
Additional fix for a very unlikely entrance randomizer softlock: Void Mayonnaise can be fished from the witch's swamp, and this has been added in logic to avoid problems with obtaining void eggs making an infinite loop there
Ran the automated tests and checked the result of randomization. Generate a few manual multiworlds
> Stardew Valley: Fixed Leo's Treehouse being randomized too aggressively

- setup.py
allow Hollow Knight to be an APWorld on current Python versions
This is the result of testing HK and realizing it's broken AF on old versions.
> HK: apworld support on 3.10+

- worlds/witness/__init__.py
- worlds/witness/items.py
- worlds/witness/player_logic.py
- worlds/witness/static_logic.py
- worlds/witness/utils.py
Lots of "list[int]" and "dict[str, int]" made it into the most recent PR.
That is incompatible with Python 3.8, it needs to be List[int] with a capital L, as imported from the typing module.
Also, removed a dead import (bc it was right there)
> Witness: Fix type hints being incompatible with 3.8

- worlds/terraria/Checks.py
- worlds/terraria/Rules.dsv
Fixes Python 3.8 compatibility in the Terraria world
I ran `Generate.py` and with Python 3.8 and it crashed. Then I made this change and ran it again, and it didn't crash.
> Terraria: Fix Python 3.8 compat

- WebHostLib/generate.py
Title. a new CL arg was added but since it doesn't exist from webhost caused gen to crash when it was hit. Alternative fix is to use getattr but this allows it to be more easily exposed if that becomes desired in the future.
Generated with multiple players before and after the change.
> Webhost: Fix failing gen for players > 1

- worlds/dark_souls_3/Locations.py
- worlds/dark_souls_3/__init__.py
Progression items being placed in Archdragon Peak causes
```
RuntimeError: Not all progression items reachable ({AP: Soul of the Nameless King}). Something went terribly wrong here.
```
apparently due to the access rule using `can_reach("Go To Untended Graves", "Entrance", self.player))`. I also tried using `can_reach("Consumed King's Garden", "Region", self.player))` which caused the same problem. So this adds an event item in CKG for the Path of the Dragon gesture you get just before Untended Graves. Not the most elegant, but using a gesture to reach an area is unique to Path of the Dragon; everything else is an item.
Also changes the `late_dlc` option to lock of _all_ the DLC behind Small Doll instead of allowing the first half of the painted world to stay in logic. An oversight from …
> DS3: Accessibility error fix

- worlds/stardew_valley/__init__.py
- worlds/stardew_valley/data/items.csv
- worlds/stardew_valley/items.py
- worlds/stardew_valley/rules.py
- worlds/stardew_valley/test/TestOptions.py
Leo's Treehouse construction is now an Archipelago Item. This allows it to be used in logic and simplify unlock conditions.
With Entrance Randomizer, this allows the fill algorithm to give access to this door regardless of Leo's status, removing some rare softlocks
Ran tests, generated some games and played with them to check the new item
Also reproduced the softlock originally found by @ThePhar and confirmed it no longer happens
> Stardew Valley: Turned the Treehouse into an unlockable item

- worlds/terraria/Rules.dsv
Having the Lunatic Cultist goal would cause victory upon joining with the Terraria client. This fixes that.
Before/after testing. The bug is a pretty obvious one.
> Terraria: Fix Lunatic Cultist goal immediately awarded

- Options.py
Just adds a display name. Mostly so spoiler prints `Item Links` instead of `item_links`.
Also re-sorts the imports in `Option.py` since my IDE does that. \:P
Looked at spoiler log after generating game.
wow
> Core: Add display name for `item_links` Option.

- worlds/stardew_valley/data/items.csv
- worlds/stardew_valley/items.py
- worlds/stardew_valley/mods/logic/deepwoods.py
This adds the feature of
- Allowing player to actually receive Woods Obelisk floors by naming the item correctly.
What I did was stare at the fact that I typed the letter "s" for perhaps five minutes, and then spent twenty minutes remembering for the billionth time how to push a branch to a different remote.
No.
> Stardew Valley: Fix typo with woods obelisk item

- Fill.py
#1800 introduced a cleanup pass to "eject" unreachable items to hopefully get better error reporting of what could not be placed. The code to do so has an unnecessary amount of sweeps from pool.
> Fill: fix cleanup-after-swapping performance

- inno_setup.iss
Allows launching the launcher as a post install action
By launching the launcher
> Setup: allow user to auto launch the launcher, so they can conveniently launch things when the setup is done.

- setup.py
No module named 'websockets.legacy.server'
Running MultiServer with a multidata file, that was frozen.
> Setup: package the entire websockets module

- .github/workflows/unittests.yml
Cython 3.0.0 was released: https://cython.readthedocs.io/en/latest/src/changes.html
If we want to keep it for when Cython makes a pre-release of 3.1, just close the PR.
> CI: remove cython3 beta testing

- worlds/AutoWorld.py
Exception: Exception in <bound method StardewValleyWorld.create_items of <worlds.stardew_valley.StardewValleyWorld object at 0x000001CB2EF3BD90>> for player 4, named Tester
By crashing SDV
> Core: trace error to player, if possible.

- worlds/witness/items.py
Basically: "copy.copy" of data that should not be changed -> Now replaced with "copy.deepcopy".
Problem being that the code later changes item classifications of the values of this dict, which then bleed over into other seeds, causing impossible scenarios.
> Witness: Fixing a world bleed issue with multiple Witness seeds, preventing generation

- worlds/witness/WitnessLogic.txt
- worlds/witness/WitnessLogicVanilla.txt
There is a path behind the 2nd Pressure Plates puzzle across the wall of the Keep that allows you to completely skip it and advance to Pressure Plate 3.
Knowing that this shortcut exists and that you can skip the Pressure Plates 2 puzzle was deemed unintuitive when the randomizer came out and made a not logically valid path.
This has been the subject of a lot of debate in the #witness channel. With the advent of autotracking and considering many opinions from both veteran players and beginners, I have chosen to make this shortcut logical, meaning it is now possible to e.g. have your Progressive Stars on the third Pressure Plates puzzle or in any of the Shipwreck puzzles.
Note: Expert has always *required* this path (part of the design of Expert is to force you to use lesser known …
> The Witness: Make the path behind Keep Pressure Plates 2 logical in Vanilla and Normal

- LinksAwakeningClient.py
- data/lua/connector_ladx_bizhawk.lua
There was a bug that randomly after opening and closing the menu, some players on Bizhawk would get old items again. Tracking this down took multiple hours over the course of several weeks. The root cause turned out to be reading from the System Bus domain while an DMA copy was happening. Doing so is undefined behavior on GBC (though I'm sure some game relies on it). On Gambatte, you end up reading some garbage byte no matter what the read is (unsure what the providence of the byte is - some garbage, some register, the actual DMA data, who knows?). Normally, this isn't an issue, as Bizhawk callbacks only happen during vblank/halt, which is generally a state where we have valid WRAM to read from. However - a setting is being passed around the community for Bizhawk that changes the frame …
> LADX: Fix getting old items over and over again in Bizhawk

- MultiServer.py
Removes an unclosed parenthesis within the MultiServer connection message.
Hosted using MultiServer.py and then joined with a TextClient, confirmed that the resulting message did not contain the additional parenthesis.
> MultiServer: fix unclosed parenthesis in connection message

- CommonClient.py
Should fix issues reported with energy link not working.
Wasn't yet.
> CommonClient: fix 0.4.2 EnergyLink datastore key

- Main.py
If games reassign `Location.item_rule`s in `set_rules` ~~or `generate_basic`~~, then `local` and `non_local` item rules will be "overwritten". 
For example, Clique sets an item_rule in `set_rules` (made sense to me), but another player set an item as "local_only". In the seed generated, it may still ended up on the Clique location.
Since there's doesn't appear to be consensus that `item_rule`s should not be set after `create_items`, this should prevent weird behavior if that were to occur up until `item plando` and `fill` stages, where I argue this chance should be less likely.
Since
Ran unit tests and seed with known placement error, and misplacement disappeared.
Spoiler:
Before fix w/ same seed:
After fix w/ same seed:
> Core: Set locality rules after `set_rules` stage.

- worlds/stardew_valley/__init__.py
- worlds/stardew_valley/docs/en_Stardew Valley.md
- worlds/stardew_valley/docs/setup_en.md
- worlds/stardew_valley/mods/mod_data.py
It was pointed out that distributing an archive with copies of all the supported mods could lead to legal problems down the line. So we are moving away from this approach.
This also means that, in the event that a mod gets updated and the previous version is no longer available, we need the ability to update the mod's supported version at any point in time, and cannot rely on AP's release schedule for such updates that will, in most cases, be only changing the string for the required version.
Changes:
- Scrub all references to the support mods zip file from documentation
- Create dedicated "Supported Mods" documentation page, external to AP so we can keep it updated with mod versions regardless of their release schedule
- Remove mod version validation from the AP backend, and manage that …
> Stardew valley: Supported Mods documentation and changes required for legal reasons

- settings.py
- test/__init__.py
- test/general/TestHostYAML.py
* avoid saving and gui stuff when running tests
* change TestHostYAML to use a fresh yaml rather than the local/user copy
* host.yaml is .gitignored, so it makes no sense to validate it
* the test changed from "validate consistency" (between host.yaml and defaults) to "validate output" (of settings)
By running the tests
> Settings: change/fix tests behavior

- worlds/ladx/LADXR/generator.py
Probably fixes the crash - TIL unplaced items are normal.
> LADX: Fix hints crash 

- worlds/ladx/Options.py
Adds option to remove rooster from the pool
Did a bunch of generations - rooster appears to be removed. I'm not aware of any inaccessible checks due to this.
> LADX: Add rooster option

- NetUtils.py
- test/netutils/TestLocationStore.py
* The pure python implementation had a bug in get_missing for empty state optimization, which is an optimization for the case where everyone is connecting to a fresh game for the first time. This was missed because 3 of the tests got disabled during a refactor.
* Re-enable the 3 tests
* New test to verify set intersection behave correctly.
By running the tests
> MultiServer: fix wrong missing for empty state w/o speedups and add/fix tests

- _speedups.pyx
The cython-generated code triggers C4551 on MSVC,
which does not get silenced by pyximport's build flags. So we silence it on source code level instead.
> Speedups: ignore warning C4551 for pyximport+MSVC

- Fill.py
- test/general/TestFill.py
In `fill_restrictive` it is possible that the item which is placed is *not* the same item as the one that is removed from the pool of items to be filled.
(This can happen because `list.remove` operates on equality (not identity) and items compare equal as soon as their name and player are the same.
The bug thus occurs when there are two item instances in the pool that belong to the same player and have the same item name.)
This can lead to strange behavior such as locations where `loc.item.location is not loc` or items where `itm.location is None` after fill (*without* triggering any warning about unplaced items), which also lead to https://discord.com/channels/731205301247803413/1134521806099853352.
The PR includes a new unittest that failed when ran without the corresponding fix.
> core: remove the correct item from the item_pool in fill_restrictive

- worlds/dlcquest/Rules.py
a missing rule in the logic was implemented where the gun pack was not needed for the gun location item, but only the ability to get to the npc.
run test
> DLCQuest: Add missing gun law

- worlds/stardew_valley/test/__init__.py
Removes duplicate code from Stardew Valley's test setup and optimized imports. Would be good practice to also rename the setup function as Python doesn't like functions with the same name but different signatures.
Unit Tests
@agilbert1412
> Stardew Valley: Remove some duplicate code in tests

- worlds/tloz/docs/multiworld_en.md
- add section about configuring lua core (shamelessly taken from the OoT setup guide) on bizhawk version 2.8 and below
- fix wrong reference to the ff1 connector lua to correctly reference the tloz connector lua
- remove reference to recommended bizhawk version. it's unnecessary
ran the webhost to verify changes
> TLoZ: Setup doc update

- Options.py
Title. It seemed weird to me that these aren't really supported by the "OptionDict". I think if you make something that isn't actually a dict, you probably know to override or not use these.
Put it in The Messenger and generated a few seeds/debugged.
> Core: Add dict functionality to OptionDict

- worlds/alttp/__init__.py
- worlds/zillion/logic.py
Add fill_slot_data function. 
Used by StripesOO7's pop-tracker pack to auto populate settings as convenience for the user
Generated a bunch of seeds and played most of them with a smaller private group.
N/A
> alttp: Add fill_slot_data function

- BaseClasses.py
An issue would occur when attempting to plando items to multiple worlds of varying games. "location_names" would be populated by the locations of the first game, and then not cleaned afterwards. Thus, later iterations of the loop would fail as it would be looking for locations from the first game in subsequent games. This fixes the issue by setting "valid_locations" to a copy of "location_names" if it is non-empty or the list of locations per game if it is.
https://cdn.discordapp.com/attachments/1135349606176260258/1135350398727766116/Plando_Dumping_All_Items_to_Single_Game.zip
Test sample given from bug report, "A Link to the Past" and "Ocarina of Time" have Triforce Pieces plando'd into 5 different worlds. Without this change, Triforce Pieces would only be placed into Radz Awakening and …
> Plando: fix automatic locations only working for the first world

- worlds/dkc3/__init__.py
- worlds/smw/__init__.py
Adds an explicit custom filler item pool for SMW and DKC3.
Generated with item links with `null` replacement items.
> SMW & DKC3: Add `get_filler_item_name` override

- worlds/sa2b/__init__.py
`generate_filler_item_name` in SA2 has been broken on main since December. I fixed it.
Generated with some sketchy item links settings.
> SA2B: Fix `generate_filler_item_name`

- worlds/messenger/__init__.py
Returns more proper filler for item links instead of hardcoded "Time Shard" which is basically worthless. The 100 is a completely arbitrary number, could be any number really, but that should be enough to satisfy most multiworlds, as maximum filler generated without starting_inventory is 98. This isn't high priority, as it really only has an effect on item links.
Generated a few multiworlds to satisfy all the different combinations and tests.
> The Messenger: actually implement `get_filler_item_name`

- MultiServer.py
When running MultiServer without stdin or with broken stdin, the console task will spin in
```python
while queue.qsize() == 0:
await asyncio.sleep(0.05)
```
Returning from the task when the thread dies frees up resources.
> MultiServer: exit console task when console thread dies

- worlds/tloz/Rom.py
The method TLoZ was trying to validate it's baserom with was different from basically every other ROM game. Almost all the other ROM games use the same method as each other (except for the external patchers like FF1 and SoE, and OoT has its own special handling that's vastly different), so updating TLoZ to match. Otherwise, attempting to generate without having the base rom present will attempt to ask for the base rom but fail to validate, as reported here: https://discord.com/channels/731205301247803413/1136846040998346842
Also got rid of the checksum attribute for the TLoZDeltaPatch as it didn't seem to be used anywhere, so felt it was unnecessary and partially confusing to have it right next to the hash attribute that is actually used.
did a test gen with the ROM file not present. …
> [TLOZ] MD5 validation update

- worlds/tloz/__init__.py
using os.path.join was causing duplicate parts of the filepath in certain environments. turns out it's not needed when loading the basepatch in our current world structure. this should hopefully fix genning issues on the RC beta site (and presumably the main site once the RC turns into the release)
genned a seed successfully. made sure base patch took by checking a shop and seeing that a checked shop location moved upwards as is intended.
i request @Berserker66 to test this with his environment on a webhost to make sure a TLOZ properly gens and does not have the same error that birthed this PR (bug report with error here: https://discord.com/channels/731205301247803413/1139279406343393301) before merging.
N/A
> [TLOZ] Fix filepath error for base patch

- worlds/ladx/LADXR/generator.py
- worlds/ladx/LADXR/pointerTable.py
- worlds/ladx/LADXR/romTables.py
Fixes text pointer storer running out of space when location name is long by:
1. Giving some more space in bank 9 for hints
2. Capping hint length at 85
...this would be better solved by redoing how owl hint text boxes are done but this is far easier to fix for now.
Generation with forced long unique hint names. I haven't technically run a ROM using this, but the space is unused, unless something specifically goes looking in bank 9 for zeroes (why?!).
> LADX: Fix hints generation for longer location names

- worlds/terraria/Rules.dsv
Fixes a simple logic bug where [Necromantic Scroll](https://terraria.wiki.gg/wiki/Necromantic_Scroll) required the Post-Mourning Wood check item instead of inheriting the requirements for Mourning Wood (it's a Terraria item that drops by killing Mourning Wood)
Generated games, printed internal debug info verifying the problem was fixed. The bug likely hasn't ever manifested, so there were no seeds to test on.
> Terraria: Fix Necromantic Scroll requiring Post-Mourning Wood instead of access to Mourning Wood

- worlds/stardew_valley/data/crops.csv
- worlds/stardew_valley/data/items.csv
- worlds/stardew_valley/data/locations.csv
- worlds/stardew_valley/logic.py
- worlds/stardew_valley/rules.py
The Help Wanted setting, when using a number not divisible by 7, was missing some logic rules for the remainder. Now the rules should be set properly
The cropsanity setting was missing one crop, the coffee bean. This adds it
Ran unit tests, generated a couple of worlds.
> Stardew Valley: Fixed Help wanted rules, added missing coffee bean to cropsanity

- worlds/sm64ex/Rules.py
If BitFS leads to HMC, then COTMC entrance (which is in HMC) should not be allowed to point to DDD, which is required to enter BitFS in the first place.
Still generates fine, and uses the same fix method as other regions
> sm64ex: Fix possible inaccessible region

- MMBN3Client.py
MMBN3 was sending the list of all hinted objects every server tick, which was spamming the server with hints after one is collected. Now, it'll keep a running list of sent hints and only send new hints.
Generated a game, checked each hint location, and received only one message. Checked both internal and external item hints.
> MMBN3: Fixes hint spam when receiving a hint

- worlds/musedash/MuseDashCollection.py
- worlds/musedash/__init__.py
Changes how the Muse Dash world creates the `item_name_to_id` and `location_name_to_id` dictionaries to ensure that they have the same ordering each time. Without this, the datapackage for Muse Dash seemed to change each time generation was run. 
Also included is a `data_version` update that I missed in https://github.com/ArchipelagoMW/Archipelago/pull/2047
- Multiple generations to check ordering and checksum stayed consistent. 
- Ran tests and generations to ensure no logic changed.
N/A
> Muse Dash: Make item_name_to_id and location_name_to_id ordering deterministic

- WebHostLib/static/styles/player-settings.css
Fixes a layout bug when displaying player settings if view-port width is too small which causes settings to become misaligned and waste a lot of screen real-estate to the right.
Also removes portrait orientation media rule as it forces the aforementioned "small view-port width" display mode, which is (to me at least) annoying on larger displays that have long portrait windows if my width was still large enough to render the normal display anyway.
Checked output on Firefox and Chrome for PC and Safari on iOS to verify changes against [archipelago.gg](https://archipelago.gg). 
Was not able to verify on Android mobile browsers. ~~Think I can afford two phones? I can barely afford the one!~~
> WebHost: Adjustments to player-settings.css for better UI on small view-port widths.

- worlds/AutoWorld.py
The `generate_output` docstring has become particularly confusing now that MultiWorld objects are being encouraged to be named `multiworld` and `per_slot_randoms` is deprecated in favor of `AutoWorld.random`, which might now be confused with the term `world.random`.
Did a search for `world.random` in the whole codebase outside world implementations and didn't find any other documentation that looks like this.
> Docs: Update `generate_output` docstring

- worlds/pokemon_rb/__init__.py
When accessibility is `locations`, Dexsanity locations not reachable in an all state are deleted. However some locations may already have been added to a list of locations to fill with local items. This fixes a `ValueError` that would occur in this case.
Also fixes the corresponding item removal which was reducing the number of items it was deleting by 5. I haven't the slightest recollection or idea why this was done in the first place.
Adds an error when local location fills fail. I've only observed this happening on a branch with lots of crazy other changes for my own games but probably a good thing to have.
Updates required client version because why are you playing on 0.3.9? Time to update.
Generating yaml provided by @ScorelessPine with their seed number, seeing no errors.
> Pokemon R/B: locations accessibility fixes, etc

- worlds/stardew_valley/data/museum_data.py
- worlds/stardew_valley/logic.py
- worlds/stardew_valley/rules.py
- worlds/stardew_valley/test/TestRules.py
When using Museumsanity with Entrance Randomizer, it is possible that the museum is not immediately accessible.
This adds logic rules that were previously missing, requiring museum access before you can make any donation
- Created new unit tests for the desired behavior, checked that they failed, applied the fixes, checked that they now succeed
- Ran all previous tests as well
> Stardew Valley: Added rules requiring museum access to make donations

- worlds/messenger/Regions.py
- worlds/messenger/test/TestLocations.py
`I` =/= `i`
wrote a unit test for it.
> The Messenger: Fix a typo preventing a location from being created

- worlds/terraria/Rules.dsv
Fixes [Soul of Sight](https://terraria.wiki.gg/wiki/Soul_of_Sight) requiring Post-The Twins flag instead of access to The Twins. It's a Terraria item that drops from The Twins.
I generated 2 games and they were fine
> Terraria: Fix Soul of Sight requiring Post-The Twins flag instead of access to The Twins

- worlds/stardew_valley/logic.py
Talking to Leo requires the Island West turtle to have moved, so he comes down from his perch and talks to the player. That rule was not there, which means it can softlock a world if the turtle was in his friendship hearts.
Unit tests
> - Added a missing logic rule for talking to Leo

- SNIClient.py
As it turns out, SD2SNES / FXPAK Pro has a limit as to how many bytes can be written in a single command packet.  Exceed this limit, and the hardware will crash.  That limit is 512 bytes.  This limit not only includes that data to be written, but ALSO the 65816 assembler code required to write that data to ram.  As a result, a full release of all locations in the game exceeds this buffer, and on older versions of the Super Nintendo Interface,  caused crashes on real hardware.   Even 512 bytes of data to write is too much as that leaves no room for the data writing code. (which super nintendo …
> SNIClient: Fixed root cause of crashes of hardware for ALttP Collect.

- worlds/pokemon_rb/regions.py
Removes an errant region connection putting Good Rod fishing in logic with access to the Cinnabar Lab Fossil Room. I can only guess this was a copy-paste mistake.
Not, but this line definitely shouldn't be here.
> Pokémon R/B: Fix fishing logic mistake

- worlds/witness/hints.py
I hope this gets a prize for "Most irrelevant PR in AP history"
**Explanation:**
Witness has joke hints that were submitted by community members.
When changing the hint system on the client side to be able to auto-wrap, decisions were made about which line breaks in joke hints were still explicitly important, with most of them being removed.
The hint that is subject of this PR was somewhat devalued in the process.
-. --- - .... .. -. --. translates to "Nothing", which I thought was the entirety of the joke.
However, the line breaks were actually also important, because:
dash dot, dash dash dash,
dash, dot dot dot dot, dot dot,
dash dot, dash dash dot
is a Haiku! And the hint's creator (oddGarrett I believe) said this was specifically part of the creative vision for this joke hint. They …
> Witness: "Fix" one of the hints not being a Haiku (seriously)

- inno_setup.iss
- setup.py
adds stderr/stdout capable launcher to windows.
In turn, this allows use of --help or to capture errors before log init.
https://discord.com/channels/731205301247803413/1141562528632152135
> Windows: create terminal capable Launcher

- worlds/stardew_valley/logic.py
It was brought to my attention that about half the special orders have, as a completion condition once the items are collected, to drop them off somewhere or talk to someone. These drop-off locations are always available in vanilla, but with entrance randomization, they might not be.
So I went over the whole list and added missing logic rules for either regions or NPCs, so that the quests are garanteed to be completable with entrance randomization.
Ran the unit tests to make sure I didn't break anything, other than that it's just making logic a bit more strict so it can't really introduce new softlocks, just remove some
The changes were made based on the requirements listed here: https://stardewvalleywiki.com/Quests#List_of_Special_Orders
> Stardew Valley: Add missing special order logic rules

- BaseClasses.py
- worlds/alttp/Rules.py
nothing
unittest and find usage
> Core/LttP: remove can_reach_private

- worlds/timespinner/Options.py
Line 63, changed the commend from (Reccomended) to (Recommended)
> Options.py Typo

- WebHost.py
- WebHostLib/__init__.py
cache config was not taking, as the config was not updated when the cache actually initializes.
I know for sure this used to work, but I didn't check on it for months :(
on prod, of course.
> WebHost: flask caching doesn't do lazy init anymore

- Main.py
collect errors from generate_output at same step as multidata
by breaking LttP and Archipelago games
> Core: collect errors from generate_output at same step as multidata

- WebHostLib/templates/multiFactorioTracker.html
- WebHostLib/tracker.py
https://discord.com/channels/731205301247803413/1145166962910040104
minimally
> Factorio: fix website multitracker

- worlds/dark_souls_3/__init__.py
This adds the options to slot_data, mainly for auto-tracking purposes.
This was tested by generating a couple dozen seeds, and playing through most of one to make sure it didn't mess with anything.
> DS3: add more options to slot_data for autotracking

- worlds/zillion/__init__.py
- worlds/zillion/config.py
Zillion generation on archipelago.gg is failing.
https://discord.com/channels/731205301247803413/1147772247562534996
I can't reproduce this with my own webhost. Generation works when I run `WebHost.py` I don't know how the archipelago.gg webhost is configured to make this happen.
This seems like it should fix it based on the error message I see, but without being able to reproduce the webhost configuration, I don't see a way to test whether this fixes the problem.
I made sure it didn't cause any new generation problems with my configuration.
> Zillion: webhost config fix

- worlds/pokemon_rb/docs/en_Pokemon Red and Blue.md
Fixes a typo on the Pokemon RB game info page
Thanks Shiny for pointing it out https://discord.com/channels/731205301247803413/1043592720603693167/1147300361883893790
It wasn't, just a doc change
> Pokemon RB: Fix typo on the game info page

- worlds/witness/WitnessLogicExpert.txt
The Expert logic file says Tutorial Gate Close is impossible to solve.
This is a relic from when that used to be true. Which it isn't anymore.
This probably leads to accessibility checks failing sometimes in Expert + EP shuffle
> The Witness: Fix Expert Tutorial Gate Close logic

- worlds/pokemon_rb/__init__.py
- worlds/pokemon_rb/logic.py
- worlds/pokemon_rb/rom.py
1) Fixes `key_items_only` which was attempting to set `dexsanity` to an invalid value due to a last-minute renaming of the choices, and fixes a crash due to an attempt to check gym leader TM locations to set TM moves.
2) Fixes a missing check for Moon Stone on Key Items checks, which caused setting the Key Items conditions to 100 to lead to generation failure.
Generating a `key_items_only` game with 100% key items required
> Pokémon R/B: Fix broken options

- WebHostLib/check.py
- WebHostLib/generate.py
- WebHostLib/templates/check.html
- WebHostLib/templates/generate.html
This will allow the user to select multiple YAML files via Shift-Click or Control-Click in their browser when generating a game via the site instead of having to zip them locally first.
Implements this suggestion from #general-suggestions: https://discord.com/channels/731205301247803413/1139359972401102940
There were some suggestions in that thread to make this even better that aren't implemented here, but I agree with " just allowing multi-select in the prompt would go a long, long ways to make it easier" and chose to implement that for now.
Locally by running WebHost.py. Validated that single-YAML and single-zip uploads still work as expected, then also tried multiple YAMLs. For fun I also tried multiple zips, then a zip+yaml upload and those worked too. I don't think multiple zips or …
> WebHost: Support multi-select during check/generate file upload

- WebHostLib/static/assets/weighted-settings.js
Clean up exported yaml in weighted settings by removing weighted options in instances where there is only one possible option, in addition removes some empty arrays and empty 'starting_inventory'
exported a few dozen yamls with variable settings and verified
> WebHost: Clean up the exported yaml in weighted settings

- worlds/terraria/__init__.py
Added some Terraria settings to slot data that were missing, but not necessary. @SerpentAI wanted them for their tracker.
I generated a game and printed the slot data and it looks good
> Terraria: Add the rest of the settings to slot data

- worlds/stardew_valley/logic.py
- worlds/stardew_valley/test/TestRules.py
When playing on friendsanity marriage, for some values of heart size, "milestone" hearts can end up being skipped. For example, with heart size 3, the hearts are 3-6-9-12-14, which skips 8 and 10, which are the milestones for dating and marriage.
In order to "earn" heart 9, you need to have 8 hearts and give a bouquet to the NPC to date them. Under the current logic, only heart 6 would be required for heart 9 to be in logic, as the design was "previous heart only". This is a problem, because at 6 hearts, you cannot date the villager, and therefore you cannot "earn" hearts past the 8th one.
This fixes the problem. Any heart earned past 8 requires dating, so 8 minimum received, and any past 10 requires marriage, so 10 minimum received. Taking the same example, in order to "earn" heart 9, …
> Stardew Valley - Added missing logic rules for dating and marriage

- worlds/hk/docs/setup_en.md
The documentation for installing the map mod are outdated as of the most recent version of the mod. The instructions currently instruct users to uninstall a required dependency. I also moved the instructions for installing optional mods after the instructions for installing the mod installer and required mods.
I read it
> Hollow Knight: Update outdated setup documentation

- settings.py
`dict.get` has `default=None`, which was missing from `Group.get`'s dict emulation.
This should fix the crash in https://discord.com/channels/731205301247803413/1151196512181833790
Running mypy, unittests and 
```python
>>> from settings import get_settings; get_settings()["soe_options"].get("does not exist") is None
True
```
> settings: add default=None to Group.get

- worlds/raft/__init__.py
According to #2062, filler items should not be collected (IIRC due to performance reasons). Raft was collecting progressive non-progression (...yea) items, which is unnecessary since they don't contribute to progression. This makes Raft's `collect_item` return `None` with non-progression progressive items.
Ran the unit test in #2062 for Raft only.
> Raft: Fix collecting progressive filler items

- worlds/sc2wol/docs/setup_en.md
Point the documentation to the new Map/mod data location
> Docs: Update SC2 map/mod link

- data/lua/connector_tloz.lua
Certain multiworld settings (bug observed with item link settings) can cause the total item count in TLoZ world to exceed 255. This causes an overflow in the loop to receive all pending items. This adds an additional byte to be used as a high byte for the items obtained counter.
This approach was taken due to the surrounding bytes being occupied, preventing a direct 16-bit number from being used without moving to a different location and leaving more empty bytes in the memory block for save data.
When I encountered this problem in my own game, I made this as my fix for the problem. It worked without any noticeable side effects. Save persistence was checked with a reboot after ensuring data had been saved. Additionally, the [variables …
> The Legend of Zelda Conntector: Make items obtained counter in save data 16 bits.

- worlds/dark_souls_3/Locations.py
- worlds/dark_souls_3/__init__.py
Health items (estus shards and undead bone shards) are contained within the progressive item tables. So if progressive items aren't enabled, health items can never be added to the multiworld, even if the player has them turned on using `enable_health_upgrade_locations`. The only way to have health locations added is to turn on both `enable_health_upgrade_locations` _and_ `enable_progressive_locations`.
This moves health item locations to their own table so they can be added to the list of progressive items separately from the rest of the consumables. This changes the location ids of just these locations, but nothing we know of checks these location ids. The client will work with any location ids out of the box, and the tracker doesn't monitor progressive locations.
Generating a game for …
> DS3: Fix health locations setting not enabling

- Main.py
https://discord.com/channels/731205301247803413/1152413200067854407
I joinked the Subnautica yaml, wrote the assert, saw it trigger. Then wrote the fix and tested that the assert doesn't trigger anymore.
> Core: fix start_inventory_from_pool only adding one filler per item name

- worlds/subnautica/__init__.py
Adds a fourth Laser Cutter Fragment to the pool, if there is space for one.
This was supposed to be there, I just forgot to list it.
Running Generate and counting Fragments
> Subnautica: add extra Laser Cutter Fragment to priority filler

- worlds/sc2wol/Options.py
Fixes wrong option display name
Broken:
Fixed:
> SC2: Typo fix in option display name

- worlds/zillion/requirements.txt
Zillion could rarely have no locations in 1st sphere
https://github.com/ArchipelagoMW/Archipelago/actions/runs/6191949342/job/16811145959
unit tests (in both zilliandomizer package and AP)
and playing through an AP game
> Zillion: ensure 1st sphere not empty

- worlds/stardew_valley/data/villagers_data.py
- worlds/stardew_valley/logic.py
- worlds/stardew_valley/test/TestGeneration.py
- The logic rule for meeting the wizard was "Forest" instead of "Wizard Tower", which means the generator could give you tasks related to him even if his entrance was randomized behind a lock
- The logic rule for completing bundles only had the wizard potion condition for item bundles. The money bundles were missing that rule.
Both those issues can cause a critical softlock when using "Entrance Randomizer: Buildings". A single user managed to hit both issues in a single seed and got his multiworld completely blocked because of it
Ran all the existing tests. I could not really think of good new tests to add for this case.
> Stardew Valley: Fix two logic bugs with the wizard on Entrance Randomizer

- worlds/factorio/Client.py
The above message for loading mods from appdata never triggers if the lock file is shared, as Factorio acquires the lock first.
On the Windows version of as of making this, current Factorio
> Factorio: offer error message with some more insight for lock file in use

- Fill.py
https://discord.com/channels/731205301247803413/1153493567575171224
Plando gets confused and tries creating items from worlds that don't belong
Taking the problem yamls and confirming they properly generate with the change.
> Plando: Fix early_locations/non_early_locations overwriting outer scope variable

- WebHostLib/tracker.py
The summary row feature added in #1965 did not filter out group slots when calculating `completed_worlds`, so item links would always make the numerator too high.
Fixes bug reported in https://discord.com/channels/731205301247803413/1152293234677133324
Ran WebHost.py before and after my change.
Before:
After:
> WebHost: Don't count groups in the summary row completed worlds

- WebHostLib/tracker.py
If you navigate to the LttP mutlitracker in a multiworld with non-LttP games, the non-LttP game will cause a KeyError because `player_location_to_area` only contains the LttP games:
```
File "\WebHostLib\tracker.py", line 1686, in get_LttP_multiworld_tracker
if location not in player_locations or location not in player_location_to_area[player]:
KeyError: 1
```
Reported in the replies of https://discord.com/channels/731205301247803413/1152293234677133324
Loaded WebHost.py after this change, the page loads again.
> WebHost: Avoid KeyError in LttP multitracker when non-LttP games are present

- NetUtils.py
- Utils.py
- WebHost.py
- WebHostLib/autolauncher.py
- WebHostLib/customserver.py
- WebHostLib/locker.py
- test/webhost/TestAPIGenerate.py
- test/webhost/TestFileGeneration.py
this should hopefully fix customserver's memory consumption
haven't tested it yet
> Core, WebHost: lazy-load worlds in unpickler, WebHost and WebHostLib

- WebHostLib/static/assets/weighted-settings.js
LocationsDiv wasn't becoming invisible when collapsing games.
Ran webhost
Before
After
> Webhost: Hide LocationsDiv

- worlds/witness/WitnessLogicExpert.txt
Expert Swamp Maze currently thinks it needs Red Underwater 4 instead of the door. This could lead to an unbeatable seed in door shuffle, although it's very unlikely.
> Witness: Expert Doors Logic Fix

- worlds/factorio/Options.py
World Generation values are split into basic and advanced in-game. The split was done using a set operation, resulting in inconsistencies during spoiler output.
Rolling the same seed twice and comparing the spoiler.
> Factorio: fix world generation in spoiler

- worlds/witness/__init__.py
Define a get_filler_item_name for the Witness world.
For the record, this [used to exist](https://github.com/NewSoupVi/Archipelago/blob/18c97798158ccd07a352deec10c8760ba9838556/worlds/witness/__init__.py#L315-L320) but was then [removed](https://github.com/ArchipelagoMW/Archipelago/pull/1953).
Bringing back the old way of how it worked would be more trouble than it's worth now probably.
> The Witness: Fix Itemlinks

- Utils.py
```
$ DISPLAY="" python Generate.py
_tkinter.TclError: couldn't connect to display ""
```
```
$ DISPLAY="" python Generate.py
FileNotFoundError: Pokemon Red (UE) [S][!].gb does not exist, but PokemonSettings.red_rom_file is required
```
Also fixes and enables kdialog and zenity for `open_directory()`. This was tested with latest kdialog and zenity.
Also fixes the suggestion not working with zenity in `open_filename()`
* `TclError` as shown above
* `open_directory` with `import Utils; print(Utils.open_directory('test', '../with space'))`
* zenity fix in `open_filename` with `import Utils; print(Utils.open_filename('test', [], '../with space/a.bin'))`
> Core/GUI: Better fileselection error

- worlds/musedash/Options.py
- worlds/musedash/docs/en_Muse Dash.md
- worlds/musedash/docs/setup_en.md
Adds mentions of [Muse Plus] (The upcoming replacement to [Just as Planned])
> Muse Dash: Add mentions to Muse Plus to Docs and Options.

- WebHostLib/customserver.py
on spinup of customserver, check if worlds are imported, crash if so
by adding `import worlds` to WebHost.py
> WebHost: assert that worlds system is not loaded in customserver

- worlds/alttp/Rom.py
Making the number of checks before you get the GT big key accurate when key drop shuffle is enabled.  With it enabled, there are 25 check locations for the GT big key, rather than 22.
Rolled a seed with Key drop shuffle turned on, then did a game completion to get to the credits.
> ALttP: Update credits text for GT Big Key  when key drop shuffle is on.

- test/TestBase.py
Title. Also has `assertAccessDependency` use its own CollectionState to be cleaned up after running to make test writing for it a bit easier, and adds an arg to only check the provided locations instead of the entire multiworld.
> Tests: add a name removal method

- worlds/dark_souls_3/__init__.py
@Marechal-L 
Adds a "Cinders" item group. These are all functionally the same, so there's no reason to hint for any specific one over another. Usually you just have to try to remember which ones you have and don't have before you hint for one.
Generating a seed and hinting for "Cinders".
> DS3: Add cinders item group

- worlds/zillion/__init__.py
- worlds/zillion/config.py
- worlds/zillion/requirements.txt
change test detection for running tests with multiprocessing
As requested by @black-sliver 
In addition to the changes to the detection, I also moved the detection function into the zilliandomizer package so it can use the same detection in both places.
unit tests in both places and generated and played through a 1-player game in both places
> Zillion: change test detection for running tests with multiprocessing

- Utils.py
CI unittests sometimes randomly fail on macos because gethostbyname fails. Instead of a hard error, fall back to "127.0.0.1" or "::1" and print a warning.
We'll see
> CI: ignore invalid hostname of some macos runners

- .github/workflows/unittests.yml
- test/TestBase.py
- test/__init__.py
- test/programs/TestGenerate.py
Use pytest-xdist to better utilize runners' CPUs.
by watching the green :heavy_check_mark:
> CI: run tests multi-threaded

- .gitignore
gitignore stuff that is likely to exist in a working AP directory
* versioned venvs (i.e. `/venv312/`)
* profiler output (`/prof/`)
* appimagetool (`/appimagetool` or `/appimagetool-XXX.AppImage`)
* unzipped versioned sni downloads that were not renamed to `SNI` (`/sni-xxx/`)
> Core: more gitignore

- Launcher.py
Right now the "Open Patch" button in the launcher is restricted to only recognize file extensions associated with root-level clients. So the only way for an apworld with a bespoke internal client to open a patch file is to open it directly with the launcher.
This removes the exe requirement, and if no exe is found after the file is identified, the file is given directly to the launcher, which should identify the patch file and run `component.func` in `run_component`.
Dropped a Pokemon Emerald apworld into `worlds/` and was able to open an `apemerald` patch file to launch the Emerald client that's inside the apworld. Also verified that an `apz5` file still opened and patched correctly. All tested on source only.
> Launcher: Allow opening patches for clients without an exe

- WebHostLib/static/styles/landing.css
- WebHostLib/templates/landing.html
link to stats from the use statistics directly on landing
clicked
> WebHost: link to stats from the use statistics directly on landing

- test/__init__.py
- test/worlds/__init__.py
An import got broked when changing imports for pytest-xdist. This should fix it.
running unittests
> Core: fix unittest world discovery

- worlds/messenger/Rules.py
- worlds/messenger/test/TestAccess.py
Caught this from the item fill unit test branch. When I added a separate cloud ruins region, I didn't properly change the access rule for the singular location in cloud ruins under these specific settings. The location is in Cloud Ruins Right, but the only way to reach it is from Cloud Ruins, and the entrance to that region are where the actual limiting rule is. Instead of doing the whole nonsense to allow the item, I just removed the item requirement.
unit tests and plandoing the item.
> The Messenger: Fix items accessibility region rule

- WebHostLib/static/assets/player-settings.js
https://discord.com/channels/731205301247803413/1154320397974655027
ran webhost
> Webhost: random button presisted after being inactive

- LttPAdjuster.py
https://github.com/ArchipelagoMW/Archipelago/pull/2268#issuecomment-1748228270
having it die by following the steps. Fixing it, then not having it die.
> LttP: Adjuster no longer breaks when sprite path doesn't exist.

- worlds/checksfinder/__init__.py
ChecksFinder was adding items to the itempool in `generate_basic`, which is not allowed.
Ran unittests including the one from #1460.
Generated a game and played it.
> ChecksFinder: Move create item logic to `create_items`.

- setup.py
I've seen several user logs that start with an import failure on the old Ori world, this cleans that finally up.
oribf shows up in installdelete.iss
> Setup: also delete old disabled worlds

- CommonClient.py
- Utils.py
fix json prints not being logged in UI mode
quickly
> CommonClient: fix json prints not being logged in UI mode

- worlds/zillion/__init__.py
- worlds/zillion/requirements.txt
Zillion needed the rom for early steps in generation, and that caused problems with testing.
The need for the rom in early generation steps has been removed, and the workaround for unit tests because of it.
unit tests both with and without the rom
and generating and playing through games
> Zillion: remove test detection hack

- worlds/musedash/__init__.py
- worlds/musedash/docs/setup_es.md
This adds a spanish guide for Muse Dash, based off the current (from main) english guide.
By me, proofreading a couple of times.
> Docs: add Spanish guide for Muse Dash

- worlds/lufia2ac/Options.py
- worlds/lufia2ac/__init__.py
Moves the Lufia 2 Ancient Cave world to the new options system introduced in #993 
Generated a game with non-default option and verified that the option values are reflected in the spoiler log as well as in game.
> lufia2ac: switch to new options system

- worlds/hk/docs/setup_en.md
Updating the HK Setup Guide to mention Lumafly instead of Scarab+
Looking at it.
> HK: Update Setup Guide to use/mention Lumafly

- docs/triage role expectations.md
Define expectations for users added as an Archipelago repository member with triage role access only.
There was some discussion in [this discord thread](https://discord.com/channels/731205301247803413/1163595034956939355).
N/A
> Docs: Triage role expectations documentation.

- worlds/sm/__init__.py
Missing an import for Accessibility that was being used in generate_early
> SM: fix missing option import

- worlds/oot/Utils.py
Ocarina of Time uses `lru_cache()` for caching JSON data being read for logic and hints with a `maxsize` of 13.
While there are 12 dungeon files and an overworld file, there are also Master Quest dungeons, glitched logic, etc. to cache as well.
For now, I removed the optional `maxsize` parameter, setting it to the default of 128.
From testing these changes on a multiworld with 9 OoT players, using various combinations of Glitchless, Glitchless MQ, and Glitched logic, the total files reads was brought from 126 to 40.
> Ocarina of Time: Increase function cache size for reading JSON data

- WebHostLib/static/assets/weighted-settings.js
This moves most of the infrastructure into two classes:
* WeightedSettings covers the settings page as a whole. It tracks the
user's current settings in local storage as well as the game data
from the server so they don't need to be manually passed around from
function to function.
* GameSettings covers the settings for a single game, and provides a
view of the current settings and the game data just for that game.
Manually tested adjusting settings, reloading from local storage, exporting to YAML, etc.
> WebHost: Refactor weighted-settings.js

- settings.py
- worlds/_bizhawk/context.py
Adds autostart settings to BizHawkClient.
`rom_start` behaves the same way as most other `rom_start` settings. `true` for enabling autostart, `false` for disabling it, and a custom string as a path to a specific program.
`emuhawk_path` is the exe the player intends to use with BizHawkClient, and what we launch the ROM with when `rom_start` is `true`. Getting the user to tell us where this is instead of using `webbrowser.open` means we can pass the `lua` arg and autostart the connector script in BizHawk as well. We'd lose automatically opening in the system default program, but to use this client, the user has to use BizHawk anyway, and an adept user can just override `rom_start` to use a different program if they still want to.
Opening a patch file with all three possible `rom_start` …
> BizHawkClient: Add autostart setting

- Fill.py
OoT has randomized shop locations which are considered events, but are only filled during prefill. Since plando runs first, the consequence is that plando could place items into these locations. Usually this isn't a problem, but `early_items` acquired all locations including unfilled events, which could cause items to be placed on event locations. This adds multiple safeguards against this occurring.
> Core: guard against plandoing items onto event locations

- Main.py
Currently in Python, threadpool only fires up new threads as actually required, so lowering the number of allowed workers in the threadpool does nothing *currently*. But that's an implementation detail I'd prefer to not rely on never changing. It's well possible threadpool spins up threads ahead of time in the future so it takes less time for them to be available, for example.
So I'd rather explicitly limit the amount ahead of time, since we know exactly how many we might need.
a few gens
> Core: explicitly limit threadpool

- Fill.py
https://discord.com/channels/731205301247803413/1161022518631608320/1161022518631608320
If a user specifies early_locations, non_early_locations, or manually puts the same location name multiple times in the locations field, plando can place items onto non-existent duplicate locations, leading to unfilled locations.
Added the following plando to a default DS3 yaml, and generated alongside 2 LttP yamls.
```
plando_items:
- items:
- Small Lothric Banner
- Basin of Vows
locations:
- Mushroom
- Mushroom
from_pool: true
world: true
force: true
```
Checked that the issue was no longer present. It should be noted that in the case of specific duplication, it treats the length of the list as the number of unique locations.
> Plando: Prevent duplicate candidate locations

- worlds/stardew_valley/items.py
- worlds/stardew_valley/logic.py
- worlds/stardew_valley/options.py
During the shenanigans with 993, I had to make new fields for Stardew Valley options. I was not aware that the name of these fields needed to match the internal names of the options, so I wasn't particularly careful about that. Turns out they need to, and I have no clue why, but I was told it causes problems. So I renamed the ones that didn't match.
Ran unit tests
> Stardew Valley: Fix option that was accidentally renamed in 993

- WebHostLib/check.py
- WebHostLib/templates/checkResult.html
- worlds/alttp/docs/multiworld_de.md
- worlds/alttp/docs/multiworld_es.md
- worlds/alttp/docs/multiworld_fr.md
- worlds/dkc3/docs/setup_en.md
- worlds/factorio/docs/setup_en.md
- worlds/generic/docs/setup_en.md
- worlds/ladx/docs/setup_en.md
- worlds/lufia2ac/docs/setup_en.md
- worlds/sm/docs/multiworld_en.md
- worlds/smw/docs/setup_en.md
- worlds/smz3/docs/multiworld_en.md
- worlds/soe/docs/multiworld_en.md
- worlds/tloz/docs/multiworld_en.md
- worlds/zillion/docs/setup_en.md
adds a  combined yaml file as download to a succesful /check run with multiple files
bonus inclusions:
fixes many guides hitting a redirect
fixes import * in check.py
on Vivaldi
> WebHost: offer combined yaml file on /check if successful

- worlds/witness/__init__.py
- worlds/witness/hints.py
Sigh.
Today I learned that random.randint is **inclusive** of the upper bound.
Just. Wow
> The Witness: Fix random events not having the correct probabilities

- test/TestBase.py
adds a seed field to WorldTestBase, generates the seed just like regular generattion, and adds it to the fill subTest
broke fill and checked it logged
> Tests: log the multiworld seed in WorldTestBase fill test

- worlds/oot/ItemPool.py
- worlds/oot/Location.py
- worlds/oot/LocationList.py
- worlds/oot/Options.py
- worlds/oot/Patches.py
- worlds/oot/Rules.py
- worlds/oot/__init__.py
- Added location name groups, so you can make your entire Water Temple priority to annoy everyone else
- Significant improvement to ER generation success rate (~80% to >99%)
- Changed `adult_trade_start` option to a choice option instead of a list (this shouldn't actually break any YAMLs though, due to the lesser-known property of lists parsing as a uniformly-weighted choice)
- Major improvements to the option tooltips where needed. (Possibly too much text now)
- Changed default hint distribution to `async` to help people's generation times. The tooltip explains that it removes WOTH hints so people hopefully don't get tripped up.
- Makes stick and nut capacity upgrades useful items
- Added shop prices and required trials to spoiler log
- Added Cojiro to adult trade item group, because it …
> Ocarina of Time: long-awaited bugfixes

- worlds/pokemon_rb/regions.py
Sweep only current player's locations so that more players does not slow it down.
Fix a slight possibility of Full door shuffle crash by only sorting for outdoor dead ends only when connecting from a non-dead end.
Slightly
> Pokémon R/B: Door Shuffle efficiency improvement and crash fix

- inno_setup.iss
https://discord.com/channels/731205301247803413/1158944149685411880
In detail: 
1. Less upfront decisions for the user, who might otherwise face a wall of text and confusion.
2. All registry hooks are always registered, in the past we've seen users not install clients, assign patch files to emulator and mess up their file associations. This should help by having it always installed.
3. Everything is available. This currently includes a bunch of .exes, which I'd like to move to the Launcher anyway as an ongoing effort.
4. People need to use the Launcher for apworlds anyway, this gets us further into that path.
5. A bunch of links  in the start menu and desktop are removed in favor of just leaving the launcher.
6. There is less customizability, and those who did not install everything will …
> Setup: new setup experience (read: torch almost all of it)

- worlds/terraria/Rules.dsv
Tier 2 and 3 of Terraria's Old One's Army event require you to have Hardmode (the item associated with Wall of Flesh), but that wasn't accounted for in the logic. Someone found this bug the hard way, rip
I generated a world and nothing went wrong
> Terraria: Old One's Army Tier 2 and 3 missing Hardmode requirement

- pytest.ini
We forgot to update pytest.ini in #2298 
---
Want to leave both test_\*.py and Test\*.py in for now so pytest discovers world test that have not been renamed yet until we have the test that tests that tests are named test_.
> pytest: run tests on non-windows with new names

- Options.py
while sets are json serializable, they are slower, since the goal of this method is to quickly return needed options for slot_data, it only makes sense to have it convert sets to lists. 
tested with oot using break points
> Options: have as_dict return set values as lists to reduce JSON footprint

- worlds/soe/__init__.py
keep local reference instead of hitting multiworld cache
also technically fixes a bug where all locations are in 'menu', not 'ingame'
---
**Edit:** I have numbers. This saves 13 seconds on a 1000 player SoE-only multi and more if it's mixed with worlds that create actual regions.
> SoE: create regions cleanup and speedup

- BaseClasses.py
- worlds/alttp/InvertedRegions.py
- worlds/alttp/ItemPool.py
- worlds/alttp/Regions.py
removes initialize_regions. Should generate faster without it as well.
an LttP template and unittests. During which my SoE apparently died.
> Core/LttP: remove initialize_regions

- worlds/subnautica/__init__.py
Should be slightly faster in multiworlds. Mostly it splits steps to easier follow for tutorialization.
once
> Subnautica: avoid cache recreation in create_regions call and clean up function.

- worlds/dlcquest/Items.py
- worlds/dlcquest/Regions.py
- worlds/dlcquest/Rules.py
- worlds/dlcquest/__init__.py
Makes DLCQuest logic go vroom
Grabbed the base yaml, enabled coinsanity, set it to 1, copied the file to a total of 3. Ran it, took 45 seconds. After applying my shenanigans it now ran in 10 seconds.
@axe-y @agilbert1412
> DLCQuest: logic speed up
