worlds/_bizhawk/__init__.py
worlds/_bizhawk/context.py

If multiple coroutines try to make requests using the same `BizHawkContext`, one of them might try to read from the `StreamReader` while another one is already waiting on it, which seems to lead to one of the responses getting discarded because of the asyncio exception and the other gets passed to the wrong coroutine which bubbles up as a `SyncError`.
The connector script isn't built to service more than one connection, but multiple coroutines have access to the connection from the python side and may have reason to use it. For example, an `on_package` handler and a game watcher.
This adds a lock to `BizHawkContext` and shuffles code around a little. So now anything trying to communicate with the lua script will have to wait until nothing else is trying to.
This will simplify #2306 a bit …

BizHawkClient: Add lock for communicating with lua script

---

worlds/pokemon_rb/regions.py

This PR changes Pokemon ER to not constantly check state inside the `dead_ends()` function for cases where it should already know the outcome. This PR should not change any actual logic within ER.
This seems to save roughly 30%-50% of time spent within `create_regions`. Though the time will still grow as more players are in the generation, and it seemingly does less as more players are completed.
Time Before/After running 32 Insanity ER + Trainer Sanity
```
Took 8.56065619999572/2.9293287999971653 seconds in PokemonRedBlueWorld.create_regions for player 1, named DeamonPoke1.
Took 7.143686400006118/3.29854239999986 seconds in PokemonRedBlueWorld.create_regions for player 2, named DeamonPoke2.
Took 6.896408300002804/2.74106490000122 seconds in PokemonRedBlueWorld.create_regions for player …
```

Pokemon R/B: Avoid a case of repeatedly checking of state in ER

---

worlds/LauncherComponents.py
worlds/_bizhawk/client.py

Adds a new field for individual clients to specify the suffixes of their patch files. When the client is registered, the BizHawk Client component has its file identifier updated to include the new suffixes.
Also removes mentions of BizHawkClient from `LauncherComponents.py` entirely, which fixes some duplicated code. And now the component will _actually_ only load if a world imports it.
Tested with Emerald, and also made a dummy clients with each of `str`, `tuple[str, str]`, and `None` in their `patch_suffix` var, and then checked the listed file extensions in the "Open Patch" file selection dialog.

BizHawkClient: Improve updating component's suffix identifier

---

worlds/timespinner/__init__.py

In the new options system added in #993 the options on the multiworld instance are nolonger available inside the constructor, therefor i had to move my method that calculates logic constrains based on those options to generate_early
If the options do again become available at constructor time, than this can be close
Many local generations with one or multiple players

Timespinner: Fixed generation error caused by new options system

---

worlds/stardew_valley/__init__.py
worlds/stardew_valley/regions.py

Fixes SDV failures. should also speed it up since it uses the pre-existing cache instead of just pretending it doesn't exist.
unit tests succeed now.

SDV: Use the pre-existing cache in location creation

---

worlds/stardew_valley/stardew_rule.py

No class should ever inherit from And, Or, False_ or True_ and isinstance is not free. Sadly there is no cheap way to forbid inheritance, but it was tested using metaclass.
Speed up overall rule creation in Stardew Valley by ~4%, hopefully without interfering with upstream changes.
Unittests and verifying that no class inherits from Or, And, True_ or False_

Stardew Valley: speed up rules creation by 4%

---

BaseClasses.py

custom_data was meant as container for per-world data. Nowadays we have World classes for that so it has lost its use.
wasn't.

Core: remove custom_data

---

BaseClasses.py
worlds/oot/__init__.py

Made a 300 world Factorio gen take 132 seconds instead of 160  seconds.
With 300 Factorio worlds

OoT: create and copy less useless data state

---

Utils.py
test/general/test_host_yaml.py
worlds/adventure/Rom.py
worlds/lufia2ac/Rom.py

Also changed the two games in main that were using Utils.OptionsType, so dropping that is easier when we drop it.

Core: deprecate Utils.get_options and remove Utils.get_default_options

---

worlds/minecraft/__init__.py

Minecraft's \*.apmc files came with an additional prefix, resulting in the name "AP_AP_\<seedname\>_\<player\>.apmc", unlike most other game patches.
Generated a game and looked at the generated patch file.

Minecraft: avoid duplicate prefix in output file name

---

worlds/sm64ex/Options.py
worlds/sm64ex/Rules.py
worlds/sm64ex/__init__.py

New goal for sm64ex, instead of just BitS this requires completing both BitDW and BitFS as well.
Was asked for on discord, felt like adding it.
Generated, playtested.
If someone is interested in testing this, note that sm64ex needs to be compiled on branch `ap_test`

sm64ex: All Bowser Stages Goal

---

worlds/stardew_valley/stardew_rule.py
worlds/stardew_valley/test/TestLogicSimplification.py

~~giving 33% speedup in set_rules~~
giving 20% speedup in set_rules
Instead of creating new rules in `simplify()`, we try to replace the current one and remember if it was simplified already. This has the effect of simplification-caching in some of the dicts, like item_rules.

Stardew Valley: reuse simplified rules

---

worlds/hk/Rules.py

just a tiny  optimization I happened to notice when looking at region and location access
wasn't

HK: skip for loop

---

Fill.py
worlds/alttp/Dungeons.py
worlds/alttp/__init__.py

Some alive signals during a long fill step
with 300 Factorio worlds

Core: log fill progress

---

worlds/oot/Entrance.py
worlds/oot/EntranceShuffle.py
worlds/oot/Rules.py
worlds/oot/__init__.py

- Entrance randomizer no longer grows with multiworld
- Improved ER success rate again by prioritizing Temple of Time even more
- Prefill is faster, has slightly reduced failure rate when map/compass are in dungeon but previous items in any_dungeon (which consumed all available locations), no longer removes items from the main itempool; itemlinked prefill items removed to accomodate improvements
- Now triggers only one recache after `generate_basic` instead of one per oot world
- Avoids recaches during `create_regions`
- All ER temp entrances have unique names (so the entrance cache does not break)

OoT Time Optimization

---

worlds/pokemon_rb/__init__.py

You can set `fossil_check_item_types` to `no_key_items` but then turn `key_items_only` on, resulting in no non-key-items to fill the fossil checks. This skips processing the `fossil_check_item_types` rules at all if `key_items_only` is on
Generating with same seed # of a previously failing generation

Pokémon R/B: Fix incompatible option combination

---

BaseClasses.py

has `Region.connect` return the `Entrance` it connects, so that additional operations can be done to it beyond just adding rules to it.
wasn't

Core: return the created entrance when connecting regions

---

BaseClasses.py
Generate.py
Utils.py
test/bases.py
test/general/test_memory.py
test/utils/test_caches.py
worlds/sm/__init__.py

Supersedes #2399
Use of @Utils.cache_self1 gives a "Parameter(s) unfilled" on call site in pycharm, but mypy claims it's fine. If anyone knows if we can fix that, please let me know.
Maybe @el-u with the typing experience.

 Core: fix some memory leak sources without removing caching

---

worlds/checksfinder/docs/en_ChecksFinder.md
worlds/ff1/docs/en_Final Fantasy.md
worlds/mmbn3/docs/en_MegaMan Battle Network 3.md
worlds/oot/docs/en_Ocarina of Time.md
worlds/pokemon_rb/docs/en_Pokemon Red and Blue.md
worlds/sc2wol/docs/en_Starcraft 2 Wings of Liberty.md
worlds/tloz/docs/en_The Legend of Zelda.md
worlds/undertale/docs/en_Undertale.md
worlds/wargroove/docs/en_Wargroove.md
worlds/zillion/docs/en_Zillion.md

Adds the commands unique to various clients to the appropriate game page.
This PR is in response to the discussion on #2213 concerning where these client commands should be documented.
Commands were pulled from their respective client python files. If any were missed, please let me know so that I can add them.
Additionally, it might be in our interest to require that world maintainers include these commands to their game page. This is not enforced in this PR, but I figured this would be a good place to spark that discussion.
Affected Games and CodeOwners:
Was not, doc change

Docs, Various Games: Add Unique Local Commands to Game Page

---

WebHostLib/static/assets/weighted-options.js

The request for the JSON file that provides the setting data was missed during the rename in #2037, so prior to this the weighted settings page wasn't rendering at all.
I visited the weighted-settings page before and after.

Fix weighted-settings page

---

worlds/ror2/Options.py

With the new options I didn't notice that the item weights got moved to the beginning of the settings and I'd rather them be at the end.
This also changes the default game mode to explore, and turns scavengers off by default.
Ran Webhost

RoR2: update options

---

worlds/terraria/docs/setup_en.md

a line to the Upgraded Research Mod that tells people that it can automatically research items to prevent people from reporting the mod not working cause they don't notice the item they received got automatically researched and did therefore not land in their inventory.
by reading it

Docs: Terraria Setup Guide added information about the Upgraded Research Mod

---

worlds/oot/Patches.py

99 bugs on the wall
take one down, patch it around
99 bugs on the wall
(this is caused by a fix that allowed you to start with thieves hideout keys, which broke the only place that the variable is blindly iterated over, hidden by one setting)

OoT: fix enhanced_map_compass generation failure

---

BaseClasses.py
test/general/test_fill.py
worlds/AutoWorld.py
worlds/alttp/UnderworldGlitchRules.py
worlds/alttp/__init__.py
worlds/archipidle/Rules.py
worlds/dlcquest/Rules.py
worlds/dlcquest/__init__.py
worlds/hk/__init__.py
worlds/ladx/Locations.py
worlds/ladx/__init__.py
worlds/messenger/__init__.py
worlds/oot/__init__.py
worlds/smz3/__init__.py
worlds/stardew_valley/test/TestRules.py

Changes `CollectionState.prog_items` from a `Counter[Tuple[str, int]]` to a `Dict[int, Counter[str]]`, offering more speed.
Generated 1000 world messenger multiworld 10 times before and after and saw a ~9% speed increase. Could use more testing and benchmark numbers, but this should increase generation speed overall.

Core: make state.prog_items a `Dict[int, Counter[str]]`

---

worlds/oot/Rules.py
worlds/oot/__init__.py

I made a rather severe mistake and must fix it before more async generations die

OoT: fix incorrect calls to sweep_for_events

---

worlds/sm/__init__.py

In #2400 i failed to update one of the lines that accessSMWorld.spheres. This PR fixes that by updating the missed line.
Generating with [this yaml](https://discord.com/channels/731205301247803413/1169643213787779212/1169643213787779212) and a couple of random yamls and not seeing the error anymore.

SM: fix missed SMWorld.spheres in #2400

---

Utils.py
worlds/__init__.py

AppImage: allow loading apworlds from ~/Archipelago and copy scripts
also fixes some mypy and flake8 violations in `worlds/__init__.py`
`from worlds.AutoWorld import AutoWorldRegister; AutoWorldRegister.world_types.keys()` on py3.9 and py3.11
and [Generate Template Settings] from the AppImage

AppImage: allow loading apworlds from ~/Archipelago and copy scripts

---

worlds/dlcquest/__init__.py

I fix a bug where I made an item early but it didn't exist so stardew was waiting for the early item to be collected and the generation exploded.
I also finally added get_filler_item_name
a generation bug between DLC Quest and Stardew
ran the yaml that didn't worked before with success

DLC Quest Stardew bug

---

worlds/factorio/Locations.py
worlds/factorio/__init__.py

Gives almost 1000 locations per science pack.
I've received the occasional bug report of failed gens when  using max traps with red science. I don't understand why people do it, but now they can. It also switched from hex to dec, which  seemed  to have confused some people.
sending and receiving some Factorio stuff

Factorio: inflate location pool

---

UndertaleClient.py
worlds/undertale/docs/en_Undertale.md

Added code review that was mistakenly left as pending in #2285
Additionally, modified docstrings in client to reflect the additional information.
Running webhost

Docs, Undertale: Added Suggestions Missed in #2285

---

test/general/test_implemented.py

slot data test needs to run fill so that all data that a world might need is available and can be properly tested against. we've been getting far more failures on this test than i ever expected due to fill, so this prints the seed to help find and fix those.

Tests: log the seed for slot_data failures

---

worlds/sc2wol/Client.py
worlds/sc2wol/Locations.py
worlds/sc2wol/Options.py
worlds/sc2wol/PoolFilter.py
worlds/sc2wol/Starcraft2.kv
worlds/sc2wol/__init__.py

Fixes few minor generation-related bugs:
Generated few affected games and some other ones, launched the client and connected to the slot
See also: 
https://github.com/Ziktofel/Archipelago/pull/59
https://github.com/Ziktofel/Archipelago/issues/58
https://github.com/Ziktofel/Archipelago/pull/66

SC2: 0.4.3 bugfixes

---

worlds/raft/__init__.py

Raft's \_\_init\_\_.py has a few instances of "random.choice" in the world class, which should be "self.random.choice"

Raft: Use world.random instead of global random

---

worlds/lingo/LL1.yaml
worlds/lingo/player_logic.py
worlds/lingo/static_logic.py

An intermittent generation failure was found involving painting shuffle and the region Outside The Wise. Outside The Wise + The Wise make up a two room island that can only be entered via painting, and so to ensure that this area is reachable when painting shuffle is enabled, one of the paintings in Outside The Wise is marked as a "required" painting. However, it was possible for the painting *inside* The Wise to lead to the required painting in Outside The Wise, and for no other paintings to lead to either the required painting or the non-required painting in Outside The Wise. This PR fixes this hole by preventing the internal painting from mapping to any required painting.
A couple of similar issues were identified in The Wondrous (Table) and the Owl Hallway specifically when door …

Lingo: Fix edge case painting shuffle accessibility issues

---

worlds/lingo/player_logic.py
worlds/lingo/rules.py

I have been told that it is safe to use state.can_reach for Regions within the access rules of a Location (not an Entrance). Previously, I was using event items to determine whether a room had been reached within a Location access rule, but I've removed those items and switched to using state.can_reach. This has resulted in a 70-80% speedup in single world generations.
I ran multiple generations with 100 Lingo worlds, which succeeded (and there was a marked speedup in them).

Lingo: Removed "Reached" event items

---

worlds/messenger/__init__.py
worlds/messenger/regions.py
worlds/messenger/rules.py
worlds/messenger/subclasses.py
worlds/messenger/test/test_shop_chest.py

Fixes a logic mistake with incorrect parens, and a missing rule to get to the goal region for power seal hunt. Also reverts to the older region connection method since it's faster with the new cache. Also removes some extra unused data.
Generated a couple hundred seeds and checked states.

The Messenger: fix logic rule for spike darts and power seal hunt

---

WebHostLib/options.py
WebHostLib/static/assets/weighted-options.js
docs/world api.md
test/bases.py
worlds/AutoWorld.py
worlds/dark_souls_3/Items.py
worlds/dark_souls_3/__init__.py

These are displayed in the weighted options page as hoverable tooltips.
I've added an example description in the DS3 world. I verified that it produces a tooltip. I manually verified that the new tests pass and fail under the expected circumstances.

World, WebHost: Allow worlds to provide item and location descriptions

---

inno_setup.iss

#2268 removed all of the `client/*` components from `inno_setup.iss`, but this wasn't removed from the #1813 Emerald PR, meaning creating the installer fails with an "Invalid component" error
Created an installer after making my change, it doesn't error anymore.

Installer: Fix invalid component error in inno_setup.iss

---

worlds/lingo/regions.py

Previously, some region entrances were generated with identical names (e.g. there are two different doors that connect the Hub Room and The Tenacious, so both entrances had the same name). This caused test failures under #2453. This PR makes normal entrances unique by putting the name of the door into the entrance name, and it makes painting entrances unique by putting the ID of the source painting into the entrance name.
I patched #2453 into my workspace and verified that the tests failed before the change and now pass after the change.

Lingo: Made entrance names unique

---

worlds/Files.py

limits how many threads are trying to write files to something reasonable.
just quickly with LttP to see that it works, did not measure time impact.

Core: limit parallel APContainer writing

---

worlds/AutoWorld.py

limit perf logger to 4 post-point places
I meant to do that, but kind of forgot.
nope

Core: limit perf logger to 4 post-point places

---

setup.py

orjson has a .py entry point that imports `from .orjson` (from the DLL), which does not work on 3.8 if the DLL is not in the same folder as the .py. The changed import system in 3.9+ seems to allow this. Excluding it from libraries.zip will put both files into the same folder.

Setup: fix orjson import on frozen py3.8

---

worlds/lufia2ac/__init__.py

Modifies various access rules in the lufia2ac world with the aim of making them evaluate quicker.
Instead of having to determine the reachability of another location, they now only have to count items in state, which is faster.
(Also made it reuse the identical lambda for multiple locations, which might save a smidgen of memory.)
*"But el_, why didn't you rewrite everything using regions?"*
Not sure if much faster, the current benchmark PR is not entirely suitable to compare that. Anyway, the location access rules should at least be reasonably fast now at least.
Also, introducing more regions would probably have made the world code slightly more involved, while I'd argue that this PR instead makes the code more readable. 
So I'll leave it like that for now and we can see whether further …

lufia2ac: improve performance of access rules

---

BaseClasses.py

https://discord.com/channels/731205301247803413/731214280439103580/1174096630425862256
also threw in some micro optimizations
unittests

Core: relax typing hints on has_all and has_any

---

test/bases.py
test/general/test_items.py
test/general/test_locations.py

As part of #2409, `test_descriptions_have_valid_names` was added to `WorldTestBase`. The implementation has various disadvantages:
- The identical test is run over and over again, once for every non-default world test class.
- The test does not run at all for worlds that do not define any non-default world test classes.
- (The test creates a world instance and runs various generation steps, even though the behavior being tested is that of the world type.)
This PR removes the descriptions test from bases.py and adds two new tests, in test\_items.py and test\_locations.py, which test all registered world types while not creating any multiworlds or world instances.
- Observed that the number of tests discovered by pytest goes down by about 150 when switching to the new tests.
- Verified that …

core: fix item/location descriptions test

---

docs/apworld specification.md
docs/options api.md
docs/world api.md

Changes the recommendations to use modern PEP8 conventions, such as lower-case modules, and adds typing to all the example methods. Also gives a bit stronger example of `options.as_dict` and recommends against setting up the world before `generate_early`
👀

Docs: minor updates to recommend modern PEP8

---

docs/contributing.md

Adding a lot of details to the contributing.md document to make it more beginner-friendly
Feedback?

Docs: Rework of Contributing.md

---

Main.py

in debug mode, checks that location address is unique per player
just with a run of LttP so far

Core: check that location address is unique per player

---

WargrooveClient.py
worlds/wargroove/docs/wargroove_en.md

Wargroove: Fixed WargrooveClient retaining victory and location information during slot switching. Fixed Documentation wording around navigating steam menus. https://discord.com/channels/731205301247803413/1090824439710625822/1174041565170245742
I swapped between a slot with victory achieved and a slot with no victory yet. I verified the slot with no victory yet did not receive a victory in error.

Wargroove: Fixed WargrooveClient retaining victory and location information and minor doc fix

---

worlds/pokemon_emerald/data/regions/routes.json
worlds/pokemon_emerald/rules.py
worlds/pokemon_emerald/test/test_accessibility.py

Access to a particular cave requires Surf, but that requirement wasn't represented by existing regions and rules. This just splits the pond itself into a new region and adds the requirement.
`ITEM_ROUTE_120_NEST_BALL` is visible in the below screenshot
`ITEM_SCORCHED_SLAB_TM11` is inside the cave
Wrote a new test that fails on `main` and passes here.

Pokemon Emerald: Fix scorched slab missing surf requirement

---

worlds/hk/__init__.py

Some discussion here https://discord.com/channels/731205301247803413/1176684007061205074
In short there's 5 mimics, them being local or not doesn't really matter at all because there are so few that they're barely meaningful anyway except when it breaks setup in unexpected ways, especially since they can go in shops and such. Plus we have plans to improve the quality of traps in HK anyway https://github.com/ArchipelagoMW-HollowKnight/Archipelago.HollowKnight/issues/20
It wasn't but I can't see any possible way this would break anything

Hollow Knight: Don't force mimics local

---

.gitignore

After a local mess up, adding a file to the git that is probably illegal to add to a git, and having to clean up the resulting mess, I figured maybe gitignore should prevent it.

Git: Added file type .smc to gitignore

---

worlds/mmbn3/docs/setup_en.md

Adds instructions to MMBN3's Setup Guide for how to extract the ROM from the PC version of the Legacy Collection.
Instructions provided and verified by Discord users (Notably tauakiou who provided all the file names in one place, thanks!) who have successfully patched and played the randomizer with files from the Legacy Collection

MMBN3: Adds instructions for using the Legacy Collection ROM for setup

---

worlds/stardew_valley/__init__.py
worlds/stardew_valley/data/bundle_data.py
worlds/stardew_valley/items.py
worlds/stardew_valley/test/TestItemLink.py

It was brought to my attention that when playing with item links, Stardew Valley only generates Joja Cola. I fixed that to generate any resource pack. It can also provide traps if traps are enabled. Special conditional resource packs will only be provided if they should, based on settings
New unit tests for that feature, then running every test

Stardew Valley: Generate proper filler for item links

---

worlds/pokemon_emerald/__init__.py

The first 0-4 moves in a pokemon's learnset are empty placeholders so that there's room for extra moves if the player sets `level_up_moves` to `start_with_four_moves`. When picking moves to give to a trainer's pokemon, it should pick from the learnset but exclude these placeholders.
A species' learnset is guaranteed in the game data to have at least 1 non-zero move starting at level 1, so there is never a situation where `level_up_movepool` will be empty.
Running a couple generations to make sure no opponents ever have a 0 in their pokemon's moveset.

Pokemon Emerald: Fix opponent trainer moves sometimes being MOVE_NONE

---

worlds/lingo/docs/setup_en.md

I'm now distributing the Lingo AP client through Steam Workshop, so I'm updating the documentation to provide a link to that (as well as to describe where you can go if you still want to manually install it).
Doesn't need to be.

Lingo: Change docs to link to the client in the Steam Workshop

---

worlds/kh2/docs/en_Kingdom Hearts 2.md
worlds/kh2/docs/setup_en.md

fixing the docs so people can still not read them
I read them on the local webhost

KH2: Update Game Docs

---

worlds/sm64ex/docs/setup_en.md

The old launcher was """inherited""" from an existing project aiming to provide a launcher for windows and linux.
Original intention was to improve upon it, and merge everything into upstream, keeping it as generic as possible.
However, upstream abandoned the project not long after, without responding to pull requests.
The launcher additionally had many assumptions built in, and was very unstable. Extending it for new features (such as the patches) was annoying to say the least. There was very little input validation, and users often stumbled on simple issues, causing frustration. Examples include leaving fields empty, use of invalid make flags, exiting the program early due to missing feedback, providing invalid paths and more. While I've fixed some of these issues (Adding `Browse...` …

sm64ex: Replace old launcher tutorial

---

worlds/_bizhawk/__init__.py

In #2369, some code was deduped between `get_script_version` and `send_requests`, but in doing that I forgot to retain the error checking that was specific to `send_requests`. Right now, when the connector sends back an `ERROR` response, it bubbles up in the python code as a `SyncError` and whatever message the connector attached isn't displayed.
This just adds back the check that will raise a `ConnectorError` with the relevant error message.
Playing some Emerald with the change, and editing the connector to intentionally send back an `ERROR` response to see that the error message showed up in the log.

BizHawkClient: Restore use of ConnectorErrors

---

requirements.txt
worlds/factorio/requirements.txt

fixes emerald importing orjson without it having it in its requirements, by moving it from Factorio to core
updates modules
quickly, no implosion yet

Core: update modules, move orjson to core

---

worlds/kh2/docs/en_Kingdom Hearts 2.md

changes "Each of the 8 cups can have a bounty" to Godess of Fate cup and Hades Paradox cup
I read it

KH2: Fix grammar to clarify which locations can have a bounty

---

Generate.py
Main.py
WebHostLib/generate.py

Adds a flag, `--skip_output`, intended for testing/debugging multiworld generation without running output stages. Also skips `assert_generate` stages as ROM output is not required.
`Generate.py --help` output:
```yaml
> python .\Generate.py --help             
[...]
options:
[...]
--skip_output         Skips generation assertion and output stages and skips multidata and spoiler output. Intended for debugging and testing purposes.
```
Ran test generation with default templates of all games currently in `main`, excluding `Archipelago` and `Sudoku`.
```yaml
> python .\Generate.py --skip_output
Archipelago (0.4.3) logging initialized on Windows-10-10.0.22621-SP0 running Python 3.11.4
[...]
Generating for 47 players, 97632999143129170817 Seed 16052371818855632864 with plando: items, …
```

Generate: Add `--skip_output` flag to bypass assertion and output stages.

---

worlds/lingo/__init__.py

When door shuffle is on, some progression items reveal paintings that you can use to warp to other places. When painting shuffle is on, it is possible for some of those paintings to not lead anywhere. In this circumstance, those items should be marked as filler rather than progression.
This is not important; it is just a nicety for the player.
pytest, as well as a single playthrough of the game on the settings described above.

Lingo: Demote warpless painting items to filler

---

MMBN3Client.py
worlds/mmbn3/Locations.py
worlds/mmbn3/__init__.py

- Fixes a text box index causing the wrong message to be replaced in the Yoka Zoo Garbage Can, which led to getting both the randomizer item and the original Repair * Chip that is found there in vanilla
- Changes item handling mode so starting inventory is properly sent by the server
- Changes logic to prevent progressive items from ending up on WWW Island, so games can no longer be BK'd waiting for MMBN3 to completely finish the game
- Local seeds generated and checked manually

MMBN3: Small Bug Fixes

---

MultiServer.py
docs/network protocol.md

Implements a new read-only data storage key `_read_client_status_{team}_{slot}` which returns the `ClientStatus` of a particular slot. Also adds the relevant documentation.
Tested with a test client using Archipelago.js.
Retrieve:
SetNotify & StatusUpdate:
SetNotify & StatusUpdate from another client, SetNotify event fired:
N/A

MultiServer: Create read-only data storage key for client statuses.

---

docs/CODEOWNERS

DOOM II merged, but dev/world not added to `CODEOWNERS` doc.
Yes.
N/A

DOOM II: Add to `CODEOWNERS`

---

inno_setup.iss

Installer will delete `_bizhawk.apworld`, which was in use for versions 0.4.2 and 0.4.3. Unsupported implementations which relied on `_bizhawk.apworld` should continue to work with no modification (assuming they followed the examples given), but if `_bizhawk.apworld` exists, it seems like it's possible that it gets imported over the version that came in the installer (may depend on import order). Whatever the case, it's redundant at best to keep the apworld version around.
Progress on creating apworlds out of lib worlds and importing them would make this unnecessary, but until then, I think this line should be included.
Creating and running an installer to watch it delete the file. Also running the currently released Pokemon Emerald apworld with and without `_bizhawk.apworld` to make sure …

Installer: Add `_bizhawk.apworld` to installer deleted files

---

docs/options api.md

some missing documentation on doing option comparisons to the options api doc
👀

Docs: add documentation for options comparison

---

worlds/sa2b/AestheticData.py

Several games are getting added with AP 0.4.4; this adds a character name for those that seem to have named characters to work with to the default Chao names.
Ran some generations, saw the names.

SA2B: Add AP 0.4.4 Game Chao Names

---

worlds/pokemon_emerald/client.py

Sometimes if the menu is opened or a battle is started between the two separate reads of the save data, the second half of the flags aren't included while checking locations and events, so they're essentially determined to be not set. This isn't a problem for locations, but for the events used by the tracker, it means the flags are temporarily assumed to be unset.
Using `or` instead of `replace` should retain the flags that were already set. And will also prevent fighting between two clients playing in the same slot which will have different event flags set.
Ran a seed until 2 event triggers to see them get sent and tracked correctly.

Pokemon Emerald: Fix tracker flags being reset in menus

---

worlds/_bizhawk/context.py

Makes the `--lua` arg to BizHawk use an absolute path to the connector instead of a relative one. Previously on Linux the relative path would be interpreted to be from the BizHawk install directory instead of the AP install directory.
Running the client with autolaunching on both Windows and Ubuntu to see it launched with the lua script running.

BizHawkClient: Use `local_path` when autolaunching BizHawk with lua script

---

Zelda1Client.py

Apparently we've been using the wrong thing to lookup location names in Z1Client and didn't realize it until #2438 removed what we had been using before. 
Booted up a test seed and made sure locations sent properly

TLOZ: Use the proper location name lookup

---

WebHostLib/static/assets/weighted-options.js

This change fixes a bug causing input values used to create a new row for a range entry to be considered invalid if the entered value sits on the edge of the range.
Tested locally.

WebHost: Fix weighted-options outer range being rejected

---

worlds/dark_souls_3/docs/setup_en.md

We want to preserve this on the AP site as the future of the speedsouls wiki is unknown and may disappear at any time.
This is adding a revised version of the downpatching guide from the Speedsouls Wiki for use with Archipelago.

DS3: update setup guide to preserve downpatching instructions

---

worlds/stardew_valley/logic.py

There was a missing logic rule when checking for different walnut areas, to verify if the player can obtain enough walnuts for purchases. The system is designed so that it is impossible for a player to make the "wrong" purchases and get stuck. But since the Field office contains 20 potential walnuts, and wasn't being checked, it was possible for a bad entrance randomizer roll to create a scenario where a player **could** misspend their walnuts and get softlocked
Ran existing tests, but did not add any new one for this rule, as I am not sure how to simulate a specific entrance randomizer roll under the current system. After ProfByte's rework of the entrance randomizer, I'll be adding tests for cases like this

Stardew Valley: Fixed potential softlock with walnut purchases if Entrance Randomizer locks access to the field office

---

WebHostLib/templates/pageWrapper.html

flash() can emit the same message multiple times, for example if @app.after_request is used and static files are served through flask, each static file will trigger the after request, which in turn can run a flash() which accumulate.
on https://berserkermulti.world
Before:
After:

WebHost: flash each message only once

---

worlds/pokemon_rb/regions.py

- Adds a missing connection from Cerulean City-T (in the doorway but potentially blocked by the officer) to Cerulean City with Fly - if you are in the City anywhere you gain access to flying to the city.
- Several entrance names were being used in multiple entrances, this has been fixed.
- When entrance shuffle was off, the specified names of entrances were being ignored, leading to even more duplicate entrance names.
- Deletes a straight up duplicate entrance (Route 8-W to Saffron City was being connected twice)
Running generate with some debug code to warn if duplicate entrance names existed.

Pokémon RB: Fix shared connection names + missing connection

---

worlds/ladx/Options.py

We were using data created in __init__ when we never called __init__

Fix bug with Webhost and LADX sprites

---

worlds/witness/player_logic.py

Door entities think they can be solved without any other panels needing to be solved.
Usually, this is true, because they no longer need to be "powered on" by a previous panel.
However, there are some entities that need another entity to be powered/solved for a different reason.
In this case, Symmetry Island Lower Left set opens the *latches* that *block your ability to solve* the panel. The panel itself actually *starts* on. Playing doors: panels does not change this, unlike usually where dependencies like this get removed by playing that mode.
In the long term, I want to somehow be able to "mark" dependencies as "environmental" or "power based" so I can distinguish them properly.
Shortest version ever: Colored Dots can be on Symmetry Island Upper Panel in a doors: panels seed, which …

The Witness: Fix logic error with Symmetry Island Upper in doors: panels (broken seed reported)

---

worlds/sm64ex/Regions.py
worlds/sm64ex/Rules.py
worlds/sm64ex/__init__.py

Refactors region code to remove references to course index.
There were bugs somewhere, but I dont know where tbh.
This fixes them but leaves logic otherwise intact, and much cleaner to look at as there's one list less to take care of.
Additionally, this fixes stopping the clock from Big Boos Haunt.
Multiple generations, attempting to stop the clock in bbh (also needs client fix, but that one is backwards compatible).

sm64ex: Refactor Regions and BBH clock fix.

---

ZillionClient.py
worlds/zillion/__init__.py
worlds/zillion/logic.py
worlds/zillion/test/__init__.py

`colorama` has type stubs when it didn't before
`ZillionDeltaPatch.hash` annotated type could be `None` but md5s doesn't allow `None`
type of `CollectionState.prog_items` changed
`WorldTestBase` moved
all of the following are related to this issue:
https://github.com/python/typing/discussions/1486
`CommonContext` for `command_processor` (is invalid without specifying immutable - but I don't need it anyway)
`ZillionWorld` `options` and `settings` (is invalid without specifying immutable - but I do need it)
unit tests and type checkers

Zillion: some typing fixes

---

WebHostLib/customserver.py

Currently when a room shuts down while clients are connected it instantly spins back up. This fixes that behaviour categorically.
I still don't know why or when this problem started, but it's certainly wreaking havok on prod.
I set room timeout quite low, connected a text client. Without this change, I would get a disconnect, the room would start back up and the auto reconnect would succeed. With this change, I get a disconnect and then nothing happens other than the text client  trying to reconnect but is not let in.

WebHost: fix room shutdown

---

worlds/witness/player_logic.py
worlds/witness/regions.py
worlds/witness/rules.py

Basically, the function for "checking entrances both ways" only checked one way. This resulted in unreachable locations.
This affects Expert seeds with (non-remote doors and specific types of EP Shuffle), as well as seeds with non-remote doors + specific types of disabled panels + specific types of EP Shuffle.
Also includes two changes that makes spoiler logs nicer (not creating unnecessary events).

The Witness: Fix unreachable locations on certain settings (Keep PP2 EP, Theater Flowers EP)

---

worlds/messenger/docs/en_The Messenger.md
worlds/messenger/docs/setup_en.md

The alternative tracker hasn't been updated since the poptracker pack was made so doesn't contain most of the locations or items that exist in the rando now, and the logic is inaccurate. Cleans up some of the links a bit and renames settings to options.
Ran webhost and clicked stuff

The Messenger: remove old links and update relevant ones in docs

---

worlds/witness/player_logic.py

https://github.com/ArchipelagoMW/Archipelago/pull/2565 didn't actually fix what it was supposed to fix.
I got lazy and didn't properly test the last fix, I just tested that it doesn't break anything, but not whether it actually fixes the problem.
Big apologies, I got a bit panicked with all the logic errors that were being found inbetween being busy with other stuff. Not an excuse though.
This iteration is tested - Medic plandoed Colored Dots onto Symmetry Island Upper Panel and it didn't generate (which is correct)

The Witness: Fix Symmetry Island Upper Panel logic (2nd try)

---

ZillionClient.py

Fix processing a retrieved packet when it doesn't have the expected key.
This is the fix from https://github.com/ArchipelagoMW/Archipelago/pull/2560 so that it doesn't have to wait on review of another game.
On the https://github.com/ArchipelagoMW/Archipelago/pull/2560 branch, I played through a game, testing the feature that this touches.

Zillion: fix retrieved packet processing

---

worlds/alttp/ItemPool.py
worlds/alttp/__init__.py

Ensure all small and big keys for Hyrule Castle are always local items in Standard mode.
Generating multiworlds and observing spoiler log.

ALTTP: Ensure all Hyrule Castle keys are local in Standard

---

worlds/tloz/ItemPool.py

As discovered by this bug report https://discord.com/channels/731205301247803413/1182522267687731220 it's currently possible to accidentally have the starting weapon of a player overwritten by a triforce fragment if TriforceLocations is set to dungeons and StartingPosition is set to dangerous. This fix makes sure to remove the location of a placed starting weapon if said location is in a dungeon from the pool of possible locations that triforce fragments can be placed in this circumstance.
rolled with the yamls and seed given in the bug report and confirmed that the starting weapon did not get overwritten by a triforce fragment.

TLOZ: Fix starting weapon possibly getting overwritten by triforce fragments

---

worlds/factorio/Options.py

fix wrong parent class for FactorioStartItems
no

Factorio: fix wrong parent class for FactorioStartItems

---

BaseClasses.py

some type annotations and a doc string
unit tests

Core: some typing and documentation in BaseClasses.py

---

worlds/factorio/Mod.py

https://discord.com/channels/731205301247803413/1178493541983465643
Also even less copy-pasting as even in non-.apworld form it avoids copying into a temp folder.
The crash was related to trying to clean up the temp folder, when the temp folder is neither needed nor made in apworld form.
Now it's never needed and the remove command is also removed.
rapidly

Factorio: remove staging folder for mod assembly

---

worlds/lingo/__init__.py
worlds/lingo/data/LL1.yaml
worlds/lingo/data/ids.yaml
worlds/lingo/player_logic.py
worlds/lingo/regions.py
worlds/lingo/rules.py
worlds/lingo/utils/validate_config.rb

The most serious issue this PR addresses is that entrances that use doors without items (a small subset of doors when door shuffle is on, but *every* door when door shuffle is off, which is the default) underestimate the requirements needed to use that entrance. The logic would calculate the panels needed to open the door, but would neglect to keep track of the rooms those panels were in, meaning that doors would be considered openable if you had the colors needed to solve a panel that's in a room you have no access to.
Another issue is that, previously, logic would always consider the "ANOTHER TRY" panel accessible for the purposes of the LEVEL 2 panel hunt. This could result in seeds where the player is expected to have exactly the correct number of solves to reach LEVEL 2, but in …

Lingo: Fix entrance checking being broken on default settings

---

worlds/sm64ex/Regions.py
worlds/sm64ex/Rules.py

#2546 has broken generations due to stupid mistakes on my part.
This fixes it together using partial backport from #2569.
Reported on discord from RC.
Generations
~100 gens

sm64ex: Fix generations

---

worlds/witness/WitnessLogicVanilla.txt
worlds/witness/items.py

Ok so for being a PR that changes 10 characters, explaining it is actually quite involved, so stay with me here
Some EPs (Environmental Puzzles) require you to use alternate solutions to specific panels that affect the environment.
When EP shuffle was introduced, we had to make certain puzzles remove their symbols after solving them for the first time, because the solvability of related EPs is not guaranteed in Sigma Rando.
However, when "puzzle_randomization: None" was introduced, the client added a check for it on whether to remove panel symbols, because it is not necessary if the panels have their vanilla contents - The vanilla panels were made with EP solvability in mind (obviously)
HOWEVER.
The specific solution to Keep Pressure Plates 2 that allows you to solve Keep Pressure Plates …

The Witness: Fix Logic Error for Keep Pressure Plates 2 EP in puzzle_randomization: none

---

worlds/witness/hints.py

Exempt-Medic discovered that the in-game hints have been non-deterministic for a while. This should address that, mostly by changing some sets to lists and doing a sorted() call on the remaining set.
Exempt-Medic has verified that the hints seem to be deterministic now.

The Witness: Fix non-deterministic hints

---

Fill.py

remove a variable and its updates, skipping instructions
pops by index instead of equality, which is quite a bit faster in itself, though not that much in the context of the whole function
just a few gens that hit that code path

Core: faster prog balance

---

Main.py

Exhausts start_inventory_from_pool items from early_items as well, which fixes:
1. Cases where say early Seaglide has 2 early items, but player could start with 4, making AP search for them to place early but never finding them, wasting time. I believe this would  also crash SDV.
2. Cases where too much would be early. Early Seaglide in Subnautica places 2 Fragments out of 4 into sphere 1, if you have 2 as start_inventory_from_pool you actually have 2 start and 2 in sphere 1, which technically means 4 "early", when 2 was desired.
With Subnautica Seaglide Fragments

Core: remove start_inventory_from_pool from early_items

---

Fill.py
Main.py

Seems the Kaeli Mom Fight Minotaur option is causing failures. I do not know how this got past my initial generation testing. But it seems it results in a rooms.yaml that has this location specified but with no on_trigger which leads it to being created as an empty location (it is an event).
~~I am awaiting wildham's confirmation that this fix is the correct one, but there will need to be a fix.~~ Should be good.
Fixes the Companion Spellbook option as one of the choice's names was not what FFMQR expected, which apparently broke the Progressive Gear option somehow.
Generating with the options on and ensuring patching succeeds and progressive gear works

FFMQR: Fix Empty Kaeli Companion Event Location and Spellbook option

---

data/lua/connector_bizhawk_generic.lua

The problem addressed in this block of code should account for SGB as well as GB and GBC, since it also uses Gambatte and so has the same problematic setting.
See https://github.com/TASEmulators/BizHawk/issues/3711 for more context
Ran Pokemon Red from source, picked up a couple items, used `getitem`. Ran with the Gambatte setting on both equal length frames and vblank frames. Nothing unexpected happened.
Did not try to reproduce the issue. It was noticed by someone playing Wario Land 1, which I don't own.

BizHawkClient: Add SGB to systems using explicit vblank callback

---

WebHostLib/check.py
WebHostLib/upload.py

Does some refactoring and adds additional checks for files that are uploaded to the WebHost.
Additional checks include:
- Screening for additional known ROM extensions.
- Validation that `.zip` files are proper zip files (e.g. not renamed `.rar`/`.7z` files).
- Checks filenames inside subfolders within zips correctly.
- Ignores dot files (i.e. starts with `.`).
- Prevents nested zips from being uploaded (protection against zip fork-bombs).
- Allows additional supported known options extensions.
Also tweaks some of the error messages to be a bit more clear and list all known valid option files if files are submitted without them.
- Uploaded an archive containing dot files inside a `__MACOSX` folder.
- Uploaded a zip containing a `.zip` file.
- Uploaded a zip containing no files.
- Uploaded …

WebHost: Some refactors and additional checks when uploading files.

---

worlds/alttp/Rules.py

Changes `set_defeat_dungeon_boss_rule` to use `add_rule` so it will not overwrite existing boss rules. I believe this only affects Swamp Palace and could have also been solved by moving the boss rules to the entrance to a new boss room region, as is how other boss room access rules work, are but this fix should be less likely to screw up and break something else.
Generating with Small Key (Swamp Palace) plando'd to the Boss, with and without this fix, and seeing it fail only on this branch.

LTTP: Boss Rule Fix

---

worlds/sm64ex/Rules.py

Holdover from #2583.
SM64Levels enum does not seem to be available post-generation?
This fixes it.
Running multiserver again

sm64ex: Fix server

---

worlds/alttp/Dungeons.py

Restores allow_excluded to the dungeon fill_restrictive call, which was apparently removed by mistake during merge conflict resolution
Generating

ALTTP: Restore allow_excluded to fill_restrictive call

---

Options.py
WebHostLib/misc.py
WebHostLib/options.py
docs/options api.md

Makes the python code PEP8, uses `setdefault` instead of importing `defaultdict`, and cleans up most of `WebHostLib\options.py` (i know you barely modified that but it bothered me)
Ran webhost, changed my game options, and checked that it worked.

PEP8 current option_groups progress

---

worlds/sa2b/Rules.py

The `Weapons Bed - Omochao 2` location required the incorrect Eggman upgrade for standard logic difficulty.
Generations with Omosanity on, sanity check. Double checked tracker, data spreadsheet, and in-game.

SA2B: Fix Weapons Bed - Omochao 2 Logic

---

BaseClasses.py
Utils.py
worlds/AutoWorld.py

Old options API had options being set before worlds were created and some worlds relied on that. That behavior has been purposefully deprecated, but old API should still use it for back compat.
Also deprecates the old options API. these can be dropped and wait a version if *really* desired but we've already made the effort of making everyone aware and I'd prefer to properly deprecate it next version.
unit tests. Also very low risk.

Options: set old options api before the world is created

---

worlds/hk/Options.py

https://github.com/ArchipelagoMW-HollowKnight/Archipelago.HollowKnight/issues/157 - Splits DeathLink options up to allow more configuration of behavior on death without needing to program all possible combinations in existing DeathLink option.
https://github.com/ArchipelagoMW-HollowKnight/Archipelago.HollowKnight/issues/58 - Also adds an "ExtraPlatforms" option to create additional platforms in Hallownest to make moving around easier.
@BadMagic100 - Leaving in Draft until client-side can be updated and verified they work with these changes.
No logic changes were made, but verified output on WebHost. Awaiting client-side tests before pulling out of Draft state.
N/A

Hollow Knight: Add additional DeathLink option and add ExtraPlatforms option.

---

worlds/pokemon_rb/__init__.py

Fixes the logic used in determining if a Pokémon must be able to learn Flash.
If no Pokémon can learn Flash, and dark rock tunnel logic is on, then it should be forced on if minimal accessibility is not minimal, OR there are no location checks and no door shuffle. Not AND.
Generating with the yaml supplied in the bug report made by @Exempt-Medic

Pokémon R/B: Flash forced-learnable logic fix

---

worlds/lingo/__init__.py
worlds/lingo/player_logic.py
worlds/lingo/test/TestDoors.py
worlds/lingo/test/TestOrangeTower.py
worlds/lingo/test/TestProgressive.py
worlds/lingo/test/__init__.py
worlds/lingo/testing.py

The static class with the "disable forced good item" field is gone. Now, certain tests that want to check for specific access progression can run a method that removes the forced good item and adds it back to the pool. Tests that don't care about this will collect the forced good item like normal. This should prevent the intermittent fill failures on complex doors unit tests, since the forced good item should provide enough locations to fill in.
Unit tests were run many times. The previously failing seed (windows, 3.11, 98257536790111663995) has been shown to pass now.

Lingo: Tests no longer disable forced good item

---

BaseClasses.py
Options.py
WebHostLib/misc.py
WebHostLib/options.py
WebHostLib/templates/playerOptions/playerOptions.html
worlds/AutoWorld.py

moves option group definitions to webworld so that devs can determine the order to allow for their own custom sorting. This currently forces game options to always be at the top, doesn't allow devs to "add" to it, but it's the default group where options go if they aren't in a separate group. This ensures an option can't be defined in multiple separate groups, and can't appear multiple times in the same group. Items & Location Options is also default filled and put at the end. A world can add custom classes to it and move it to a separate spot if desired, but can't remove the pre-defined options from it.
Set up a few option groups in my world and checked all the above cases worked, as well as moved groups around to check the webhost reflected the changes.

Webhost: implement option groups on webworld to allow dev sorting

---

worlds/factorio/Mod.py

When running source form (non-.apworld) on some OS it would not correctly build the arc_path for the files in the  base directory, due to trailing /, \ or ., this fixes that.
By loading the mod into Factorio and seeing if it complains.

Factorio: fix files from mod base directory not being grabbed correctly in non-apworld

---

worlds/factorio/__init__.py

Fixes issue #2612
Chemical plant requires two stages of progressive processing.  However, the rules didn't actually check for the player having all of the required technologies for the required crafting machine for the recipe.  so in some instances, it might only put one, or maybe even none of the first two processing technologies before the science pack requiring the chemical plant.
Regenerated a known seed where this bug existed with the fix to verify that the issue was in fact fixed.

Factorio: Fix unbeatable seeds where a science pack needs chemical plant

---

worlds/pokemon_rb/__init__.py

Only attempt to place badges in badge locations if they are empty. Return unplaced badges to the item pool if fewer than 8 locations are being filled.
This should fix errors that occur when items are placed into badge locations via plando, or whatever other worlds may do.
By doing the thing.

Pokémon R/B: Badge Plando Fix

---

worlds/pokemon_emerald/docs/en_Pokemon Emerald.md
worlds/pokemon_emerald/docs/setup_en.md

Brings the Emerald docs in line with #2037.
Ran web host, checked pages, clicked links.

Pokemon Emerald: Change "settings" to "options" in docs

---

worlds/tloz/ItemPool.py

It was brought up that if you attempt to non_local any of the starting weapons, there is still a chance for it to get chosen as your starting weapon if you are on a StartingPosition value lower than very_dangerous. This fix will attempt to build the starting weapons list accounting for non_local items, but if all possible weapons have been set to non_local, force one of them to be your starting weapon anyway since the player is still expecting a starting weapon in their world if they have chosen one of the lower StartingPosition values.
Test genned with two yamls, one with just Magical Sword in non_local_items, and one with the weapons item group in non_local items. Confirmed that the Magical Sword yaml did properly remove the item from the possible starting weapons, and that the all …

TLOZ: Try accounting for non_local_items with the pool of starting weapons

---

worlds/noita/__init__.py
worlds/noita/docs/setup_en.md

Adds a note about what characters can be used in slot names. I am currently trying to figure out a good way to not need this note, but in the mean time this note should help avoid issues.
Attempting to generate with yamls with ä in them
N/A

Noita: Don't allow impossible slot names

---

worlds/ff1/__init__.py

terminated_event.access_rule wasn't always set, meaning that the terminated_event was sometime accessible from the very start. See: https://github.com/ArchipelagoMW/Archipelago/issues/2647
Generated a test game with yamls known for triggering that issue and confirmed with the spoiler log that the terminated_event wasn't in sphere 1.

FF1: Fix terminated_event.access_rule not getting set

---

worlds/shivers/Rules.py

Shivers: Bug Fix
Fixes rule logic for location 'puzzle solved three floor elevator'.
Universal tracker showed I had access to a location I did not. Looking in the logic a missing set of parenthesis was found for that locations rules. Universal tracker no longer shows access to the location.
N/A

Shivers: Fixes rule logic for location 'puzzle solved three floor elevator'

---

data/lua/connector_bizhawk_generic.lua

Someone reported an error
```
ERROR: .\json.lua:115: unexpected type 'function'
Consider reporting this crash.
NLua.Exceptions.LuaScriptException: tableConnection to client closed
Client timed out
```
Essentially the `pcall` for `process_request` caught an error, and that error was type `function`, so when the script tried to convert it to JSON to tell the client there was an error, it caused another error.
The actual error was an out of bounds write on GBA, and I guess BizHawk's response is to just throw your own function back at you when you cause an error. So in the case of
```lua
local status, response = pcall(process_request, req)
```
if `process_request` does an out of bounds write on GBA, `response` will be set to `process_request`. I tried letting it bubble up in BizHawk to see if …

BizHawkClient: Add some handling for non-string errors

---

worlds/generic/Rules.py

Checks if a location is already flagged as an event before excluding it during exclusion rule setting. It's possible that a progression item has already been placed on the location by the world, so excluding that location can break things.
:)

Core: check if a location is an event before excluding it

---

CommonClient.py

Updates the reference clients to request one game's datapackage at a time. While it can handle very large packets and doesn't really need it, it makes it slightly more future proof and might inspire someone to copy it into their library as well.
By making a client forget it has a cache.

CommonClient: request datapackage per-game

---

MultiServer.py

nothing
am about to dig into why the server instantly restarts in a webhost environment if a client is connected and cleaned this up in my path. So it's about to be tested.

Core: clean up MultiServer.py/auto_shutdown

---

worlds/ffmq/Items.py

Push the base item as starting weapon instead of the Progressive gear version. Fixes an issue with the starting weapon not being counted properly in logic, making progressive gear option + cat claw or bomb as starting weapon fail.
Generating with and without it.

FFMQ: Fix starting weapon with Progressive Gear

---

worlds/zillion/client.py

The logical win item check wasn't being made when completing the goal. Now it is.
It just looked a little awkward getting the item after release.
played through a game and saw win check at end

Zillion: client win location check

---

worlds/kh2/Rules.py

Keyblades would error out when placing items when plando puts an item there and it tries to fill a filled location
I genned a seed and it didnt break (It works with donald and goofy abilities)

KH2: Fix plando breaking because of keyblades

---

worlds/musedash/MuseDashCollection.py
worlds/musedash/MuseDashData.txt
worlds/musedash/Options.py
worlds/musedash/__init__.py
worlds/musedash/test/TestDifficultyRanges.py

- Adds all the songs from the Touhou Mugakudan -Ⅲ- update. 
- Increases the upper limit of additional songs to 508 due to there being 512 songs now.
- Finally fixes umpopoff. As it was the only song that had less than 3 difficulties but also didn't have proper difficulty values
Tests. And double checked via debugging the umpopoff was now getting difficulty values.

Muse Dash: Update song list to v3.12.0 and fix up a missing song

---

WebHostLib/api/generate.py
test/webhost/test_api_generate.py

Fixes POSTing files to the `/api/generate` endpoint. This was broken because I missed updating this call to `get_yaml_data` in #2138.
Added a new test to validate posting a file. It failed before, it succeeds now. Also tried running the webhost locally. It raised an uncaught exception before, it succeeds now.
I tried to also add type hints to `get_yaml_data` by making `files` a `list[FileStorage]`, but this ended up with all sorts of type errors when trying to call `zipfile` functions:
```
Argument of type "FileStorage" cannot be assigned to parameter "filename" of type "StrOrBytesPath | _SupportsReadSeekTell" in function "is_zipfile"
Type "FileStorage" cannot be assigned to type "StrOrBytesPath | _SupportsReadSeekTell"
"FileStorage" is incompatible with "str"
"FileStorage" is …
```

WebHost: Fix /api/generate

---

worlds/landstalker/docs/landstalker_setup_en.md

Fixing a link to the player options page that was setup incorrectly on the landstalker guide
Verified that the new link directed you to the correct page.
(PR reopened to check that I cleaned up my commit history correctly)

Docs - Fix broken link in Landstalker setup Guide

---

test/bases.py
test/general/test_reachability.py

This old option access is deprecated.
This removes lots of deprecation warnings from a run of the unit tests.
just unit tests

Tests: remove deprecated option access from `WorldTestBase`

---

worlds/shivers/Rules.py
worlds/shivers/data/excluded_locations.json
worlds/shivers/data/locations.json

Office elevator logic was written as
`can reach Underground Tunnels OR can reach Office AND have Key for Office Elevator`
Meaning that key for office elevator was not required if Underground Tunnels could be reached when it should be.
Changed to
`(can reach Underground Tunnels OR can reach Office) AND have Key for Office Elevator`
Wasn't, simple issue and same as [2657](https://github.com/ArchipelagoMW/Archipelago/pull/2657)
Until this fix is out either `normal` should not be used for lobby access or elevators stay solved should not be used.

Shivers: Fixes issue with office elevator rule logic.

---

.run/Archipelago Unittests.run.xml

Includes a run config for unittests that PyCharm should pick up on automatically.
Only locally, which isn't that useful, as it doesn't test if another PyCharm finds this config and can run it.

PyCharm: ship a working unittest run config

---

worlds/pokemon_rb/__init__.py

If no Pokémon know a move required move, fix by changing that instead of attempting to find such a Pokémon when it does not exist.
For masochists setting their HM compatibility to 0% or extremely low.
Generating the EvieRed yaml in https://discordapp.com/channels/731205301247803413/1193142272338952272

Pokémon R/B: Fix move intervention

---

worlds/tunic/docs/en_Tunic.md
worlds/tunic/docs/setup_en.md

Add a section to the game page discouraging the player from playing the rando before playing vanilla, as that is a terrible idea.
Also changing settings -> options
Reading
N/A

TUNIC: Update game page for blurb about playing vanilla first

---

worlds/AutoWorld.py

people were complaining about the message showing up and not specifying which world/s were actually the issue, which I initially left out to not shame people so by popular request ig 🤷 
ran a quick gen to make sure all the worlds that haven't updated yet were logged.

Core: Log the worlds still using the old options API

---

ModuleUpdate.py
setup.py

It looks like WebHostLib is not required anymore for setup.py, so we can remove the requirements.
Also adds some code to avoid the `update_ran = False` hack we currently have in setup.py
CI

Setup: don't install webhost dependencies

---

WebHostLib/templates/generate.html
settings.py

set consistent server defaults
Some reasonings:
In general these should be reasonable defaults someone can just start a game with, and the other options should offer customization from there.
items plando allows modifying of other worlds, the others are world-local. It should therefore be opt in, preferably after the host has read the plando guide to know what to look out for.
Collect and Release on Auto, teaches that the systems exist, can be customized if changes are desired and is a reasonable default; as  well as a default encountered in say The Big Async.
Moved Items plando visually up, as it has the biggest impact and support.
I only tested the webhost changes

Core: set consistent server defaults

---

worlds/stardew_valley/rules.py

The club card is needed to enter the casino, but the rule was not there

Stardew Valley: Added missing rule on the club card

---

worlds/tloz/ItemPool.py
worlds/tloz/Options.py
worlds/tloz/Rules.py
worlds/tloz/__init__.py

I really hope I caught everything >.<;
a couple test gens with successful outputs, and no more depreciation messages (that are related to my world. the ones remaining seem to be for the generic world, which looks like is being addressed as a part of #2626 )

TLOZ: Update to new options API

---

worlds/shivers/Rules.py

Fixing logic rule for location 'Final Riddle: Guillotine Dropped'
-Broken seed found. Spoiler logic checked
-Incorrect logic found with location 'Final Riddle: Guillotine Dropped'
-Several seeds generated including the broken seed
-Spoiler log checked to ensure steps to check that check were now correct.
N/A

Shivers: Fix rule logic for location 'Final Riddle: Guillotine Dropped'

---

worlds/soe/__init__.py
worlds/soe/options.py
worlds/soe/patch.py
worlds/soe/test/__init__.py
worlds/soe/test/test_access.py
worlds/soe/test/test_goal.py
worlds/soe/test/test_oob.py
worlds/soe/test/test_sequence_breaks.py
worlds/soe/test/test_traps.py

Gets rid of almost all errors in CI: Analyze: mypy and flake8
Note:
for flake8, some of the functions are still "too complex". Worst being `SoEWorld.create_regions` with 19. This may need discussion since I don't think reducing complexity would make the code more readable.
for mypy we still have the missing type stub for the native code, so this is also still exit 1 for now.
CI, it doesn't change actual code.

SoE: minor typing and style fixes

---

worlds/tloz/__init__.py

whoops used a = instead of a :
mad that I'm doing a literal one character change PR :/
didn't. doing as told

TLOZ: properly assign options

---

test/general/test_options.py

In https://github.com/ArchipelagoMW/Archipelago/pull/2714 snuck in a options = instead of options :, which is an easy mistake to make and one I overlooked. So let's test for it.
It's a test.

Tests: test that World.options is not set on the class

---

worlds/ffmq/Client.py

Bizhawk's "hard reset" option fills RAM with 0x55s. This causes game completion to be erroneously flagged, and likely many erroneous location checks with it. This fix checks for 0x55 and will not proceed to process anything if present.
Resetting.

FFMQ: Reset protection

---

worlds/lingo/data/LL1.yaml

The Colorful currently, in logic, does not expect you to solve the achievement panel until all of the doors are opened. This is not enforced by the client in complex door shuffle (in which the panel is revealed once the grey door is open). It is also not typical of how achievements in Lingo usually work, and it ended up this way because of the fact that THE COLORFUL is, uniquely, not a countdown panel.
This change modifies logic so that solving each panel within The Colorful is required in order to access the achievement, rather than opening all of the doors. This will be accompanied by a change to the client that will turn THE COLORFUL into a countdown panel. (https://code.fourisland.com/lingo-archipelago/commit/?h=future&id=78789475f9cbbfc4015219fbf218e24599809c91)
Test generations.

Lingo: Turn The Colorful into a countdown achievement

---

worlds/lingo/data/LL1.yaml

The SIX panels in The Bearer are white, so they should not be marked as being red and yellow like they currently are. This is not urgent, because the client and generator are consistent about this incorrect logic, but it would be good to get this fixed for the future since it is unintuitive.
Ran the validate config script and pytest.

Lingo: Remove colors from Bearer SIXes

---

worlds/witness/hints.py

There are certain EPs in the game that are supposed to be always and priority hints if you have the audio log hints enabled.
However, their corresponding Obelisk Side locations are never hinted, because I forgor.
This adds those.
Worth noting: "Does the location exist" is already checked elsewhere, so a check for obelisk_sides being enabled is not necessary.
Considered a bug because this was always supposed to be the case, I just forgot.

The Witness: Add Obelisk Side locations to always and priority hints

---

worlds/pokemon_emerald/__init__.py

Automatically excludes the specific locations which aren't accessible until after the player's goal is completed.
Excluding locations rather than not creating the locations because I get the item pool from the location pool directly. Removing a location that carries a progression item in the vanilla game would mean I'd have to explicitly add that item back in later and remove a filler item. This is much cleaner, and barely makes a dent in the location count anyway.
It's technically still possible to further detect whether a player could reach post-champion locations without first defeating Norman, but it gets messy, and nobody's asking for that right now anyway. When you play for a Norman goal, you're probably expecting to reach your goal quickly and release without approaching anywhere …

Pokemon Emerald: Automatically exclude locations based on goal

---

worlds/lingo/player_logic.py

This was supposed to be the case before, but a programming error caused the conditional clause to always be true.
Test run.

Lingo: Disable forced good item when early color hallways is on

---

.coveragerc

Makes pytest-cov not report `if TYPE_CHECKING:` blocks as untested (they are not covered by unit tests and will instead be tested with mypy).
```bash
pip install pytest pytest-xdist pytest-cov
pytest -nauto --cov-report term-missing --cov=worlds/soe
```

Tests: create sane cov defaults

---

.github/workflows/analyze-modified-files.yml

Changes the complexity limit of our flake8 CI action to 14.
The value of 10 does not really fit some of our world patterns and values up to 15 may be acceptable. Looking at some worlds, 14 seems to be achievable without too much work and reduces the noise in test output, making it more usable.
We should consider reworking some of core to fit this new limit and recommend it to world authors. It could make code easier to test and review. Maybe one day we get to enforce it for core and require explicit `# noqa: C901` for functions where it makes sense to go beyond this.
Looking at flake8 output.

CI: flake8: max-complexity=14

---

inno_setup.iss
setup.py

update the checked for VC Redist version to current as of now
always download up to date vc redist for x64 and arm64
on my Windows 10 x64

Setup: auto update vc redist

---

worlds/lingo/data/LL1.yaml

Cross Tower (North) - NORTH and Outside The Agreeable - NORTH shouldn't be logically solvable if the player cannot access and solve the three hint panels in Outside The Bold. Previously, both NORTH panels were marked as just requiring access to Outside The Bold, but this is insufficient as the three hint panels have colours and thus may not be solvable even if the player has access to that room. Thus, both NORTHs have been changed to require the individual hint panels rather than the room.
This issue does not apply to the other set-of-four puzzles because the hints for them are all white panels.
Ran validate_config.rb and pytest.

Lingo: NORTH requires hint panels

---

worlds/soe/__init__.py
worlds/soe/test/test_item_mapping.py

In pyevermizer, it's called Atlas Medallion, not Amulet, leading to an empty group and to code not considering them as an alchemy ingredient when swapping out for a trap or an energy core fragment.
Also adds a test.
Bug was reported [on Discord](https://discord.com/channels/731205301247803413/909605724190019645/1198142248102141952).
Unit tests.

SoE: fix naming of atlas medallion

---

worlds/tunic/er_data.py
worlds/tunic/er_rules.py
worlds/tunic/er_scripts.py

Fixes a logic bug where the "Overworlds Laurels Region" basically just connected some irrelevant entrances to each other, creating a (very rare) potential for a logic bug. This splits that region into three separate regions.
Also the hallway helper (for generating ER hint paths) wasn't working properly for NMG (it wasn't supposed to take the same hints as UR).
Ran generation a few times with varied settings.
N/A

TUNIC: Fix for nmg logic bug

---

worlds/adventure/__init__.py

Fixing errors in Adventure pre_fill due to calling .copy on what is now an iterable and not a list.  Would hit this code if there were not enough items to fill all locations, mainly when max_freeincarnate is set to a low value.
Generated full-random 1050 Adventure multiworld, 100 full-random individual single-adventure multiworlds, and generated and played some of a 4 Adventure world with low random max_freeincarnate settings
N/A

Adventure: Fix iterable copy error when freeincarnate_max is tuned low

---

worlds/kh2/Locations.py

removes the empty location groups from the data package
genned a seed and ran unittests

KH2: Fix empty location groups

---

docs/network protocol.md

We have a GM native ("C") lib (WIP) for older GM/GMS and an example GMS project for newer GMS (2.2.x) now. Add this to docs so people can maybe find it.
Reading.

Doc: add GM libs to network protocol.md

---

test/general/test_groups.py

Adds a test to see if any game defines empty item/location name groups, which is likely a bug.
Unit tests.

Tests: test that item/location name groups are not empty

---

test/general/test_items.py
test/general/test_locations.py

As the title says, make two tests' comparisons strict equality instead of less/greater than or equal.
In particular, `test_item_count[_greater]_equal_locations` becomes a very useful test for catching simple off-by-N errors once its comparison is made strict. I've already caught multiple bugs in my (unsupported) world with this change. `#archipelago-dev` believes this test started out with .assertGreaterEqual() only because .assertEqual() would not have passed at the time, but today it does.
Ran all unittests in PyCharm on my machine on this branch

Tests: use strict equality in some tests

---

worlds/pokemon_rb/items.py

Adds a missing comma in Thunder Stone's item groups list
Not

Pokémon R/B: Fix missing comma in Thunder Stone item groups

---

worlds/lingo/__init__.py
worlds/lingo/options.py

Enables start_inventory_from_pool option. get_filler_item_name is also implemented now. Filler items are distributed differently now; they are chosen at random instead of sequentially, which has no impact on gameplay as all filler items are no-ops.
Test generation with a couple of different options.

Lingo: Enable start_inventory_from_pool

---

worlds/alttp/Rules.py

Fixes a bug in which the Zelda's Chest rule requiring the Big Key is skipped if Universal Small Keys is on, which also causes the Throne Room entrance, and by extension the rest of the outside world, to be in logic without the Hyrule Castle Big Key.
Generating and observing spoiler playthrough showing the Hyrule Castle Big Key in sphere 1 and everything beyond the Throne Room in sphere 2 or later.

LTTP: Create Hyrule Castle Big Key Rule On Universal Small Keys Option

---

BaseClasses.py
Fill.py
Main.py
OoTAdjuster.py
Utils.py
test/general/test_fill.py
test/general/test_reachability.py

I was showing core code to other randomizer developers and had to explain this variable naming issue. It's time to be rid of it.
Ran some generations, seems fine.

Core: Purge the evil (`world: MultiWorld`)

---

WebHostLib/templates/macros.html

Should make Firefox able to connect again
Not on Firefox yet.

WebHost: provide None password to URI so it doesn't get stripped

---

worlds/pokemon_rb/client.py

After playing a game with Pokémon Red and Blue with Stardew Valley, I believe the exchange rate between the two of 10:1 is excessive. This changes it to a 5:1 ratio which I hope will be more reasonable
Checking bank balance on both games and ensuring a 5:1 ratio between the reported numbers.

Pokémon R/B: Halve Bank Exchange Rate

---

worlds/ffmq/Output.py

Importing from Main is a recursive import during Generate, also it's not listed in `Main.__all__` (and pycharm warns about this).
Only ran unit tests.

FFMQ: fix `__version__` import in Output.py

---

worlds/tunic/er_rules.py
worlds/tunic/options.py
worlds/tunic/rules.py

Adds entrances between the Monastery Front region (the space in front of Monastery) and Quarry Back (the mountain stairs down to where the miasma starts), with a rule of having Laurels. This is just an easy connection to make since no combat is required, so you don't need a sword/wand for it.
This is for Entrance Rando only, since non-entrance rando does not split up Quarry to this degree.
Also removed an access rule from an entrance, as we changed our minds on having the player causing a potential soft lock.
A few test generations.
N/A

TUNIC: Add an ER static connection, modify an nmg rule

---

.github/labeler.yml
.github/workflows/label-pull-requests.yml

First and foremost, a lot of commits. You should probably squash merge this.
There are 2 categories of automated labeling described below.
Several labels are applied based on the content of the PR. When the PR is updated, labels may be added and removed accordingly  with the changes.
* the `is: documentation` label is added to any PRs which only affects things in docs folders, or any README.md file.
* the `affects: webhost` label is added if any change to WebHost.py or any content in the WebHostLib folder.
* the `affects: core` label is added if any non-world file is modified, with a large handful of exceptions. Changes to .py files in worlds/generic are also counted.
The `waiting-on:` labels are added and removed during certain PR events.
* When a non-draft PR is opened or reopened, the …

CI: Add a workflow which automates some labeling

---

worlds/pokemon_emerald/locations.py

Adds a couple items to a location group which were missed.
Context: This location group isn't directly used anywhere; it's meant as a shortcut for excluding certain locations which may require you to beat the game before accessing them (most can still be accessed early based on other options, and the list is only relevant to the champion goal)).
Generating with the group in `exclude_locations` and checking the spoiler log for their inclusion in excluded locations.

Pokemon Emerald: Add missed locations to postgame locations group

---

worlds/lingo/data/LL1.yaml
worlds/lingo/test/TestProgressive.py

The final stage of Progressive Art Gallery opens up the four-way intersection between the Art Gallery, Orange Tower Fifth Floor, The Bearer, and Outside The Initiated. This is a very useful door, and it would be cool to be able to open it without having to get five progressive items. The original reason this was included in the progression was because getting into the back of Art Gallery early would cause sequence breaks. At this point, the way the client handles the Art Gallery has changed enough that it does not matter if the player can go through this door before getting all progressive art galleries.
pytest, validate_config.py, and a test run.

Lingo: Detach Art Gallery Exit from Progressive Art Gallery

---

worlds/lingo/data/LL1.yaml
worlds/lingo/data/ids.yaml
worlds/lingo/player_logic.py

"Color Hunt" and "Champion's Rest" are now two separate rooms. The resulting logic is similar to before, with the exception that the painting inside of Champion's Rest is now a possible exit, meaning that the room can be accessed and the panels solved without accessing Color Hunt.
validate_config.rb, pytest, and a test playthrough.

Lingo: Split up Color Hunt and Champion's Rest

---

BaseClasses.py

With BaseClasses running `worlds/__init__.py` and worlds importing `from BaseClasses`, this is likely to result in some extra code being run because of partial recursive imports. This now lazily loads worlds when needed, at which point `sys.modules` should be properly populated.
Total time to run `python test/benchmark/load_worlds.py` is 50-100ms faster for me with this change, but that might be a fluke (noise level is pretty high).
Unit tests
Rolling a simple item_link and looking at the spoiler to see the link was created.

Core: remove module level AutoWorld import from BaseClasses

---

worlds/tunic/er_rules.py

Fix a duplicate entrance name, which fails the test here https://github.com/ArchipelagoMW/Archipelago/pull/2453
Fixed name, ran gen
N/A

TUNIC: Fix duplicate entrance name in ER

---

Patch.py
worlds/Files.py

Whether https://github.com/ArchipelagoMW/Archipelago/pull/2536 is what we want or not,
if we are going to have different types of patch files, we should have an interface that defines what is required for them.
We can see in `Patch.create_rom_file` that, in addition to members from `APContainer`, the patch only needs to have a `result_file_ending`, and a `patch` method.
This interface would give a path for other implementations that don't need or want everything offered by `APProcedurePatch`.
Here is what it looks like combined with the `APProcedurePatch` PR: https://github.com/Silvris/Archipelago/pull/2
generated and played a rom file game that uses `APDeltaPatch` (Zillion)

Core: APPatch interface

---

worlds/pokemon_emerald/__init__.py

When `item_pool_type` is `diverse_balanced`, duplicate TMs shouldn't be added until all TMs are represented, so it has special handling to shuffle the TMs and then pop them as needed. But I forgot to shuffle the list on the first go, so it will always add TM50 and count down.
This adds an initial shuffle.
Generating with the option set and seeing a randomized list of TMs in the pool.

Pokemon Emerald: Shuffle TMs for `diverse_balanced` option

---

worlds/lingo/items.py
worlds/lingo/player_logic.py

The Colorful did not actually properly split into individual doors when progressive colorful was off. This change refactors the code that handles special cases with progressive items to make things clearer (which is important because I will be introducing another one).
Test generations and pytest.

Lingo: Fix non-progressive The Colorful

---

data/lua/connector_bizhawk_generic.lua

Addresses #2763. I suppose it's probably technically a speed improvement and better follows typical lua practices. But otherwise shouldn't change functionality. Just cleanup.
Also moves the debug variable up to the top of the file. for easier access.
Ran Emerald for a couple minutes. Triggered an "unknown command" error to make sure it still got sent to the client.

BizHawkClient: Use callbacks in connector script instead of else/ifs

---

worlds/tunic/options.py

Adding a couple of aliases to logic rules, because I keep manually writing in logic_rules: nmg into my yaml and it keeps not working. Also slightly updated the description for this option to include that tricky laurels zips (through certain gates, doors, etc.) are in logic in NMG.
Reading
N/A

TUNIC: Add aliases to LogicRules, slightly update description

---

worlds/tunic/__init__.py
worlds/tunic/er_rules.py
worlds/tunic/items.py
worlds/tunic/options.py
worlds/tunic/rules.py

Renames the Ice Rod ability to Icebolt, a more recently adopted name for it by the community.
Generating locally and testing with an in-development client mod update.

TUNIC: Rename ability item

---

worlds/pokemon_emerald/__init__.py

Caused/revealed by #2655 and found in the recent beta test. If one or more of the badge/hm locations is excluded, when Emerald's `pre_fill` tries to place shuffled badges or HMs onto those locations, it ignores them, doesn't place every badge/hm, and causes a lot of locations/items to become inaccessible. I thought setting `allow_excluded=True` would protect against this, but I think I misunderstood what it does.
This will prevent those locations from being excluded just before trying to give them to `fill_restrictive`, which will catch both the automatic exclusion of a couple post-goal locations in Petalburg and the manual exclusion by players.
The same problem seems to appear if you exclude a location that Emerald converts to unrandomized event locations, like badges or key items like …

Pokemon Emerald: Un-exclude locations that must contain progression

---

CommonClient.py

For whatever reason, log level resets to default (30) an makes `CommonClient.py --nogui` unusable for me. I spent some time looking for the culprit and haven't found it, so this is a work-around by forcing the log level at the end of the file to the expected value.
Any one of those imports destroys log level for me:
`from MultiServer import ...`, `from NetUtils import ...` and `from worlds import ...`
Looking at stdout and in the log folder.

TextClient: fix logging not always showing up

---

_speedups.pyx

* **remove unnecessary cinit**
This was meant for (memory) safety, but [cython docs](https://cython.readthedocs.io/en/latest/src/userguide/special_methods.html#initialisation-methods-cinit-and-init) clearly state that this
is done automatically. The code generated for cinit with args is what
triggers a 'possible null deref' in clang's static analyzer, so by removing
cinit, we can now use static analysis.
* **disable pickling of LocationStore and internal classes**
This reduces code size and avoids accidentally pickling them.
(Declaring `__cinit__` did disable `__reduce__` for LocationStore (but not for internal classes), so adding this in the same PR.)
Unit tests and `scan-build -disable-checker deadcode.DeadStores --status-bugs python setup.py build`

Speedups: no cinit, no pickling

---

.github/labeler.yml

#2536 lost the "affects: core" tag after resolving conflicts, as the conflicts removed the changes to `Patch.py`, leaving the labeller to see the edits to `worlds/Files.py` and decide it wasn't core enough.
Wasn't. Not actually aware of how Github CI can be tested.

CI: add missing core files to "affects: core" labelling

---

docs/network protocol.md

LocationScouts doc still talks exclusively about the "ledge items" case, which has now [provably](https://discord.com/channels/731205301247803413/731214280439103580/1192725919459192894) led to someone not considering them for retrieving location-item data for a fully remote client.
I am not a native English speaker, someone who is should look at this.

Docs: Better description for LocationScouts

---

worlds/alttp/Rules.py

Changes the "self locking" rules on the Thieves' Town Big Chest so that it always logically requires Hammer.
Generated two games with a Small Key (Thieves Town) plando'd onto the Big Chest, one with Hammer plando'd in the attic and one without. The former failed and the latter succeeded.

LTTP: Thieves' Town Big Chest fix

---

.github/workflows/scan-build.yml

Runs static analysis of native code using clang's scan-build when a native code file or setup.py changes.
When it finds a problem (warning), the action fails and it uploads a report.
CI here and at https://github.com/black-sliver/scan-build-cython-test

CI: add static analysis for native code / cython

---

worlds/tunic/__init__.py

Uses push_precollected for the start_with_sword option instead of adding a sword to filler items. This makes it so that starting sword is considered in logic.
Several gens, running unit tests, and checking to make sure the sword is still delivered in the client mod.
N/A

TUNIC: Use push_precollected for start_with_sword

---

docs/options api.md

The current phrasing of this sentence made me expect "random" to work on literally all options, even my `OptionsDict` option. After asking `#archipelago-dev` and checking the `Options.py` code, it's become clear that many option kinds don't (and can't) support "random". After reading `Options.py` a bit more, I believe this wording would be correct.
The change itself, N/A. It's just docs.
If you mean how I ran into this, I tried writing a test for my world with all options set to `"random"`, and got `NotImplementedError: Cannot Convert from non-dictionary, got <class 'str'>` on the `OptionsDict` one.
N/A

Docs: Clarify which kinds of options actually support "random"

---

worlds/tunic/er_rules.py

I thought you could dash across the bridge before the double admin fight when doing lower Zig backwards. I was wrong.
Adds the requirement of having Prayer and Sword to the Laurels requirement for doing Lower Zig backwards in ER.
Ran gen a few times, mostly.
N/A

TUNIC: Fix for incorrect Zig 3 ER rule

---

worlds/tunic/er_data.py
worlds/tunic/er_rules.py
worlds/tunic/regions.py
worlds/tunic/rules.py

Adds logic to a couple of quick kills for bosses when using nmg or ur logic.
Also removed ice grappling into zig with ER off due to the soft lock potential caused by saving in zig without prayer.
Also adds a couple of dependent regions that should have been there, which just made the ER pairing more conservative than it needed to be.
Also fixes a minor bug with the Atoll portal and Atoll statue being the same region, implying traversal from the portal region to the statue region without prayer.
Generations, looking at the logic, unit tests
N/A

TUNIC: Misc Logic Changes, Additions

---

Utils.py
test/utils/test_yaml.py

Use native/libyaml SafeLoader, which is faster.
Also add tests to validate we don"t break the API.
With the tests. Also tests succeed when throwing an ImportError in the try block.

Utils: YAML goes brrrt

---

worlds/blasphemous/docs/setup_en.md

It doesn't work on the current version anymore.

Blasphemous: Remove poptracker pack from setup guide

---

worlds/ffmq/Regions.py

Removes unnecessary message prints that were for debug purposes
Not

FFMQ: Remove debug print statements

---

Launcher.py
kvui.py

As Archipelago grows and more clients are added, the amount of space given to any given client in the launcher grows ever smaller. This changes the launcher such that the list of tools and clients can be scrolled, and each button is rendered at a straight height of 40.
Opening the launcher, confirming the visual changes. Clicked on the OoT Adjuster, Minecraft Client, and Undertale Clients and confirmed the correct program was launched.
(I don't have recording software on this machine, so hopefully screenshot will suffice)

Launcher: make launcher scrollable

---

MultiServer.py

Makes it so that !hint only lists the hints to the slot that send the command, not "spamming" anyone else.
I've heard complaints about this feature a few times, so hopefully this improves things.
Also left a note that this was changed to reduce potential player confusion.
Barely, please test more.

MultiServer: make !hint without further arguments only reply to the instigating player

---

setup.py
typings/kivy/graphics/texture.pyi
worlds/zillion/__init__.py
worlds/zillion/client.py
worlds/zillion/config.py

changed some package data access to use `pkgutil`
so that it can be accessed from an apworld
I think that makes it work as an internal apworld.
("internal" = `zillion/requirements.txt` is installed in the frozen build, and `ZillionClient.py` is built)
- zipped up the `zillion` folder
- renamed it `.apworld`
- removed the original `zillion` folder
- generated 1-player Zillion game
- played through the game connected to `MultiServer`, toggling map tracker off and on and watching it for accuracy
I did not test the whole Windows frozen build.
(I don't know how to build it and don't use Windows.)
But I'm confident any problem with that would be found in release candidate phase.
edit: Thank you remyjette for testing the Windows frozen build.

Zillion: apworld-compatible package data

---

docs/settings api.md

Tells world devs to use paths before the generate_output happens. generate_output may not be able to open a file browser. Also if the user does not have access to the file, it's better to fail fast, not at the end of generation.
Reading

Docs: add note for stage_assert_generate to settings api

---

BaseClasses.py

Adds specific can_reach helpers to CollectionState so that passing a string and strict string comparisons are no longer necessary. Should be marginally faster but didn't benchmark it.
Used the new helper in my world and made sure it was still passing logic tests. Existing can_reach also calls into the new helpers so any tests with logic related to those also hits this.

Core: add specific can_reach helpers to CollectionState

---

worlds/Files.py

Since any game can override `read_contents` in `APContainer` (and might need to),
we could use a more clear error message if something goes wrong with that implementation.
A suggestion was made to do something with the version number that's defined in core.
But if the plan is to move games out of core, or have better support for games outside of core, then we can't use a patch version number in core to keep track of changes in game implementations.
The solution needs to be something that is available to games that have never been in core and never will be in core.
I created a patch before this change: https://github.com/ArchipelagoMW/Archipelago/pull/2875
Then tested opening that patch with https://github.com/ArchipelagoMW/Archipelago/pull/2875 with and without these changes.
Before:
``` …
```

Core: clarify error message when reading an `APContainer`

---

worlds/alttp/Options.py
worlds/alttp/Shops.py
worlds/alttp/__init__.py
worlds/alttp/test/options/TestOpenPyramid.py

- Fixes a bug with Open Pyramid searching for the class object in a set instead of current key
- Moves `push_shop_inventories` to `stage_generate_output` and uses threading events in `generate_output` to wait for it. This fixes a bug where the shop inventories are pushed based on items in locations before progression balancing is done.
- Observing behavior with debugger with and without open pyramid fix.
- Generating games with logged Progression Balancing item swaps, observing items swapped into and out of shops, testing to ensure they are the correct items in-game.

LTTP: Open Pyramid and Shop Prog Balancing Bug Fixes

---

worlds/generic/Rules.py

Changes the `local_items` and `non_local_items` option getters in `world/generic/Rules.py` to use the new options system.
Generations and reading.
I opened this PR because of printed warning messages when generating games. I am aware that this change is also covered in [PR 2626](https://github.com/ArchipelagoMW/Archipelago/pull/2626), but that PR touches numerous other files, is a draft, fails tests, and has merge conflicts. I figured getting the changes into core as soon as possible was desirable and so I have opened this PR.

worlds/generic: Changing deprecated option getter

---

worlds/musedash/MuseDashCollection.py
worlds/musedash/MuseDashData.txt
worlds/musedash/test/TestCollection.py

Adds 4.1.0 songs. (Valentine Stage)
- Also adjusted exclusions to now be explicit rather than implicit due to a new song having normal value difficulties but being hidden.
Several test generations + Tests.

Muse Dash: Add Muse Dash 4.1.0 songs

---

worlds/pokemon_rb/client.py

* If the user tried to run `/bank` with no arguments to see the current value while disconnected, previously it threw an exception `KeyError: 'EnergyLinkNone'`. Now it informs the user that they must be connected and in-game, like `/bank deposit` and `/bank withdraw` do.
I'm also open to adding another `if` branch to make `/bank` only check for `ctx.server` instead of combining it with the other bank commands, to allow connecting to check the bank before the game save is loaded. If that's preferred let me know.
* If the user tried to run `/bank` or `/bank deposit` when the EnergyLink hadn't been used yet, they would get a `TypeError` exception. Trying `/bank withdraw` would give no output and would crash the lua connector script. Now it treats a `None` EnergyLink as `0` and works …

Pokemon RB: Fix exceptions raised by /bank

---

Options.py

As it stands right now, the compatibility fallback for `SpecialRange` now that it has been deprecated in favor of `NamedRange` won't work under any circumstances. While `__new__` needs to have the same signature as `__init__`, `NamedRange` and its parent classes (`Range`, `NumericOption` etc.) are not overriding `__new__` themselves and their `__init__` has a different signature, so you can't pass arguments in your `super()` invocation.
This PR simply fixes that usage of `__new__`. Other option could be to avoid using `__new__` at all and place the deprecation notice elsewhere.
**Before**
**After**
With an APWorld that uses `SpecialRange` and was working prior to the introduction of `NamedRange`

Fix usage of `__new__` for `SpecialRange` compatibility fallback

---

worlds/generic/docs/commands_en.md

Fix typo in commands_en.md as reported here: https://discord.com/channels/731205301247803413/1200171058179874897/1200171058179874897
Also fixes indentation to match other sections.
:eyes:

Doc: fix typo in commands_en.md

---

worlds/terraria/Rules.dsv

Mothron only drops Broken Hero Sword if you have all post mech boss flags, which I hadn't accounted for. So I updated the logic to fix this.
I generated a world and it looks fine

Terraria: make Broken Hero Sword require post mech bosses

---

worlds/witness/__init__.py

Bump required client version from 0.4.4 to 0.4.5.
The [client](https://github.com/NewSoupVi/The-Witness-Randomizer-for-Archipelago/releases/tag/v5.0.0p14) now connects with version 0.4.5.

The Witness: Bump required client version

---

worlds/witness/__init__.py
worlds/witness/hints.py
worlds/witness/options.py
worlds/witness/presets.py

Adds the "Laser Hints" option.
If laser hints are on, and laser shuffle is being played, walking up to a laser in-game will show a hint for where the corresponding laser item is.
`Jungle Laser can be found at Shipwreck Discard`
There is a compatible client: https://github.com/NewSoupVi/The-Witness-Randomizer-for-Archipelago/releases/tag/v5.0.0p15
Tested:
Playing seeds with it. I don't think a lot can go wrong here

The Witness: Laser Hints

---

Generate.py

There is a unique edge case where if a player has a slot name over 16 characters, but the 16th character is whitespace it will keep the leading whitespace in the slot name, which can cause issues for clients that trim username inputs (including CommonClient). This change trims the username again after the slice to ensure no whitespace remains.
Example:
A user has the slot name of `15CharacterName ThatIsToLong` which gets sliced in code to `15CharacterName ` (16 chars). Because the trim only happens before the slice, MultiServer will expect the final space character to be present, but some clients (like Rogue Legacy for example), will trim user input so there is no way to actually send the request properly.
Ran 2 generations before and after the change with the example name above. Was able …

Generate: Trim slot names again after 16 character limitation slice.

---

worlds/alttp/Shops.py

#2890 moved `push_shop_inventories` to `stage_generate_output` which necessitated changing some uses of `multiworld.random` to `per_slot_randoms`. One use was missed, causing a crash when `randomize_shop_prices` is on. That is fixed here.
Generating with `randomize_shop_prices` on.

LTTP: Missed `per_slot_random` Change

---

.github/workflows/label-pull-requests.yml

Fixes a CI race condition in #2904 where the labeler job, by calling the set labels API, may overwrite labels added or removed by the other 2 jobs if timed poorly.
Wasn't. I tried to test on my branch and realized that it only runs on main so I gave up
As far as verifying this is the correct fix for the issue, I checked labeler's source code to verify it does what I expected it did (using set labels instead of add/remove) and checked actions' yaml schema to verify this is semantically valid

CI: Avoid race condition in labeler workflow

---

worlds/AutoWorld.py

https://discord.com/channels/731205301247803413/1201171226886951022/1201171226886951022
calls the from_any for initialization of options of item links groups instead of the constructor, to support things like default = random
https://discord.com/channels/731205301247803413/1201171226886951022/1202004618889154570

Core: Fix creation of options for an item link group

---

Fill.py

When generating a multiworld with 1000+ excluded locations and 1000+ `remaining_fill` locations afterwards, the printed messages are confusing and unclear. This adds a parameter like the one in `fill_restrictive` to improve the message's clarity.
Generations and reading.
Before:
After:

Fill: Improve clarity of remaining_fill messages

---

worlds/kdl3/Client.py
worlds/kdl3/Rules.py

#2870 got merged, but didn't actually include KDL3 with its changes. This adds the needed patch_suffix required for patching.
Two logic rules were also adjusted. I learned that ChuChu can also eat enemies while underwater, not just Kine. Every animal except for Kine is capable of breaking the Ice blocks in 3-5, Coo and Rick were just the ones I had known prior.
Ran unit tests, opened the launcher to confirm ".apkdl3" can be patched via Open Patch.

KDL3: Post-PR adjustments

---

MultiServer.py

This extra quote was pointed out in the Discord: https://discord.com/channels/731205301247803413/731205301818359821/1215882443261870190
Here's a PR to remove it
wasn't

Core: Remove extra " character in /forbid_release help message

---

worlds/alttp/ItemPool.py

Also show `timer` value not `mode` value when raising a NotImplemented exception. I'm assuming this was a copy/paste gone wrong.
Ran generations with other timer values before and after this change and generation continues instead of fails after this fix.
N/A

ALTTP: Fix NotImplemented error when using non-`none` values for `timer`.

---

CommonClient.py

adds commands to commonClient to see what item and location groups your current game has avaliable
ran the commands against a default hollow knight and tunic game and noted the UI output matched expected groups

CommonClient: Add commands to view Item/Location Groups

---

worlds/bumpstik/Regions.py
worlds/bumpstik/__init__.py
worlds/bumpstik/test/TestLogic.py

There were a number of errors in the generation and test logic for Bumper Stickers, logically requiring one less Treasure/Booster Bumper for each Treasure Bumper/Bonus Booster check (respectively) than the actual game requires. In addition, no restrictions were being placed on the "Treasure Bumper 32" and "Bonus Booster 5" checks, due to improper use of a "range" function. This corrects these errors.
To clarify: The following checks had these logical requirements.
Treasure Bumper 1: No requirements (should be 1 Treasure Bumper)
Treasure Bumper 2: 1 Treasure Bumper (should be 2)
Treasure Bumper 3: 2 Treasure Bumpers (should be 3)
...
Treasure Bumper 31: 30 Treasure Bumpers (should be 31)
Treasure Bumper 32: No requirements (should be 32 Treasure Bumpers
Bonus Booster 1: No requirements …

Bumper Stickers - logic fixes for "off-by-one" errors

---

worlds/terraria/Rules.dsv

The Witch Doctor can sell Bewitching Tables if the Wizard is present, which I hadn't accounted for in the rules. So I added it.
I generated a world and it looks fine

Terraria: Add logic for Witch Doctor selling Bewitching Table

---

data/lua/connector_ff1.lua

When the client would disconnect during gameplay, the internal count of items would get reset to 0; upon reconnecting to the client, AP would resend every items received creating duplicate of all items.
Beta tested over the course of 2 weeks by 3 players without any issue.

FF1: Fix items getting resent on disconnect/connect

---

inno_setup.iss
worlds/kdl3/Client.py

Managed to forget removing `Components: client/sni` from when the installer changes were merged, and I didn't test it since then. 
Built the installer, it would fail before this change was made.

KDL3: fix invalid inno_setup components and deathlink messages

---

Options.py
Utils.py

Still have to figure out how item links work to test this, but yeah that should fix it.
N/A

Fix OptionList and OptionSet to allow Iterable of Iterable

---

worlds/messenger/rules.py
worlds/messenger/test/test_access.py

The new rules setup adds the access of these two locations to the entrance of the region they're contained in instead of directly to the location.
Added tests to check the new behavior. The location that can have two different items locked on it already has its region reachable in the initial setup so the extra sweeps don't hurt.

The Messenger: fix items accessibility reachability bug due to new rules

---

worlds/witness/options.py

`laser_shuffle` was changed from a `Toggle` to a `Choice`.
The old behavior is preserved, false is "off" and true is "anywhere".
People have been complaining about their 0.4.4 yamls breaking on the beta (idk, it's a thing I guess)
Exempt-Medic has made me aware of this non-that-evil hack that gets around that
Also, did the same for `early_caves` which has the same history, although it's been a version for that one. Idk, doesn't really hurt
Probably will just close this if it doesn't make it into 0.4.5

The Witness: Don't unnecessarily break people's 0.4.4 yamls

---

CommonClient.py
NetUtils.py

Makes /received use colored text, add the location name and in kvui allow tooltips.

CommonClient: use rich text for /received

---

kvui.py

Previously a close bracket was interpreted as ending the tooltip, causing the remainder of the text to spill into the log. Now it does  not.
Fixes https://discord.com/channels/731205301247803413/1203150255982518384
Created an item link group where a member's slot name contained brackets. Observed bug. Created a new room with the same seed and the fix in this PR. Confirmed it's fixed.
Before:
After:

CommonClient: Fix item link group name when member slot name contains brackets

---

.github/workflows/build.yml
inno_setup.iss

Build the inno setup as part of our build CI and upload-artifact the result
also add /DNO_SIGNTOOL to inno_setup.iss
This is used to test changes that may break building the setup.
I updated only the actions in the changed job. Updating all (other) actions should be a separate PR imo.
CI and trying to run the resulting installer in wine.

CI: build: create setup

---

worlds/ffmq/Options.py

Updates the Map Shuffle Seed option description to mention the two newer options that affect Map Shuffle

FFMQ: Update Map Shuffle Seed description

---

BaseClasses.py

always_allow is called with (state, item) but the default static method has it as (item, state). since it always returns False it's "fine" but it threw me off when working with some code hitting that path.
:eyes:

Core: fix incorrect ordering on the always_allow static method

---

.github/workflows/analyze-modified-files.yml
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/release.yml
.github/workflows/unittests.yml

* Update checkout, upload-artifact and setup-python to latest.
* Update softprops/action-gh-release to the sha of the latest commit before 2.0. I did not (find the time to) review 2.x.
CI. Also we already use most of this in the current build-win-py38 job in build.yml. The action-gh-release commit is the one I updated PopTracker to recently, so this was tested as well.

CI: update actions

---

worlds/hk/Items.py
worlds/hk/Options.py
worlds/hk/__init__.py

All logic-less items when not randomized will not be added to the itempool and should default in-game to their vanilla placements/rewards
All logic-relevant items when not randomized will also not be added to the itempool but will be represented as Events so logic can remain unchanged (for now)
Also adds the Grimmchild1 item to the itempool instead of Grimmchild2 when relevant (when both flames and charms are shuffled), otherwise uses Grimmchild2 as default
* Note: that default is inherited from the Extracted data, so if that changes this fix will likely have to change to match.
quickly
tested logicless removal with geo rocks and soul totems off, and with lore on
confirmed the off locations were not present in the spoiler log, were not sent to the server by the game, and did default to …

HK: Removes Vanilla Items from ItemPool and Uses Grimmchild1 when relevant

---

CommonClient.py

make invalid slot and invalid game connections be disconnect intentionally so they don't try to retry while you're trying to update the connection details
Errors are not impacted, it just doesn't auto retry when the connection details are invalid.
connecting to a live server with:
* an invalid slot name with format `slotName:@url:port`
* an invalid slot name with format `url:port` and passing in an invalid slot name when prompted
* a valid slot name using both formats on a different game client (Undertale client connecting to a Tunic slot)
All of which showed a correct error message and did not try and reconnect with the same invalid connection details.

CommonClient: Don't retry connection when connection details are invalid

---

kvui.py

Discussion in ap-core-dev showed that many believed the scrollbar in the Launcher was too subtle. This updates the scrollbar to match CommonClient, as well as allowing scrolling by clicking and holding the bar.
I ran Launcher.py and scrolled.

Launcher: make scrollbar more prominent

---

worlds/tunic/options.py

This PR updates the display name of a few options to match their labels in the game client mod.
Running webhost locally and viewing updated option names.

TUNIC: Update option display names

---

worlds/smw/CHANGELOG.md

Adds a changelog markdown file to the SMW World.
I read it, and tossed it into a markdown renderer.

SMW: Add CHANGELOG.md

---

worlds/oot/__init__.py

i should not have assumed that setting entrances for the spoiler was safe to do in write_spoiler
also fixes a minor oversight for trials at 0

OoT: Entrance Spoiler Fixes

---

worlds/stardew_valley/rules.py

Recent test failures on main.
One specific door had one specific key that ER could put inside itself.
In practice, that key is not a hard requirement, just a very strong item to survive the transition.
Added a logic alternative of other strong combat abilities instead, so it's possible
Ran the failing test seed, then ran all the test seeds, then ran all the tests about 20 times. No more test failures

Stardew Valley: Added a Great Combat requirement to an entrance that could block its own key

---

worlds/smw/__init__.py

Sets SMW's required version to the new AP version.
Generated a seed on latest main with this change, connected successfully.

SMW: Increment Required Client Version

---

worlds/noita/options.py

Remove a newline from the Extra Orbs option description so it doesn't look bad on the webhost.
Looking at it.
Old:
New:

Noita: Remove newline from option description so it doesn't look bad on webhost

---

worlds/smw/Regions.py

Some blocksanity locations had wrong item requirements due to the script generating them (outside AP, not bundled here) had something else written in them and never caught those until today.
Generated games with those locations set as priority and check the spoiler log afterwards.
nop

SMW: Blocksanity logic fixes

---

worlds/smw/Client.py
worlds/smw/Rom.py

Fixes the following issues in SMW v2:
* Bowser is no longer beatable on Yoshi Egg Hunt if the egg count is over 128
* CI2's Dragon Coin Room is now always accesible if the level's Dragon Coins were collected
Ran some private test locally, confirmed that both are working
nop
@PoryGone asked me to mention him.

SMW: Fixes for Bowser being defeatable on Egg Hunt and CI2 DC room access

---

CommonClient.py

when a port is used to connect in CommonClient that cannot be cast to an int urllib.parse() throws an exception that is uncaught and puts the client into an invalid state where the port can never be updated to be valid without closing the application.
This adds a try/catch for that does not set the port when not a valid int, which causes downstream code to error and handle the disconnect gracefully. 
I think a prettier solution would be much better, since this adds a lot more error messages that hide the actual issue, but at least this allows you to retry a connection.
using ports with spaces (i.e. "123 ") full text ports (i.e. "asdf") and valid ports (i.e. "123") and making sure an error was thrown when the port was invalid, and a connection was attempted when the port was valid. And …

CommonClient: Port Casting Bug

---

worlds/stardew_valley/locations.py
worlds/stardew_valley/options.py

Right now, if you use the Fishsanity setting `exclude_legendaries`, only the basic legendary fishes will be excluded. Extended family fish are still locations when the special orders are set to `board_qi`, they should not. (Because they have the same difficulty as their original copy, player won't want to catch them if they don't want to catch basic one).
This bug was already there in 4.x.x btw, it's not a 5.x.x thing.
Locations before the change (from spoiler). 
<details><summary>See that "Ms. Angler", "Son of Crimsonfish", "Glacierfish Jr.", "Legend II" and "Radioactive Carp" are there</summary>
<p>
```
Fishsanity: Albacore: Stardrop
Fishsanity: Anchovy: Ancient Seeds Recipe
Fishsanity: Blue Discus: Farm Computer
Fishsanity: Bream: Progressive Mine Elevator
Fishsanity: Bullhead: …
```

Stardew Valley: Fix extended family legendary fishes being locations with fishsanity set to exclude legendary

---

worlds/witness/options.py

I was made aware that newlines in option tooltips are actually applied on the Webhost.
Some of the Witness option tooltips look strange as a result.
I am very, very upset that I have to break Pep8 guidelines (line length) for my option tooltips to look good.
Also, changed some outdated hints.

The Witness: Fix newlines in Witness option tooltips

---

docs/options api.md

The example uses `:` when it should use `=`
Reading (also actually running into an APWorld using the wrong method and fixing it)

Docs: Fixing special_range_names example

---

kvui.py

Turns out the issue was solved before for the text tabs, just needed to implement `fix_heights` for HintLog.
Manually, by hinting out an entire slot's items and scrolling through the hint tab to confirm the issue no longer occurred.

CommonClient: fix hint tab overlapping

---

worlds/witness/player_logic.py

Pretty self explanatory if you look at the file diff
What I tested:
In a Multiworld, any seed following a seed with `elevators_come_to_you: true` would act as if that setting was enabled even when it wasn't. I confirmed that with this change, that no longer happens.

The Witness: Fix world bleed issue creating impossible seeds in Multiworld

---

worlds/alttp/ItemPool.py
worlds/alttp/__init__.py

~~Don't know how that slipped through.~~ Crashes when non-local triforce hunt is generated.
It didn't slip through, it was broken in #2290 along with take-any shops which is now fixed in this @alwaysintreble 
Re-generating with the fix.

ALTTP: Fix #2290's crashes

---

worlds/sc2/PoolFilter.py

Fixes Kerrigan Presence when resolving used player's races in the world.
Kerrigan is assumed to be not present if HotS missions aren't enabled
Generated a YAML affected by this bug, checked the spoiler
No

SC2: Fix Kerrigan presence resolving when deciding which races should be used

---

WebHostLib/templates/tracker__Starcraft2.html

Fixes both levels of `Replenishable Magazine (Vulture) ` having the same icon without any visual distinction in the tracker
Ran the webhost and looked at the result (see screenshot)

SC2 Tracker: Use level tinting to let the player know which level he has for Replenishable Magazine

---

WebHostLib/tracker.py

This fixes some wrong item IDs that caused some SC2 options to not show certain received items on the tracker.
Running the webhost locally and comparing the tracker on a /collect-ed world.
This is from a world with the option `generic_upgrade_items: bundle_all`. Previously the center and right columns were blank.

SC2 Tracker: Fix grouped items pointing at wrong item IDs

---

WebHostLib/templates/tracker__Starcraft2.html
WebHostLib/tracker.py

The SCV Hostile Environment Adaptation upgrade was missing from the custom tracker. Added it in, shuffling some icons around to make room.
Started up the webhost, generated a game, checked the tracker with no upgrades and after doing a `/collect`.
Old layout:
New layout (uncollected):
New layout (collected):

sc2: Fixed missing upgrade from custom tracker

---

worlds/cv64/__init__.py
worlds/cv64/docs/en_Castlevania 64.md
worlds/cv64/docs/setup_en.md
worlds/cv64/options.py

At @ReverM's request, changes all the mentions of player "settings" that I could find to player "options". Also fixes a link to the options page that is currently broken on the English setup page and changes a couple of wording oddities I happened to notice.
Ran the webhost and made sure all the links were working.

CV64: Change all mentions of "settings" to "options" and fix a broken link

---

worlds/stardew_valley/docs/en_Stardew Valley.md
worlds/stardew_valley/docs/setup_en.md
worlds/stardew_valley/options.py

With the 1.6 release of the game on Steam soon, the game needs to be downgraded on Steam to work for Archipelago. It will  be a huge source of tech support requests if not specified, so I added documentation about downgrading to the correct version, for 5.x.x
When 6.x.x releases, and downgrading is no longer required, this section will be removed
I also fixed the indent on some existing documentation in the game page
It's documentation

Stardew valley: Game version documentation

---

worlds/pokemon_emerald/data.py
worlds/pokemon_emerald/data/locations.json

Misspelled a pokemon species label, which is displayed for pokedex entry locations and used as a key for the blacklist options.
Generated a game with dexsanity enabled and the correctly-spelled species blacklisted in `wild_encounters`, Ctrl+F "cindaquil" has no more occurrences.

Pokemon Emerald: Fix typo

---

worlds/stardew_valley/logic/ability_logic.py
worlds/stardew_valley/logic/fishing_logic.py
worlds/stardew_valley/logic/skill_logic.py
worlds/stardew_valley/logic/tool_logic.py
worlds/stardew_valley/test/TestRules.py

While looking for performance improvement, I found this potential soft locking bug where Clint's Blacksmith is not required for tool upgrade. For instance, you could a setting where Clint is as the bathhouse, which requires the "Railroad Boulder Removed" item. However, this item is randomized in a foraging bundle which requires the Copper Axe to access. You could still get it with a chair skip, but it's out of logic. There are for sure other locations that are really locked being having an upgraded tool, but it's late, and it's the first example I came with.
Anyway, there is also a significant performance improvement (around 20%) when running the vanilla skill progression, which come from not requiring the previous skill level. In that setting, all those require a tool, which ended up …

Stardew Valley: Fix potential soft lock with vanilla tools and entrance randomizer + Performance improvement for vanilla tool/skills

---

worlds/ladx/__init__.py

This fixes failure to generate when `instrument_shuffle` is set to `own_world` or `different_world`.
Before https://github.com/ArchipelagoMW/Archipelago/pull/2804 got merged, instruments were not a shuffleable dungeon item and the code assumed there is a dungeon item of each kind for each dungeon. However, there is no instrument in D0, so this assumption does not hold anymore.
This PR adds instruments as exception to the rule.
Original bug report:
https://discord.com/channels/731205301247803413/1219301554654548109
I verified that the world generates with both settings and checked the spoiler log to verify that the instruments are placed accordingly.
n/a

LADX: fix local and non-local instrument placement

---

worlds/generic/docs/plando_en.md

Connection Plando was called "Connections Plando", once. Now it isn't.
Reading.

Docs: Consistent naming for "connection plando"

---

worlds/tloz/docs/en_The Legend of Zelda.md

Never thought I'd see the day when a trailing dash would heck something up
Ran webhost to verify markdown is correct
Before: 
After:

TLOZ: Fix markdown issue with game info page

---

worlds/tunic/docs/en_TUNIC.md

Adds a link to the AP plando guide to the bottom of the "does this game support connection plando?" section of the Tunic game page.
Reading.
N/A

TUNIC: Add link to AP plando guide to connection plando section of game page

---

docs/network protocol.md

It has happened multiple times recently that people get to the `Sync` portion of the network docs and get completely misled about what they should do to handle asynchronous play / multiple play sessions.
I think that "what you actually have to do" should be more front and center in this section of the doc.
Not a native, this could probably be written better in a multitude of ways.
Proof that this is confusing for people:
https://discord.com/channels/731205301247803413/1214608557077700720/1219457896509865985
https://discord.com/channels/731205301247803413/1214608557077700720/1217287203835871372

Docs: Mention the "last received item index" paradigm in the network protocol docs

---

WebHostLib/templates/tracker__Starcraft2.html
WebHostLib/tracker.py
worlds/sc2/Items.py

Fixes HERC upgrades being attached to Warhound.
Fixes `Resource Efficiency (HERC)` missing in the tracker
Checked the tracker that the missing item is rendered
[
](url)

SC2: Fix HERC upgrades

---

worlds/kdl3/Client.py
worlds/kdl3/Regions.py
worlds/kdl3/Rules.py
worlds/kdl3/docs/en_Kirby's Dream Land 3.md
worlds/kdl3/docs/setup_en.md
worlds/kdl3/test/test_locations.py

Bugs found within the RC period.
* Deathlink would throw a KeyError when fighting Zero since `self.levels` does not actually account for Level 6 (since it is only ever Zero).
* Added deathlink messages for the Boss Butch and Jumping sub-games.
* Cloudy Park 4 stars would logically require Clean instead of requiring Coo as they should.
* Fixed a rare fill error caused by Level 1 requiring more items than locations possible to clear (test case was 17 items logically required and only 12 possible locations)
* Updated docs to replace settings with options and include some additional info about possible checks.
Ran unittests.
Tested the deathlink changes by generating a KDL3/SM world and ensuring that the correct messages were sent when dying in Hyper Zone/Boss Butch/Jumping.

KDL3: RC1 Fixes and Enhancement

---

worlds/pokemon_emerald/__init__.py

Locations which are always only accessible after a player completes their goal should be excluded. With the addition of trainersanity, I missed adding Norman's trainer reward to this list.
Generated a game with `norman` goal and trainersanity turned on. No issues; spoiler showed a filler item on the location.

Pokemon Emerald: Exclude Norman Trainer Location During Norman Goal

---

Generate.py
worlds/__init__.py

Makes it a bit clearer what broke, hopefully.
By adding carp at the top of factorio's init
[...]NameError: name 'carp' is not defined
[...]Exception: No functional world found to handle game Factorio. Did you mean 'factorio' (100% sure)? If so, it appears the world failed to initialize correctly.[...]

Core: differentiate between unknown worlds and broken worlds in error message

---

worlds/sc2/Locations.py

In testing #3017 I put a victory location into `exclude_locations` to make sure it worked. I found the location was not created. Evidently SC2 filters out excluded locations, and attempts to prevent victory locations from being filtered out, but fails due to a bug. I didn't check what happens if a game is played under this condition but since victory locations determine whether a mission is considered beaten, I can't imagine it goes well.
Generating with an excluded victory location and observing in the spoiler log that the location is still created.

SC2: Don't Filter Excluded Victory Locations

---

worlds/pokemon_emerald/__init__.py
worlds/pokemon_emerald/opponents.py

After reordering the randomization in `generate_output` for organization, the randomization of TMs was inadvertently moved to after TMs are used to create opponent movesets. So opponents currently use moves based on the TMs in the vanilla game, rather than in the player's randomized game.
Opponents could also learn blacklisted moves through vanilla TMs, so they are now filtered when selecting opponent movesets.
Generated a few times with random TMs and blacklisted moves.

Pokemon Emerald: Fix opponents learning excluded and non-randomized TMs

---

worlds/hylics2/__init__.py

I should probably just rewrite the whole Hylics 2 world at this point

Hylics 2: Fix invalid multiworld data, use `self.random` instead of `self.multiworld.random`

---

Fill.py

Whenever a Fill Error gets thrown from main fill, it's super hard to parse and make sense of, so this attempts to improve the error message.
overwrote can_fill with `return False` and read the failure message.

Core: Make fill failure error more human parseable

---

WebHostLib/tracker.py

Adds the starting inventory back into the inventory tables for trackers. Also adds those pre-collected items to received items on generic tracker.
Ran WebHost and checked with a SC2 game with starting items.

Tracker: Add starting inventory to trackers and received items table.

---

worlds/messenger/portals.py

Fixes plando portals being assigned and then immediately overwritten. Fixes the pool of portal outputs not matching what the option description actually says - checkpoints and anywhere *only* had checkpoints when they were supposed to have everything. Fixes a scoping issue that could cause plando to crash.
Was moving portal plando to the options API introduced with #2904 and wrote a unit test to test everything worked correctly. unit test is not currently included here or there as we don't have an API to assign settings for tests.

The Messenger: Fix various portal shuffle issues

---

WebHostLib/check.py

https://discord.com/channels/731205301247803413/1223786643333320767
with the zip file from the discord thread

WebHost: fix /check creating broken yaml files if files don't end with a newline

---

worlds/messenger/__init__.py
worlds/messenger/constants.py
worlds/messenger/options.py

it was comparing items to names which we don't really have a proper override for; we probably should get that at some point. either way this fixes the comparison, and bumps the required client version due to some client side bug fixes.
simple change but still generated and debugged a few times to verify they were being properly removed.

The Messenger: Fix precollected notes not being removed from the itempool

---

worlds/pokemon_emerald/data/locations.json

All the other location names are of the format `Berry Tree Berry Master #`. This one got them mixed up.
Generated with berry tree locations enabled. Inside the Emerald apworld, these user-facing location names are never used as keys or referenced directly (except location groups, I suppose). So this wouldn't affect logic or anything anyway.

Pokemon Emerald: Fix inconsistent location name

---

worlds/yoshisisland/Client.py

Must've missed it during review, but Yoshi got merged without defining patch suffix, so currently "Open Patch" misses it.
Ran the launcher, clicked Open Patch, and confirmed .apyi was present as a selectable option.

Yoshi's Island: add patch suffix

---

worlds/shorthike/docs/setup_en.md

I was just helping someone else set up ASH, and one of the things that confused them was the same thing which confused me when I tried to set it up: When you extract Randomizer.zip, are you supposed to drag and drop the `Randomizer/` folder into `Modding/`, or its subfolders? We both guessed wrong at first and had to be told it's the subfolders.
Also, https://github.com/BrandenEK/AShortHike.ModdingTools/releases is a blank "There aren’t any releases here" page, so not a great thing to link to directly. (The README there also confused the person I was helping, see https://github.com/BrandenEK/AShortHike.ModdingTools/pull/1 )
This is how I got ASH working, and it worked for the person I was helping after I clarified these points.

A Short Hike: Clarify installation instructions

---

worlds/cv64/docs/en_Castlevania 64.md
worlds/cv64/options.py

Two things:
1. Under the "what does another world's item look like in CV64" in en_Castlevania 64.md, changed the "common" by "Light brown-ish" to its proper classification name of "filler". Thanks to Snolid Ice for pointing this out.
2. Corrected the number of multi hit breakables in the game under the MultiHitBreakables options description from 17 to 18 (and subsequently the number of checks it adds to 79/80). I had this at 17 before discovering an additional one in Tower of Execution but never thought about that since. Whoops! Thanks to Mauwhir for catching this one.
If anyone finds any other inaccurate info to add, please speak up before this merges! I don't want to do a third one of these (assuming there'll even be time for that before the release).
Ran it in my vision to make sure …

CV64: A couple of very small docs corrections.

---

worlds/messenger/docs/en_The Messenger.md
worlds/messenger/docs/setup_en.md
worlds/messenger/options.py

Noticed some incorrect information in the docs so this addresses those. The website also doesn't correctly indent 2 space bullet points so swaps to 4 space where needed to render as intended. This still looks pretty bad but it at least gets across the correct intention.
👀

The Messenger: update docs formatting and fix outdated info

---

worlds/kdl3/__init__.py

If you don't manually shuffle the items/locations you pass to `fill_restrictive`, it will provide a relatively deterministic result. Since shuffled animals always has the same animals in the same order, it was affected by this.
Generated with and without this change. Without, confirmed it had the animal layout that a previous seed also had. With, confirmed a new layout was generated.

KDL3: fix shuffled animals not actually being random

---

worlds/pokemon_emerald/client.py

https://discord.com/channels/731205301247803413/1218987814352584785
If the first player to modify the wonder trade key manages to finish another loop of their client's game watcher before receiving the response from their first `Set`, their local `ctx.stored_data` will still have the original `None` in it, since nothing has set it to its default value yet.
This defaults the key on connect instead of using `Get`, so the first client to connect will initialize the value and it will always be a dict.
Connected a fresh client to a fresh server while logging the changes to `ctx.stored_data`, saw that it always contained at least the default value.

Pokemon Emerald: Fix wonder trade race condition

---

worlds/alttp/EntranceShuffle.py

What locations end up as early locations following plando connection changes
Set the world to inverted.  Plando'd Moon Pearl into "Secret Passage".  Plando connected the Hyrule Castle secret entrance dropdown to one of the skull woods holes.
Without this fix, the game is declared unbeatable by the generator even though the moon pearl is definitely in logic.

ALttP: Re-mark light/dark world regions after applying plando connections

---

WebHostLib/autolauncher.py
WebHostLib/templates/userContent.html
WebHostLib/upload.py

delete button
a bit, which is how I found out:
```
>>> bool(uuid.UUID(int=0))
True
```
and why the logging statement exists
This instantly hides the entry, but continues running it if it's still in use.  Unlike some other platforms  we do actually eventually delete the entry though.

WebHost: allow deleting Rooms and Seeds, as well as their associated data

---

worlds/alttp/__init__.py

fixes that fix fake world always applies
wasn't, but we've fixed the same problem in other places with this method.

LttP: fix fix fake world always applying

---

worlds/kdl3/Regions.py

With `open_world` disabled, the player must go through all 6 of the prior stages before being able to reach the boss. However, it was currently setup so the boss entrance would be placed on the world itself, rather than connected to the previous level that must be completed. This leads to an impossible seed when combined with `strict_bosses` off when a required item to complete a stage prior to the boss is placed after the boss.
Recreated the situation using connections plando, and confirmed spheres were required to pick up the item needed to pass the stage (boss was forced into sphere 2, rather than sphere 1).

KDL3: Fix boss access on open world disabled

---

worlds/tunic/docs/setup_en.md

These are case sensitive, and this one got missed in the Tunic -> TUNIC change earlier on.
Clicking the link.
N/A

TUNIC: Fix link to player options page in setup guide

---

worlds/pokemon_emerald/client.py
worlds/pokemon_emerald/data.py
worlds/pokemon_emerald/data/locations.json
worlds/pokemon_emerald/options.py
worlds/pokemon_emerald/rules.py

Changes the capitalization of Ho-oh to Ho-Oh, which is consistent with the way it's capitalized in newer generations.
Screencap from ORAS:
Generated using "Ho-Oh" in `allowed_legendary_hunt_encounters` and `wild_encounter_blacklist`. Searched for every instance of `ho.?oh` in the code and changed any with the wrong capitalization.

Pokemon Emerald: Change Ho-Oh capitalization

---

worlds/sc2/PoolFilter.py

See bug: https://github.com/Ziktofel/Archipelago/issues/187
After main culling process done, some items might be brought back. However, the item dependencies were ignored. This fixes that by filtering `unused_items` by using dependency rules
Tested with YAML that produced the issue, the problem is gone now
No

SC2: Fix unused_items refill to respect item dependencies. 

---

BaseClasses.py

Title. `Location.event` kept being used this way so it probably make sense to have a proper shorthand convenience property.
Wasn't

Core: add Location.is_event property

---

worlds/sc2/Regions.py

Fixes vanilla mission order connection in NCO (a copy-paste error)
Generated an offending YAML, that failed before
No

SC2: Fix vanilla mission order connection

---

worlds/dkc3/Names/LocationName.py
worlds/dkc3/__init__.py

In #2820, I moved hint extension from `modify_multidata`, which was run on a thread, to `extend_hint_information`, which apparently isn't, and now that it's running on the main thread, it can be seen that it actually crashes at the end from an off-by-one error. It doesn't do that anymore.
(Also I noticed a player-facing name had an underscore and no one has ever commented on it)
I actually generated with a level shuffle seed, which I apparently failed to do last PR.

DKC3: Fix List Out of Range Error on Level Shuffle Hint extension

---

WebHostLib/templates/startPlaying.html

On the start playing page, it says "You'll need to upload either a config file or a zip file containing one more config files."
Instead of "one more", it should be "one or more".
Standardized common core
N/A

Webhost: Fix a typo on Start Playing page

---

MultiServer.py

Getting rid of the two remaining uses for `forfeit_mode`. Partly because it's outdated, partly because I ran into an error where my `host.yaml` still had `forfeit_mode` which was overriding my `release_mode` setting.
Generations and running webhost locally.

Core: Getting rid of forfeit_mode

---

worlds/pokemon_rb/__init__.py
worlds/pokemon_rb/client.py
worlds/pokemon_rb/locations.py
worlds/pokemon_rb/pokemon.py
worlds/pokemon_rb/regions.py

- After making a fix to the route 4 subregions in the last update, the item location wound up in the wrong one. This fixes that.
- Fixes a bug in the loop for 10 attempts to get Door Shuffle done, which caused a crash on the third attempt due to the second run corrupting the cache since it wasn't copied.
- Fixes a bug in the client. I confused the Route 18 Gate script value with the Route 18 script value. Assumption of max valid value was based on Route 18, leading to the client reporting a crash when being stopped by the route 18 guard when you have no bicycle.
- Fixes an issue with verification of available HM moves. In order to preserve expectations you'd have with various combinations of settings, this verification is now in a function `verify_hm_moves` which is called both during …

Pokémon Red and Blue: 0.4.5 Fixes

---

worlds/lingo/__init__.py
worlds/lingo/regions.py
worlds/lingo/rules.py

A world's player_logic is accessible from the LingoWorld object, so it's not necessary to also pass the LingoPlayerLogic object through every function that uses both.
pytest.

Lingo: Remove unnecessary player_logic parameters

---

worlds/tunic/__init__.py

Currently, if there was an error encountered where a location is unreachable in entrance rando, it would raise an exception that isn't the most clear to a host.
Now, it'll log a warning and make the entrance hint "Inaccessible". This is so that gen can continue, since I wouldn't want something like this that doesn't always lead to a game that can't be beaten to stop games from happening.
There aren't any currently known bugs in the entrance rando logic, this is mostly a just in case.
Test gens.
Easy way to test is to go to the line in er_scripts that is `while len(connected_regions) < len(non_dead_end_regions):` and change it to `while len(connected_regions) < len(non_dead_end_regions) - 10:`, with the entrance rando option enabled in the yaml. It might take a few tries for it to actually …

TUNIC: Error catching for logic bugs in ER

---

worlds/stardew_valley/options.py

An option that was deprecated in 5.x.x still had a documentation line about it. Now removed
It's documentation

Stardew Valley: Remove early shipping bin documentation

---

worlds/sc2/Client.py

Fixing mission levels not counting towards the level 35 threshold to unlock primal Kerrigan.
Reported by JarJarThinks in the Discord 2024-04-06:
> Hmm does the lvl 35 Kerrigan Primal status only consider items and not Level from mission completions?
When KerriganPrimalStatus is set to level_35, Kerrigan is supposed to become Primal if her level is 35 or higher. However, the client-side check on her level was calculating based on items, which didn't account for levels that could come from completing missions.
I developed this on a branch that let me change the levels per check option dynamically, and have it apply on next mission startup. I completed one mission, set levels per check to 34, and opened a map to ensure Kerrigan was in her Ghost form. Then I exited, updated the option to 35, …

sc2: Fixing mission levels not counting towards the level 35 threshold

---

worlds/noita/__init__.py
worlds/noita/locations.py
worlds/noita/regions.py
worlds/noita/rules.py

This PR exists: https://github.com/ArchipelagoMW/Archipelago/pull/3107
So just doing a little clean up. It isn't everything mypy complained about, just the easy stuff.
Ran gen.
N/A

Noita: Do some cleanup to make mypy happy

---

worlds/sc2/__init__.py

Remove the deprecated data package version in order to avoid cached old item names
Some ppl got old `+15 Starting Minerals` instead of modern `Additional Starting Minerals` in received item messages as the amount is configurable now.
See: https://discord.com/channels/731205301247803413/980554570075873300/1222598200607903744
Bumped the number as the world doc says. However, the world name has changed too and the old apworld could remain on the RC website

SC2: Remove the deprecated data version attribute in order to avoid cached old item names

---

worlds/_bizhawk/context.py

When a user opens a patch file and is asked to select their vanilla ROM through the settings api, if they close the file selection window or select a file that doesn't validate, the exception isn't visible to the user except through the console/log files. This adds a message to the client UI notifying the user what happened.
It's possible something like this should be closer to CommonClient or Settings, but would probably require quite a bit more UX design. At least compared to catching an error and logging something to the UI.
Deleted my Emerald ROM and tried opening a patch file by providing
1. No file
2. An incorrect file
3. A correct file

BizHawkClient: Add error message if patching fails

---

BaseClasses.py
worlds/sa2b/__init__.py

Previously, items added to a player via `push_precollected` in a World implementation would not appear anywhere in the Spoiler Log, unless they were playthrough-relevant. This adds a section (when relevant) which displays all precollected items for the MultiWorld, whether added through World code or a player's `start_inventory`.
I discovered this shortcoming amidst development of a forthcoming game implementation, wherein under some circumstances, items which are important to gameplay, but irrelevant to logic, can get added to the player's `start_inventory`. I think it will be important for the players to be able to see that information in the spoiler log.
This should behave similarly to the `Locations:` section, in that it will list the player name for the item if there are multiple …

Spoiler: Display all precollected items in the Spoiler Log

---

MultiServer.py

If the second argument of "!missing" or "!checked" is a valid location group, return all missing/checked locations from that group.
This also means adding @mark_raw to _cmd_missing and _cmd_checked, as there are location groups with spaces in them.
Tested:
Tried it with the new location groups in Witness, don't know what else to test

MultiServer: Support location name groups in !missing and !checked commands

---

CommonClient.py

https://discord.com/channels/731205301247803413/1227216984593268736
https://discord.com/channels/731205301247803413/1227216984593268736

CommonClient: set max_size to 16 MB

---

worlds/alttp/Rom.py

make locked locations less likely to appear as hint,
with some logs

LttP: deprioritize locked locations for ingame hints

---

kvui.py

Allows the kivy UI to multi-class the items tooltip

kvui: use all flags in Item Class tooltip

---

SNIClient.py
worlds/alttp/Options.py

SNI for over a month now prevents the payload overflow that crashed hardware on its end, so we can get rid of it on ours.
I haven't tested it for this PR recently, so someone with hardware and a full !release probably should.

SNIClient/LttP: modern SNI prevents payload overflow

---

BaseClasses.py
Options.py
WebHostLib/options.py
worlds/alttp/Options.py

allows hiding of options in certain contexts. Multiple use cases  have been discussed, this brings legacy alerts for LttP as one such use case with it.
I've tested each flag barely, so this could use some more testing.

Core: add visibility attribute to Option

---

WebHostLib/check.py

WebHost: check: display exception chain one layer deep

---

worlds/alttp/Rules.py

Only allow locking a Thieves' Town key in the Big Chest if KDS is off (when only one key is placed randomly). I may work on a more elegant solution that works with KDS in the future, but this quick fix should do for now.
Just generated an LTTP game and made sure it doesn't crash or anything

LTTP: Thieves Town KDS Key Fix

---

worlds/alttp/ItemPool.py

- Limits Triforce Pieces to 90
- Fixes the code that condenses items so that it will not skip down to the Bottles and run it every step
Generating the yamls + seed @Silvris provided in the bug report thread

ALTTP: Triforce Pieces and Condense Items fixes

---

worlds/alttp/Rules.py
worlds/alttp/UnderworldGlitchRules.py

Targets the branch for PR #3160 
Fixes `fix_palaceofdarkness_exit` and a world -> multiworld reference

Fixes for #3160

---

worlds/lufia2ac/Client.py

One of the SRAM reads in the client is implemented using a variable size; that size can be 0.
This doesn't seem to be a problem for luabridge-base emulator connections, which simply return a 0 byte result in that case.
But when such a read command with size 0 is sent to snes9x-nwa it causes an error and a disconnect.
We can avoid this entirely by performing the read only if the size is greater than 0.
https://discord.com/channels/731205301247803413/1229626698216116265/1229936513299779584

lufia2ac: prevent 0 byte reads

---

worlds/noita/locations.py
worlds/noita/options.py
worlds/noita/regions.py

Adds the new Kivi, Tapion vasalli (Deer), and Kolmisilmän sydän (Meatball) to the boss check pool when you have Bosses as Checks set to All Bosses.
Tested gen, updated client to send the new checks.
terrifying, isn't it?

Noita: Add the new bosses to the check pool

---

worlds/cv64/__init__.py
worlds/cv64/aesthetics.py
worlds/cv64/data/patches.py
worlds/cv64/docs/obscure_checks.md
worlds/cv64/options.py
worlds/cv64/rom.py
worlds/cv64/stages.py

Changes some stuff in CV64's generate_output to have it use the new AP Procedure Patch. Single game gen times now take milliseconds instead of seconds thanks to no longer needing to wait on bsdiff, and the ROM is no longer needed to generate.
Took my ROM out of my source directory and went through the entire process of generating and patching to make sure it didn't ask for the ROM until opening the patch through the launcher. And then played the seed to completion to make sure everything in the game was working as it should.
NOTE: This PR includes the fixes from https://github.com/ArchipelagoMW/Archipelago/pull/3129. If this merges first, feel free to close it (or I will).

CV64: Use AP Procedure Patch

---

worlds/pokemon_emerald/__init__.py
worlds/pokemon_emerald/client.py

A client on `main` connecting to a seed generated on 0.4.5 will encounter an exception if the player is playing legendary hunt, catches Ho-Oh, and Ho-Oh is a valid legendary hunt encounter.
This is the only thing needed to make the client backwards compatible.
Also bumps the required client version to avoid the crash in the other direction, where a game is generated on main/0.4.6 and a player attempts to connect with a 0.4.5 client.
Generated on 0.4.5, set the Ho-Oh flag, and ran on `main` and this branch. `main` hit an exception, this branch fixed it.

Pokemon Emerald: Fix client crash if 0.4.6 client connects to 0.4.5 seed

---

worlds/sm64ex/Regions.py
worlds/sm64ex/Rules.py

- Replaces **entrance** entrance rules that relied on `can_reach` to remove accessibility check errors.  Ignored the legacy entrance dependencies on the Bowser in the Fire Sea entrance (entrance entrance rule depends on a location) as that rule has been around for several versions and has never been reported causing a failure.
- Logic no longer ignores the Strict Move Requirements setting when moves are not randomized.  This was causing hard logic to be unintentionally used on the following checks: - DDD: Pole-Jumping for Red Coins", "WDW: Go to Town for Red Coins", "WDW: Quick Race Through Downtown!", and "WDW: 1Up Block in Downtown"
- A few small changes to move rando logic based on player feedback, making Strict logic easier and non-Strict logic slightly harder.
100 generations with …

SM64ex: Logic and Generation Fixes

---

worlds/generic/docs/commands_en.md

it would be good to document things, huh
pretty sure i ran local webhost

Docs: adds new commonclient commands to webhost docs

---

MultiServer.py

Bug Report Thread: https://discord.com/channels/731205301247803413/1227391160520278066
Server admins are allowed to send any value when using the `/option` command for `release_mode`, `collect_mode`, and `remaining_mode` which acts like `goal` when a user runs `!release` or other variant because of the final else-clause in the command processing methods, if it is not one of the valid options: `enabled`, `disabled`, `auto`, `goal`, `auto_enabled`.
These changes add an additional check for explicitly the `*_mode` options to ensure they are given a valid value or it will fail with a "Unrecognized {*_mode} value" log printed to the standard output.
Comparing functionality between before and after this patch with `/option release_mode off` (an invalid value), and confirmed that post-patch the …

MultiServer: Prevent invalid `*_mode` option values.

---

worlds/zork_grand_inquisitor/data_funcs.py
worlds/zork_grand_inquisitor/world.py

Turns out I had 2 separate small issues affecting determinism on fixed seeds:
* An iteration on sets of location enum items
* An inline cast of a set to a list in `get_filler_item_names`
In both cases, I made sure the operations happened on lists instead to make sure the order is deterministic.
**Before**
2 generations with fixed seed `12345` would yield completely different item placement, progression items included
**After**
2 generations with fixed seed `12345` yield identical item placement
World tests are still green after the changes.

Zork Grand Inquisitor: Fix Determinism Issues on Fixed Seeds

---

worlds/pokemon_emerald/data/regions/cities.json
worlds/pokemon_emerald/rules.py

Dewford Town has water, but needed a separate region for it so it could be locked behind Surf.
Generated a game with dexsanity enabled. Testing is limited since I'm doing this on my phone.

Pokemon Emerald: Fix missing region for water encounters in Dewford

---

Options.py
test/general/test_options.py

Item Links properly unfold item_name_groups but the unfolded names don't get assigned back to the link
Debugged and added a unit test

Core: fix item_name_groups unfolding in item links

---

worlds/messenger/__init__.py
worlds/messenger/connections.py
worlds/messenger/options.py

Removes the special cased april fools' behavior now that that's over, and fixes item links filler gen crashing due to the new option behavior.
Generated some seeds with item links to verify they actually work now.

The Messenger: Hotfix item links filler gen

---

worlds/sa2b/Options.py
worlds/sa2b/docs/setup_en.md

SA2 now has a fancy new Mod Manager, and the old one is deprecated. This requires slightly different setup instructions.
Additionally, a single, much-requested option tooltip clarification is included.
We read it, and followed it, and it worked.

SA2B: Update Setup guide for new Mod Manager

---

worlds/adventure/Locations.py
worlds/adventure/Regions.py
worlds/adventure/__init__.py

Does not assign room id or room_x, room_y to the fixed location table entries (except room_id in some cases when it only can have a single possible value).
Ran determinism test from https://github.com/ArchipelagoMW/Archipelago/pull/2977, all other tests, generated a couple 2600 world multiworlds, generated a few 1 and 4 world Adventure multiworlds and played one of them..
N/A

Adventure: Remove runtime changes to location templates to fix determinism issues

---

worlds/cv64/__init__.py

"player" is set to Optional, but forgetting to set it will cause WebHost to be unable to find your files.
Generated with this change, then hosted on 24242, confirmed the patch file was available.

CV64: Include player in APPP constructor

---

worlds/alttp/ItemPool.py
worlds/alttp/__init__.py

Changes a use of `self.swordless` and `self.glitches_required` to `self.multiworld.swordless[self.player]` and `self.multiworld.glitches_required[self.player]` respectively.
Round returns the datatype that was passed in, so we cast the resulting float to an int when on percentage Triforce Pieces.
Generated using the offending yaml.

LttP: fix percentage Triforce Pieces and missed cleanup from #3160

---

BaseClasses.py
Generate.py
Main.py
settings.py
worlds/alttp/Rom.py

remove glitch triforce setting
nope

LttP: remove glitch triforce setting

---

WebHostLib/tracker.py

Makes a dict into a Counter collection to prevent a "attr not found" error.
Also fixes a type hint that was wrong.
Ran webhost and checked tracker.
N/A

Factorio: Fix 500 error on Factorio multi-tracker.

---

worlds/stardew_valley/options.py

1: Fixed a typo (leaning -> learning)
2: Shortened the goal documentation so that the tooltip is more readable (hopefully)
Documentation

Stardew Valley: Options page documentation improvements

---

worlds/zillion/options.py

This is a common question that comes up in the Zillion discord channel.
"What does the skill option do?"
run WebHost.py, open zillion options page to see how it looks there

Zillion: Docs: add information to skill option documentation

---

Options.py

When the user puts in an invalid option for a Toggle, it fails at the end of gen with a very unhelpful
```
File "__startup__.py", line 124, in run
File "console.py", line 16, in run
File "Generate.py", line 549, in <module>
File "Generate.py", line 240, in main
File "Main.py", line 442, in main
File "BaseClasses.py", line 1377, in to_file
File "BaseClasses.py", line 1360, in write_option
File "Options.py", line 137, in current_option_name
File "Options.py", line 397, in get_option_name
IndexError: list index out of range
```
Now, it'll just convert it to something valid.
Ref discussion: https://discord.com/channels/731205301247803413/1224562534753898647
Previous PR: https://github.com/ArchipelagoMW/Archipelago/pull/3098
Easy way to reproduce the error: …

Core: Silently fix invalid yaml option for Toggles

---

MultiServer.py

/datastore
only a little, turns out among my 3 games I use a single datastore key, so I don't have much known data to test with.

MultiServer: add datastore list command to MultiServer

---

SNIClient.py

When we disconnect from the SNES (intentional or otherwise), we don't actually change our state to reflect this. This means SNIClient cannot reconnect, as `snes_connect` will see our status as SNES_CONNECTED and think we're waiting on the SNES to load a game.
Connected to Snes9x-rr using SNI's lua, and then paused the emulator, forcing SNIClient to disconnect. Then, unpaused the emulator and confirmed that SNIClient was capable of reconnecting without any further help.

SNIClient: set SNESState to SNES_DISCONNECTED when disconnected

---

worlds/tunic/er_rules.py
worlds/tunic/er_scripts.py
worlds/tunic/rules.py

When set to minimal with hex quest off and ladder shuffle on, there's a chance of it not giving you access to the place you need to place the 3 hexagons to finish the game.
Now, there's an event there that is required to reach the Spirit Arena.
Few test gens.
N/A

TUNIC: Fix minimal Heir access in ladder shuffle

---

MultiServer.py

As reported in: https://discord.com/channels/731205301247803413/1231278945199067157
Current implementation of server-side `/alias` did not allow removing an alias due to an unpacking logic bug. This change fixes that. 
Ran MultiServer.py and tested changes.
Before:
After:

MultiServer: Fix `/alias <name>` not removing aliases.

---

setup.py

Disable upgrade to cx_freeze 7.x since that is incompatible for the way we hook into the build process. Also update to latest 6.x while at it.
**Important:** CI release action for Linux will fail if neither this nor #3195 is merged.
`python setup.py build_exe bdist_appimage`

Setup: update cx_freeze to latest 6.x and exclude 7.x

---

Utils.py

I keep seeing people confused why generation stopped or why the client isn't patching, when they didn't see the dialog asking for a file. By logging that it's happening they may have a higher chance to notice.
It wasn't, I go to sleep now.

Core: make open_filename log that it's asking

---

docs/webhost configuration sample.yaml

Last time I saw this option it came  with a deprecationwarning, so it's either already removed or no longer relevant.
Nah

WebHost: remove JSON_AS_ASCII

---

worlds/messenger/portals.py

An incorrect import that breaks the 3.8 build
Rebuilt and checked that the world loads

The Messenger: fix import that shouldn't be relative

---

WebHostLib/upload.py

This is a two-fold PR just because both fixes were trivial.
1. Prevent committing data packages with invalid checksums to database.
If a game with a data package checksum that does not match the re-calculated checksum is uploaded, an error would flash on the screen with the specific error, but the data package would still be uploaded to the database. Then the next time a user uploads the same game data package, it will return a 500 error instead as PONY would throw an exception.
The fix was to compare the checksums first, then create a `GameDataPackage` entity as doing it before would still commit to DB even without running `commit`.
2. Prevent 500 error from invalid `zip` files.
Similar to the above, if a `.zip` file containing the `.archipelago` file with the invalid  data package …

WebHost: Prevent committing data packages with invalid checksums to database and prevent 500 error from invalid `zip` files.

---

worlds/cv64/__init__.py

Fixed an import in `__init__.py` that caused CV64 to not work on the Python 3.8 build.
Ran a generation to make sure it worked. I didn't test the 3.8 build specifically, but it should be the same fix as https://github.com/ArchipelagoMW/Archipelago/pull/3219.

CV64: fix import that shouldn't be relative

---

worlds/tloz/Rules.py

Properly name the Book to Book of Magic in Rules.py so you can actually possibly be expected to use Magical Rod plus Book of Magic to get through dark rooms. No wonder we tend to see candles so early oops.
Also adding a rule that you need candles for access to Level 8 so you aren't required to time a Rod+Book shot against a moblin to burn the bush. Might make this a logic trick or something later.
Test gens with a yaml that plandos candles in places that forced Rod + Book in early enough places to get proper dark room access, and other test gens that plandos the candles in Level 8 to see that it makes the game unbeatable

[TLOZ]: Dark Rooms and Level 8 Logic Fixes

---

worlds/lingo/options.py
worlds/lingo/static_logic.py
worlds/lingo/test/TestDatafile.py

There was an issue where the Lingo world would not load on a python 3.8 frozen build. This fixes that.
Generated on both frozen 3.8 and frozen 3.10. Ran pytest on non-frozen 3.8 and 3.10.

Lingo: Fix world load on frozen 3.8

---

setup.py

Make setup.py compatible to cx_freeze 7.x and upgrade cx_freeze.
`python setup.py build_exe bdist_appimage`
Since this is a major release number change and was only tested very little, I'd strongly prefer to merge this **after** the upcoming release and merge #3194 now instead.

Setup: update cx_freeze to 7.x

---

MultiServer.py
worlds/tunic/__init__.py

- Adds the `HintGame` tag, for projects like BKSudoku/APSudoku/HintMachine (this tag, like `TextOnly`/`Tracker`, allows `ignore_game`)
- Adds new verbs to join messages:
- `hinting` for `HintGame`
- (unchanged) `tracking` for `Tracker`
- `viewing` for `TextOnly`
- Default (unchanged) `playing`
- Adds verbs to leave messages (which were previously completely lacking)
- `stopped hinting` for `HintGame`
- `stopped tracking` for `Tracker`
- `stopped viewing` for `TextOnly`
- Default (unchanged) `left` 
- Adds client version/tags info to leave messages (same as it was previously on join messages)
Where multiple tags that have associated verbs are on the same client, it picks the first applicable verb, in tag order `HintGame`, `Tracker`, `TextOnly`, default.
Connected and disconnected with …

Core: Improve join/leave messages, add "HintGame" tag

---

worlds/lingo/locations.py
worlds/lingo/player_logic.py

When door shuffle is on and early color hallways is off, sphere 1 is only three checks. This has proven to be difficult for the fill algorithm sometimes. This PR adds four more checks to the starting room under these conditions to make things less likely to fail.
Client branch: https://code.fourisland.com/lingo-archipelago/log/?h=tinysphere
Tracker branch: https://code.fourisland.com/lingo-ap-tracker/log/?h=tinysphere
Test gens using both the updated client and tracker.

Lingo: Expand sphere 1 under restrictive conditions

---

Generate.py

Use alphabetic rather than asciibetic sorting when ingesting files for generation (upper and lower case letters will be interspersed rather than upper case before lower case. This doesn't fully order names. It's unclear if that would make things easier or harder (having all seeds together from a single file may make them easier to find).
Generated many seeds.

Core: organize files on ingest via alpha, not ascii

---

worlds/sc2/MissionTables.py
worlds/sc2/PoolFilter.py

If the mission order isn't `vanilla_shuffled` or `mini_campaign`, pick just one of the hardest missions that's enabled and make it goal.
This allows End Game as the goal even if long campaigns are present
Generated a couple of games with various YAMLs, subject to goal selection
No

SC2: For non-campaign order pick one of the hardest missions as goal

---

worlds/lingo/player_logic.py

There was an issue where the combination of door shuffle, panelsanity, no early color hallways, and being in a multi player world would break generation. This was because of the code that generated an early good item. The code is not supposed to run under panelsanity, but the conditional was not correct. This fixes that.
Pytest, and running a test generation under the specific error case from above.

Lingo: Fix broken good item in panelsanity

---

worlds/hk/__init__.py

move godhome events to create_regions with the others to not try and make them non-events when unshuffled is on
generated with a mix of goals and unshuffled settings and released to confirm the correct amount of non-event items were created

HK: Fix Godhome Events

---

worlds/yoshisisland/Rules.py

As of easy logic for this goal is
```logic.has_midring(state) or (state.has("Tulip", player) and logic.cansee_clouds(state))```
normal logic shouldn't need any collectable as `logic.cansee_clouds(state)` allways evaluates to `true` in normal logic and therefore the hole equation is `true`. Normal logic shouldn't need more collectables than easy logic.

Yoshi's World: Fixed minor logic inconsistincy in Rules.py

---

worlds/pokemon_emerald/__init__.py

Changes a couple `ValueError`s in `generate_early` to `OptionError`s.
Triggered one of the errors.

Pokemon Emerald: Use OptionError

---

worlds/lingo/__init__.py
worlds/lingo/player_logic.py

The Lingo world raises exceptions for impossible configurations of options. This converts those exceptions to the newly added OptionError. Exceptions not related to options are still Exceptions.
Didn't really need to. Ran pytest though.

Lingo: Started using OptionError

---

worlds/pokemon_emerald/locations.py
worlds/pokemon_emerald/pokemon.py
worlds/pokemon_emerald/rules.py

Current behavior is that dexsanity requires every species to be placed on a wild encounter table so that its dexsanity location is reachable. If the player blacklists a species from wild encounters while dexsanity is enabled, the blacklist must be ignored once to place the species.
This changes the interaction so that the dexsanity location is not created if the user blacklisted the species from wild encounters.
Generated with dexsanity on while blacklisting each of
- nothing,
- one species,
- "_Legendaries",
-  "_Legendaries" plus Wailord (with a legendary hunt goal, to make sure Wailord still gets placed)
Total location count dropped as expected, no generation failures. Blacklisted species did not show up anywhere in the wild according to the spoiler log (except for Wailord, which is …

Pokemon Emerald: Change dexsanity to not create locations for blacklisted wilds

---

WebHostLib/misc.py

removes
if you enter a command into the bar in  /room,  then go back/forth via browser controls.
comparing localhost to archipelago.gg
Turns
into:

WebHost: use redirect for /room form submission

---

worlds/soe/docs/multiworld_en.md

As was mentioned in SoE Channel on Discord:
* "Connect to SNI" section is actually wrong(ly ordered, and has wrong header levels inside)
* "Required software" was not 100% correct because it expected people to have a modern web browser, and in fact Archipelago install is optional for SoE.
Other suggestions from Discord discussion would affect the global style and would have to be handled there - those were changing the margin and/or padding around ol and/or h3 as well as making h3, h4 and h5 easier to distinguish.
(For completeness sake, I reject the alternative suggestion to change h5 into ul, because massive nested lists are even harder to parse imo.)
:eyes:

SoE: Docs: rework some styling

---

data/lua/connector_mmbn3.lua

Adds in a check preventing the game from reading garbage data as a game completion flag. Addressing a bug report in [Discord](https://discord.com/channels/731205301247803413/1232659654237225030)
Idling on the title screen long enough could write garbage data to the Save ROM when the title screen restarts. This data can sometimes write to the area of the Save that the client uses to check if the game is completed.
Ran the attached seed in the discord post with and without Lua fix for 30 minutes. Pre-patch consistently hit the bug within a few minutes, post-patch the bug never occurred.

[MMBN3] Fixes incorrect "Game Completion" Flag getting set

---

BaseClasses.py

`has_group` and `count_group` currently exist to be able to check for a specific overall quantity of a list of items.
However, these need item groups to be defined, and also the user has no way of telling this function **which items from a group actually exist**. Those functions will just blindly try all items from the item group.
So, I decided to add two new functions called `has_list` and `count_list`, that are completely analogous to `has_group` and `count_group`, except you can specify the list of items you care about. This way, you 1. don't need an item group to be defined for the items and 2. can prepare the item list yourself, first sorting out any items that don't exist because of e.g. the options the player chose.
This function uses a for loop for a sum despite not having any …

Core: Add has_list and count_list and improve (?) count_group

---

worlds/pokemon_emerald/data/regions/cities.json
worlds/pokemon_emerald/data/regions/routes.json
worlds/pokemon_emerald/rules.py
worlds/pokemon_emerald/test/test_accessibility.py

Slateport has water encounters that may be logical access to dexsanity species which are currently considered reachable without surf. This adds a new region for the water inside the city to seal those encounters behind using Surf.
The included new lines in the tests fail without this PR and succeed with it.

Pokemon Emerald: Fix incorrect access to Slateport water encounters

---

worlds/doom_1993/__init__.py
worlds/doom_ii/__init__.py
worlds/heretic/__init__.py

Changes from `self.multiworld.exclude_locations[self.player]` to `self.options.exclude_locations`
Generations and comparing spoiler logs

Doom I/II, Heretic: Removing old option getters

---

worlds/bumpstik/Options.py
worlds/bumpstik/Regions.py
worlds/bumpstik/__init__.py
worlds/meritous/Options.py
worlds/meritous/Regions.py
worlds/meritous/__init__.py

Affects both Bumper Stickers and Meritous. Specifically changes them to use the options dataclass, removes deprecated option getters, and removes `world: multiworld`
Generations, connecting to one multiworld with both games, and the unit tests

Bumper Stickers and Meritous: Options and world: multiworld fixes

---

worlds/zillion/__init__.py
worlds/zillion/client.py

`Logger.warn` is deprecated
just type checking

Zillion: remove deprecated `Logger.warn`

---

worlds/AutoWorld.py

Can take it or leave it, but I believe the ClassVar typing is incorrect here. Some worlds already change this attribute per world, and when core checks this attribute it checks it per player, not per world type.
Wasn't, just a typing change.

World: remove ClassVar typing from topology_present

---

docs/options api.md
worlds/generic/docs/advanced_settings_en.md

Currently, it says that priority_locations is the inverse of exclude_locations. This is not true, since neither exclude_locations nor priority_locations allow useful items.
I'm not a huge fan of the wording, I'm mostly just mirroring the exclude_locations text.
Reading
N/A

Docs: Update advanced yaml guide wording for priority locations

---

worlds/cv64/text.py

Fixes an oversight with the `cv64_text_truncate` function wherein for some reason I completely and utterly forgot to check to see if the character we're taking the length of is in `cv64_char_dict` to begin with. This is problematic for the item names in Renon's shop specifically as they are the only thing that currently use this.
Also changed the replacement character from an `_` to a `?` because I thought it looked better.
Plando'd MegaMan Battle Network 3's "AlphaArmΩ V" onto a Renon shop slot and made sure it generated properly.

CV64: Fix items with weird characters landing on Renon's shop crashing

---

docs/running from source.md

The line about template yamls from WebHost was added when we didn't have the "Generate Template Options" button in the launcher,
so this was one of the best ways to generate the default yamls.
Even though the information is still accurate, I don't think it's useful enough to keep here anymore.
on Thursdays

Docs: remove obsolete yaml generation info

---

BaseClasses.py

Removing `item_count`
Unit tests, looking for things that use it, and one generation with every world except DKC3.
After this, so far as I can tell, the only things that are deprecated and don't have PRs addressing them are ~~`data_version`~~ and `per_slot_randoms`

Core: Removing item_count

---

Options.py

Removing two deprecated things that can now be removed and are unused.
Unit tests and searching.

Core: Remove deprecated get_current_option_name and SpecialRange

---

worlds/messenger/__init__.py
worlds/messenger/test/test_portals.py

I wrote code to guarantee the searing crags portal is always open when portal shuffle is disabled but i never considered that someone would have their starting portals set to 3 when doing that for some reason.
Added a test for it that fails without the change.

The Messenger: fix generation failure for no portal shuffle with 3 available portals

---

Launcher.py

Should fix the message appearing in places like https://discord.com/channels/731205301247803413/1214608557077700720/1233912447933481006
Made adventure into an apworld and somehow that triggers it.

Core: prevent "Could not find identify Component responsible for None" from being logged.

---

worlds/ff1/Options.py
worlds/ff1/__init__.py

Changes FF1 to the new options system
Some generations, unit tests, connecting to a multiworld, reading spoiler logs, and comparing playthroughs before and after.

FF1: Switching Options System

---

worlds/witness/data/WitnessLogic.txt

This doesn't actually matter right now because a previous panel in the chain requires Colored Squares anyway, but in the future there might be modes that change the order in which you do panels, and things like that, so yeah
(Found by Exempt-Medic)

The Witness: Fix Mountain Floor 2 Near Row 5 Symbol Requirement

---

worlds/pokemon_emerald/CHANGELOG.md

Updates Emerald's changelog for all merged PRs since 0.4.6 (and one that got missed that was released in 0.4.6).
Emerald 2.1.0 and 2.1.1 were released separately from the main AP release. AP 0.4.6 contained Emerald 2.0.1.
Reading

Pokemon Emerald: Update changelog

---

README.md
docs/CODEOWNERS
inno_setup.iss

After the merge of yugio06 there where a few things that where overlocked.
Namely the game needs to be added to CODEOWNERS, inno_setup and readme

YGO06: adds the new game yugioh06 to CODEOWNERS, inno_setup and readme

---

worlds/AutoWorld.py
worlds/overcooked2/__init__.py

`self.multiworld.get_player_name(self.player)` is so stupid lol
Edit: Overcooked was already doing this itself so I needed to make it not do that. @toasterparty

Core: Player name property on world class

---

worlds/yugioh06/__init__.py
worlds/yugioh06/structure_deck.py

Support Python 3.8
The pipeline did run

YGO06: make sure it runs on 3.8 support

---

WebHostLib/customserver.py

when switching to multiple rooms per process, we ended up modifying the static server data
because that's how _load works and the data is now shared between multiple rooms.

CustomServer: don't mutate static server data

---

WebHostLib/autolauncher.py
WebHostLib/customserver.py

Rooms are spinning  too much
locally

WebHost: fix AutoLauncher restarting rooms due to race condition

---

MultiServer.py
WebHostLib/customserver.py

If a webhost is running long enough for rooms to go to sleep, they would still have an atexit handler registered that would save that old version of the room at exit, rolling back data if you got unlucky if that is the last save to DB made.
Quickly locally and currently on prod.

WebHost: move atexit saving to end of room hosting function

---

WebHostLib/generate.py
WebHostLib/options.py

auto-fix imports
added typing
removed self-calling network request
removed forfeit-mode again, which had been gone for months
removed explicit settings and let them default instead
extracted "start_generation" as function in WebHostLib/generate.py
options pages no longer redirect to archipelago.gg
fix Visibility being used via <, instead of like an intflag
using  the generate buttons on the player options page of Factorio and the upload yaml page.

WebHost: fixup WebHostLib/options.py

---

worlds/zillion/__init__.py
worlds/zillion/options.py

adds an "item counts" option group for Zillion
run web host and see options page
generate yaml from launcher and see option group

Zillion: add OptionGroup

---

WebHostLib/customserver.py

The change to per-room datapackage accidentally removed "Archipelago" is the room was in custom data package mode.
This adds it back in.
See this report https://discord.com/channels/731205301247803413/1043855558303821844/1241808390947344424
An assert in `def load`.

CustomServer: re-add missing Archipelago to data package

---

WebHost.py
WebHostLib/autolauncher.py

In the current code
* with SELFHOST:
* killing the main thread will hang waiting for the worker threads to stop.
* this has the side effect of multiprocessing workers to receive Ctrl+C, die and respawn because the pool never stops
* pressing Ctrl+C again will stop waiting for the worker threads and just terminate
* without SELFHOST: 
* similar to above, but we immediately enter the state where we wait for the threads to stop, so only one Ctrl+C is required to actually terminate the process
After this change:
* with SELHOST:
* we gracefully stop the worker threads once waitress finishes
* the application terminates cleanly (with just 1x Ctrl+C)
* without SELHOST:
* similar to above, but we spin the main thread ourself until SIGINT is received
Only with waitress locally and with SELFHOST: …

WebHost: properly stop worker threads

---

worlds/alttp/Rules.py

Last attempt to fix this issue was by changing the boss kill logic to use `add_rule`, but I guess I misunderstood the order these happen. So change Swamp Palace rule to use `add_rule` so they aren't 
Re-generating with reported yamls and set seed to observe corrected item placement.

ALTTP: Second attempt to fix Swamp Palace boss logic

---

Options.py
worlds/subnautica/options.py

uses correct version of valid_keys
adds assert in core  to prevent others from making my mistake
includes an assert to test. Also tested against option page listing all items instead of valid keys before.

Subnautica: fix use of _valid_keys where valid_keys should be used.

---

WebHostLib/templates/playerOptions/macros.html
WebHostLib/templates/weightedOptions/macros.html

This causes both options pages to use the list of `valid_keys` instead of `world.location_names` or `world.item_names` if `valid_keys` is not empty.
Ran it locally and confirmed the correct lists were displayed.

Update options pages macros to respect valid_keys for item and location options

---

WebHostLib/options.py

This prevents a crash on Python 3.8 by removing a bitwise or comparison between two dicts
Tested locally by running WebHost

Use world.web.options_presets directly

---

WebHostLib/customserver.py

ctx._save() on finally may force a save of empty data if data was never loaded  successfully.
~~locally by adding a raise() into load.~~
On prod.

Customserver: only save on exit if it's in a good state.

---

worlds/mlss/Client.py

Removes a logger.info() call from validate_rom. This would be called in other games clients if they we're alphabetically past mlss.
Loaded a game of Pokemon Emerald and the logger message from mlss didn't pop up.

MLSS: Remove logger message from validate_rom

---

worlds/bomb_rush_cyberfunk/Options.py

Adding spaces between lines because it looks nice.

Bomb Rush Cyberfunk: Update option docstrings

---

worlds/sa2b/Options.py
worlds/sa2b/__init__.py

Option Groups and Dataclass for Sonic Adventure 2: Battle
I ran the WebHost and see the Option Groups.
I generated template YAMLs from the launcher and saw the group headers.
I ran generations and validated option output.

SA2B: Option Groups and Dataclass

---

worlds/smw/Options.py
worlds/smw/Presets.py
worlds/smw/__init__.py

Option Groups and Presets for Super Mario World
I ran the WebHost and see the Option Groups.
I verified the Presets set what I expect.
I generated template YAMLs from the launcher and saw the group headers.

SMW: Option Groups and Presets

---

worlds/tunic/__init__.py
worlds/tunic/options.py

Adds an option group to section off the logic options (since those are more "advanced" options that we want to section off).
Also changes the descriptions to not look weird with the new webhost update.
Ran webhost
N/A

TUNIC: Add option groups, fix option descriptions

---

worlds/pokemon_emerald/docs/setup_es.md
worlds/pokemon_emerald/options.py

The [Spanish setup guide](https://archipelago.gg/tutorial/Pokemon%20Emerald/setup/es#generando-y-parcheando-el-juego) has a line break in between the link text and target, which causes it all to render as text. This fixes it.
Also removes some trailing whitespace and updates some line breaks while I'm here.
Ran webhost

Pokemon Emerald: Fix broken Markdown in spanish setup guide

---

worlds/_bizhawk/__init__.py
worlds/_bizhawk/client.py
worlds/_bizhawk/context.py

Tiny linting/style so boring that they might never change except via this PR.
Also ran pep8 and ignored a couple line length violations :stuck_out_tongue:. Those can be addressed when we drop 3.8 and 3.9 and can adjust the type hints.
Ran the Emerald client with these changes while testing other things (python 3.11).

BizHawkClient: Minor linting/style

---

worlds/noita/options.py

Basically changes it from having the triple quote in-line to not in-line so it doesn't have weird tabs in the option description.
Also adjusted the death link option description to state it can be disabled in-game.
Ran webhost, ran gen
N/A

Noita: Update option descriptions after webhost change

---

worlds/tunic/__init__.py
worlds/tunic/options.py

Adds a few option presets for TUNIC. The first two to give a little recommendation for someone unsure what to bring to a sync or async. The third to punish the curious.
Ran webhost, made sure the presets worked as intended. Ran tests.
N/A

TUNIC: Add option presets

---

worlds/cv64/__init__.py
worlds/cv64/options.py

Adds option groups for CV64 and changes the formatting of the option descriptions to remove indentations whenever there's a manual line break.
Ran the WebHost and made sure it all looked good there.

CV64: Add option groups

---

worlds/lingo/__init__.py
worlds/lingo/options.py

Added two option groups: "pilgrimage" and "fine-tuning". Options that don't fall into those groups are just in the default group.
Looked at the webhost.

Lingo: Add option groups

---

Options.py
WebHostLib/options.py
worlds/AutoWorld.py

prevents worlds from defining an option group with no options in it, fixes options always being printed to the template when they shouldn't be, removes the default "Game Options" option group if it's empty.

Webhost: Disallow empty option groups

---

BaseClasses.py
worlds/bomb_rush_cyberfunk/Rules.py
worlds/yugioh06/rules.py

Based on this poll https://discord.com/channels/731205301247803413/1243111773419339847/1243199985797828658
Will undraft once that poll finishes, although it's looking like everyone is unanimously on board with this change so far.
We haven't released a major stable version with the `exclusive` variants in it yet, so this change can still be made without making any aliases. Requires changing some worlds tho that have already started using these methods.

Core: Rename "count_exclusive" methods to "count_unique"

---

setup.py

7.1.0 is broken on Linux when using pygobject, which we use as optional dependency for kivy.
Already reported upstream. 
The last round of builds was done with 7.0.0 and they worked.

Setup: pin cx_freeze to 7.0.0

---

worlds/_bizhawk/context.py

Clarifies common reasons a player might be seeing the "no handler was found" message. I've seen occasional confusion from players what they should do when they see it, and almost every time the answer is that they didn't install the apworld in the right place.
Wasn't

BizHawkClient: Add suggestion when no handler is found

---

Generate.py

#3380
i forgot about weighted files when i added that delete line apparently. this reverses that checking by just adding the actual valid options to the set instead of deleting weights that we decide are valid.
generated with 1 custom and a weights file confirming that invalid options still print and custom options from the weights all worked.

Core: Fix weights file data not being reused

---

worlds/terraria/Options.py
worlds/terraria/__init__.py

Switches Terraria to the new options API. See #3284.
I generated some worlds with different options and checked the spoilers to make sure the options are still being respected. I also played the beginning of a game with the client.

Terraria: migrate to new options API

---

WebHostLib/generate.py
WebHostLib/options.py
settings.py

/api/generate always had its own defaults, which this fixes and single player gen gained its own fresh defaults after the option rework, so this re-fixes it, as we just in 0.4.6 made them follow the same defaults.
Tested it against this case: https://github.com/ArchipelagoMW/Archipelago/issues/3378
Got an output that matched my expectation.

WebHost: use settings defaults for /api/generate and options -> Single Player Generate

---

docs/CODEOWNERS

Removing as world maintainer based on this comment: https://github.com/ArchipelagoMW/Archipelago/pull/3284#issuecomment-2110461370
Keeping `ff1` world in `worlds` as world still works, but may move to `worlds_disabled` if world compatibility breaks with no new maintainer to take on the role.
N/A
N/A

CODEOWNERS: Remove @jtoyoda as world maintainer for Final Fantasy

---

worlds/sc2/Client.py

Fixes the `half_completion` value for the `kerrigan_primal_status` option incorrectly counting completed missions.
Generating a seed with 5 missions and comparing Kerrigan primal status in-game after 2 completed missions and after 3 completed missions.

SC2: Fix Kerrigan Primal Form on Half Completion

---

WebHostLib/options.py

This fixes a bug causing values on the options pages to sometimes display as blank fields if a preset was chosen which was defined in a particular way
Tested locally by running WebHost

Fix options pages sometimes displaying blank values in form fields

---

Options.py

The tooltip for `ProgressionBalancing` had awkward spacing and did not match the format used in any of the recently-PR'ed option docstring changes for worlds, so this changes that. Also removes the only instance of "not local".
Reading, WebHost.
->
->

Docs: Making option description more readable and accurate

---

worlds/yugioh06/__init__.py
worlds/yugioh06/rom.py

When a player has the option "ocg arts" enabled and the another player doesn't, the patch file of the player that has it not enabled ends up being broken. Inside the archipelago.json is a file listed that doesn't exist, that entry needs to be removed for the patch to work again.
This fix prevents the two players affecting each others procedure patch.
Generated multiple games that would reproduce the error.

YGO06: prevent multiple players affecting each others procedure patch

---

worlds/pokemon_rb/regions.py

When a player has the Exp. All removed and has Key Items Only, the filler replacement item for the Exp. All is never added to the itempool. Previously, a "Nothing" item would be created, now a filler item is made. Worth noting, a filler item was already created when Exp. All was set to Start With, so this is just adding that behavior to the Removed case. The Exp. All is a progression key item, so nothing changes in this if statement when it is randomized.
Generations and checking the spoiler log for Nothings and filler

PKMN R/B: Fixing Key Items Only + Removed Exp. All

---

worlds/landstalker/Hints.py
worlds/landstalker/Locations.py
worlds/landstalker/Regions.py
worlds/landstalker/Rules.py
worlds/landstalker/__init__.py

This fixes generation bugs reported in the following Discord threads:
https://discord.com/channels/731205301247803413/1199949415373344798
https://discord.com/channels/731205301247803413/1225442951447187456
These issues were caused by three different causes:
- World hint system referencing location for progression items whereas in some cases, progression items appear to have no location on generation end (that's weird, but at least Landstalker won't try to hint them anymore)
- World was using `can_reach` in an unreliable way, those were replaced by events
- There was one case of `multiworld.random` being used instead of `world.random`. This was not reported but I preferred to fix it.
This was tested by generating hundreds of seeds with various option combinations each.
Not a single one …

Landstalker: Fixed rare generation issues

---

worlds/alttp/Rom.py

When Triforce Pieces are in start inventory instead of crashing the triforce pieces required counter is decreased.
Only that a yaml with
```yaml
start_inventory:
{"Triforce Piece": 10}
```
no longer crashes gen.

LttP: allow Triforce Piece as start inventory item

---

WebHostLib/static/assets/trackerCommon.js
WebHostLib/templates/multitracker.html
WebHostLib/tracker.py

checks if the tracker is visible before updating  it.
If the tracker becomes visible after a missed update it instantly updates
with logging.

WebHost: update trackers only if they're visible.

---

worlds/pokemon_rb/items.py

HMs are suffixed with the name of the move, e.g. "HM02 Fly". If TM move are randomized, they do not have the move name, e.g. "TM02".
If someone hints for an HM using the just the number, the fuzzy matching sees "TM02" as closer than "HM02 Fly", and in fact sees it as close enough to not ask the user to confirm, leading them to waste hint points on non-progression item that they didn't intend.
Emerald already [does this](https://github.com/ArchipelagoMW/Archipelago/blob/main/worlds/pokemon_emerald/items.py#L62) for this reason, adding the same for RB.
Hinted for an HM via `!hint HM02` before and after this change.
Before:
After:

Pokemon RB: Add an item group for each HM to improve hinting

---

WebHostLib/options.py
test/webhost/test_option_presets.py

[Issue 3439](https://github.com/ArchipelagoMW/Archipelago/issues/3439)
OptionLists, OptionSets, and ItemDicts can all display just fine on the new WebHost but the preset test still prevents them from being used in presets despite them working just fine. This changes the test and also simplifies explicitly including Choice, Toggle, Range, and NamedRange by just including NumericOption
Unit Tests and modifying worlds to use these new options, seeing the test go from failing to passing and seeing WebHost no longer throw errors from these being in presets.

WebHost: Allowing options that work on WebHost to be used in presets

---

worlds/tunic/__init__.py
worlds/tunic/er_scripts.py
worlds/tunic/options.py

Fixes plando connection + seed groups support. For appending things in the new plando connections system, I need to add `.value`.
Fixes seed groups. For getting whether a custom string is used, I now need to compare to `EntranceRando.options.values()` instead of just `EntranceRando.options` like before.
Fixes a Universal Tracker support issue. If fixed shop is off in the yaml, it removes the Zig Skip Exit portal from the portal map. So if the slot has fixed shop on, and the yaml doesn't, it would mismatch. Since this option does not get loaded into slot data (since it is unnecessary for trackers), I had to write a quick thing to fix that up.
Many test gens with weird yamls. Lots of triggers, plando connections, etc.
N/A

TUNIC: Fix plando connections, seed groups, and UT support

---

Utils.py

During #1933, I defined a custom `__init__` for `Utils.KeyedDefaultDict` to make PyCharm happy when creating a new dict, but forgot to add a `*args` param, which was only utilized in the tracker code, so I missed in testing. This adds it and fixes the 500 server error that gets displayed on multitracker.
Ran WebHost before and after.
Before:
After:
:P

Utils: Fix mistake made with `KeyedDefaultDict` from #1933 that broke tracker functionality.

---

worlds/lingo/test/TestMastery.py

Test failures because `Orange Tower Seventh Floor - Mastery` was renamed to `The Fearless - MASTERY`
Unit Tests.

Lingo: Fixing KeyError from name change

---

worlds/_bizhawk/context.py

If a client handler sets `finished_game` on the context and then the client is disconnected and reconnected to a new slot or server, it automatically sends the game complete update.
This resets it to `False` any time the ROM hash changes with the expectation that a game handler will be able to re-detect being in a finished state.
Wasn't

BizHawkClient: Reset `ctx.finished_game` if ROM hash changes

---

worlds/tunic/rules.py

For NMG logic, now includes ice grappling into the elevator hole to get to gauntlet. I don't know who is so eager to get to gauntlet that they would do this, but this is for you, weird guy.
https://discord.com/channels/731205301247803413/1224388891948093540/1247356605465362434
And also running gen and it genning, and running tests.
N/A

TUNIC: Add ice grapple logic to get to gauntlet

---

worlds/kh2/Options.py
worlds/kh2/__init__.py

* [Start Inventory error](https://discord.com/channels/731205301247803413/1236770508360388768)
* * You could not include more than one of various items in `start_inventory` because `item in A or B` evaluates as `(item in A) or B`
* [Custom Item Pool error](https://discord.com/channels/731205301247803413/1090817012416118815/1246841288708325458)
* * Only [certain items](https://github.com/ArchipelagoMW/Archipelago/blob/main/worlds/kh2/__init__.py#L216C57-L216C92) actually have an effect in the CustomItemPool option, however they are all displayed on WebHost. This adds a `valid_keys` argument and removes `verify_item_name = True` as that's already the default.
* Typos
* * WebHost showed "CoR Skip Toggle.:"
* * Output showed " [...] cannot have more than X of itemChanging the amount [...]" …

KH2: Fixing Start Inventory bug, limiting CustomItemPool keys, fixing two typos

---

docs/options api.md

Fixes an incorrect assertion on the ordering of option groups and adds detail on the two auto generated groups as well as how you can customize them.
:eye:

Docs: Add detail on customizing the forced groups

---

worlds/hk/Options.py

per extractedData pool_options, only 20 eggs are created by default, so if a random filler egg isn't generated 21 max egg costs can be unreachable
could be updated when/if tuk check adds an egg to the default pool 
wasn't

HK: lower max egg cost

---

inno_setup.iss
worlds/LauncherComponents.py
worlds/__init__.py

Running Launcher with an APWorld will now install that APWorld. On Windows this can be triggered by double click an .apworld file.
On Win10.
Before:
After:

Launcher: handle apworld installation

---

WebHostLib/requirements.txt

flask - should only be bug fixes - [all commits](https://github.com/pallets/flask/compare/3.0.0...3.0.3)
werkzeug - flask dependency, adding to the list to force a security update (that shouldn't really matter for us)
waitress - [release notes](https://github.com/Pylons/waitress/releases/tag/v3.0.0) look somewhat safe - [all commits](https://github.com/Pylons/waitress/compare/v2.1.2...v3.0.0)
flask-caching - looks safe - [changelog](https://github.com/pallets-eco/flask-caching/blob/master/CHANGES.rst)
flask-compress - adds zstd, should be fast (we may have to bench and tweak options), but uses more memory than zlib - [all commits](https://github.com/colour-science/flask-compress/compare/v1.14...v1.15)
flask-limiter - only bugfixes - …

WebHost: update dependencies

---

.github/workflows/unittests.yml
MultiServer.py
WebHost.py
WebHostLib/customserver.py
test/hosting/__main__.py
test/hosting/client.py
test/hosting/generate.py
test/hosting/serve.py
test/hosting/webhost.py
test/hosting/world.py

* Fixes various things in MultiServer and customserver:
* auto-save thread could in theory run forever
* auto-save thread could overwrite save (in practice, the room timeout is >1min, so this won't do anything)
* `/exit` would not cleanly shutdown, because cancelling a task raises one level higher
* Shutdown rooms would not free memory because they are never awaited / `.result()`ed
* Exceptions could be hidden (same reason as above)
* Fix data package not being consistent (with *_name_groups)
* Ctrl+C on autohoster would not save rooms
* Add some type hints that helped while writing the code
* Add test for the above, run with `python test/hosting`
* Add CI for the test
* I added a test util and added that to CI
* rolling on webhost
* ~~verifying (and fixing) that autohoster saves on …

MultiServer, customserver, CI, Test: Fix problems in room hosting and test/simulate it

---

.gitignore

https://github.com/ArchipelagoMW/Archipelago/pull/3472 made a new `custom_worlds` directory and didn't gitignore it
git status

Core: gitignore custom_worlds

---

Launcher.py
typings/kivy/uix/boxlayout.pyi
typings/kivy/uix/layout.pyi
typings/schema/__init__.pyi
worlds/LauncherComponents.py
worlds/__init__.py

I saw this comment: https://github.com/ArchipelagoMW/Archipelago/pull/3472#pullrequestreview-2100092971
New buttons appear in Launcher when you install apworld.
There are probably still some things that don't work without restarting the Launcher, but this covers a lot of what players will want to do.
- prepared a new `button.apworld` with nothing but a new component button
- cleaned out template yaml directory
- cleaned out lib directory (subversion dependencies)
---
- run `Launcher.py`
- This window stays open for all the remaining steps here. It is never closed.
- drag `button.apworld` onto Launcher window
- see button appear
- press button
- see effect of button (`print` to console)
- drag `ff6wc.apworld` onto Launcher window
- drag `subversion.apworld` onto Launcher window
- press …

Core: hot reload components from installed apworld

---

worlds/tunic/er_rules.py
worlds/tunic/rules.py

Neither of us really remember why we put this rule in the first place, and think the other person convinced them to do it. So we're removing it, since it's really unnecessary.
It wasn't -- we are removing a rule, testing seems very unnecessary here.
N/A

TUNIC: Remove rule for west Quarry bomb wall

---

worlds/bomb_rush_cyberfunk/__init__.py

"Pyramid Island: Polo graffiti" is not supposed to ever get skipped. Oops.

Bomb Rush Cyberfunk: Fix missing location

---

worlds/hk/Options.py

adds schema to validate plando charm costs
just ran generations,
3 charms set to 0, gen'd as expected
each failed as expected: with a typo, with a negative cost, with too high a cost

hk: adds schema to validate plando charm costs

---

WebHostLib/templates/weightedOptions/macros.html

See title.
Run locally and tested that weighted-options pages with Choice and TextChoice options whose defaults' were "random" loaded properly.

Fix weighted-options page crashing if a Choice option's default is "random"

---

WebHostLib/api/__init__.py
WebHostLib/api/datapackage.py

Adds /api/datapackage/<checksum> which may be useful if we want to add  /api/tracker stuff and return raw data, possibly has other uses.
Locally, in which I realized not all checksums from currently loaded worlds can be accessed, as only datapackages that have been generated with, or hosted with, exist. Then I came to the follow up realization, that that doesn't matter, as the only time something would request that checksum is when it's hosted in some way on that website, which means it will be in the DB.

WebHost: allow getting checksum-specific datapackage via /api/datapackage/<checksum>

---

worlds/hk/Items.py

because of extractedData labling, split movement items weren't in the 'skills' category, this adds all movement to skills appropriately 
added some prints before and after and imported the class in a shell, visually confirmed that the only things added to the group were the right/left/split movement items and that nothing was removed

HK: adds split movement items to 'skills' item group

---

test/hosting/webhost.py

The `/room/<room>` route can fail if autohoster writes to DB at the same time. This change will simply retry in hosting test if that happens.
Should fix the failed run
https://github.com/ArchipelagoMW/Archipelago/actions/runs/9421679862/job/25956273385?pr=3489
that was [posted on Discord](https://discord.com/channels/731205301247803413/731214280439103580/1248709441948356679)
Maybe we'd also want to add such handling to WebHost itself, but this is out of scope for getting hosting test to work.
Test still works.

Test: hosting: handle writes during start_room

---

worlds/__init__.py

loads frozen decompiled worlds again, like non-apworld supported worlds
With cx freeze 7.0.0 on python 3.11 on windows
Also needs https://github.com/ArchipelagoMW/Archipelago/pull/3224/ for full fix.

Core: load frozen decompressed worlds

---

Generate.py
Utils.py

inpsired by https://discord.com/channels/731205301247803413/731214249828941884/1248629204845596682, this ensures worlds are loaded after logging is initialized, so that load errors appear in the log. It also appends " (frozen)" to Python if we're operating in a frozen environment.
(Observe the option system spam being inside the log now.)
```
Archipelago (0.5.0) logging initialized on Windows-10-10.0.19045-SP0 running Python 3.11.5
P1 Weights: A Link to the Past.yaml >> Default A Link to the Past Template
P2 Weights: The_Witness.yaml >> Default The Witness Template
Generating for 2 players, 75984463335213314275 Seed 98538513751088280759 with plando: items, texts, bosses
AdventureWorld Assigned options through option_definitions which is now deprecated. Please use options_dataclass …
```

Generate: improve logging capture

---

CommonClient.py
NetUtils.py
data/client.kv
kvui.py
worlds/sc2/Client.py

Client command history
* When executing a command (ie enter a message starting with `/` or `!`) in the common client, the command gets saved to a history buffer.
* Pressing "up" fills in the text input with the previous command, up to a maximum of 50 commands
* Pressing "down" returns to newer commands
* Pressing "down" from the last executed command returns to the empty command (ie clears the text prompt)
* Pressing "down" when on the empty command doesn't clear history (ie this will only clear your text if you've already been scrolling through history)
* Executing a new command adds to the history and resets the history index to the empty command
Client command echo
* Executing a command (ie enter a message starting with `/` or `!`) in the common client will echo the command back to you …

Core: CommonClient: command history and echo

---

worlds/mlss/Rom.py

Removes an unnecessary if statement that would equate to false if Xp scaling was set to the minimum range of 0.
Generated a game with yaml option set to 0 for xp scaling and successfully patched a game.

MLSS: Fix for Xp scaling when set to 0

---

worlds/sc2/Client.py

After PR #1933 merged, it seems to have broken the custom `/received` command in the Starcraft 2 client. The root of the issue was that the item printout just used the default player ID of 0, but that's not considered an actual player by the decoder and it needs that information to translate a local item ID to an actual item name.
Ran `/received` from the starcraft 2 client with a start inventory and a few items collected from doing a mission. It now prints correctly and no longer returns a stack trace. Didn't test this with items that were collected by slots playing a different game, not sure if that's a potential issue.
None

sc2: Fixed sc2 client's /received command breaking after PR 1933 merged

---

worlds/musedash/__init__.py

Removes the regions for Muse Dash in order to gain a decent amount of performance for larger worlds.
Tests and checking the generation log to ensure nothing broke.
Performance testing
| Gen | Average Before | Average After |
|--------|--------|--------|
1 x 50 | 0.08304867998 | 0.06629044001 |
10 x 50 | 3.52350716 | 1.65648329  |
1 x 500 | 0.52350967 | 0.31642301  |
10 x 500 | 52.85262655 | 23.17679973  
Tests were not done with set seeds. As the performance difference was consistently large.

Muse Dash: Remove regions for a decent speed gain in generating worlds

---

worlds/_sc2common/bot/sc2process.py

Currently, when any SC2 instance quits, all of them get terminated. Every now and then  I want to run two missions at the same time, but that means timing them correctly to not have it close on me. This removes that frustration.
I kept to the "style" of the surrounding code. Though in my opinion this is in dire need of a cleanup, but that's beyond the scope of this PR.
By starting two missions, then closing one, then the other still worked.

SC2: don't close all SC2 instances when one quits

---

worlds/AutoWorld.py

Previously, this crashed because `typing.NamedTuple` fields such as
`group.name` aren't assignable. Now it will only fail for group names
that are actually incorrectly cased, and will fail with a better error
message.
I updated the DS3 beta to add options to a prebuilt group.

Allow worlds to add options to prebuilt groups

---

worlds/timespinner/Regions.py

Reviewing the spheres of an ongoing async showed that Timespinner is using `can_reach(Region)` in an Entrance rule without defining indirect connections, so they would often "miss spheres".
Did some test generations, including with GyreArchives enabled. Ran unittests.

Timespinner: add indirect connections

---

Fill.py

In #3261 a mark_for_locking callback crept in on prog fill on accident. 
It was not, though it is a revert to something that was tested.

Core: don't lock progression

---

.github/workflows/ctest.yml
.gitignore
_speedups.pyx
_speedups.pyxbld
intset.h
test/cpp/CMakeLists.txt
test/cpp/README.md
test/cpp/intset/CMakeLists.txt
test/cpp/intset/test_intset.cpp
test/netutils/test_location_store.py

Removes dependency on C++ for _speedups.
But Why? C++ adds extra dependencies that need to be loaded into the process and afaik only _speedup requires them at the moment. Also currently we also don't handle C++ exceptions that could occur. This change fixes both and saves some memory because it should always have less memory overhead.
Only pytest and a few benchmarks and tests on C level. I wanted to push this so we can discuss.

Speedups: remove dependency on c++

---

worlds/sa2b/docs/setup_en.md

Fixes a typo in the Linux portion of the SA2B setup guide that prevented the link from getting formatted correctly, it's now following proper markdown syntax.
Can view it rendering correctly when looking at it in the GitHub markdown preview, screenshot:

SA2B: Fix Incorrect Link Syntax in SA2B Linux Setup

---

WebHostLib/templates/weightedOptions/macros.html

This "add" button is part of a form, which causes it to submit the form, because the default type for a button is "submit", making this button completely useless (destructive even)
This PR changes the type of the button to "button", which causes it to not submit the form and just execute its normal effect.
(An alternative would be `event.preventDefault()` but that seems less clean to me, but also I'm not a HTML/JS dev)

WebHost: Fix "Add" button for custom option values causing a weird redirect

---

WebHostLib/templates/weightedOptions/macros.html

The default option value for the Old Man option in Pokemon RB is "Early Parcel"
To check for the default in `weightedOptions/macros.html`, we compare:
`option.get_option_name(option.default)|lower == name`
Problem:
`"Early Parcel"|lower != "early_parcel`
The underscore is missing.
Alterate fixes that I considered:
- `|lower|replace(" ","_")`
Things that I could do ontop of this:
- rename `name` to `readable_name` and assign `option.get_option_name(id)` to a new variable called `internal_name`. Bc either solution makes already long lines even longer.
Lmk if either of those are better / desirable
Before:
After:

WebHost: Fix default values that are 2 or more words in Weighted Options

---

Options.py
WebHostLib/templates/playerOptions/macros.html
WebHostLib/templates/weightedOptions/macros.html

As with my other two WebHost PRs, I have no idea if this is "structurally" the best fix.
Note: Just telling worlds to change the option names in `special_range_names` to what they want **does not work**. If any of the names in there contain capital letters, your yaml will never generate (unless you use the numeric values instead)
Before:
After:

WebHost: Fix Named Range displays on Player Options page

---

WebHostLib/templates/playerOptions/macros.html

Apparently in the big option website  revamp the rendering of option documentation diverged from how it is rendered to yaml. So this copy pastes and adapts the yaml  filters for webhost, so they look the same/similar.
localhost.
Before:
After:
YAML:

WebHost: fix option doc indent

---

Options.py
data/options.yaml

https://discord.com/channels/731205301247803413/731214280439103580/1250848259677618196
Some strings  like "6_2" may be dumped raw, which then get interpreted as for example 62 back. This runs it all through the yaml dumper, so if any special handling is needed it should get applied.
https://discord.com/channels/731205301247803413/731214280439103580/1250857822153867264
I have since moved the instructions from the template to the new function in Options.py, but it does the same thing,
As far as I know, nothing should change for currently supported games.

Options: fix yaml export corner case "6_2"

---

Options.py

An option's aliases are now stored as an attribute on the option class, for use by a world or tool that may want to see them.
Wrote some code that looks at an option's aliases field and it was able to successfully retrieve them. pytest still passes.

Core: Expose option aliases

---

worlds/pokemon_emerald/README.md

Information that used to be in here was moved into `docs/`. Version number being in here and CHANGELOG only really makes it a pain to keep them in line with each other.
N/A

Pokemon Emerald: Remove README

---

worlds/alttp/OverworldGlitchRules.py
worlds/alttp/Rules.py

As far as I could tell, overworld_glitch_connections is a direct copy of no_logic_rules, and in single-player no-logic both get run, creating duplicated connections. Those dupes then trip the cache's checker.
By seeing the gen no longer error and the playthrough looking correct. Which for no-logic is:
0: {}
I'd appreciate some no-logic players confirming this didn't break something unanticipated though.

LttP: fix single-player no-logic generation

---

worlds/pokemon_rb/__init__.py

Added require_pokedex, blind_trainers, and area_1_to_1 mapping, which would be helpful to the poptracker pack to more accurately reflect the checks available to players.
Generated a game with 10 games, and checked the spoiler log against the info in slot_data
No visual changes

Pokemon Red/Blue: Add new options to slot_data

---

worlds/witness/player_logic.py

In the last reworking of automatic postgame, I changed some stuff about how the victory location is dealt with in postgame.
There is a pretty major bug with it.
`handle_postgame` uses the victory location *before* it is actually set, so it just uses the default value every time, always acting like it's Challenge Victory.
This makes `shuffle_postgame` just not work correctly at all.
Considering this a blocker because a whole option just doesn't work and results in people having locations in their seed they don't want.
My base unit tests PR is not merged yet so I can't add a unit test for this yet, but I can make that property *not have a default value*, so it *errors* when it's not set

The Witness: Fix Shuffle Postgame always thinking it's Challenge Victory

---

Generate.py
test/hosting/generate.py
test/programs/test_generate.py

splits up  main and ERmain, which might be required for Universal Tracker to work again.
It also  allows deallocation of a few objects, as main().__locals__ can be cleaned up.
Both functions might also be in need of a better name,  maybe in a follow up PR?
I ran generate.

Generate: split ERmain out of main

---

worlds/ladx/__init__.py

LADX was requesting the ROM for the output in generate_output. This leads to some issues while generating. Now this part is moved to stage_assert_generate like it is done i.e. in ALttP and DKC3.
Removed any ROMs from the dev folder. Generated locally and observed that the ROM request comes in the same step like SMW.
Console shows that the ROM request is now similar to other games.

LADX: Moved ROM requirement from generate_output to stage_assert_generate.

---

worlds/tunic/options.py

Updates the description to use a custom one instead of the generic one, since the generic description includes `direction`, which Tunic ignores.
Reading, generating template yaml.
N/A

TUNIC: Update Plando Connections description

---

AdventureClient.py
CommonClient.py
UndertaleClient.py
WargrooveClient.py
Zelda1Client.py
worlds/alttp/Client.py
worlds/cv64/client.py
worlds/dkc3/Client.py
worlds/factorio/Client.py
worlds/kdl3/Client.py
worlds/lufia2ac/Client.py
worlds/sc2/Client.py
worlds/sc2/ClientGui.py
worlds/sm/Client.py
worlds/smw/Client.py
worlds/smz3/Client.py
worlds/yoshisisland/Client.py

Bug Report: https://discord.com/channels/731205301247803413/1249434122212872252
There are some code paths that attempt to lookup names prior to connection to the Archipelago server, and I foolishly used `lookup_in_slot` everywhere when I refactored for #1933. This caused some areas to raise an exception and not finish prior to queuing LocationChecks packets, causing a failure to sync local state with server (like in Factorio's case in the bug report).
This changes those methods to `lookup_in_game` as CommonContext-derived clients should have already set the game value, so this lookup for own-game items should work even while disconnected.
Ran before and after with a Factorio world that had a location checked prior to connection. The location did not resync before, but did successfully …

CommonClient: Use `lookup_in_game` instead of `lookup_in_slot` in case of own-game name lookup when disconnected from server.

---

worlds/ladx/LADXR/generator.py
worlds/ladx/Options.py
worlds/ladx/Rom.py
worlds/ladx/__init__.py

This PR contains a handful of refactors for LADX:
* It now uses the new options API, and most options access goes through named fields on the objects object rather than through getattr.
* Moved away from using `self.multiworld.random` or `per_slot_randoms` in favor of the world random field.
* Moved away from accessing other various fields through `self.multiworld`, such as the player's name.
* The world object is now passed to generateRom so that the various parameters can be accessed through it instead of having to be passed manually, since they are almost all members of the world class anyway.
* Fixed a couple of typos.
Ran 100 generations with random options. pytest continues to pass.

LADX: Converted to new options API (+other small refactors)

---

worlds/tunic/docs/en_TUNIC.md

Bush logic is weird, since there's many different ways past them. Some require progression items, some require items that are not currently marked progression, some require no items but require effort. Ultimately, the decision made was that they are not considered in logic, since they would force a sword or wand to show up basically immediately, especially in single player.
So, this just adds a note regarding it to the game info page that we can point at.
Reading
N/A

TUNIC: Add note about bushes to logic section of game info page

---

worlds/shivers/Rules.py

Adds missing indirect conditions
This was done based on discussion in the ap-world-dev channel and related to @NewSoupVi's PR https://github.com/ArchipelagoMW/Archipelago/pull/3552
Made sure generation works and ran tests.
Please note that @GodlFire (world maintainer) is on vacation for 3 weeks or so.

Shivers: Adds missing indirect conditions.

---

worlds/ladx/Options.py
worlds/ladx/__init__.py

Adding the option groups to the options page for LADX.
This PR is a separated part of #3541 which was a duplicate of #3542. So this one is an addition of the already merged #3542.
Starting the webhost locally and open the player options page. Also configuring and exporting configs, compare with a config from before the change and take a look if the result is the same.

LADX: Adding 'Option Groups' to the player options page.

---

worlds/doom_ii/__init__.py
worlds/heretic/__init__.py

In Doom II, the Megasphere (which was an item not in Doom 1993) is never added to the pool at all, despite already being present in AP's item list. In Heretic, the Torch is in a similar situation, not being added to the pool at all despite existing as a possible item.
Neither of these omissions seem to be intentional, and in fact I recall Daivuk stating in the past that the Megasphere in Doom II was completely forgotten about since so much of that is just copied from Doom 1993. So this PR aims to reintroduce these two items for a bit more added variety in multiworlds.
Also because I swear if I have to go through some of Heretic's darker rooms again without a torch--
Generating a multiworld with these changes, and making sure both items appeared and function correctly.
[Receiving a Torch …

id Tech 1 games: Reintroduce missing items

---

worlds/generic/docs/setup_en.md

Really simple change to point users to the Latest release page instead of the Releases page.  Saw a user accidentally download 0.3.6 because it was the last item on the page (they're accustomed to scrolling down to the bottom of the page in GitHub for the Assets section), and this change prevents that outright.
Was tested by opening a single link in my preferred web browser.

Docs: Change setup_en.md to use Latest releases page

---

worlds/messenger/rules.py

Fixes a missing rule on the double swing saws seal.
Wasn't, but there's no risk here. Only affects portal rando.

The Messenger: Fix missing rules for Double Swing Saws

---

worlds/oot/__init__.py

Adds all options to fill_slot_data that are worth tracking in a poptracker pack. 
This is aimed at providing information for the oot poptracker-pack for autofilling of settings within this pack.
Generated a few Solo OOT Seeds and connected to the Slot via poptracker and printed the received slotdata to the console

OOT: Adds Options to slot_data for poptracker-pack

---

worlds/AutoWorld.py

To load a 0.5.0 multidata you need a 0.5.0+ server. This was however not marked in our required versions.
I changed a value of a system that was hopefully tested long ago.

Core: update required_server_version to 0.5.0

---

inno_setup.iss

Fixes .apworld registration in Windows so users can double-click a .apworld to install it. Previously the registry entry for `shell\open\command` wasn't actually being added.
Created an installer with this inno_setup.iss change, and installed Archipelago. Observed `HKCR\Archipelagoworlddata\shell\open\command` is now populated in regedit. Also checked my file associations in Windows, .apworld is now associated with Archipelago. Double-clicked pokemon_crystal.apworld and it was copied into custom_worlds with a success message.

Installer: Fix .apworld registration

---

worlds/alttp/Rules.py
worlds/alttp/test/dungeons/TestThievesTown.py

Adds a missing rule for Blind's Cell.
Only generated to ensure no crash.

LTTP: Add Missing Blind's Cell rule

---

CommonClient.py

/received with prior /send would crash due to no key 0 in slot_info. This adds key 0.
locally

CommonClient: fix /received with items from Server

---

worlds/musedash/docs/setup_en.md
worlds/musedash/docs/setup_es.md

The current version of MelonLoader (v0.6.4) causes internal errors while loading dlls required for network connectivity. (DLL Not Found: System.Security.Permissions)
This rewrites the guides to explicitly mention installing v0.6.1
Checked rendering on webhost.

Muse Dash: Update installation guides to recommend installing v0.6.1.

---

worlds/musedash/MuseDashData.txt

Adds 6th anniversary songs.
Note: Territory Battles has not been updated yet. So will keep the same info as the last PR.
With tests.

Muse Dash: 6th Anniversary Song update

---

worlds/oot/__init__.py

Adds an item_name_group for keys.
There was discussion on which settings for OoT slow down gen, in the context of the big async. One of them was small key shuffle being set to one of the options that makes the small keys in your own world. Since there's potential of this option being meta'd off, I figure there should be a convenient way to make the keys local if you want them to be that is separate from the option.
Ran gen, did /item_groups
N/A

OOT: Add keys item_name_group

---

test/general/test_reachability.py

Same fix as #3520, but for an additional test. I looked through, and I think this is the only remaining test with this issue.
Wasn't, but it's the same fix as the prior PR.

Core: fix execnet error for test_default_all_state_can_reach_everything

---

WebHostLib/misc.py
WebHostLib/templates/hostRoom.html

* add Range= to log, making responses a lot smaller for massive rooms
* switch xhr to fetch
* post the form using fetch if possible
* also refresh log faster while waiting for command echo / response
* do not follow redirect, saving a request
* do not post empty body
* smooth-scroll the log view
* paste the log into the div when loading the HTML (up to 1MB, rest will be `fetch`ed)
* fix duplicate charset in display_log response
* on waitress
* on nginx + gunicorn
* with firefox, looking at developer tools to verify transmission is what i expect
* with chromium, looking at developer tools to verify transmission is what i expect
**Side notes:**
I really dislike the 2 spaces indentation, but I guess this is set in stone?
I feel like `scrollToBottom` is something I would want to paste into a …

WebHost: Better host room

---

docs/world api.md

Clarifying that locations are included in the list of things that shouldn't change after `create_items`
[Relevant discord chat](https://discord.com/channels/731205301247803413/1214608557077700720/1257378767286964280)
Viewed the `.md` in github's viewer.
just markdown, can preview the rich diff

Docs: Clarify docs for `create_items` stage

---

WebHostLib/misc.py

yielding from a generator function would raise the error outside of the try block. This opens the file before entering the generator.
Local webhost with waitress, starting a room and deleting the file. Seeing no errors being logged to console.

WebHost: Log: handle FileNotFoundError

---

worlds/witness/player_logic.py

Door shuffle logic just completely doesn't work right now because every door thinks it still needs every item it normally needs to open it
~~Please merge my [unit tests](https://github.com/ArchipelagoMW/Archipelago/pull/3328) lol~~
Tested:
With those unit tests I just mentioned

The Witness: Fix door shuffle being completely broken

---

worlds/tunic/er_rules.py
worlds/tunic/rules.py

There has been enough feedback about this that it's about time to add it, especially since people keep doing single player ladder shuffle.
Normally I would add the rule to the entrance, but for the er_rules, there are either 1 or 6 (default 6) entrances that lead to the shop, so it's probably better to just add the rule directly to the location.
Ran gen
N/A

TUNIC: Make the shop checks require a sword

---

worlds/sc2/ItemGroups.py

Fixing spurious item groups created by a typo.
Note this is already fixed in the sc2-next beta, looks like we just forgot to port the fix back to main.
Put a temporary printout of all item group names, verified "Abili", "Un", etc didn't appear in the list.
None

sc2: Fixing typo in itemgroups.py causing spurious item groups

---

test/webhost/__init__.py
test/webhost/test_api_generate.py
test/webhost/test_host_room.py

* Tests behaviour that was added in #3496 and would've found the mistake that was fixed in #3603
* Tests that only the owner can see the log and queue commands
* Moves flask app init for tests to a common place (and ignores failure from double init)
* Create 1 flask client per test rather than per class
* Enables DEBUG for those, which allows printing the server traceback on failure
* Fix some typing and a typo in test_api_generate
pytest, pytest-xdist

Tests, WebHost: add tests for host_room and minor cleanup

---

worlds/alttp/Rules.py

Adds missing logic for the bombable/bonkable wall before the Crystaroller room, which itself is just after the big key door so it was just added to the big key door logic.
Ran unit tests

ALTTP: Bombable Wall to Crystaroller Room Logic

---

worlds/zillion/client.py
worlds/zillion/gen_data.py
worlds/zillion/requirements.txt

an extension to the new option added in https://github.com/ArchipelagoMW/Archipelago/pull/3604
now includes the lower section of the base, including split rooms
plus a backwards compatibility patch for seeds generated before this option
zilliandomizer diff: https://github.com/beauxq/zilliandomizer/compare/v0.8.0...v0.9.0
a few games generated and played from zilliandomizer and one from AP

Zillion: more rooms added to map_gen option

---

worlds/tunic/er_scripts.py

The event location for the Quarry Fuse event item was in the wrong region, making it incorrectly require a sword or wand to reach if you enter Quarry from either the portal, the shop, or the main entrance.
This is now fixed.
Test gens.
N/A

TUNIC: Fix event region for Quarry fuse

---

WebHostLib/customserver.py

GC seems to be lazy.
Adding a weakref with callback to ctx and to auto_save_thread and watching it **not** trigger before the change while there is no pressure, and then watching it actually trigger after the change whenever hosting a new room.
Side note: `gc.collect(0)` should be the cheapest variation and is already enough to find the two objects.

customserver: preemtively run GC before starting room

---

WebHostLib/customserver.py

Old code keeps ref to last started room's task and thus never fully cleans it up.
Looking at weakref pointing to `None` after the change.

customserver: fix minor memory leak

---

worlds/pokemon_emerald/rules.py

The coin case is a key item, but it's not progression like almost every other key item is, so it got mixed up in the rules. The rule shouldn't be applied conditionally with the `npc_gifts` option, it should always be applied. Key items are converted to events, so the location will always exist.
Generated with all 4 combinations of key items and npc gifts turned on and off.

Pokemon Emerald: Fix logic for coin case location

---

UndertaleClient.py

Fixed the error that when the client is opened outside of the archipelago folder, the patched folder would be created in there instead of the ap folder, which on windows ends up trying to create it in the system32 folder
Bug Report: https://discord.com/channels/731205301247803413/1148330675452264499/1237412436382973962

Undertale: Fixed output location of the patched game in UndertaleClient.py

---

worlds/raft/Options.py
worlds/raft/Rules.py
worlds/raft/__init__.py

This moves Raft off of the old deprecated Options API and on to the new Options API to address #3284 
Manually. Made sure logical values were still being respected via debugging during generation. Ran with multiple different options.
N/A

Raft: Move to new Options API

---

setup.py

Update cx_freeze to latest version
supersedes ArchipelagoMW/Archipelago#3405
Generate and TextClient on AppImage with py3.8 and py3.11.
Windows was not tested,

Core: Update cx_freeze to 7.2.0 and freeze it

---

kvui.py

Previously, the Common Client would accept kivy markup syntax from user input. This is now fixed by escaping markup for plain text nodes.
This should also fix these issues:
- https://github.com/ArchipelagoMW/Archipelago/issues/2741
- https://github.com/ArchipelagoMW/Archipelago/issues/2742
- https://github.com/ArchipelagoMW/Archipelago/issues/2743
Ran the common client, and sent kivy markup to verify that it was properly escaped. I also ran !hint to make sure that text that is intentionally styled isn't messed up.

CommonClient: Escape markup sent in chat messages

---

worlds/stardew_valley/logic/bundle_logic.py
worlds/stardew_valley/logic/museum_logic.py
worlds/stardew_valley/logic/time_logic.py
worlds/stardew_valley/stardew_rule/base.py
worlds/stardew_valley/stardew_rule/rule_explain.py
worlds/stardew_valley/stardew_rule/state.py

The improves performances when generating with museum sanity. Here is why:
- Museum sanity rules make a heavy usage of `Count` rule, which is not very efficient at short-circuiting. 
- The `Count` rule was improved in #2984 (which ended up being merged with the 6.x.x branch). This improvement consist of grouping the equal rules. They are then only evaluated once, but count multiple times in the total.
- With 6.x.x, time logic was added to the museum rules, so museum locations are spread through spheres. However, the months were calculated as `float` and not as `int`. That slowed down the generation by a lot.  See benchmarks below for more visual details on that.
- `HasProgressionPercent` are only equal when they have the exact same number, which never happen with the months calculated as …

Stardew Valley: Make sure number of month in time logic is a int to improve performance by ~20%

---

kvui.py

makes the kivy connect button do the same username forgetting that /connect does to fix an issue where losing connection would make you unable to connect to a different server
With two servers that have different valid slot names
* connect to server1, enter slot name when prompted
* close server1 to simulate the server losing connection for any reason
* enter server2 server address (with just host:port), click Connect button
* notice without the fix the connection is rejected for invalid slot (even without a prompt)
* notice with the fix the client prompts for slot name and can connect without issue after inputting it

CommonClient: fix bug when using Connect button without a disconnect

---

worlds/shorthike/Locations.py

Fixes the Boat Rental not being considered a 100 coin purchase. (missed when adding new options)

A Short Hike: Fix Boat Rental purchase being incorrectly calculated

---

worlds/stardew_valley/data/locations.csv

Stardrop Tea, even though it's a tea, is not an artisan good, is not in the shipping collection tab and shouldn't be on the list of checks for shipsanity full shipment. This was a simple oversight.
Automated Tests

Stardew Valley: Removed Stardrop Tea from Full Shipment

---

worlds/stardew_valley/rules.py

In-game, the gourmand frog gives you its 3 tasks in order, like the raccoons, so this adds a logic rule for completing previous tasks in order to reach the following one.
This is the very simple fix. A more complicated design is being worked on to allow randomization of the gourmand frog tasks, which would make for a more "randomizer" experience, but it won't come right away and we don't have a timeline. So in the meantime, this avoids potential softlocks
Automated Tests

Stardew Valley:  Add gourmand frog rules for completing his tasks sequentially

---

worlds/dlcquest/__init__.py
worlds/dlcquest/option_groups.py

Added option groups to DLC Quest, to categorize options in a more intuitive and user friendly way. It will also hopefully keep unsuspecting users away from the more evil options available in this game
It's just option groups

DLC Quest - Add option groups to DLC Quest

---

worlds/ladx/__init__.py

Adding an item group for instruments, because LADX players deserve nice things.
I did a test gen using the LADX template on my branch, then ran a local server, connected a client to it and ran `!hint Instruments` with a hint cost of 0. This was the outcome.
It does not.
I know LADX doesn't have a maintainer at this point, so I understand if this PR ends up being a low priority, but I do believe it would benefit players quite a lot, and it's a pretty small change. Thank you in advance!

LADX: Add an item group for instruments

---

.gitignore

This replaces `.code-workspace` with `*.code-workspace` in the root `.gitignore`
VSCode, these days, by default, names the workspace file `foldername.code-workspace`. This change will make life a little easier by no longer requiring vscode users explicitly save the workspace as `.code-workspace`
This will enhance developer experience. It is unlikely that adding a wildcard to .code-workspace would negatively affect or break the project. It was verified that there wasn't any other files that contained ".code-workspace" in the github project.

Project: Add .code-workspace wildcard to gitignore

---

worlds/subnautica/rules.py

Two instances of using the deprecated (soon to be removed) method of getting options.
Generations and comparing spoilers on the same seed before and after.

Subnautica: Fix deprecated option getting

---

worlds/pokemon_rb/locations.py

When the Route 4 item location region was changed, the nearby hidden item should have been changed as well. This does so.
Not

Pokémon R/B: Also fix Rt 4 Hidden Item

---

worlds/stardew_valley/data/items.csv
worlds/stardew_valley/data/locations.csv
worlds/stardew_valley/items.py

We used to give the Fairy Dust recipe as a freebie even if a player excluded ginger island, but in an attempt to make Stardew more open to very low-check settings in the future, it has now been removed when it should not be accessible, since it is a ginger island recipe in the base game.
Automated Tests

Stardew Valley: Make Fairy Dust a Ginger Island only item and location

---

docs/apworld_dev_faq.md

A workflow was discussed about devs with stale docs knowledge referencing the FAQ first, since we don't want to replicate data this just adds a header to inform/remind devs of what other docs they can check for their answers as well.
reading

Docs: Add header to FAQ doc referencing other relevant docs

---

worlds/lingo/__init__.py

Lingo shows a warning (in a solo game) or throws an exception (in a multiworld) if a slot does not have progression. Door shuffle, color shuffle, and sunwarp access all contribute progression items to the world. Disabling pilgrimage also adds a progression item, but it is not taken into consideration here.
Previously, this check erroneously looked for sunwarp shuffle, not item-locked sunwarp access. This change fixes that. Additionally, item-locked sunwarp access now must be combined with the Pilgrimage victory condition in order to pass the progression requirement.
pytest and test generations.

Lingo: Changed minimum progression requirement

---

worlds/stardew_valley/__init__.py
worlds/stardew_valley/regions.py
worlds/stardew_valley/test/__init__.py
worlds/stardew_valley/test/rules/TestBundles.py
worlds/stardew_valley/test/stability/StabilityOutputScript.py
worlds/stardew_valley/test/stability/TestStability.py
worlds/stardew_valley/test/stability/TestUniversalTracker.py

This fix 
- Universal Tracker when used with Stardew Valley. This however only work with seeds generated with this fix. 
- The stability of the entrance randomizer, which could generate different layout when playing with mods.
The fix in itself is pretty simple. Instead of using the seed provider by the multiworld, a new seed is generated and saved in the slot data. Then the saved seed is reused to generate with UT. 
Note that there is a limitation to this fix. The generation and the player need the same version of the apworld (which should usually be the case). If someone is outdated, the random might end up in a different state. For instance, you will not be able to track a 5.x.x game if you have 6.x.x installed.
Unit test, and also generated a couple seed to confirm it works. Compared …

Stardew Valley: Properly support Universal Tracker

---

Main.py

If a location's `progress_type` was set to `EXCLUDED` and it was in a user's `priority_locations`, it would end up prioritized. In contrast, if something is in both `exclude_locations` and `priority_locations`, it ends up excluded. This makes it so that dev/world-excluded locations stay excluded and are removed from `priority_locations` (matching the behavior of using both `excluded` and `priority` through user-facing options) and a warning is logged if this overrides a user's `priority_locations` option.
This also simplifies part of an exception that could not be reached because of an earlier [key verification exception](https://github.com/ArchipelagoMW/Archipelago/blob/7058575c9502a4a35bb8e75fae767f2269c576c4/Options.py#L796) with [LocationSet key …

Core: Make excluded locations and priority locations excluded and remove unreachable code

---

worlds/tunic/__init__.py

Was still using the old version of the option call for plando connections in a couple spots, those are now adjusted to use the new system.
Test gens.
N/A

TUNIC: Update plando connection option call to use options API

---

worlds/smz3/__init__.py

Re-classifies the items in SMZ3's nice item pool from filler to useful. As a result, the extra swords, bottles, and the like are excluded from the Ganon's Tower junk fill.
Generated 30 each of 1, 2, and 3-player SMZ3 multiworlds with default settings before and after the change. None of the worlds after the change had swords, silver arrows, or any other nice item in GT.
As a secondary observation, the multiplayer games before the change had significantly more useful items per player in GT than the single player games:
- 1 player: 0-4, average 2.23
- 2 players: 14-29, average 22.07 (11.03 per player)
- 3 players: 33-51, average 42.60 (14.20 per player)

SMZ3: Use useful item classification for nice items

---

worlds/factorio/data/mod_template/control.lua

Fixes nil value related crashes where a player happens to attempt to run /ap-get-technology from within the game itself. (This is a potential source for denial of service on public Factorio Archipelago servers (player runs /help, sees various commands, then runs /ap-get-technology out of curiosity))
Run /ap-get-technology by itself, and run /ap-get-technology [known tech or trap name] from within the game.

Factorio: Fix ap-get-technology nil value crashes

---

worlds/stardew_valley/data/locations.csv

It was mentioned to me that, in game, Moss is a "resource" (like wood), not a forageable or a crop. So it made no sense to have it in shipsanity crops. I just removed that flag
Automated tests

Stardew Valley: Take shipsanity moss out of shipsanity crops

---

WebHostLib/options.py
WebHostLib/templates/playerOptions/macros.html
WebHostLib/templates/playerOptions/playerOptions.html

If a NamedRange has a `special_range_names` entry outside the `range_start` and `range_end`, the HTML5 range input will clamp the submitted value to the closest value in the range.
These means that, for example, Pokemon RB's "HM Compatibility" option's "Vanilla (-1)" option would instead get posted as "0" rather than "-1".
This change updates NamedRange to behave like TextChoice, where both the select dropdown and the additional input element for custom values get posted with the form.
This uses a different suffix of `-range` rather than `-custom` that TextChoice uses. The reason for not just reusing `-custom` is we need some way to decide whether to use the custom value or the select value, and that method needs to work without JavaScript. For TextChoice this is easy, if the custom field …

WebHost: Fix NamedRange values clamping to the range in player-options

---

worlds/bomb_rush_cyberfunk/Rules.py

This doesn't happen on glitchless logic because of entrance rules, but (most) entrance rules don't exist on glitched logic.

Bomb Rush Cyberfunk: Fix Coil quest being in glitched logic too early

---

worlds/ffmq/__init__.py
worlds/ffmq/docs/en_Final Fantasy Mystic Quest.md
worlds/ffmq/docs/fr_Final Fantasy Mystic Quest.md
worlds/ffmq/docs/setup_en.md
worlds/ffmq/docs/setup_fr.md

Adding a French Setup Guide for Final Fantasy Mystic Quest and making some minor fixes to the English Guide.
n/a

Docs: Add FFMQ French Setup Guide + Minor fixes to English Guide

---

BaseClasses.py

missing local import of AutoWorld for the usage of call_all/call_single
generated before and after with 2 copies of a test yaml
[The Messenger.txt](https://github.com/user-attachments/files/16484439/The.Messenger.txt)

Core: fix missing import for `MultiWorld.link_items()`

---

worlds/generic/docs/advanced_settings_en.md

Changes the advanced yaml guide to match the new accessibility types
Reading

Docs: Missed Full Accessibility mention/conversion

---

worlds/tunic/er_data.py

I had missed a traversal requirement, which I'm surprised I never ran into any failures from it before, and I still haven't run into any failures with it from testing this -- only found out because I'm writing a direction pairing thing for ER, where that failure is much much more likely to show up.
Test gens in a branch with more features.
N/A

TUNIC: Fix missing traversal req

---

worlds/ror2/rules.py

The access rules for "\<Environment name> Chest n", "\<Environment name> Shrine n" etc. locations recursively called state.can_reach() for the n-1 location name, with the n=1 location being the only location to have the actual access rule set.
This patch removes the recursion, instead setting the actual access rule directly on each location, increasing the performance of checking accessibility of n>1 locations.
Risk of Rain 2 was already quite fast to generate despite the recursion in the access rules, but with this patch, generating a multiworld with 200 copies of the template RoR2 yaml (and progression balancing disabled through a meta.yaml) goes from about 18s to about 6s for me.
From generating the same seed before and after this patch, the same result is produced.

RoR2: Remove recursion from explore mode access rules

---

worlds/hk/Options.py
worlds/hk/__init__.py

makes grub hunt goal option that calculates the total available grubs (including item link replacements) and requires all of them to be gathered for goal completion
Note: this is dependent on game mod updates to enable the goal
generated with two HK worlds with both item links set to:
```yaml
item_links:
- name: Everygrubby
item_pool:
- Grub
replacement_item: Grub
link_replacement: true
```
and:
```yaml
item_links:
- name: Everygrubby
item_pool:
- Grub
replacement_item: Grub
link_replacement: false
```
and viewed the spoiler log / playthrough for issues

HK: add grub hunt goal

---

BaseClasses.py

The comment about self.access_rule computing faster on average appears to no longer be correct with the current caching system for region accessibility, resulting in self.parent_region.can_reach computing faster on average.
Generation of template yamls for each game (excluding sudoku) that do not require a rom to generate (52 total), generated with `python -O .\Generate.py --seed 1` (all durations averaged over 4 or 5 generations):
Full generation with `spoiler: 1` and no progression balancing: 89.9s -> 72.6s
Only output from above case: 2.6s -> 2.2s
Full generation with `spoiler: 3` and no progression balancing: 769.9s -> 627.1s
Only playthrough calculation + paths from above case: 680.5s -> 555.3s
Full generation with `spoiler: 1` with default progression balancing: 123.5s -> 98.3s
Only …

Core: Check parent_region.can_reach first in Location.can_reach

---

worlds/hk/__init__.py

Would cause generation to fail when generating with HK and another game.
Mistake in 6803c373e5ff.
Ran generation with one of every game before and after the patch

HK: fix iterating all worlds instead of only HK worlds in stage_pre_fill

---

worlds/doom_1993/docs/setup_en.md
worlds/doom_ii/docs/setup_en.md

As of August 8, 2024, Doom and Doom 2 have been merged into the same game ID on Steam. This updates the URLs for both games in their setup guides to point to the correct location.
Reading and clicking on links

DOOM, DOOM II: Update Steam URLs

---

worlds/tloz/__init__.py

`world: MultiWorld` -> `multiworld: MultiWorld`
Unit tests, a generation, and comparing spoiler logs before and after.

TLOZ: Removing world: multiworld

---

worlds/soe/__init__.py

Fixes randomly placed ingredients not being deterministic (depending on settings) and in turn also fixes logic not being deterministic if they get replaced by fragments.
Running `python Generate.py --seed 5555` twice and comparing output for a yaml that has
* Energy Core = Fragments
* Sniffamizer = Everywhere
* Ingredients = Random Ingredients

SoE: fix determinism

---

worlds/__init__.py

`ModuleNotFound: No module named 'worlds.None'`
Presumably as a part of the differences between `module_from_spec` and `load_module`, modules loaded with `load_module` do not actually populate `__package__` and instead have it as None. For 90% of use cases, the invalid package would not cause any issues. However, when an import occurs within a function (such as the import of a client from within a launcher subprocess), the invalid package would be checked and the import could not resolve.
Currently, this populates `__package__` to be the same as `__name__`. While this is not always the case with Python, our zipimport scheme only attempts to import the `__init__.py` of each world, where this will always be true.
Manually, by attempting to load Universal Tracker from within custom_worlds on …

Core: fix invalid __package__ of zipped worlds

---

worlds/tunic/__init__.py

People copy Tunic's implementation for Universal Tracker a lot, so I figured I should include a link to its docs, and a brief explanation of why we're just returning slot data in `interpret_slot_data`
Reading
N/A

TUNIC: Add note to Universal Tracker stuff

---

Main.py

makes start inventory from pool warn and fixes the itempool to match when it can not find a matching item to remove
lightly,
Generate a Lingo game with:
```
start_inventory_from_pool:
{"Black": 2}
```
see screenshots
and with `{"Black": 3}` once i noticed my math was off
and with `{"Black": 500}` once it was noticed that a previous iteration was popping from the entire itempool not just the new filler
previous error
new warning

Core: change start inventory from pool to warn when nothing to remove

---

Options.py

"Unused" is an assertion for which I have no direct evidence, but this code path has been [crashing on the first statement for 6 months](https://discord.com/channels/731205301247803413/731214280439103580/1272568415277678605) and noone's complained

Core: Remove broken unused code from Options.py

---

BaseClasses.py
Launcher.py

Changes an option getter in `BaseClasses` for ALttP
Changes an output to use decoded bytes for the filename instead
Finding a generation that hit the ALttP path and seeing it still work.
Printing `file` and `filepath` and seeing that filepath was `b'text'` instead of just `text`

Core: Two Small Fixes

---

test/multiworld/test_multiworlds.py

Missed a spot when renaming the accessibility options, in a test that gets skipped on main.
Ran the test that was being skipped.

Tests: fix the all games multiworld test

---

WebHostLib/templates/weightedOptions/macros.html

OptionLists do not display their proper default values on the advanced/weighted options page for a game, instead always selecting all members of the list. I literally just looked at the player options version of OptionList and other options in the file and saw that this one was different, this is truly a guess.
Loading WebHost and looking at Timespinner Traps and Ocarina of Time Logic Tricks options, including modifying their default values to see that the defaults were always shown.

WebHost: Maybe fix OptionList somehow?

---

worlds/tunic/options.py

Adds an off and on alias for the Entrance Rando option.
It is a TextChoice, which doesn't automatically convert off to turning Entrance Rando off, and doesn't automatically convert on to turning Entrance Rando on to a random seed, which is different than how most other option classes work. So if someone does `entrance_rando: off`, I'd imagine they wanted entrance rando to be off, and not set to the seed "off".
I didn't do a test gen, it's following the format of the other aliases so it should be fine.
N/A

TUNIC: Add off and on aliases for the Entrance Rando option
