BaseClasses.py, test/bases.py, test/general/test_reachability.py
Changes full/locations accessibility and all_state_can_reach_everything tests to require excluded locations to still be reachable.
Unit tests and a generations with every game with default options except for DKC3.
=> Core: Require excluded locations to be reachable with full/locations accessibility

worlds/tloz/ItemPool.py
The way the item pool was constructed involved iterating unions of sets. Sets are unordered, so the order of iteration of these combined sets would be non-deterministic, resulting in the items in the item pool being generated in a different order with the same seed.
Rather than creating unions of sets at all, the original code has been replaced with using Counter objects. As a dict subclass, Counter maintains insertion order, and its update() method makes it simple to combine the separate item dictionaries into a single dictionary with the total count of each item across each of the separate item dictionaries.
Fixes #3664 - After investigating more deeply, the only differences I could find between generations of the same seed was the order of items created by TLOZ. The issue appears to …
=> TLOZ: Fix non-deterministic item pool generation

Main.py
Saw this warning in PyCharm, uhm, yeah
Fixes bug instroduced in https://github.com/ArchipelagoMW/Archipelago/pull/2579
Custom changes to Lingo to change local, local_early and start_inventory_from_pool values, eventually hitting:
> AttributeError: 'MultiWorld' object has no attribute 'early_local_items'. Did you mean: 'non_local_items'?
=> Core: early_local != local_early

worlds/pokemon_emerald/rom.py
Dig is required to reach the three regis for legendary hunt, but the vanilla enforcement of access to Dig is the ability to find pokemon in the wild that are able to learn Dig; it isn't tied to any permanent items. So the apworld forces a static move tutor to always teach Dig, regardless of options, and access to that tutor is used for logic. But if a player sets their tutor compatibility to zero or near zero, they're effectively unable to use the tutor.
This sets a floor for how low the compatibility can be at 50% (or vanilla compatibility with the tutor's original move, Sleep Talk, which is nearly 100%).
If a player were to blacklist every wild pokemon except ~10 specific species that don't have evolution lines, it might be possible to get extremely unlucky and have 50% not be enough. …
=> Pokemon Emerald: Ensure dig tutor is always usable

BaseClasses.py
`MultiWorld.can_beat_game()` with no arguments would initially check if `self.state` is beatable, but then would create an empty state, `state = CollectionState(self)`, to sweep spheres from to determine if the game is beatable. The issue was that `self.state` and the new empty state could be different.
Currently, it seems that everywhere in Archipelago's codebase that calls `MultiWorld.can_beat_game()` with no arguments or `starting_state=None` has a `self.state` that only contains precollected items, so the new empty state happens to result in an equivalent state, but this should not be relied upon to always be the case.
This patch changes `can_beat_game()` to initially check if the new empty state is beatable instead of `self.state`.
This appears to be a bug introduced way back in …
=> Core: Fix incorrect default state checked in MultiWorld.can_beat_game

worlds/witness/rules.py, worlds/witness/test/test_weird_traversals.py
There was a valid in-game path for Tunnels Theater Flowers EP that was not considered valid by the logic, making logic more restrictive than necessary.
This path is Theater Exit -> Windmill Entry -> Tunnels Theater Shortcut.
This has been fixed.
Also did some general code cleanup around these functions.
I also added unit tests for this and Expert PP2, which are the two checks with required "pathing".
I plan to revamp the way the logic works for these soon, so this will be useful then as well.
=> The Witness: Fix Tunnels Theater Flower EP Access Logic + Add Unit Test for it (and Expert PP2)

worlds/mm2/rules.py, worlds/mm2/test/test_weakness.py
As it turns out, 4 * 4 == 16, not 28.
Ran the failing seed from <https://github.com/ArchipelagoMW/Archipelago/actions/runs/10471721213/job/28999592774?pr=3818>
=> MM2: fix Wily 5 Time Stopper rule

worlds/yachtdice/docs/setup_en.md
On the installation page, link to the latest release, instead of the page with all releases
=> Yacht Dice: setup: change release-link to latest

worlds/alttp/ItemPool.py
When triforce_pieces_mode is set to "extra", the number of Triforce pieces in the pool should be equal to the number required plus the number extra. The number available was being used in this calculation, instead of the number required. This is correcting that typo.
By generating a game of LTTP with triforce_pieces_mode set to "extra", 50 "required", 90 "available", 10 "extra" and talking to Murahdala to confirm how many pieces are in the item pool.
Before this fix, these settings produced a game with 100 available pieces. After, they produced a game with the expected 60 available pieces.
N/A
=> [LTTP] Fix a bug in Triforce Pieces Mode: Extra

worlds/witness/__init__.py, worlds/witness/entity_hunt.py, worlds/witness/locations.py, worlds/witness/player_logic.py
This one just kinda slipped my mind
(This won't "take care of panel sets" automatically, but that's just something I'm not currently supporting generation-side in general. The user *can* exclude every panel in a set individually and that will work.)
Also renames one of the variables to be more precise
Also removes an unused field
=> The Witness: Ban Excluded Panels from Panel Hunt

worlds/celeste64/docs/guide_en.md
=> Celeste 64: Typo

worlds/LauncherComponents.py
When double-clicking a beta Tunic apworld, I got the above message. I did not have the regular Launcher open, so I could see this being confusing for some users.
So, this PR updates the message that displays to hopefully be a bit clearer.
Reading
=> Launcher: Update message that displays when installing a custom apworld for a game in main

kvui.py
Because kivy needs `KIVY_DATA_DIR` to be redirected to the appropriate folder in the frozen install, importing kivy directly before kvui can cause crashes on some machines using the frozen install. This adds an assert to make sure this workflow gets caught in dev.
relevant issue: https://discord.com/channels/731205301247803413/1261299992564469780
did the same `from kivy.metrics import dp` import manual was doing that was causing the crash, it got caught on source
also ran without changes and the error did not trigger,
did not test on source but i can't imagine it does anything because __debug__ should be false
=> Kvui: assert kivy is not imported before kvui

worlds/pokemon_emerald/client.py
Sends changes to the player's current map to trackers via bounce packets.
Watched the network logs while changing maps.
=> Pokemon Emerald: Send current map to trackers

Generate.py
At some point, the `game_weights` object was made to be reused across several players when `weights.yaml` is being used. This breaks plando items, as plando items expects a unique object per player while the same object would be stored per player.
Tested weights.yaml with plando items that would fail before this change. (The plando still fails as it places items into invalid locations, but it fails with the proper FillError).
=> Core: deepcopy plando items

worlds/alttp/Rules.py
A missed accessibility update. Found with https://github.com/search?q=repo%3AArchipelagoMW%2FArchipelago+%22accessibility%5B%22&type=code
Made a yaml that hit this code path and removed the `locations` alias, which threw an error. Checked that the code path is still hit properly using full instead
=> ALttP: Fix accessibility (locations -> full)

worlds/alttp/__init__.py, worlds/alttp/test/options/test_dungeon_fill.py
I make bug good. Fixes the own_dungeon option for various lttp dungeon items not being placed in any dungeon instead of in the player's dungeon.
Generated a few seeds before and after the change and wrote unit tests to cover it.
=> LTTP: fix own_dungeon option

worlds/pokemon_emerald/client.py
As mentioned in #3726, using slot and tag creates a union, not an intersection. Limiting it to slot is fine; game clients will just ignore it.
Watched a server with the network logged.
=> Pokemon Emerald: Fix map update sending to all trackers

worlds/ahit/Rules.py
The moderate logic for the Mafia Town Clock Tower Chest and Top of Ruined Tower with nothing, and for clearing Rock the Boat without Ice Hat were mistakenly using `add_rule` instead of `set_rule`, which was adding the condition of `and True` which had no effect.
This patch corrects these moderate logic rules to use `set_rule` instead.
A YAML was used with moderate logic difficulty and that act-plandos Rock the Boat onto the starting act and Barrel Battle onto the second act. The playthrough spheres in the spoiler were compared before and after. From additional generations with this YAML after the patch, both `Mafia Town - Top of Ruined Tower` and `Mafia Town - Clock Tower Chest` have been observed in sphere 1 of a playthrough as expected.
=> AHIT: Fix moderate logic rules using add_rule instead of set_rule

worlds/ahit/Rules.py
The `Time Rift - Alpine Skyline` region was incorrectly accessible from Alpine Free Roam without Hookshot Badge or Umbrella.
One of the two regions that connects to the `Time Rift - Alpine Skyline` region is `Alpine Free Roam`. The problem here is that `Alpine Free Roam` corresponds to the intro section of Alpine Free Roam, but the Time Rift is actually found in-game in what equates to the `Alpine Skyline Area` region.
The entrance connecting `Alpine Free Roam` to `Alpine Skyline Area` (`AFR -> Alpine Skyline Area`) requires the Hookshot Badge (and Umbrella if umbrella logic is enabled), but because the entrance to `Time Rift - Alpine Skyline` is placed in `Alpine Free Roam` instead, it was missing the hookshot/umbrella requirements.
The missing Hookshot Badge and Umbrella requirements …
=> AHIT: Fix Time Rift - Alpine Skyline entrance logic

worlds/apsudoku/__init__.py, worlds/apsudoku/docs/setup_en.md
Remove the "Options Page (External Link)" that just redirected to the Game Page (per [prior discussion](https://discord.com/channels/731205301247803413/731214280439103580/1255343193495441460))
Updated the setup guide:
- some small formatting tweaks
- updated repo URL to point to the Godot-based build which is the current release
- updated instructions based on the Godot-based client
Ran webhost locally to view the formatting
No more `Options Page (External Link)`:
Updated setup guide:
=> APSudoku: Update setup guide, remove extraneous options page link

worlds/pokemon_emerald/rom.py
When trainersanity is enabled, some trainers that would usually disappear under certain conditions are instead kept around. In one case, this resulted in the overlap of two NPCs whose presences are normally mutually exclusive, and the wrong NPC happened to be on top, making one trainer potentially missable.
This PR patches the position of the magma grunt underneath the old man to move him one tile to the right. This is a stopgap solution until an updated base patch, which already includes the fix, is pulled into here. Updating the base patch generally breaks backward compatibility, so I want to bring in as many changes at once in one update as I can.
Looked in a hex editor at the relevant address on main and this branch. It was `0A 00` before the change (as expected, the x coordinate is …
=> Pokemon Emerald: Move Magma Grunt

worlds/checksfinder/__init__.py
Appeasing mypy
`itempool` did not have a consistent typing since it went from a list of strings to a list of ChecksFinderItems. This just changes the name to avoid this typing error.
A generation and connecting to a world.
=> ChecksFinder: itempool naming/typing

worlds/tunic/__init__.py, worlds/tunic/options.py
Adding a note about plando items not playing nicely with entrance rando.
Plando happens after entrance rando pairs portals, so it can sometimes lead to inaccessible locations. Because it happens after entrance rando, I can't make entrance rando deal with item plando properly.
If there was a way to tell where an item would be placed before entrance rando happens, or of items were only allowed to be placed with logic with plando items, then it would be a lot better.
Since we're not allowed to modify regions and such after create_items, the only real solution here would be to disconnect and reconnect entrances during pre_fill, which would be an absolute mess and make this pretty difficult to maintain.
Reading
N/A
=> TUNIC: Add note about plando items to ER hint-creation failure error message

worlds/dark_souls_3/Items.py, worlds/dark_souls_3/__init__.py
We had been keeping a set of items and defining item equality, but item equality really only makes sense if you consider distinct IDs to be distinct items. But that means the set ends up having multiple copies of the same item, causing a bug where some items had the wrong upgrade level in the game.
This also removes the equality definition, which was only used by this one set.
I tested this locally with a seed that was previously known to be broken.
=> DS3: Explicitly track item equality by name when sending IDs

worlds/shivers/Options.py, worlds/shivers/__init__.py
This adds a new option that has not affect on generation and is purely for client side behavior.
This enables the player to select how collection affects their world.
I checked that the player option on webhost had the new options
=> Shivers: Add collect behavior option.

worlds/dark_souls_3/__init__.py
This fixed a bug that appeared when some locations in a group were excluded and others were not.
I ran some local generations with known-bad settings and seeds and verified that the error no longer occurs.
=> DS3: Don't return early in the location loop

worlds/dark_souls_3/__init__.py
A player could make a location DS3-excluded to allow Useful items. Thus, an item that was both DS3-excluded and AP-prioritized would have unfulfillable requirements (progression and not progression). This simply removes `allow_useful` locations from `priority_locations` to prevent this case.
Generations with `allow_useful` missables and prioritized "CD: Black Eye Orb - Rosaria from Leonhard's quest" (a missable location) and generations with `allow_useful` excludeds and a location in both `exclude_locations` and `priority_locations`.
=> DS3: Prevent prioritized+excluded locations

worlds/stardew_valley/logic/grind_logic.py
Owning a Mystery Box or a Prize Ticket isn't enough to get rewards from it. Mystery boxes must be opened at the blacksmith, and Prize tickets must be redeemed at the prize machine in Lewis's house.
With Entrance Randomization, these two areas are not always available. But they were missing from the condition when grinding these items. Now I added it
Note: You do **not** require these areas to own a mystery box or prize ticket, for checks like "Shipsanity: X". You only need access to claim these items to use the rewards from them, which at the moment includes very few things. The most notable one is the book "Friendship 101", which was the reason the bug was discovered.
Unit tests and local generation with spheres
=> Stardew Valley - Prize Ticket and Mystery Box grinding requires the abilty to redeem them

worlds/alttp/docs/plando_en.md
The default values for plando were changed. Also added that `world` can use a list of names. Couldn't figure out a way to update the example image in a way that it actually worked though, if anybody knows how, that would be great.
Reading.
=> ALttP/Docs: Correcting the plando docs

MultiServer.py, WebHostLib/customserver.py
* Fixes growing memory consumption of customserver because GC is too lazy and python won't give the memory back to the OS:
* switch from gc.collect(0) to gc.collect() - a recent change in customserver or MultiServer made the cyclic references too complex to be collected with gen=0.
* Run full gc after save thread stopped (at most every 2 seconds); this is typically the last reference to a room/context.
* Added debug logging to `Context.__del__` showing that GC does not return memory to the OS.
* Adds 2 asserts that would trigger if we were leaking futures that keep the context alive
By looking at console output.
=> customserver: fix memory leak

worlds/rogue_legacy/__init__.py
The client literally does not work when there are overlapping IDs. It crashes completely after connection, making the game unplayable.
https://discord.com/channels/731205301247803413/1279859793661788261/1279859793661788261
While overlapping IDs are not "officially supported" yet, this has unfortunately ruined many seeds in several **unsupported** asyncs, including one of mine, where the RL seeds just have to be straight up released through the server console due to an overlap between ALTTP and Pokemon Crystal IDs.
Phar is not currently intending to fix it until further notice:
https://discord.com/channels/731205301247803413/929585237695029268/1269684436853723156
=> Rogue Legacy: Raise Exception when there are overlapping IDs

MultiServer.py
UserError
```
/send_multiple 1000000000 Player1 Power Star
File "\Archipelago\MultiServer.py", line 1149, in __call__
return method(self, *command[1:])  # pass each word as argument
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "\Archipelago\MultiServer.py", line 2047, in _cmd_send_multiple
raise ValueError(f"{amount} is considered an unreasonably high number.")
ValueError: 1000000000 is considered an unreasonably high number.
```
=> MultiServer: put some limits in place

WebHost.py
allows --config_override just_generation.yaml
with 
```
SELFHOST: false
SELFGEN: true
SELFLAUNCH: false 
```
which in turn should make it a lot easier to make generation and room hosting into services that can be controlled via systemctl
locally
=> WebHost: config override

worlds/kdl3/__init__.py
Accidentally providing 96 animals and 95 locations to fill_restrictive, no wonder I was having problems.
Found a seed that failed with the "hack" removed, no longer fails.
=> KDL3: Account for additional animal in pool

worlds/messenger/connections.py
Removes an entrance that shouldn't be there. When I was testing out these pathings, this connection made sense. Turns out that it's actually wrong because there's a gate between the two areas with the switch being on the other side. The gates stay permanently open, but you can't get to it from the right side. The entrance is still technically valid, but it requires the region on the other side is reachable first at which point the entrance itself is redundant.
Re-genned a known seed where this caused an issue and checked the results were different.
=> The Messenger: remove an invalid entrance

worlds/pokemon_emerald/client.py
The constructor is the wrong place to initialize these variables because clients get instantiated once right after the class is defined, not when a game is found. This doesn't really matter for most users, because they'll only open the client once to connect to one slot in one room and then close everything down.
It did, however, result in a crash on someone running from source on Mac using Python 3.9 because the `wonder_trade_update_event`, an `asyncio.Event`, was created while the world was being imported, and then `await`ed in the game watcher loop, which is running in a different Python event loop. I didn't track down exactly where the new event loop is split off, but the reported error was pretty clear, and was resolved with these changes. It was always improper, it just worked …
=> Pokemon Emerald: Fix client crash on certain systems

docs/world api.md
I definitely don't feel like I wrote this in the best way, or in the best place, but it is a precedent that I think is necessary so we can treat it as "the law of the land" in discussions, instead of it being a secret thing that unsuspecting world devs stumble across at some point while reading a random discussion & are then told they need to change it, leading to confusion about why it is necessary and subsequently debate about whether it is necessary
I would like to save us all some emotional labor and time :D
=> Docs: Mention indirect_conditions and that they are a *hard requirement* (with a few sharp exception cases)

BaseClasses.py, worlds/AutoWorld.py, worlds/factorio/__init__.py, worlds/subnautica/__init__.py
Adds https://github.com/ArchipelagoMW/Archipelago/pull/1764 as a per-world-instance option, given we didn't find a more  performant option and  some devs would like to use it, it is now available  as opt-in
It also adds World.origin_region_name, for worlds that don't want to start in "Menu"
The two changes are somewhat related and would conflict seperately, so for now I lumped them together.
The original _update_reachable_regions_auto_indirect_conditions is a copy-paste with formatting changes, so that was tested in the PR 1764, the start name change I tested for this PR. It's a critical core functionality though, so additional testing is certainly welcome.
=> Core: Region handling customization

docs/options api.md
Adds some brief documentation on option visibility because this should exist. Also removes a reference to SpecialRange which doesn't exist.
👀
=> DOCS: Option Visibility and removing SpecialRange

worlds/hk/__init__.py
speed up collect, will be obsolete after #3786
considered just indenting it instead but whitespace changes are annoying
ran some tests (i haven't committed yet) and they ran faster
=> HK: speed up collect (a bit)

worlds/witness/entity_hunt.py
In `_get_next_random_batch()`, the `remaining_entities` and `remaining_entity_weights` lists were being constructed by iterating sets.
This patch changes the function to iterate a sorted copy of each set instead.
Generated with a fixed seed (`1`) before and after and observed that the same locations with the same items were present in the spoiler when generating with this patch, compared to before.
Yaml used: [jkxWitness.zip](https://github.com/user-attachments/files/16902284/jkxWitness.zip)
Even with this change, the locations are not always in the same order, so I'm not sure if that implies other issues.
=> The Witness: Fix nondeterministic entity hunt

BaseClasses.py
It no longer says Nothing items should be traps.
Reading
=> Docs: Update Trap classification comment

worlds/sc2/docs/en_Starcraft 2.md, worlds/sc2/docs/fr_Starcraft 2.md, worlds/sc2/docs/setup_en.md, worlds/sc2/docs/setup_fr.md
Adding the following in the English version of SC2 documentation:
- Instructions for custom hotkey
- Known issues with Starcraft 2 Archipelago
Enhanced the following in the English version of SC2 documentation:
- Goal description 
- Explicit that while all SC2 campaigns are supported, the player is required to play those he possesses
- The explanation of progress balancing in SC2
- Applied the 120 characters limit rule on the Markdown file
- Syncing the SC2 EN documentation with the SC2 FR documentation. 
By locally hosting the website, it was confirmed that the English setup and game page remains correctly rendered. 
None that are relevant.
=> SC2 EN/FR documentation update 

worlds/pokemon_emerald/data.py, worlds/pokemon_emerald/opponents.py, worlds/pokemon_emerald/pokemon.py
Uses `_replace` instead of rebuilding the class by passing in each property. If I was aware of `_replace` when this was written, I was at least under the impression that it's somewhat improper to use because of the leading underscore. But it's apparently the recommended solution for what's happening here.
Generated on `main` and on this branch with the same seed and all relevant randomization turned on and compared the file hashes of the resulting patched ROM. So these changes should all have been hit and resulted in the same values in the output.
=> Pokemon Emerald: Make use of `NamedTuple._replace`

Generate.py
make Generate handle slots without names defined better; fix existing code that seemed to want to handle missing names but was no longer functioning correctly
if there is a better solution than what the existing code was trying to do then i differ to that
https://discord.com/channels/731205301247803413/1273345114198118502
tested with the original provided yaml and with a copy that moved the slot without a name to the bottom of the yaml and confirmed with pdb that the args.name got created properly and defaulted to file name when name was missing
also tested with two slots missing name in the same yaml and saw it throw an error mentioning the duplicate names, not sure if that's the best error handling but it works enough for me
=> Core: Fix Generate's slot parsing to default unknown slot names to file name

worlds/rogue_legacy/Options.py
Technically, nothing. But it allows for https://github.com/ArchipelagoMW/Archipelago/pull/3530 which is soft-required for https://github.com/ArchipelagoMW/Archipelago/pull/3393. This changes the AdditionalNames option class into two classes (one for each type)
Unit tests, generations, and connecting to and playing games that use these options.
=> Rogue Legacy: Split Additional Names into two option classes

worlds/pokemon_emerald/__init__.py
Adds a new option value for slot data. The tracker already believed it was receiving this. Just got missed.
Generated a world and it didn't crash
=> Pokemon Emerald: Add normalize encounter rate option to slot data

CommonClient.py, worlds/_bizhawk/context.py
Makes use of the changes in #3297.
Also improves the typing of `CommonContext.make_gui`
Ran `BizHawkClient.py` and also opened it from the launcher.
=> BizHawkClient: Remove `run_gui` in favor of `make_gui`

worlds/mm2/rules.py
Currently, Air Shooter is allowed to logically defeat a boss if it does at least one damage. However, hit detection for Air Shooter is jank to the point its very easy to have shots completely phase through the boss, thus making the boss impossible without an energy refill. We just up the minimum to 2 so at least one shot needs to land properly.
Ran unittests.
=> MM2: fix Air Shooter minimum damage

worlds/osrs/__init__.py
Additionally, fixes a capitalization mistake in skill name parsing.
1. OSRS previously did not have a comment under the World declaration, so it would have had no description on the Archipelago Web Page
2. A capital letter was left in the string "Cooking" which would be compared with the lower-case skill name and therefore never return true, essentially putting all cooking tasks in logic regardless of training ability.
=> [OSRS] Adds Description to OSRS World

worlds/pokemon_emerald/client.py
When a client receives a wonder trade and tries to write it to the game's save data, it does a `bizhawk.write` when it should have done a `bizhawk.guarded_write` that protects against the save data moving (`guards["SAVE BLOCK 1"]`). If the save data does happen to move between the start of the game watcher loop and this write, it may corrupt a small part of the save data. Unfortunately, it's pretty likely that this small part includes the "items received" counter, so if it happens it will probably prevent the player from receiving any more items.
This adds the guard to the write, and then reworks the code a bit to cache the received trade so that it can keep trying to write it every game loop until it's successful.
Put two clients in a multi and traded between them. Everything worked as …
=> Pokemon Emerald: Fix unguarded wonder trade write

NetUtils.py
adds mappings for item classification colors to usable color codes for terminal/colorama output
ran the text client in a multi i'm playing in and saw colored text for prog/useful/trap items
=> Core: Add color conversions for colorama/terminal output

worlds/blasphemous/__init__.py
Two different bugs that resulted from these being done during `pre_fill`:
1. Plando could mess up any of these item placements, causing generation to fail with a far less-clear error in Blasphemous's `pre_fill` instead of a plando error.
2. This added "Thorn Upgrade" to `local_items` during `pre_fill`. This does not actually work, because `locality_rules` is called earlier and it also allows a player to put them in both `non_local_items` and `local_items` (with `non_local` taking priority due to the timing).
Generations using plando and option configurations that would hit these code paths. Also comparing spoilers before and after the changes.
=> Blasphemous: Move pre_fill to create_items

worlds/sc2/Client.py, worlds/sc2/ClientGui.py
Fixes display bugs in `/received` output in SC2 client
Launched the client, connected to a multiworld, ran `/received` and checked the output
Before:
After:
Co-authored by @Salzkorn (from a backported bugfix)
=> SC2: Fix /received display bugs

worlds/pokemon_emerald/client.py
Must've thought `ctx.finished_game` updated itself based on the server status. But it doesn't and that's not its purpose. So as long as the player is in the overworld and their save file has victory flag set, the goal status update will get sent once per watcher loop, between 2 and 3 times a second. The spam doesn't make any noise in most logs unless you log the network.
Connected to a server with the network on the server logged. Observed the spam, reset the server save data, changed branches, observed the goal get sent exactly once.
=> Pokemon Emerald: Prevent client from spamming goal status update

worlds/dark_souls_3/Bosses.py
This ensures that if Deacons is replaced with Yhorm, the Storm Ruler won't show up in these locations.
Generations
=> DS3: Mark the Archdeacon Set as downstream of Deacons of the Deep

worlds/dark_souls_3/__init__.py
This is the only case of an access rule requiring a location to be randomized to be applied. This was originally added due to the ways we handled excluded/missable/non-randomized locations in order to prevent unreachable locations, however, these methods have since changed and the conditional is no longer required.
This is technically a bug fix, since it adds the Lift Chamber Key requirement even when it isn't randomized. I say technically because the location would be excluded anyway, so it couldn't actually matter.
Every combination of missable and excluded locations with combinations of Lift Chamber Key, Leonerd's Garb, and the Black Eye Orb in `exclude_locations` and seeing that there were no unreachable locations. Also reading through the current code to see where/how these cases are …
=> DS3: Make Red Eye Orb always require Lift Chamber Key

worlds/messenger/portals.py
This fixes a few issues with portal plando. Portal exits were being naively appended to a list, despite that plando can be defined in any order and omit portals. Fixes an issue where on shuffle failure the mapping wasn't being cleaned up correctly due to the same indexing issue. Gives a much more clear error when the user provides invalid portal mappings. Cleans the parent regions of plando exits just like non plando shuffle does, so that having a plando portal to ToT won't give a different random portal to ToT etc.
A bunch of test generations and breakpoint debugging
=> The Messenger: Fix Portal Plando Issues

worlds/stardew_valley/presets.py
Accessibility has recently had a non-backward compatible rename in core, which has broken compatibility between 0.5.0 and main (upcoming 0.5.1). So I decided that I'd rather not have my apworld compatibility be reliant on that, and unexpectedly break like this sometimes.
There is no good way to make it compatible with both versions at once. So the next best thing is, not depending on it at all. Plus, these settings were never really critical for the presets anyway.
Test the main-based apworld on 0.5.0 to make sure it's no longer incompatible.
=> Stardew Valley: Remove Accessibility and progression balancing from presets

WebHostLib/misc.py, WebHostLib/static/styles/hostRoom.css, WebHostLib/templates/hostRoom.html, test/webhost/test_host_room.py
* add spinner to room command
* don't update room log while tab is inactive
* immediately update when switching back if timeout happened, which draws attention of the user
* don't include log for automated requests
* this was tested by failing the unit test xD
* refresh room also for re-spinups
* fixes https://discord.com/channels/731205301247803413/1283891621963763732
* and do so using javascript, if available, to avoid transmitting log
Running webhost locally
=> WebHost: Better host room v2

Generate.py, Main.py, WebHostLib/generate.py
yaml_output is meant to indicate that the options are outputted as yaml. It now outputs csv, so is no longer accurate.
I did an automatic rename across the project, it shouldn't fail, but no testing was done.
=> Core: rename yaml_output to csv_output

WebHostLib/api/__init__.py, WebHostLib/api/room.py
The old location is unexpected and easy to miss.
This simply moves the one endpoint to its own file and fixes some typing while we're at it.
Note: this changes `room` to `room_id`, so typing does not collide between the UUID and the actual room. This change should probably be made in the non-API routes as well, but there we'll need to fix calls to url_for().
* Opening the endpoint in a browser.
* `mypy --strict WebHostLib/api/room.py`
=> WebHost: move api/room_status out of __init__.py

worlds/osrs/__init__.py
Adding/Fixing the UT integration of OSRS
Currently UT support in OSRS works... except if you play with chunksanity (any chunk area can be the starting location)
in UT for any_bank starting location can be updated via the user changing their yaml, but for chunksanity, it requires then to receive a bank chunk connected to their accessible area network, and THEN UT will work
This PR puts the starting area in slot_data (will be useful for Digi when they add local tracker support anyway) and connects Menu to the correct starting location regardless of yaml settings
generate multiworld with chunksanity enabled, looked at spoiler log to confirm that a non-bank chunk got rolled, (HAM Hideout) then changed yaml to be a chunk nowhere near that rolled chunk (Wilderness)
Launched MultiServer and …
=> UT integration for OSRS to support chunksanity

worlds/kh1/Client.py
Fixes a bug where hints would be spammed if a player had released and collected items in KH1's synth shop.
Adds new commands that query the players slot data, allowing them to see what the particular slot's goal and other relevant settings are set to.
Hint spam: Created a multiworld with several players, confirmed that another players items were in KH1's synth shop, released and collected that player's items, and entered the synth shop to ensure the hints were sent but not more than once.
New commands: Tested several setting combinations and ran the commands while both disconnected and connected.
=> Kingdom Hearts: Fix Hint Spam and Add Setting Queries

worlds/hk/__init__.py
add race bool to slot data
wasn't
=> HK: add race bool to slot data

worlds/tunic/er_rules.py, worlds/tunic/rules.py
Adding logic for getting past those boxes, since we're assuming elsewhere that the player needs shop access to have bombs
Test gen
=> TUNIC: Deal with the boxes blocking the entrance to Beneath the Vault

worlds/tunic/er_rules.py
Forgot to add the Laurels as a viable way to get past the boxes in the previous PR, woops.
Test gen.
N/A
=> TUNIC: Add forgotten Laurels rule for Beneath the Vault Boxes

WargrooveClient.py, kvui.py, worlds/sc2/ClientGui.py
Intending for this to get in before #3934, this should allow clients to be cross-compatible between the two client versions. The main (currently-only) failure point for current clients on the KivyMD branch is the swap of GameManager.tabs and what types are accepted its children. As such, this abstracts away this behavior into GameManager itself such that clients need only call the function and provide the content for the tab.
Loaded up Starcraft 2's client, ensured that tabs worked correctly.
=> kvui: abstract away client tab additions

worlds/stardew_valley/content/unpacking.py, worlds/stardew_valley/data/artisan.py, worlds/stardew_valley/data/game_item.py, worlds/stardew_valley/data/harvest.py, worlds/stardew_valley/data/shop.py, worlds/stardew_valley/data/skill.py, worlds/stardew_valley/items.py, worlds/stardew_valley/locations.py, worlds/stardew_valley/requirements.txt, worlds/stardew_valley/test/stability/TestStability.py
Remove python 3.8 backported stuff
I ran the unit tests
N/A
=> Stardew Valley: Remove Python 3.8 backports 🎉 

BaseClasses.py
This is how it already works for locations.
Also update some other similar errors to be a bit more verbose
Tested: No
=> Core: Put an assert for parent region in Entrance.can_reach just like the one in Location.can_reach

worlds/bumpstik/__init__.py
Hazard bumpers were not specified as part of world completion, causing logic issues as reported [here](https://discord.com/channels/731205301247803413/1287853629461758035/1287853629461758035). This adds hazard bumpers to the world completion condition.
Unit tests run locally and on Github.
=> bumpstik: add hazard bumpers to completion

BaseClasses.py
use base collect/remove for item link groups
not in the slightest, not even sure what the __get__ part does to be honest
=> Core: use base collect/remove for item link groups

worlds/timespinner/Locations.py
I noticed a typo in the check name that was changed while playing a run (funny how I never noticed that before)
Test generated a seed and confirmed the typo was no longer present in the spoiler log.
=> Timespinner: Fix Typo in Download Location

worlds/sc2/Items.py
Fixes a bug that some non-vanilla items spawned when shouldn't
Generated a game without NCO. Turned all non-vanilla items off. Collected the game and checked items in the tracker. 
No
=> SC2: Fix item origins, so including/excluding NCO/BW/EXT items works properly

worlds/hk/__init__.py
Cleans up some outdated stuff in the slot data which was discovered due to #3971. Specifically,
* Updates a comment to be clear about its scope and correct in its content
* Removes very old backwards compatibility slot data - clients that old will not work with new generations and newer clients already don't read them anymore.
* Removes an unnecessary int cast
* Move a questionable `else` block into the related `try` block
Tested the client can connect and read slot data correctly before and after the change
=> Hollow Knight: Clean outdated slot data code and comments

worlds/sm64ex/docs/setup_en.md
Recent clientside changes (See: https://github.com/N00byKing/sm64ex/pull/6 and https://github.com/N00byKing/sm64ex/pull/7) made it so that loading an old save file will no longer have notable issues with a new multiworld. I removed anything from the setup portion of the guide referencing this and workarounds, as new builds made by following the guide will not have this issue. Additionally, I amended the FAQ item referencing this to mention that updating will permanently solve the issue.
I looked at the changes to the setup guide. The clientside changes have been extensively tested by myself and others over the past two months they've been fully implemented and publicly released, and all bugs specifically mentioned in this setup guide have been confirmed to be remedied.
=> SM64: Remove outdated information on save bugs from setup guide

worlds/generic/docs/plando_en.md
This is adding whitespaces to the example block of the Plando Guide so copying the textblock makes the Plando work correctly. Right now when this is copied, it will silently not work. After the update, it will work.
Also removed whitespaces from the first codeblock because Exempt-medic said it's actually wrong how it is right now. https://discord.com/channels/731205301247803413/731205301818359821/1282065216590581792
-
-
=> Adjusts Whitespaces in the Plando Doc to be able to be copied directly

CommonClient.py
adds more documentation to what CommonClient is doing and how you are expected to extend it
all descriptions are based on my understanding of the relevant code so correct me if i'm wrong / if there is better wording
reading
=> CommonClient: add more docstrings and comments

worlds/messenger/__init__.py, worlds/messenger/client_setup.py, worlds/messenger/connections.py, worlds/messenger/constants.py, worlds/messenger/options.py, worlds/messenger/portals.py, worlds/messenger/regions.py, worlds/messenger/rules.py, worlds/messenger/shop.py, worlds/messenger/subclasses.py, worlds/messenger/test/test_shop.py
Updates typing to 3.10+ and replaces str.replace with str.remove_prefix where relevant for a minimal speed increase.
A few gens and tests. Existing tests hit all of the code paths that were touched here
=> The Messenger: remove 3.8 compatibility

Utils.py, worlds/AutoSNIClient.py, worlds/zillion/options.py
Import `TypeGuard` from native typing instead of typing_extentions. I'm not removing typing_extentions from the `requirements.txt` tho, because it's used for other stuff only supported since 3.11 and 3.12
Ran the unit tests
N/A
=> Core: Import `TypeGuard` from native typing instead of typing_extentions

CommonClient.py, Main.py, MultiServer.py, kvui.py
Adds race mode to the multidata on generation then the server adds it to datastorage. i think the api for https://github.com/ArchipelagoMW/Archipelago/pull/2561 would probably be better but this works and was quick and easy so 🤷. also adds whether race mode is enabled/disabled to the commonclient tooltip ui (sorry silvris).
Generated games with race mode enabled/disabled and checked the packets and tooltip ui.
=> Core: add race mode to multidata and datastore

worlds/pokemon_emerald/client.py
The same fix as #3939. Only write the data (and only send the trade) if the save block hasn't moved.
This one is even rarer because your client would need to try to send a trade while your map is transitioning, which would be exceptional. And slightly less destructive because you'd just receive all your items again. But still a problem.
Did a wonder trade between two clients.
=> Pokemon Emerald: Another wonder trade fix

worlds/ladx/LADXR/patches/owl.py
Change: Make the Ghost in your starting house fill up your consumables (Magic Powder, Bombs, Arrows) up to initial max (20/30/30) instead of just up to 10.
The reason is that in Vanilla Magic Powder is logically restored through Trendy Minigame and Bomb & Arrows are filled with the Shop. But with Entrance Shuffle and minimal accessibility, this cannot be guaranteed. Even on full accessibility it could create scenarios where refillables are only possible up to 10 but logic requires more than 10 consumables to get from start to a specific check.
TL;DR: Currently, AP can create logically impossible seeds with ER if logic requires a lot of consumables. The ghost-refill-change will fix this. Thus, this will also not be a YAML-option but a specific change.
The original maintainer, zig, also …
=> LADX: ghost fills ammo to initial max

test/multiworld/test_multiworlds.py
The "filling multiworld" subtest was at the wrong indentation, so was only running for the last world_type.
"games" has additionally been added to the subtest to help better identify failures.
Now that the subtest is actually being run for each world type, this adds about 20 seconds to the duration of the test on my machine.
I ran the test.
=> Tests: Fix indentation in TestTwoPlayerMulti

CommonClient.py, MultiServer.py, docs/network protocol.md, kvui.py
From my miniscule understanding at the time stored_data seemed more appropriate but API wise, read_data is actually the more appropriate place for this so this moves it there. also adds it to the docs which was previously forgotten.
=> Core: move race_mode to read_data instead of stored_data

MultiServer.py
`/send "Ber ser ker" some bread`
is now interpreted as sending the player `Ber ser ker` `some bread`
locally, mostly in a command prompt to see how it behaves and then a handful of tests post integration.
=> Core: use shlex splitting instead of whitespace splitting for client and server commands

WebHostLib/generate.py, test/webhost/test_generate.py
"generating of multiworlds is limited to X players" error is currently not showing because the code path does not return a response.
This change is fixing it by using a redirect back to the form, which then shows the error.
Also adds a test for that and 2 more simple tests to validate basic functionality of the generate endpoint.
* Uploading a single yaml with 21 players and seeing the error.
* Added tests.
=> WebHost: Fix too-many-players error not showing

worlds/dark_souls_3/__init__.py
https://discord.com/channels/731205301247803413/731214280439103580/1293370421026230350
> why was this allowed into main 
Instead of checking the region cache, make your own and check that. Also just stops using the weird `any`
Literally not at all in any way.
=> DS3: Make your own region cache

worlds/messenger/rules.py, worlds/messenger/test/test_shop.py
I accidentally deleted this rule when i did the major rewrite, so this adds it back :)
added a test for it
=> The Messenger: fix missing money wrench rule

MultiServer.py
Makes it so users don't need to fiddle with shlex escaping on !hint Link's House. Also it would error on regular messages that happen to contain quotation marks without a closing one.
quickly
=> Core: make shlex split an attempt with regular split retry

docs/network protocol.md
just noticed `ConnectUpdate` wasn't in the list of client packets even though it was documented lower down, so I added it.
wasn't
=> Docs: Add ConnectUpdate to the list of client packets in the network protocol documentation

MultiServer.py
Fixes names leaking into other rooms https://discord.com/channels/731205301247803413/1295089686578200697
locally, just made sure that id(ctx.item_names) differs for two rooms on the same hoster process.
=> Core: turn MultiServer item_names and location_names into instance vars

worlds/oot/__init__.py
Person hinted Longshot, fuzzy matching decided that was close enough to Slingshot to hint that instead.
Adds a Longshot item name group containing Progressive Hookshot to prevent this issue going forwards.
Also adds a Hookshot item name group with the same contents, mostly for consistency, since it'd be weird to be able to !hint Longshot and that works, but !hint Hookshot and that says "oh did you mean slingshot? 69% sure"
Test gen, !hint
N/A
=> OoT: Add aliases for Progressive Hookshot

worlds/aquaria/__init__.py
Adding options to slot data to make the Poptracker work.
- Unit testing,
- 10 generations
- Starting a game
- Making sure the tracker get the values
=> Aquaria: Adding slot data for poptracker

worlds/aquaria/Regions.py, worlds/aquaria/__init__.py
There was some bugs in the logic (including a game breaking one). This PR fixes them.
- Testing with unit tests
- Generate 100 single slot worlds
- Run the game with a generated world
=> Aquaria Fixing some bugs

worlds/pokemon_emerald/__init__.py
Copy/paste error left the opponent blacklist checking the `_Legendaries` alias in the starter blacklist option instead of the trainer party blacklist option.
Inspected the value of `self.blacklisted_opponent_pokemon` after this change when `_Legendaries` is in `trainer_party_blacklist`.
=> Pokemon Emerald: Fix opponent blacklist checking wrong option for legendaries shortcut

WebHostLib/misc.py, WebHostLib/requirements.txt
Sane lists do not fix the billets now showing with missing blank line before the list. This does.
The render on WebHost looks basically identical to github with this.
=> WebHost: allow lists without leading blank line in markdown

test/general/test_options.py
adds a test to make sure option transfer to database works
locally, fails Timespinner
=> Test: option instances have to be pickleable

CommonClient.py
After joining a game with a datapackage for a given game different to the one in the installed world then joining a room with the same game but the installed datapackage, the cached datapackage isn't updated on CommonClient. 
I also made so that the local datapackage could be loaded if it is the right one
I tried with a modified clique, worked fine.
=> Core: (CommonClient) Making local datapackage load correctly if it was overriden by a custom one

Launcher.py
saves the settings before opening host.yaml so all defaults are populated
had an outdated host.yaml for TUNIC, installed the new one, clicked the open host.yaml button in the launcher, saw the new settings values populated
=> Core: save default settings before opening file for users

worlds/pokemon_emerald/client.py
Shoal cave is a special place that has 2 states: high tide and low tide. Both states exist within the low tide map, except that the game updates the layout to the high tide layout based on the state of a flag. The high tide map exists as a stub. Trackers that care about map updates care which state the tide is in if the player enters one of these maps.
Adds a field that forwards the state of the tide flag with the map update if the new map is relevant to being high or low tide. Also adds the `IN OVERWORLD` guard to map updates. The map and tide flag aren't updated on the same frame, so this delays sending the update until the map has finished transitioning.
```
Outgoing message: [{"cmd":"Bounced","slots":[1],"data":{"type":"MapUpdate","mapId":256}}]
Outgoing message: …
```
=> Pokemon Emerald: Add flag for shoal cave to bounces

WebHostLib/static/assets/playerOptions.js
@agilbert1412 wrote up a very good description of the bug in https://discord.com/channels/731205301247803413/1295518127974776885.
This issue is caused because when applying presets, after we determine the true value of the NamedRange from the preset, we try to set the `namedRangeSelect` to that value. If the value doesn't exist, trying to do so unsets the `select` element. This change detects if it was flipped to unselected (`.selectedIndex == -1`) and changes it to `"custom"` instead.
Ran the WebHost locally, loaded up the Stardew Valley player option page, applied the available presets.
=> WebHost: Fix NamedRange dropdown being blank instead of Custom for presets

worlds/yachtdice/Items.py
This marks Dice and 100 Points as useful, in addition to progression.
Checked Text Client and Yacht Dice Client. Also did 100 test gens.
=> Yacht Dice: Proguseful items: Dice and 100 Points

Utils.py
PlandoConnection had a hack that allowed it to be pickled from `worlds.generic`. #2904 moved PlandoConnection from worlds.generic to Options, so this hack had to be adjusted.
Ran Webhost locally and generated a Minecraft game featuring a plando connection
=> Core: fix pickling plando connections

worlds/hk/Options.py
Change the "hook" in the "Precise Movement" option's description to "claw" to align with the "Mantis Claw" item in-game.
Inspect-elementing default HK options page to check if putting claw would change anything
=> HK: Replace "hook" in Precise Movement description to "claw"

setup.py
Adds / fixes some typing in setup.py
mypy
=> Setup: more typing

BaseClasses.py
not assume origin is Menu in Groups
vi made me do it
two link everything factorios
=> Core: fix item links for alternate menu regions

worlds/oot/__init__.py
Start region name PR changed from using the multiworld get_region to the world get_region, which broke OoT which still had its own get_region before the helpers existed. We just remove the functions that are now replaced by the helpers.
This has apparently existed for a while, but went untested from lack of plando/item links tests.
Tried genning OoT before making the fix, unable to gen.
Tried genning OoT with item links after the fix, gen succeeds.
=> OoT: fix plando/item links (again)

WebHostLib/misc.py, WebHostLib/static/styles/markdown.css
Fixes https://github.com/ArchipelagoMW/Archipelago/pull/4061#issuecomment-2417999195
see title,
such as /faq/en/#what-does-multi-game-mean
Looking at DOM and trying link shown above.
=> WebHost: restore fragment links for glossary and faq and make titles clickable

setup.py
Downloads a working version of SNI
~~Not yet, waiting for https://github.com/alttpo/sni/pull/43~~
Seeing 
> Downloaded SNI from https://github.com/alttpo/sni/releases/download/v0.0.98/sni-v0.0.98-windows7-amd64.zip
in github action
=> Setup: SNI: separate win7/non-win7 build, update macos naming

worlds/sm64ex/docs/setup_en.md
Adds links for the appropriate documentation for makeflags and patches. #3300 will be fully resolved once N00byKing/sm64ex#11
is merged
Looking at render and clicking links
Resolves #3300
=> SM64ex: Add links to documentation for makeflags and patches

WebHostLib/templates/playerOptions/macros.html
Previously, because `default(..., true)` only checks if the left-hand-side is falsey, not just `None`, this always forced options to render in non-rich mode if they were explicitly set to `rich_text_doc = None`. Now it matches the intended and documented behavior, where `None` falls back to the world's
`rich_text_options_doc` setting.
I modified a world's `Option.rich_text_doc` value locally.
=> Core: Properly fall back to a world's `rich_text_options_doc`

worlds/kh2/docs/setup_en.md
Adding the new Poptracker Pack developed by @Ugh-Sunlight and me. Both have full access to the repository and can continue the work if the other dies.
The pack is based on the logic sheet and is still being tested thoroughly but it already extremly accurate. The maintainer of KH2 is aware of the pack and it is pinned in the channel.
The pack is currently not yet fully done (1.0.0) because some Icons are still placeholder but before 0.5.1 drops that will be done.
Visual look at the Setup Guide. Pack itself is being tested [here](https://discord.com/channels/731205301247803413/1295193435418005554)
=> [KH2] Add new Poptracker Pack to the KH2 Setup Guide

Utils.py
On macos, when kivy handles the GUI of the process, trying to instantiate tk will crash.
This spawns tk in multiprocessing for open_filename and open_directory if tk is required.
Fixes [[Launcher] Open Patch button crashing (MacOS)](https://discord.com/channels/731205301247803413/1277050370756972596).
Note: even if we had plyer, there are edge cases that are not handled well by it, so the tk code is likely gonna stay. More on that in the linked discord thread.
https://discord.com/channels/731205301247803413/1277050370756972596/1300051092603797619
=> macos: fix crash when 'Open Patch' is used

worlds/pokemon_emerald/options.py
Adds some notes to a few option descriptions to help clarify player expectations.
Addresses #3945
Reading
=> Pokemon Emerald: Add some warnings to option descriptions

worlds/tunic/docs/en_TUNIC.md
For the new logic options that have already been merged into main, I put together a doc detailing each of the individual instances of these tricks and which logic level they fall under.
I'm not attached to how I wrote the sentence describing this doc here, so please feel free to suggest an alternate.
Reading.
N/A
=> TUNIC: Add link to logic tricks doc

worlds/lingo/options.py
The old documentation for this option was unclear, so it was updated.
Launched the webhost and looked at it with my sinful eyes.
Oh I should've done that when I had the webhost open huh.
=> Lingo: Update documentation for panel shuffle

worlds/osrs/__init__.py
All entrances to Cooks_Guild and Crafting_Guild and all entrances using special logic for canoes were missing indirect conditions for the regions that the cooking, crafting and woodcutting skill rules require access to.
Ran the spheres test in #3924 multiple times and ran many generations with my own implementation of a missing indirect condition checker (prints a stacktrace on a recursive can_reach(region) call if the indirect condition is missing).
=> OSRS: Add missing indirect conditions

worlds/dark_souls_3/docs/setup_en.md
This is a common mistake when players are getting set up with the new DS3 version.
=> [DS3] Remind players to remove the old dinput8.dll

worlds/tunic/options.py
Changing it client-side so that the Torch (warp to start) is given when you have ice grappling set to easy now, along with the other times it was already given. Mainly, someone found a way to soft lock with easy ice grappling on, and the Torch is used to deal with soft locks in logic.
Also updated the LS description to be consistent.
Reading.
N/A
=> TUNIC: Minor revision to IG and LS option descriptions

worlds/overcooked2/Logic.py
@toasterparty 
`meets_requirements` is presently one of the largest callers of `CollectionState.count`, at about 6.6 million calls in a seed with 1 slot per currently supported game. I noticed that `has_requirements_for_level_star` recursively checks that earlier stars are available, including global requirements at each star. However, within the global requirements for 3 stars are exclusive requirements that imply the 2-star additive requirements are met (0.4 + .35 + .2 + .2 = 1.15), and 1-star has no requirements at all, so we can just test only the current star's global requirement. The remaining level-specific checks per star can be done in a loop.
(Arguably we can go even further and pre-combine all of the requirements together but I can save that for later.)
This eliminates about 1 …
=> oc2: Remove recursive level star check and check only one level of global reqs

worlds/hk/__init__.py, worlds/hk/test/__init__.py, worlds/hk/test/test_grub_count.py
somehow this mixup got into the final grubhunt PR
the original code that somehow got mixed up in the final grubhunt PR (in a per player loop, which is why we need the loop in the new code)
```
if grub.location and grub.location.player in relevant_groups:
pass
else:
world.grub_count += 1
```
gen'd with a breakpoint to confirm world.grub_count with 4 grubhunt: all players using both replacement grubs and null, and confirmed that the number gets honored when not using all still
=> HK: fix grubhunt required grubs count

test/general/test_fill.py
Updates test_fill.py to use the Options API to access local items and progression balancing rather than the deprecated multiworld way
Running unittests
=> Tests: Update test_fill.py to use Options API

Generate.py
Closes #4124 
Prevents ini files from being read into generation. This can be a problem if desktop.ini is created by Windows. This does not prevent any other file formats from being used.
Transplanting a desktop.ini file into the folder and running a generation with a valid yaml included
=> Generate: Prevent ini Files from Being Included in YAML Discovery

worlds/AutoWorld.py
This puts the bandaid that was holding Item Links together for years back on. It's called "Items accessibility by default" (but only for groups this time)
It's a bad solution
But it's what we had previously, and the change away from this is what originally "broke" item links. Apparently item links were considered fine with this in place.
So in the interest of 0.5.1 releasing this century, maybe we should just go with this.
Ran it with two identical everything-linked Bumper Stickers yamls.
Idk, does this break Webhost or something?
```
name: Player{number}
description: Default Bumper Stickers Template
game: Bumper Stickers
Bumper Stickers:
item_links:
- name: BSLink
item_pool:
- Everything
replacement_item: null
link_replacement: true
```
=> Core: The Item Links fix to end them all (for now, hopefully)

worlds/pokemon_emerald/CHANGELOG.md, worlds/pokemon_emerald/rom.py
If the `MUS_EVOLVED` sound is replaced with `MUS_RG_POKE_FLUTE`, when a pokemon finishes evolving, it pauses and goes silent for like 40 seconds. I'm not entirely sure why; the same sound is happy to play for the correct duration in other scenarios, and other sounds don't have this problem.
This just swaps the sound for something else if it ever gets randomized into this matchup. Perhaps slightly overengineered to future proof it in case the `_FANFARES` dict gets modified for some reason.
Inspected `randomized_fanfares` after the condition to make sure it swapped correctly and breakpointed inside the condition to make sure it ran. Also modified `_FANFARES` to be sure it generalized.
=> Pokemon Emerald: Prevent evolution fanfare from being replaced with flute

worlds/checksfinder/__init__.py
Making description of ChecksFinder match with current rules of the game
by running webhost locally
=> ChecksFinder: Update description

worlds/alttp/test/items/TestDifficulty.py, worlds/alttp/test/items/TestPrizes.py, worlds/alttp/test/minor_glitches/TestMinor.py, worlds/alttp/test/owg/TestVanillaOWG.py, worlds/alttp/test/shops/TestSram.py, worlds/alttp/test/vanilla/TestVanilla.py
=> LTTP: Update tests to use bases.py

worlds/rogue_legacy/__init__.py
RL has been updated to support id overlaps. This removes that code that rejects.
It wasn't.
=> Rogue Legacy: Remove item/location id overlap rejection code.

worlds/bumpstik/test/__init__.py
=> Bumper Stickers: Update tests to bases.py

worlds/alttp/EntranceShuffle.py, worlds/alttp/__init__.py
ALttP makes common use of entrances with access rules that require another entrance to be accessible. This results in requiring an indirect condition to be registered for the other entrance's `.parent_region`, but this indirect condition is often missing. Additionally, if that other entrance also requires indirect conditions, those same indirect conditions would also need to be registered on the original entrance.
There are so many missing indirect conditions, and due to the complexity of some of the chained rules, it is simply not realistic to add all the missing indirect conditions.
This patch changes ALttP to use automatic indirect conditions instead of explicit indirect conditions and removes the places that were registering indirect conditions.
Without this patch, the missing …
=> ALttP: Use auto indirect conditions

setup.py
This is quite the big dependency (~20MB) that is unused.
For non-webhost it is an optional dependency to requests.
=> Setup: exclude zstandard

BaseClasses.py
Some worlds might want to check for "Item is junk", i.e. an excludable item.
Because this is both `filler` and `trap`, and because `filler` is `0`, there are many "wrong ways" to do this. So I think we should provide a helper function for it.
I believe the only one that covers all cases and is somewhat future proof is to just list out the things that are **not** excludable, and then check that the classification isn't any of those.
=> Core: Add Item.excludable helper function

worlds/sm64ex/Options.py, worlds/sm64ex/__init__.py
The "Off" vs "1Ups Only" options for the "Randomize 1Up !-Blocks" option is a frequent source of confusion to new players. Here's two separate questions about it in #super-mario-64 on the discord in just the past month:
https://discord.com/channels/731205301247803413/937206798014898186/1303553542900023358
https://discord.com/channels/731205301247803413/937206798014898186/1296220828555546705
The "1Ups Only" name makes it seem as if it will just put 1Ups in those locations, when it actually means that it will "only" randomize the 1-Up blocks. But given that the display name is _already_ "Randomize 1Up !-Blocks", the expectation is already that only 1ups will be confused. The docstring/tooltip reinforces that, stating "Include 1Up Exclamation Boxes during randomization". So, to clear up that …
=> sm64ex: Make the Randomize 1Up !-Blocks option a Toggle

worlds/pokemon_rb/__init__.py
stage_post_fill iterates sets of locations, so the iteration order is non-deterministic, resulting in different items being converted from Progression to Useful when generating with the same seed.
I don't think this currently causes any problems because the main use of these locations after stage_post_fill is playthrough calculation, which is non-deterministic to begin with, but maybe there could be problems in the future.
This patch makes stage_post_fill deterministic by sorting the duplicate pokemon locations in each sphere before choosing which of the duplicates should remain as progression.
I added debug checks for deterministic results to the end of the generator (dumping the locations and items to a file with a unique name per seed and yaml combinations and comparing against the …
=> Pokemon RB: make stage_post_fill deterministic

worlds/tunic/er_rules.py
The `Overworld -> Cube Cave Entrance Region` Entrance checks `can_shop()` which checks for being able to reach the "Shop" Region, so the Entrance requires an indirect condition of reaching the "Shop" Region.
I ran multiple generations with the template yaml modified to enable entrance rando, before and after this patch, with both Violet's and my indirect condition checker.
Without entrance rando being enabled, it seems that either `state.has(gun, player)` always ends up `True` or `has_sword(state, world.player)` (part of `can_shop()`) always ends up `False` meaning that the `state.can_reach_region("Shop", world.player)` part of `can_shop()` does not get called, making it appear as if there are no missing indirect conditions.
For reference, `can_shop()` is:
```py
def can_shop(state: …
```
=> TUNIC: Add Shop indirect condition

worlds/cv64/__init__.py
Changes the multiworld random used to generate the player's slot authentication into a world random instead, bringing it more in-line with other worlds. Unless someone finds any others that I missed, CV64 should be free of multiworld random usages now.
Generated the same seed twice, made sure the auth did not change.
=> CV64: Remove multiworld random usage

worlds/dark_souls_3/test/TestDarkSouls3.py
=> DS3: Update tests to use bases.py

worlds/witness/__init__.py, worlds/witness/data/WitnessLogic.txt, worlds/witness/data/WitnessLogicExpert.txt, worlds/witness/data/WitnessLogicVanilla.txt, worlds/witness/data/WitnessLogicVariety.txt, worlds/witness/hints.py
Simple change for Witness, since "Menu" already just led to "Entry", which is the real origin region. So hey, this might actually be a performance boost for Witness too :) It's legit one less region.
Also, Witness' "vague hints" feature has a special case for "Menu" regions of other worlds, so this needs to be adjusted too (technically making this a bugfix? Kind of)
=> The Witness: Get rid of Menu region, prepare for other worlds to change theirs (hints)

.github/workflows/unittests.yml, MultiServer.py, requirements.txt
* Downgrades websockets to 13.x, because
* some API changed in 14.x, which is incompatible with current code
* 14.x is incompatible with py3.8, making it unsuitable for AP 0.5.x
* Add a timeout to hosting CI to make sure it fails if MultiProcessing MultiServer doesn't stop
* Make cmd_exit set the exit_event on error (otherwise the process wouldn't stop) 
CI
=> Core: downgrade websockets and minor fixes

WebHostLib/requirements.txt
Update werkzeug dependency. The old min requirement has a known bug.
Running webhost locally, loading a couple of pages, rolling and hosting a game.
=> WebHost: update werkzeug

worlds/pokemon_rb/__init__.py
Adds a flag to slot data that is just dummy-true so the poptracker can test for whether the slot data exists to apply 0.5.1 or 0.5.0 logic for Pokémon RB.
Generated a game successfully. Connected with a Debug Pack, verified slot data was present.
N/A
=> [PKMN RB] Adds slot data that tells the tracker V5 logic should be considered

worlds/mmbn3/Items.py, worlds/mmbn3/Names/ItemName.py
This fixes the Archipelago item name for SloGauge in Mega Man Battle Network 3 which was misspelled as SloGuage, causing the typo to appear in the Archipelago client and in games that display AP item names.
Not necessary due to the change only being swapping two characters in a single string.
N/A
=> Cleanup: MMBN3 Typo for SloGauge

worlds/stardew_valley/data/craftable_data.py, worlds/stardew_valley/data/recipe_source.py, worlds/stardew_valley/logic/crafting_logic.py, worlds/stardew_valley/test/assertion/rule_assert.py, worlds/stardew_valley/test/rules/TestBundles.py, worlds/stardew_valley/test/rules/TestCraftingRecipes.py
The furnace is a unique case of a recipe that is obtained based on a skill, but not as a skill recipe. It is obtained in a cutscene later on, after earning the skill. The craftsanity shufflings are based on what recipes get shuffled by other settings first, and handles everything else. This qualified, plus blocking the furnace makes for good progression in Archipelago.
But the logic did not consider this. It was a "skill recipe" like any other. This was reported this week by people in Discord who discovered this due to Universal Tracker.
This PR introduces a new type of recipe source, just for this one because the obtention method is unique, and checks all the proper factors about it. Notably, on craftsanity, you just need to receive it. If not on craftsanity, you need both the skill …
=> Stardew valley: Fixed furnace logic bug

worlds/dlcquest/test/TestOptionsLong.py, worlds/dlcquest/test/checks/world_checks.py
Removes unused imports in DLCQuest world tests and uses Options API for checking the value of campaign
Running unittests
=> DLCQuest: Use options API for campaign and remove unused imports in tests

worlds/landstalker/__init__.py
LandstalkerWorld's `cached_spheres` holds a reference to the multiworld, which leaks the multiworld if multidata is skipped. Instead of making it a class variable, give a reference to each matching world. These count as circular references, so the multiworld is correctly GC'ed even if multidata is skipped.
Run on console: `python Generate.py --seed=42 --skip_output`
Before:
```
AssertionError: MultiWorld object was not de-allocated, it's referenced 62 times. This would be a memory leak.
Press enter to close.
```
After: (no error)
=> Landstalker: remove global ref to multiworld

test/__init__.py
Adds a filter to ignore Deprecation Warnings from the s2clientprotocol module.
s2clientprotocol is managed entirely by Blizzard, therefore seeing deprecation warnings from this module is unhelpful.
Currently, on Python 3.11+, multiple deprecation warnings are produced by this module. It is unclear if updating the module would remove these warnings since changelogs are not provided.
Running unittests and checking output
=> Tests: Ignore s2clientprotocol Deprecation Warnings

worlds/LauncherComponents.py
We frequently see user errors where someone has downloaded an updated version of an apworld, and tried installing it without first deleting the original one that's still in their Downloads Folder.
This leads to the new APWorld being named `tracker (7).apworld` and failing to install.
Intentionally renamed my APWorlds to include download artifacts, and then installed them.
=> Core: Detect and account for apworlds being downloaded with a (1) in their name

worlds/cv64/client.py, worlds/cv64/rom.py
Properly truncates injected player names when they should be; before they were not. 
There is no limit on ItemLink group names, so any of those that are longer than 16 characters being injected for each of the game's Locations at patch time has potential to cause weird unintended behavior depending on how long the player and item name is. This PR fixes that by truncating these player names at 16.
For the server player names injected into the game during runtime whenever an item is received, from what I can tell, the max number of characters those names can have is 35 (16 for the original slot name + 16 for the alias + 3 for the added space and parenthesis around the original name). Still, they are now being truncated at 40 characters just to be on the safe side. CV64's item names …
=> CV64: Fix some textbox message truncation issues

worlds/dark_souls_3/__init__.py
This will make it easier for players to understand when they have a
mismatch between their DS3 apworld and their local randomizer version,
mitigating a common source of confusion and support requests.
N/A
=> DS3: List compatible static randomizer versions in slot data

worlds/pokemon_rb/rules.py
https://discord.com/channels/731205301247803413/1306419629115314257
The checks "Victory Road 1F - Left Item" and "Victory Road 1F - Top Item" were missing their strength requirements.
It wasn't
N/A
=> [PKMN RB] Fixes faulty logic in Victory Road 1

worlds/pokemon_rb/__init__.py
Previously the game only checked if the location was for Pokemon R/B and if the item name contained "Static " which would include items from other worlds. Now it only modifies R/B items.
Running generations with a modified ChecksFinder to include an item named "MapStatic Item" (replacing Map Bombs).
This previously caused generations to fail because progression items were made Useful, with this change, those generations now succeeded. Print debugging was used to check if any off-world items were being made Useful, they were not after these changes and were before them.
=> PKMN R/B: Don't change classification of items from other worlds

Launcher.py
Change import order in Launcher.py to fix ModuleUpdate not working (i.e. Utils import error if pyyaml is missing).
* Uninstalling pyyaml, launching the Launcher and seeing Modules getting installed
* Running launcher and clicking random buttons
=> Launcher: change import order to fix ModuleUpdate

WebHostLib/templates/genericTracker.html, WebHostLib/templates/multitrackerHintTable.html, WebHostLib/tracker.py
* Prevent player-specific trackers from attempting to link to an ItemLink player tracker (they do not exist, which is what caused a 500 error).
* Caused by #3569 not taking item links into account.
* Fixes a 500 server error on the Factorio multi-tracker when item links exist.
* Also makes adjustments to the style for these slots by italicizing its names (including multi-tracker).
Tested before/after effects with a game containing item linked players and hints involving said players. Server returns a 500 error before, but no longer does after.
=> WebHost: Fix 500 server errors for hints involving ItemLink slots on tracker pages

worlds/subnautica/options.py
Prevents divergence if core text is updated. (Which it was.)
=> Subnautica: compose DeathLink custom text instead of overwriting

test/general/test_options.py
A Range option using "random" as the default currently fails unit tests.
This is because `test_pickle_dumps` is doing `option(option.default)` when it should be doing `option.from_any(option.default)`, leading to unexpected values in the option constructor.
=> Tests: Use Option.from_any instead of Option() in test_pickle_dumps, which is currently preventing Range options from using default: "random"

worlds/generic/Rules.py
If a world uses a `Location` or `Entrance` subclass that overrides the `item_rule`/`access_rule` class attribute, then
`spot.__class__.item_rule`/`spot.__class__.access_rule` will get the overridden rule, which may not be an empty rule.
Uses of `spot.__class__` have been replaced with getting the class attribute rule belonging to the `Location` or `Entrance` class.
```py
from BaseClasses import Location
class MyLocation(Location):
pass
class MyLocationOverride(Location):
item_rule = staticmethod(lambda item: False)
my_loc = MyLocation(player=1)
print(my_loc.item_rule is my_loc.__class__.item_rule)
print(my_loc.item_rule is Location.item_rule)
my_loc_override = MyLocationOverride(player=1)
print(my_loc_override.item_rule is my_loc_override.__class__.item_rule) …
```
=> Core: Fix empty rule comparisons with subclasses

worlds/aquaria/Regions.py, worlds/aquaria/test/test_no_progression_hard_hidden_locations.py
The `no_progression_hard_or_hidden_locations` option had the problem to not excluding `progression_skip_balancing` item. Now, this option remove every item that are advancement item.
I launched the unit test and generate 100 completely random single player game. All passed without error.
=> Aquaria: Fixing no progression bug

worlds/witness/__init__.py, worlds/witness/options.py, worlds/witness/player_items.py
Someone requested this
I realized it would take like 5 minutes
So here it is :)
Depends on https://github.com/ArchipelagoMW/Archipelago/pull/4197 because Range options can't use `default: "random"` right now.
=> The Witness: Allow setting the puzzle randomization seed yourself

worlds/tloz/Locations.py, worlds/tloz/Rules.py
- Add needing arrows for Pols Voice rule. Not super necessary at the moment since wooden arrows are always accessible in one of the opening shops, but future proofing for future plans
- Create Gohma Locations and make sure all Gohma blocked locations have the required rule (was missing at least one location before)
- Remove the rule requiring Bow for all locations of level 8 (not sure why that was there, it's theoretically redundant now that Gohma and Pols Voice are properly marked)
- Make sure Digdogger locations properly require Recorder, and clean up redundant Level 7 rules as level 7 currently requires Recorder to access the entrance
- Add a missing Food required location to food_locations
ran unit tests (note: was a failed world load for KDL3? haven't been in the loop if that is …
=> TLOZ: Assorted Logic Fixes

CommonClient.py, Utils.py
* Fixes high CPU usage for clients launched via Launcher by not spawning the stream reader if stdin is likely a MultiProcessing pipe
* Also fixes our stream reader to not turn the CPU to 100% for non-blocking files (such as MP pipes)
* Note: the 10ms sleep is not ideal; we could use blocking select() instead, but I am not sure how well that works cross platform.
Running TextClient via Launcher and via terminal
=> Clients: fix high CPU usage when launcher via MultiProcessing

MultiServer.py
adding already found hints to ctx.hints so create_as_hint=2 knows they were previously hinted and doesn't send the message in chat about them
wasn't; vi test it for me please :)
=> core: persist hints even if previously found

Launcher.py
When handling a url for a game that has a url-handling component (ex. `launcher.py "archipelago://test:@localhost?game=The Messenger"`) the popup gives you an option between text client and game-specific component, staying open to allow the user to open both if desired
The issue is if you open a Kivy app (like text client) with that popup closing the popup window without closing all the spawned kivy apps will cause the popup to go unresponsive
This just ports the _stop override in the Launcher App definition to the Popup App definition which fixes the above issue.
by doing above steps and seeing it act like I expect it to
=> Launcher: ports the _stop fix in the Launcher kivy App to handle_url Popup App

worlds/aquaria/__init__.py
Catching `BaseException` without re-raising the exception should almost never be done because `BaseException` includes exit exceptions, such as `SystemExit` and `KeyboardInterrupt`.
Ideally, the caught exception types should be as narrow as possible to not mask bugs from catching unexpected exceptions. Having narrow exception types can also help indicate to other developers what exceptions are expected to be raisable by the code within the `try` clause.
Similarly, the `try` clause should ideally contain the minimum code necessary, to avoid masking bugs in the case that code within the `try` clause that is not expected to raise an exception does so.
In this case, the only expected exception that can occur appears to be `item_table[name]` that can raise a `KeyError` when `create_item()` is …
=> Aquaria: Remove BaseException handling from create_item

worlds/ahit/Regions.py
Reconnecting an act in a telescope to a time rift removes the entrances to the time rift from its access regions because it will be accessible from the telescope instead.
By doing so early on, as a starting act with insanity act randomizer or as a plando-ed act, this can happen before the time rift itself has been reconnected to an act or other time rift. In which case, when later attempting to connect that time rift to an act or other time rift, the entrances from the rift access regions will no longer exist, so must be re-created. The original code was mistakenly re-creating the entrances from the time rift being reconnected, instead of from the rift access regions.
I'm not sure the entrances need to be removed in the first place and I think a better fix would be to not create the …
=> AHiT: Fix reconnecting rift access regions for starting and plando acts

worlds/timespinner/Options.py, worlds/timespinner/__init__.py
This is found on RC2/3 for 5.1, i am not sure if this is a major enough issue to delay an RC, but its also quite a low impacting change so maybe it can get in it dunno
During option migration to snake_case #2485 , the enemy rando option was missed
a few local generation and verified in spoiler that the value was correctly taken over
=> Timespinner: Re-added missing enmemy rando option

worlds/tunic/__init__.py
Was effectively requested to add a clarifying comment for the item link handling code, to make it clear that it's not looping over every location in the multiworld for slots that aren't in an item link in a world that contains item links.
=> TUNIC: Add clarifying comment to item links handling

worlds/sc2/MissionTables.py, worlds/sc2/Regions.py
`enabled_campaigns` is a set and iterating over a set is nondeterministic. This sorts the set and adds the `<` operator to the `SC2Campaign` class so it can be sorted.
Generations and the [Determinism Test PR](https://github.com/ArchipelagoMW/Archipelago/pull/2819)
@Ziktofel
=> SC2: Fix Nondeterministic Behavior

worlds/ffmq/Client.py
SNIClient's task will die sometime (like on hard resets) and FFMQ's client will pass the validation check when it's not supposed to on some emulator. This fix the issue by checking None type and adding a stronger validation check.
Test was done on a known seed that would reliably trigger the behaviour on hard reset.
=> [FFMQ] Fix all checks sending on hard reset + stronger read validation check

worlds/landstalker/Locations.py
`regions_with_entrance_checks` is turned into a set which has nondeterministic ordering. This sorts the set.
Generations and the [Determinism Test PR](https://github.com/ArchipelagoMW/Archipelago/pull/2819)
@Dinopony
=> Landstalker: Fix Nondeterministic Behavior

worlds/hk/__init__.py
`all_event_names` is a set and iterating over a set is nondeterministic. This sorts the set.
Yes, they're events, so it doesn't _really_ matter, I hope, but it's an easy change.
Generations and the [Determinism Test PR](https://github.com/ArchipelagoMW/Archipelago/pull/2819)
@qwint @BadMagic100
=> HK: Fix Nondeterministic Behavior

worlds/lufia2ac/__init__.py
Item groups are sets and iterating over a set is nondeterministic. This sorts the set.
Generations and the [Determinism Test PR](https://github.com/ArchipelagoMW/Archipelago/pull/2819)
@el-u
=> Lufia2: Fix Nondeterministic Behavior

worlds/zillion/options.py
Adds a display_name to the only option that didn't have one following the styling of other display names
Local webhost0
(Yes, they look the exact same)
=> Zillion: Add display_name to ZillionSkill

worlds/sc2/Locations.py
Fixes location classification. This location isn't a victory one.
Generated a YAML where the bug triggered (only victory locations were allowed) and the offending location is gone
No
=> SC2: Fix wrongly classified location type

worlds/stardew_valley/__init__.py, worlds/stardew_valley/data/items.csv, worlds/stardew_valley/items.py, worlds/stardew_valley/test/TestGeneration.py, worlds/stardew_valley/test/__init__.py, worlds/stardew_valley/test/mods/TestMods.py, worlds/stardew_valley/test/rules/TestStateRules.py
Alow our csvs to handle multiple classification, and then classified the Movie Theater as "Progression Trap" as this is how the community already views it anyway
Unit Tests
=> Stardew Valley: Make progressive movie theater a progression trap

worlds/stardew_valley/docs/en_Stardew Valley.md, worlds/stardew_valley/docs/setup_en.md
A couple links were missed during the transition. Discord user CelestialBlade found this bug about 3 hours after the release, so here's the fix
It's documentation
=> Stardew Valley - Update documentation 5.x.x links into 6.x.x links

WebHostLib/templates/weightedOptions/macros.html
This whole code looks a bit jank to me, but I don't think I'm capable of improving it.
Anyway, this problem means that you currently cannot access https://archipelago.gg/games/The%20Witness/weighted-options
Tested: Mostly just checked whether it works after
=> WebHost: Fix crash on advanced options when a Range option uses "random" as its default

worlds/tunic/er_rules.py
Library fuse was missing the ladder requirement, it is now there.
It wasn't, just it's very clear it won't fail.
=> TUNIC: Fix missing ladder rule for library fuse

worlds/LauncherComponents.py
https://discord.com/channels/731205301247803413/731214280439103580/1311410300809117717
Should now properly detect folders in the zip root even if they are missing from the zipinfo list.
=> Launcher: fix detection of valid .apworld (0.5.1-hotfix1)

worlds/LauncherComponents.py
Cherry-pick of https://github.com/ArchipelagoMW/Archipelago/pull/4267 for main
In the other PR
=> Launcher: fix detection of valid .apworld

worlds/pokemon_rb/locations.py
Corrects the location of an item pointed out in #4202 (and also on the Discord)
You can visually see the TM05 (Mega Kick) item should belong in "Victory Road 2F-C" and not "Victory Road 2F-W".
=> Pokemon RB - Fix Incorrect Item Location in Victory Road 2F

worlds/generic/docs/mac_en.md
Updated the minimum version recommended to the minimum version actually supported by AP ( as of #3973 ). I've not followed other changes too closely, so if anything else in this guide is out of date, please let me know and I'll adjust it. Also, depending on the state of 3.13 support, I can be easily convinced to add the 'not supported' version warning we previously had for 3.11 back in for 3.13.
I felt lazy this time and didn't use anything to test it, not even my eyes.
=> [Docs] Update the macOS guide to match changes in core

worlds/dlcquest/__init__.py
Fixing a generation bug
if you are playing either both or basic campaign and you have coinsanity above 50 and you are alone in the multiworld the generation crash
unit test and some game generation that failed before
=> DLC Quest Bug Fix 50+ coin bundle basic Campaign

worlds/cv64/rom.py
Breaking the "First poison parkour ledge" 3-hit breakable (3HB) in Underground Waterway when the option to randomize the 3HB items was turned off would cause the flag for the item location known as "Castle Center: Magical Nitro shelf - Heinrich side" to be set, both causing the location check to send out when it wasn't supposed to and the item later not spawning when it should be. When I added the two extra item actors in the Nitro room and put flags on them, I evidently chose to put one of them on a flag that I didn't realize at the time was already being used by something else (for whatever reason I didn't record it on my big list of the game's flags). And because I don't ever bother breaking the 3HBs when they are turned off, it wasn't until someone else recently brought it to my …
=> CV64: Fix the first Waterway 3HB ledge setting the flag of one of the Nitro room item locations.

worlds/witness/hints.py, worlds/witness/player_items.py, worlds/witness/player_logic.py, worlds/witness/rules.py
Also reorder them slightly
Basically, Witness code refers to "Progression" as "Prog". But then it introduced progressive items, so in order to avoid confusion, I called that "Multi" instead.
This just makes everything explicit
"Multi" -> "Progressive"
"No Multi" -> "Base" (Meaning: Not Progressive)
"Prog" -> "Progression"
Split off from https://github.com/ArchipelagoMW/Archipelago/pull/3961 in an effort to make that PR more reviewable afterwards
Tested:
Nah, I trust PyCharms Refactor->Rename
=> The Witness: Rename some *horrendously* named variables

docs/world api.md
https://github.com/ArchipelagoMW/Archipelago/pull/3682
=> Docs: Mention explicit_indirect_conditions & "Menu" -> origin_region_name

BaseClasses.py
The lists of precollected items were being mutated while iterating those same lists, causing playthrough to skip checking half of the sphere 0 advancement items.
This patch ensures the lists are copied before they are iterated.
I generated a playthrough before and after this patch, using a Witness yaml with `start_inventory: {Black/White Squares: 10}` and a Hat in Time yaml with `start_inventory: {Time Piece: 200}`, comparing the sphere 0 in the spoiler playthroughs afterwards.
Generating with `--log_level debug` can also show the issue clearly (generated with only the Witness yaml):
Before:
```
[...]
Checking if +1 Laser (Player 1) is required to beat the game.
Checking if Black/White Squares (Player 1) is required to beat the game.
Checking if Black/White Squares (Player 1) is required …
```
=> Core: Fix playthrough only checking half of the sphere 0 items

BaseClasses.py
Tested:
No I made this change through direct file edit lmao
=> Core: Make region.add_exits return the created Entrances

Options.py
Allows doing `for item in self.options.locationset` instead of `for item in self.option.locationset.value`
=> Core: Add __iter__ to VerifyKeys

worlds/musedash/__init__.py
If a bad item exists in the item plando, Muse Dash would throw a `AttributeError` which does not explicitly point out the bad item. This change makes it an explicit `KeyError`, which makes the error similar to what other worlds would show.
With tests, and by running the following yaml:
```
name: MuseDash
description: aaaaa
game: Muse Dash
Muse Dash:
plando_items: [{"items": {"Extra Life": true, "Great to Perfect (10 Pack)": true, "Miss to Great (5 Pack)": true}, "world": "DLC", "force": true, "from_pool": true}]
---
name: DLC
game: DLCQuest
DLCQuest:
progression_balancing: 0
```
The casing of the items is slightly off which causes the error.
=> Muse Dash: Change AttributeError to KeyError when Create_Item receives an item name that doesn't exist in the world

worlds/sm64ex/Options.py, worlds/sm64ex/__init__.py
Adds option groups to to options page for SM64.
Initially modelled after the option groups for SMW.
Unit tests, and generating a YAML.
=> Super Mario 64: Option groups

worlds/yugioh06/__init__.py
Make Guide title match the rest of the set up guides on the webhost
I looked at the changes
=> Webhost: Make YGO 06 setup title match page

worlds/alttp/Options.py, worlds/alttp/Rom.py, worlds/alttp/__init__.py
Makes LttP use the new options system in a way it should continue working when the old one is gone.
I made deprecatedict raise on error and got a generation
=> LTTP: sort of use new options system

.github/workflows/build.yml, .github/workflows/release.yml
Updates the build action to the latest supported python version for both Windows and Linux.
CI and <https://discord.com/channels/731205301247803413/1312103982776451072>
=> CI: use py3.12 for the linux and windows builds

Utils.py
When I run tests to generate all supported games, I get a lot of warnings like this:
```
Utils.py:879: UserWarning: Getting options from multiworld is now deprecated. Please use `self.options.enemy_shuffle` instead.
warnings.warn(self.log_message)
Utils.py:879: UserWarning: Getting options from multiworld is now deprecated. Please use `self.options.enemy_health` instead.     
warnings.warn(self.log_message)
Utils.py:879: UserWarning: Getting options from multiworld is now deprecated. Please use `self.options.accessibility` instead.    
warnings.warn(self.log_message)
```
Adding in the appropriate keyword argument to the `warnings` library produces the actual code that needs to be updated:
```
worlds\alttp\__init__.py:844: UserWarning: Getting options from multiworld is now deprecated. …
```
=> Core: Log warnings at call site, not Utils itself

.gitattributes
This means its diff will be collapsed by default on PRs that change it, because it is an "auto generated" file that does not need to be looked at by reviewers
=> Yacht Dice: Mark YachtWeights.py as "linguist-generated"

worlds/doom_1993/Options.py, worlds/doom_ii/Options.py, worlds/heretic/Options.py
Changes the capitalization of "Reset Level on Death" to be the same for all three games and also changes DOOM II and Heretic to actually use `display_name` now.
Locally run webhost and a custom unit test to find visible options without a display_name.
=> id Tech: Standardizing ResetLevelOnDeath display

Main.py
I think the old code is pretty ugly and unpythonic
Here's my proposal for a better version
Even had some room to spare for comments, since I made it a couple lines shorter
=> Core: Rewrite start inventory from pool code

README.md, docs/CODEOWNERS, worlds/faxanadu/Items.py, worlds/faxanadu/Locations.py, worlds/faxanadu/Options.py, worlds/faxanadu/Regions.py, worlds/faxanadu/Rules.py, worlds/faxanadu/__init__.py, worlds/faxanadu/docs/en_Faxanadu.md, worlds/faxanadu/docs/setup_en.md
New game, Faxanadu.
Faxanadu is an NES game. It does not require the server to have the ROM to generate. The patching is done at runtime in the client. The client is a custom-made NES emulator for AP Faxanadu. (Called Daxanadu, because my name is Daivuk...)
The client can be found here: https://github.com/Daivuk/Daxanadu
It has been played for months. apworld was available since a while.
The palette on the NES is restricted, especially in this game. Only 3 colors could have been used for the AP icon. Here how it looks in-game:
Or it shows the proper graphic if they are your own items:
In the menus, the icon has a different palette. Here an example receiving progression item:
Followed by a dialog explaining what it is:
When an AP item is bought from a shop, it shows "SOLD OUT":
More …
=> Faxanadu: implement new game

test/general/test_items.py
Adds a unit test that `local_items` and `non_local_items` are not modified in `set_rules`, `generate_basic`, or `pre_fill`.
Unit testing. Specifically tested Blasphemous with modified default options and reverting https://github.com/ArchipelagoMW/Archipelago/pull/3901 and saw that it failed this test.
This could test other/later stages, but those would all require fill/distribute_items_restrictive which is time-consuming.
=> Tests: Add test that local/non local items aren't modified late

Options.py
OptionGroup already requires a list, so we might as well use that ordering for something. This makes it so that option groups will order the options by the group's specification instead of the order defined in the dataclass.
with some test groups
=> Core: Allow option groups to specify option order

worlds/witness/player_logic.py, worlds/witness/test/test_roll_other_options.py
A little snag that was missed with the most recent event system revamp. These options just accessibility fail 100% of the time right now.
Essentially, `PlayerLogic.ALWAYS_EVENTS_BY_HEX` had a vital event being overwritten with the Victory event. This change assures that both events exist:
```
Mountaintop Box Long Solved: Victory
Mountaintop Box Long Solved (Effect 2): Bottom Floor Discard Turns On
```
Also add a basic regression test that just rolls these options.
=> The Witness: Fix unreachable locations on Longbox + Postgame

Main.py
Adds the item to the assert message confirming event item/locations are only paired with eachother
had an issue where a normal location had event items placed on it
this change let me debug which item was being treated as an event erroneously
=> Core: update error message for mismatched "event" placements

worlds/witness/test/test_disable_non_randomized.py
The specific option combination used by this test is somewhat prone to swap fails (about 1 in 200 if I had to guess?):
https://github.com/ArchipelagoMW/Archipelago/actions/runs/12042002658/job/33574899391?pr=3842
(I glanced over it, it looks a *lot* like a swap fail, every sphere 1 location is filled with something terrible and all items that would unlock anything are yet unplaced)
I need this test to have this specific combination though, so I'm just gonna turn off the fill test on it.
Similar (but less restrictive) options combinations are tested [elsewhere](https://github.com/ArchipelagoMW/Archipelago/blob/main/worlds/witness/test/test_roll_other_options.py#L6-L16).
=> The Witness: Turn off default tests on a test that is prone to swap fails

worlds/witness/data/static_items.py
Right now, there is a Doors item group that contains everything that sort of acts like a door (i.e. it is unlocked by a singular "key"), and these items are all implemented the same in the code.
But for the player, there are really three types of """doors""": Doors, Panels, and Obelisks.
This PR splits the "Doors" item group into "Doors", "Panel Keys", and "Obelisk Keys".
The name "Panel Keys" was chosen because "Panels" might be a location group in the future, and the name makes more sense for that.
Tested:
Launched Webhost and glanced at datapackage
=> The Witness: Add "Panel Keys" and "Obelisk Keys" item groups

MultiServer.py
Makes !status show a note if the slot is in Status Ready
lightly,
running a server, connecting with text client, running !status, /ready, !status and seeing the output text change before/after setting ready
=> MultiServer: !status shows Ready status

Launcher.py, kvui.py, worlds/LauncherComponents.py
Add kivy overrides to allow AsyncImage source paths of the format ap:worlds.module/subpath/to/data.png that use pkgutil to load files from within an apworld
locally edited the a hat in time world to use `icon_paths['yatta'] = f"ap:{__name__}/data/yatta.png"` instead of the existing icon_paths value, moving said png to inside a "data" folder in the world, and opened the launcher with:
* the world unzipped
* the world zipped as an apworld in /worlds
* the world zipped as an apworld in /custom_worlds
and all displayed the icon, also tested
* with the original icon, loaded quickly with no issue
* with an upscaled icon, which tripped zipbomb protection and did not load
* with a less upscaled icon, which took a few seconds to load, in which the launcher opened, displayed a loading icon, and was …
=> Launcher: support Component icons inside apworlds

worlds/factorio/Options.py, worlds/factorio/__init__.py
Adds this hot new thing called option groups to Factorio
=> Factorio: option groups

BaseClasses.py, Main.py
Currently, when using say !hint worlds with heavy use of events get pushed back in priority. This recursively culls events out while making the spheres, giving them similar priority.
The feature, at least on the Sphere Tracker, is told to the user to only look at sendable items, so it makes sense for the feature to consistently work that way to meet user expectations.
locally. I had 1 HK and 1 LTTP with set seed, it turned 42 spheres, of which many spheres were one-player only, into 15 spheres in which both players had things to send, which is closer to what I'd expect.
:( -> :)
=> Core: cull events from multidata spheres

WebHostLib/__init__.py, WebHostLib/misc.py, WebHostLib/session.py, WebHostLib/templates/session.html, WebHostLib/templates/siteMap.html
Some basic session save / load. It will probably be discovered by most users after they lost their identifier, but at least there is now a remedy available.
locally with Chrome and Vivaldi, settings cookies back and forth.
=> WebHost: add a page to manage session cookie

worlds/blasphemous/Options.py, worlds/blasphemous/__init__.py
Adds `start_inventory_from_pool` and removes the code that made `start_inventory` act like `from_pool`.
The items are now automatically "skipped" and replacement junk items are automatically added. So all the code could be removed.
Yamls using both `start_inventory` and `start_inventory_from_pool` with numbers of items in the pool and in excess of the pool.
=> Blasphemous: Add start_inventory_from_pool

.github/workflows/build.yml, .github/workflows/release.yml, ModuleUpdate.py, docs/running from source.md
* Makes version check for official distribution and docs match
* Add warning for 3.10.11 having known security issues
* Relaxes the check for micro updates on platforms that may not use the official distribution/versioning
* Sets min python version for build and release to current latest (with known security fixes)
* On Linux, Launcher fails on py3.9.x, but works on 3.10.14 *(updating to 3.10.15 now)*
* CI would probably fail if I got the versions wrong
* Seeing `UserWarning: Python Version sys.version_info(major=3, minor=10, micro=11, releaselevel='final', serial=0) has security issues. Don't use in production.` in CI
=> Core: rework python version check

worlds/doom_1993/Options.py, worlds/doom_ii/Options.py, worlds/heretic/Options.py
Cleans up the difficulty options for each of the three games. (Especially Heretic, looks like there was a bit of overzealous copy-pasting there...) Also adds aliases, allowing the use of community standard skill level abbreviations (e.g. `itytd`, `hmp`, `uv`, etc.) instead of the more generic ones.
Test generations to make sure new aliases mapped to correct difficulty settings.
=> id Tech 1: Clean up difficulty options

worlds/doom_1993/docs/setup_en.md, worlds/doom_ii/docs/setup_en.md, worlds/heretic/docs/setup_en.md
Daivuk and I were discussing this earlier today; there's currently no documentation anywhere of how to start APDOOM from the command line, or information on any of the command line arguments that it adds. This PR adds this documentation to the setup guide. It's especially important to have this here for Linux users, as the launcher is Windows-only.
Reading, glancing at the formatted output through a markdown editor, and running the commands I already have been for the past year lol
=> id Tech 1 games: Add command line instructions/info

Options.py
If you, like me, forget that items have counts and attempt to give yourself a unique starting item by writing in your yaml:
```yaml
starting_items:
{"Starting Item"}
```
You get an error `TypeError: '<' not supported between instances of 'NoneType' and 'int'`... because yaml interprets this as a dict with an implicit value of `None` and the original error message comes from checking whether any value is less than 1. This produces a better error message if any dict value is `None`.
Manually.
=> Core: Add new error message for item count when defined as a set instead of a dict

worlds/sm/__init__.py
Changing `create_item` with an invalid item name to throw a KeyError instead of a StopIteration.
Plando items with an invalid item name
=> Super Metroid: KeyError on invalid item name

worlds/adventure/__init__.py
Changes the error from an invalid item name (such as from plando) to KeyError instead of causing an AttributeError on the next line from the `get` default of `None`
Generations and using plando
=> Adventure: `create_item` AttributeError -> KeyError

Generate.py, WebHostLib/check.py
`---` marks the start of a yaml document which lets us put multiple yamls in one file, but if it's accidentally put at the end of the file (or twice in a row or anything), that yaml document will be empty, aka `None`. This throws an exception that doesn't clearly identify the file:
```
Uncaught exception
File "c:\Users\bswolf\Documents\GitHub\Archipelago\Generate.py", line 529, in <module>
erargs, seed = main()
^^^^^^
File "c:\Users\bswolf\Documents\GitHub\Archipelago\Generate.py", line 127, in main
f"{get_choice('description', yaml, 'No description specified')}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "c:\Users\bswolf\Documents\GitHub\Archipelago\Generate.py", line 260, in get_choice
if option not in root:
^^^^^^^^^^^^^^^^^^ …
```
=> Core: warn if a yaml is empty

Launcher.py
When handling a uri to launch it now instantly launches Text Client if nothing else is registered
I only tested Launcher.py archipelago://localhost
=> Launcher: launch without delay on URI without choice

Main.py, MultiServer.py, docs/network protocol.md
Some documentation missed in the hint priority PR
Also fixed a missing check to prevent `UpdateHint` packets from setting the status to `HINT_FOUND`
Fix precollected hints not being handled at all
Read the changed docs.
Modified TextClient to send a faulty `UpdateHint` packet with `HINT_FOUND` as the status, which gave `WARNING:Client:Invalid Packet of arguments: UpdateHint: Cannot manually update status to "HINT_FOUND"` (the correct new error message)
Tested `start_hints`, `start_location_hints`
`start_hints`,`start_location_hints` test:
(`Progressive Movie Theater` is properly marked `Avoid` due to being `Progression + Trap` classification, `Progressive Pickaxe` is properly `Priority` via `start_hints`, and the `Return Scepter` is properly `Unspecified` via `start_location_hints`)
=> Core: Hint Priority fixes

worlds/kh2/Rules.py
Entrances to the Final region require being able to reach any one of a number of locations, but for a location to be reachable, its parent region must also be reachable, so indirect conditions must be added for these regions.
I wrote a test (#3924) to sweep in spheres once as normal and then a second time with `world.explicit_indirect_conditions = False`. When all required indirect conditions are present with `world.explicit_indirect_conditions = True`, the spheres in both sweeps should always be the same. KH2 would often fail this test for locations in the Final region.
After adding in the missing indirect conditions in this PR, the test no longer fails.
=> KH2: Add missing indirect conditions for Final region access

Utils.py
logs process ID in cases where it might matter.
`[2024-11-29 23:18:30] Archipelago (0.6.0) logging initialized on Windows-10-10.0.19045-SP0 process 20648 running Python 3.12.6`
=> Core: log process ID

worlds/stardew_valley/stardew_rule/base.py
So, I don't know how it went unnoticed for so long... Basically for `Or` and `And` rule, if two rules had the same combinable sub-rules, they would automatically be considered equals completely ignoring the other sub-rules. For example, a rule that require access to 5 regions would be considered equal to a different rule requiring 5 completely different regions. They would evaluate different, but be considered equal. 
I found this while writing tests in another branch. This bug has been merged for ~9 months and no one noticed, so I guess the `__eq__` is probably not used too often. At least the `__hash__` is correctly implemented, so that probably saved a lot of problems. 
Not really tested, but it's kind of obvious that the `__eq__` method should compare with `other` and not `self`. 
N/A
=> Stardew Valley: Fix a bug in equals between Or and And rules

worlds/ladx/LADXR/generator.py, worlds/ladx/Options.py
LADX has two QoL warp options as toggles, but one only works if the other is enabled. This makes a single option combining both.
Was added very early in the ladx beta process, has had a lot of playtesting.
=> LADX: combine warp options

worlds/witness/rules.py
This is split off from https://github.com/ArchipelagoMW/Archipelago/pull/3961 in an effort to split some of my giant PRs into smaller PRs.
- Use state.has_all instead of state.has_all_counts when all counts are 1
- Sort any calls to has_all or has_all_counts by which condition is least likely to be true
The performance gain here is minor (1-2%), but it becomes bigger in the aforementioned PR because of the nature of the changes that PR makes.
=> The Witness: Another small access rule optimisation

worlds/ladx/LADXR/generator.py
Creates a list of exclusions for text shuffle.
zig wanted to exclude this when he initially implemented text shuffle but simply forgot and since then just didn't have time. This is preserving nobody's idea.
Having these options in text shuffle lessens the experience for all users as, for example, the Egg Path Textbox WILL be on another object but WILL NOT display the correct text (which path it is) which leads to users being confused and frustrated because they believe the shuffled textbox is correct. They also shuffle the path when talking to the book for the first time WITHOUT being able to EVER find out the right path without having the meta knowledge of knowing all four paths.
Excludes:
- Owl statues (hints)
- Library books (hints, egg path)
- Signpost by egg indicating goal
- Signs …
=> LADX: text shuffle exclusions

.github/workflows/unittests.yml
puts a cap on pytest-subtest in pipeline unittests to not run into a new bug
https://github.com/pytest-dev/pytest-subtests/issues/173
hopefully can be reverted when pytest-subtests fixes the bug or py3.10 gets dropped
ran pytest on local with the same pip command and let them complete successfully on my branch
=> CI: cap pytest-subtest version

worlds/raft/__init__.py
`pre_fill` runs after item plando, and item plando could place an item at a location where Raft was intending to place a locked item, which would crash generation.
This patch moves the placement of these locked items earlier, into `create_items`.
Setting items into `self.multiworld.raft_frequencyItemsPerPlayer` for each player has been replaced with passing `frequencyItems` to the new `place_frequencyItems` function.
`setLocationItem` and `setLocationItemFromRegion` have been moved into the new `place_frequencyItems` function so that they can capture the `frequencyItems` argument variable.
The `get_pre_fill_items` function could return a list of all previously placed items across the entire multiworld which was not correct. It should have returned the items in …
=> Raft: Place locked items in create_items and fix get_pre_fill_items

worlds/kdl3/regions.py, worlds/kdl3/rom.py, worlds/ladx/LADXR/patches/bank34.py, worlds/ladx/LADXR/patches/bank3e.py, worlds/lingo/static_logic.py, worlds/minecraft/Constants.py, worlds/mm2/rom.py, worlds/shivers/Constants.py
patches various worlds to use "/" explicitly instead of os.path.join for pkgutil
to any world dev who wants to pr this change yourself just suggest removing your world's change / say so and I will remove
wasn't
=> Various Worlds: use / explicitly for pkgutil

worlds/stardew_valley/options/forced_options.py, worlds/stardew_valley/test/options/TestForcedOptions.py
This force the deactivation of Mr. Qi's special orders when ginger island is deactivated. Not force disabling this option was not a bug, because every time we check if Qi's special orders were enabled, we also check if ginger island is enabled (now this is unnecessary). The goal is more to handle incompatible option combination at the same place and log a warning to the person generating knows that some locations won't be included. This will also prevent future bug if we eventually forgot to check ginger island every time we also check if Qi's special orders are enabled.
- Wrote some unit tests to validate specifically the function forcing options activation
- Generate games with qi's special orders settings and ginger island excluded/included. With those changes, is deactivated when …
=> Stardew Valley: Force deactivation of Mr. Qi's special orders when ginger island is deactivated

WebHost.py
Alternative for https://github.com/ArchipelagoMW/Archipelago/pull/4351
This one wasn't.
=> WebHost: disable abbreviations for argparse

.github/workflows/unittests.yml
Reverts ArchipelagoMW/Archipelago#4344 since https://github.com/pytest-dev/pytest-subtests/issues/173 is fixed
Was not, but I guess the CI will in like 10 seconds
N/A
=> CI: remove version restriction on pytest-subtests

MultiServer.py, NetUtils.py, kvui.py
When testing https://github.com/ArchipelagoMW/Archipelago/pull/3506, we all forgot to test itemlinks again, lol
Basically, noone can update the priority of an item links hint.
Also included: Color item links players that concern this slot pink, just like when it's the slot itself
Before:
After:
=> MultiServer/CommonClient: We forgot about Item Links again (Hint Priority)

worlds/stardew_valley/logic/logic.py
This fixes an issue where a seed could be incompletable when starting winter, if other seasons were randomized behind stuff requiring moss. Namely, a bundle requiring moss, shipping moss and some crafting/cooking recipes if relevant option is enabled.
This bug was reported by a player here https://discord.com/channels/731205301247803413/1090823633099833464/1315132425210302606
Ran the tests
N/A
=> Stardew Valley: Fix potential incompletable seed when starting winter 

worlds/musedash/Options.py
Some options used a dict as their default option, even though they were sets.
Generated a template yaml and double checked website.
=> Muse Dash: Remove bad option defaults.

worlds/tunic/er_rules.py
Changes the event to require the 3 hexes instead of just temple access. Removes the hex requirements from the heir fight since they're on the temple access event now.
Test gens.
=> TUNIC: Change rule for heir access in non-hex quest

worlds/pokemon_emerald/data.py
Generation (of any game) on Python 3.12 would print SyntaxWarnings due to invalid '\d' escape sequences added in #3832.
Use raw strings to avoid `\` being used to escape characters.
I tested running generation of emerald and non-emerald.
Before:
```
G:\git_Repos_other\Archipelago\worlds\pokemon_emerald\data.py:400: SyntaxWarning: invalid escape sequence '\d'
re_match = re.match("^B?\d+[FRP]$", word)
G:\git_Repos_other\Archipelago\worlds\pokemon_emerald\data.py:406: SyntaxWarning: invalid escape sequence '\d'
re_match = re.match("^([A-Z]+)(\d+)$", word)
```
=> Pokemon Emerald: Fix invalid escape sequence warnings

docs/running from source.md
changes docs to reference moduleupdate directly when describing how to install source requirements
if there's a reason it should be generate instead i couldn't figure it out, 
the section could be potentially removed instead as we already mention `Then run any of the starting point scripts, like Generate.py, and the included ModuleUpdater should prompt to install or update the required modules and after pressing enter proceed to install everything automatically.` earlier in the doc
ran moduleupdate and it updated my requirements just like generate would
=> Docs: Use ModuleUpdate.py

WebHostLib/generate.py
cast all the settings values so they don't try to get pickled later
ran webhost with forcing the `elif len(gen_options) >= app.config["JOB_THRESHOLD"]:` line to resolve false to trigger the else clause and didn't see unpickling errors
=> Core: cast all the settings values so they don't try to get pickled later

worlds/pokemon_emerald/rules.py
The `REGION_DEWFORD_TOWN/MAIN -> REGION_ROUTE109/BEACH` and `REGION_ROUTE109/BEACH -> REGION_DEWFORD_TOWN/MAIN` entrances require access to the
`REGION_ROUTE104_MR_BRINEYS_HOUSE/MAIN -> REGION_DEWFORD_TOWN/MAIN` entrance in their access rules, so require indirect conditions for the parent_region of the entrance: `REGION_ROUTE104_MR_BRINEYS_HOUSE/MAIN`.
I ran generations with the template yaml without the changes in this PR with both Violet's missing indirect condition checker and my own implementation and both found these missing indirect conditions.
After applying the changes in this PR, both indirect condition checkers do not report any issues when generating with the template yaml.
=> Pokemon Emerald: Add Mr Briney's House indirect conditions

Utils.py
When running Generate.py, uncaught exceptions are logged once to a file and twice to the console due to keeping the original excepthook. We can avoid this by filtering the file log out of the stream handler, and letting the original excepthook print the traceback.
Created a player yaml file with
```
Noita:
progression_balancing:
garbl: 10
```
and ran `python Generate.py --skip_output`.
<details><summary>Before</summary>
```
Uncaught exception
File "Documents\GitHub\Archipelago\Generate.py", line 417, in handle_option
player_option = option.from_any(get_choice(option_key, game_weights))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "Documents\GitHub\Archipelago\Options.py", line 732, in from_any
return cls.from_text(str(data)) …
```
=> Core: Deduplicate console exception output

worlds/hk/Options.py
adds random handling to charm cost plando by using a Range option class's from_any
used a plando charm cost block with "random", "random-range-0-3", normal ints, and some invalid keys including dicts and invalid strings and saw everything resolve as expected in the spoiler log
=> HK: add random handling to plandocharmcosts

worlds/pokemon_emerald/data.py
#4329
Checked in the debugger, the key that it sets is some warp in a regi cave. It gets set to `None` on the first loop and then overridden later. So this code is effectively dead and has no intended function anyway.
Generated after deleting the code.
=> Pokemon Emerald: Remove unnecessary code

worlds/aquaria/docs/setup_en.md, worlds/aquaria/docs/setup_fr.md
Many times, the setup documentation link in the setup guide make users download the beta client instead of the latest one. So, I change the link so that is it point to the latest release page instead of the releases page.
I started the Webhost locally to test if the links was working.
=> Aquaria: Replacing the release link to the latest link

worlds/ladx/LADXR/patches/bank3e.py
The in-game check counter that displays at the end of the game isn't counting the mandatory first check (Tarin's Gift) and so it is off by one. This inflates the check count by one at the start to correct.
It has been in the rolling ladx beta since Nov 14, waiting for a confirmation that it does what it is meant to do before undrafting.
=> LADX: correct in-game check counter

worlds/smz3/TotalSMZ3/Regions/Zelda/GanonsTower.py, worlds/smz3/__init__.py
SMZ3 used to rely on the fact that entering GT logically required all SM boss tokens as part of its victory condition, but SMZ3 version 11.3 actually changed that logic so that the number of required SM boss tokens to logically enter GT scales with its crystal entry cost. This means that some boss tokens were being considered unnecessary for game completion, which means minimal accessibility wouldn't ensure that the correct number of boss tokens could actually be reached, resulting in an impossible seed sometimes being generated. (Well, as "impossible" as anything is in LTTP, anyway.)
Test generations with 0/7/4 minimal accessibility seeds.
=> SMZ3: Fix minimal logic considering SM boss tokens unnecessary

NetUtils.py, docs/network protocol.md
Added a new JSONMessagePart type (`hint_status`) for displaying hint status/hint priority, pursuant to [my suggestion here](https://discord.com/channels/731205301247803413/731214280439103580/1320078772199882864) to fix [this issue](https://discord.com/channels/731205301247803413/731214280439103580/1320009008156901449).
This sets up correct handlers throughout the code to display hint priority in the correct coloration and to send abstract styling hints to clients.
A correctly formatted hint_status JSONMessagePart appears as:
```json
{"text": "(unspecified)", "hint_status": 1, "type": "hint_status"}
```
In contrast to `item_id` and `player_id`, I elected to store hint status and text separately as there will not be one canonical visual representation of the text. I could be convinced that …
=> Core: Add JSONMessagePart for Hint Status (Hint Priority)

worlds/landstalker/Constants.py, worlds/landstalker/Hints.py, worlds/landstalker/Items.py, worlds/landstalker/Locations.py, worlds/landstalker/__init__.py, worlds/landstalker/data/world_node.py, worlds/landstalker/data/world_path.py, worlds/landstalker/data/world_region.py, worlds/landstalker/data/world_teleport_tree.py
This bundles a few fixes for Landstalker world generation:
- Several entrances were ending up with the same name in specific conditions, causing a generation failure (https://discord.com/channels/731205301247803413/1314864280256122880)
- When using a specific short goal ("Reach Kazalt"), endgame locations were excluded but still present and causing accessibility issues (https://discord.com/channels/731205301247803413/1313260966439419965)
- The hint provided by the Lithograph was giving current player name instead of the name of the player whose location contains the hinted item
This was tested by manually generating ~100 seeds with the previously problematic options set to ensure it was fixed.
=> Landstalker: Fix issues on generation

worlds/landstalker/Rules.py
The data from `WORLD_PATHS_JSON` is supposed to be constant logic data shared by all Landstalker worlds, but `add_path_requirements()` was modifying this data such that after adding a `Lantern` requirement for a dark region, subsequent Landstalker worlds to have their logic set could also be affected by this `Lantern` requirement and previous Landstalker worlds without damage boosting logic could also be affected by this `Lantern` requirement because they could all end up using the same list instances. This issue would only occur for paths that have `"requiredItems"` because all paths without required items would create a new empty list, avoiding the problem.
The items in `data["itemsPlacedWhenCrossing"]` were also getting added once for each Landstalker player, but there are no paths …
=> Landstalker: Fix paths Lantern logic affecting other Landstalker worlds

worlds/witness/player_logic.py
In https://github.com/ArchipelagoMW/Archipelago/pull/4000, which changed a single Toggle to a granular OptionSet, I forgot to update a minor part of the code to check for the individual OptionSet values, so right now it just checks for truthiness of the set.
This leads to some items being progression when they shouldn't.
=> The Witness: Fix bridge/elevator items being progression when they shouldn't be

Fill.py
World dev wants to fill useful, filler and trap locally.
`fill_restrictive` is slow because it thinks it needs to do location access stuff.
`remaining_fill` **does not respect excluded locations** inherently for useful items - Fill actually does two calls to it, once with `excludedlocations` and `filleritempool`, then with `defaultlocations` and `restitempool`
World dev chooses to reimplement their own random fill with `location.can_fill`
This has happened at least twice now, as far as I know.
Add an argument to `remaining_fill` for whether to check only the item rule or do a full location.can_fill check
- Just always check `location.can_fill`? Idk, that'd be slower, but is remaining fill really our bottleneck?
- Move the two calls to remaining fill *inside* of remaining fill, splitting …
=> Core: Give the option to worlds to have a remaining fill that respects excluded locations

worlds/factorio/data/mod_template/data-final-fixes.lua
This allows for example, making a blueprint of your rocket silo with requester chests specifying a request for the 2-8 rocket part ingredients needed to build the rocket.
Unhiding the rocket part item from blueprint parameterization. 
Made a standalone mod to test this.
=> [Factorio] Make it possible to use rocket part in blueprint parameterization.

worlds/factorio/Mod.py
Works well in  conjunction with https://github.com/ArchipelagoMW/Archipelago/pull/4332
With this 4332 is technically not needed, as .hidden_in_factoriopedia is now defaulting to .hidden, instead of false, but I'd still prefer to have both to be more correct and explicit.
Just with Factorio, no server connection was made.
=> Factorio: require version that fixes a randomizer exploit

worlds/factorio/data/mod_template/data-final-fixes.lua
hides technologies that are meant to be hidden in factoriopedia too. The attribute is new in 2.0 and if not set completely circumvents the main hidden variable as factoriopedia allows you to jump to the original.  This may end up being considered a vanilla bug and fixed, but for now, it is what it is.
It loaded ingame.
=> Factorio: hide hidden vanilla techs in factoriopedia too

worlds/witness/data/static_logic.py, worlds/witness/regions.py
The Witness adds its locations to its regions in a non-deterministic order.
This is mostly fine, but it does mean the spoiler log is not fully deterministic (the only thing I'm aware of that cares about insertion order of locations)
This PR makes it so that the order of processing of entities is tracked when creating the entity list from WitnessLogic.txt, and then uses that to sort the locations before adding them to the regions.
This also looks quite nice:
```
Symmetry Island Lower Panel: Monastery Entry Right (Panel)
Symmetry Island Right 3 (Panel Hunt): +1 Panel Hunt
Symmetry Island Right 5: Power Surge
Symmetry Island Back 6: Treehouse Drawbridge (Panel)
Symmetry Island Left 7: Bunker Entry (Panel)
```
The Panel Hunt event "Symmetry Island Right 3 (Panel Hunt)" now shows up "in its …
=> The Witness: Make location order in the spoiler log deterministic

worlds/tunic/__init__.py
Worlds should not modify the item pool after `create_items`, but some of them do anyway. If the multiworld's item pool has not been created in a deterministic order, and a world breaks the rules and removes an item from or inserts an item into the item pool after `create_items`, then it can result in nondeterministic generation.
TUNIC was iterating values from `item_name_groups` which are sets, which have nondeterministic iteration order, resulting in the order of the items in the item pool being nondeterministic.
This patch makes the order deterministic by sorting the sets before iterating them.
I ran the tests in #4410 with these changes.
=> TUNIC: Add relics and abilities to the item pool in deterministic order

worlds/ffmq/Items.py
Worlds should not modify the item pool after `create_items`, but some of them do anyway. If the multiworld's item pool has not been created in a deterministic order, and a world breaks the rules and removes an item from or inserts an item into the item pool after `create_items`, then it can result in nondeterministic generation.
FFMQ was iterating values from `item_name_groups` which are sets, which have nondeterministic iteration order, resulting in the order of the items in the item pool being nondeterministic.
This patch makes the order deterministic by sorting the sets before iterating them.
I ran the tests in #4410 with these changes.
=> FFMQ: Create itempool in deterministic order

worlds/zork_grand_inquisitor/world.py
The order the items are created and collected generally should not matter for start inventory (`push_precollected`) currently, but could be relevant in the future.
This patch sorts the set of item enum members by name before creating and precollecting the items.
I ran the tests in https://github.com/ArchipelagoMW/Archipelago/pull/4410 with these changes.
=> Zork Grand Inquisitor: Precollect Start with Hotspot Items in deterministic order

worlds/shivers/Options.py, worlds/shivers/__init__.py, worlds/shivers/docs/setup_en.md
Adds new option to make ixupi captures priority
This had been in a [previous PR](https://github.com/ArchipelagoMW/Archipelago/pull/3287#issuecomment-2159566855) but was removed because of generation failures, that was until this PR got merged in https://github.com/ArchipelagoMW/Archipelago/pull/3592
Note this option is basically just a shorthand for behavior that can be achieved through plando / item location options.
But this will be SUPER useful for big asyncs or similar that use filler games. Makes Shivers more important as a game.
Generation of a single world and a generation of 100 worlds all with this option on (they also included puzzle hints required which is a more complex rule set)
=> Shivers: Adds ixupi captures priority option

worlds/factorio/data/mod_template/control.lua
Starting items not being given when skins factored is selected, during the cutscene phase of starting the map.  Addresses issue #4399 
loaded into games with the fix in place.
=> Factorio: Fix skins factored not giving starting items

worlds/blasphemous/Options.py
Option resolution for the `StartingLocation` option (the only `ChoiceIsRandom` subclass) was writing to the `randomized` attribute on the class instead of on the instance, meaning that `self.options.starting_location.randomized` would be `True` for all Blasphemous players in the multiworld if any one of the players set their `StartingLocation` option to `"random"`.
This patch fixes the issue by writing to the `randomized` attribute on the new instance instead of on the class.
I ran a generation with two template Blasphemous yamls, but with one yaml changed to use `starting_location: random`.
I put breakpoints in both conditional branches at the start of `generate_early`:
https://github.com/ArchipelagoMW/Archipelago/blob/a7b483e4b72e8a983875e660a2d92762baedbf62/worlds/blasphemous/__init__.p …
=> Blasphemous: Fix starting_location: random affecting all Blasphemous worlds

worlds/pokemon_rb/locations.py
The third Burglar in Cinnabar Gym's trainersanity location was named Super Nerd 4. Renamed him and Super Nerd 5 to be correct.
generated a game with trainersanity, fought Burglar 3 and Super Nerd 4 to verify that the correct checks sent.
=> Pokemon RB: Fixing misnamed locations

worlds/generic/docs/commands_en.md
Really simple doc change.  Users (myself included until recently) are generally unaware that you can reset an alias using an empty argument.  This clarifies that function for both the client and host commands.
Slight confusion regarding the full use of the !alias command
By aliasing and unaliasing a player slot.  Also, GitHub Preview seems good 'nuff for visual testing.
It's two lines of text.
=> Docs: Clarify !alias commands in commands_en.md

SNIClient.py, worlds/AutoSNIClient.py
Adds the ability for worlds using SNIClient to monitor/handle packages via the `on_package` method in their client code.
Edited my (WIP) MMX3 world to listen to `Connected`, `SetReply` and `Retrieved` packages with `EnergyLink` as their keys (if applicable) to monitor EnergyLink updates and modify a label accordingly, label got updated so it worked fine. The image below shows the label being up to date with the latest deposit which can be seen on the client lines.
Also tested SMW and ALTTP if their clients broke with my changes and they didn't. Worked fine.
=> SNIClient: Let clients based on SNIClient monitor packages via on_package method

NetUtils.py
add the pickle by value mixin to HintStatus so it works on a weird subset of python where enums don't do that by default
```py
from NetUtils import HintStatus
import pickle
from Utils import restricted_loads
x = {"thing1": HintStatus(1), "thing2": HintStatus.HINT_UNSPECIFIED}
y = pickle.dumps(x)
restricted_loads(y)
```
crashes on 3.11.4 without this change, doesn't crash with the change
=> Core: Pickle hints by value

worlds/messenger/__init__.py
Turns out the steam version puts the game in a folder called "The Messenger", but the epic version puts the game in a folder called "TheMessenger". Fun.
Generated a seed with the expected args and checked it still works.
=> The Messenger: reduce strictness of output path check

worlds/stardew_valley/options/options.py
Short version: Hide the "Mods" option from the simple options page.
Long version: A long time ago, the first time modded content was discussed, I originally predicted that the average Stardew player would not be tech-savvy enough to figure out mods and that would drastically increase the amount of tech support we need to do. But back then, an OptionSet did not show up on the options page, so I figured it was fine, as the average player would not even realize the option exists.
Later, at some point, the website UI was improved and can now display OptionSets. This is generally good, but in this case, it has had the side effect of unleashing mod support upon the type of player that doesn't know what a screenshot is, let alone a file system. Furthermore, SVE itself (the most popular mod I …
=> Stardew Valley: Hide the Mods from the simple options page

Utils.py
Closes #4337.
This affects builds with non-writable installation directories. Instead of saving data in `~/Archipelago` we now use `$XDG_DATA_HOME/Archipelago` (defaulting to `~/.local/share/Archipelago`).
If ~/Archipelago still exists we move it to the new location and link `~/Archipelago` to it.
Motivation: This follows the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/) to at least some degree and doesn't clutter the user's home directory.
I ran the AppImage once while still having a `~/Archipelago` dir and it moved it correctly and put a working symlink at `~/Archipelago`.
=> Linux: move the user home Archipelago dir to $XDG_DATA_HOME

worlds/pokemon_rb/regions.py
Removes an erroneous logical requirement to have the Poké Flute to reach Route 12-W from Route 11-E. The actual spot you need the Poké Flute is in Route 12 just beyond a hidden item location, so this location was logically requiring Poké Flute. The Sleeping Pokémon location (in Route 12-W) as well as the connections to Route 12-N and Route 12-S all require Poké Flute, so everything else should work as expected without this rule here.
I have not tested this yet
=> Pokémon R/B: Fix Route 11-E to Route-12-W logic

MultiServer.py
https://github.com/ArchipelagoMW/Archipelago/blob/main/MultiServer.py#L181 claims that Context.groups is a `dict[int, set[int]]`
However, in https://github.com/ArchipelagoMW/Archipelago/blob/main/MultiServer.py#L447-L448 it is assigned something that is a `dict[int, list[int] | tuple]`, because NetworkSlot.group_members is `list[int] | tuple`.
So far this went unnoticed, because we only used generic collection operations on the values of this dict.
However, in https://github.com/ArchipelagoMW/Archipelago/pull/3506, we introduced this line: https://github.com/ArchipelagoMW/Archipelago/blob/main/MultiServer.py#L677, which uses an actual set-exclusive operator `|`
This fixes the typing, and that crash, by actually converting to a set.
Tested:
Not really, just confirmed that PyCharm/mypy is …
=> MultiServer: Correct tying of Context.groups, fixing a crash with hints

data/lua/connector_bizhawk_generic.lua
The script is supposed to print a warning for new bizhawk versions and then proceed, but it got mistakenly put in an incorrect `elseif`.
Ran the script on BizHawk 2.10 (before changing the version it checks) to see the warning and see it start working.
There's nothing in the 2.10 patch notes to suggest any sort of breaking change with this script as far as I can tell. It worked fine for a quick test. I'll continue to use 2.10 to make sure it works.
=> BizHawkClient: Fix version warning not falling through to regular execution

Options.py, docs/options api.md
fix a typo in which class rich_text_options_doc is set on
addressed #4461
I used the bool in #4079
=> Docs: Fix typo in Rich Text Options flag documentation

worlds/_bizhawk/context.py
`Patch.create_rom_file` returns a metadata object such that rom clients can immediately connect to the room tied to the patch file should one exist (ie WebHost). BizhawkClient currently just discards this metadata without properly setting it, so we return the metadata and properly set `args.connect` from it.
Hosted a room with MM2 and downloaded the patch file. Patched the file and watched as BizhawkClient was able to connect to the room by itself.
=> BizhawkClient: set metadata from patch file

worlds/factorio/Options.py, worlds/factorio/test_file_validation.py
For a Factorio game, I hand-modified a YAML file in an attempt to increase the richness of ore patches. This is a subset of the YAML:
---
name: <me>
game: Factorio
Factorio:
world_gen:
autoplace_controls:
iron-ore:
richness: 20
---
This is invalid because it is required that 0.166 <= richness <= 6. The YAML-checker tool (archipelago.gg/check) showed that there was an error, but it could have been more helpful:
[...] Key 'iron-ore' error: Key 'richness' error: <lambda>(20) should evaluate to True
That does identify the unacceptable value, but it doesn't really tell me what's wrong.
This commit improves the error message; now it will say "20 is not between 0.166 and 6" instead of "<lambda>(20) should evaluate to True".
This only improves error messages for invalid Factorio world-generation …
=> Factorio: improve error message for config validation

worlds/aquaria/__init__.py
Moving the Regions initialization from the module `__init__` to the `generate_early` method so that item link can work.
I generate 100 single player and multiplayer multiworlds.
=> Aquaria: Fixing itemlink not working

worlds/faxanadu/__init__.py
Because itemlinks can call `create_filler` using the linking world and Faxanadu created `filler_ratios` in `create_items`, which is not called for linking worlds, it would be empty and couldn't be used. This creates an initial `filler_ratios` in `__init__` instead.
This sets the weight for Poison to be a default of 0 and then modifies it to the regular value of 13 if poisons are included. This is done so that itemlinking worlds don't get poison added when they didn't want it.
Generations and the itemlinking test PR.
=> Faxanadu: Fix generations with itemlinks

test/general/test_implemented.py
Adds a test that worlds don't submit items/locations/regions to the multiworld during `__init__`
The test fails for Aquaria. (Fixed in https://github.com/ArchipelagoMW/Archipelago/pull/4473)
=> Tests: No Creating Items/Locations/Regions in __init__

worlds/blasphemous/__init__.py
Technically nothing. This just moves changes to local/non-local items to be in `generate_early` instead of `create_items`
Generating a multiplayer game and seeing "Thorn Upgrade" added to local_items for the player that had thorn_shuffle set to local_only
=> Blasphemous: Move Locality Changes Earlier

Utils.py
Originally written by Zunawe, I figured this should be in core since it's very useful for newer devs to be able to see which regions are reachable.
Test gen with the example code.
woe be upon thee, for I have too many regions
=> Utils: Visualize Regions showing the reachable regions in color

worlds/alttp/Items.py
Itemlinks could call `create_filler` with a dummy/itemlinking world, which calls `GetBeemizerItem` and checks `world.beemizer_total_chance[player]`, throwing a KeyError. This makes it so that itemlink worlds never replace items with traps. This made sense to me as a default behavior and it allows itemlinks to work.
Generated some itemlinking multiworlds and ran the itemlinking test.
=> ALttP: Fix Itemlinks

worlds/ladx/__init__.py
Moves the LADX changes to local/non-local items into `generate_early`. This moves the whole block of code and just adds a variable to the world for later use. The main motivation here is to move locality code earlier and simplify some of the code in `main.py`
Generations (with checking spoiler logs that hit these code paths) and unit tests.
=> LADX: Move Locality Changes Earlier

MultiServer.py
Alternative to https://github.com/ArchipelagoMW/Archipelago/pull/4482 that just "restores the old jank"
=> MultiServer: Revert hints being created for already found locations

pytest.ini
Fixes mistake introduced in #4500 
The typo disabled a bunch of tests :S
=> pytest: fix typo in pytest.ini

worlds/ahit/DeathWishRules.py, worlds/ahit/Locations.py, worlds/ahit/Rules.py
Fixes various logic issues in A Hat in Time. Most are where logic was overly restrictive, but a few are where logic was too lenient and could have rarely created impossible seeds.
The most notable fix is for the missing Hookshot logic for `The Arctic Cruise - Toilet` from `Bon Voyage!` with existing access to `Cruise Ship` only through `Rock the Boat`, which has resulted in impossible seeds being reported a couple of times.
The rules were being added to for the "Director" boss in `set_enemy_rules()`, which didn't exist because the boss created was called "Conductor" instead.
The name of the boss has been changed to "Director", to match, because it is more accurate due to DJ Grooves possibly being the boss instead of The Conductor.
The missing logic was the `Hookshot Badge` requirement, …
=> AHiT: Various logic fixes

worlds/tunic/__init__.py
Currently, if one player chooses 1% local fill and another chooses 99% local fill, it'll take 1% of the first player's filler and 99% of the second player's filler and fill them equally across both games. That's dumb, so now it'll take the same number of locations as items, so they get as many filler locations as they put in filler.
Test gens.
=> TUNIC: Make the local_fill option load in a specific number of locations

worlds/ladx/LADXR/locations/itemInfo.py, worlds/ladx/__init__.py
Items with a `"` break the LADX patching, `_` doesn't display well.
`"` issue reported here: https://discord.com/channels/731205301247803413/1316960757526695997/1329539545250664488
generates, will go in beta
=> LADX: Swap out invalid characters in item names

LinksAwakeningClient.py
The bug is the following: if you launch the ladx client, connect to the server then attempt to close without connecting the client to retroarch/bizhawk, the client will just hang.
I put a bandaid there so that it stopped happening since it has been at least a year since I submitted this bug report. A proper sync like the other clients would be cleaner in the future
By opening, connecting then closing
Before:
After:
=> LADX: Closing the client window closes the window

data/lua/connector_oot.lua
It changes the name of the "receive" function in order to have compatibility with other scripts using the same name (in this particular instance, it was tested with Crowd Control).
Created a run with at least 2 worlds, added both CC's and AP's scripts to Bizhawk (patching the script with AP's .apz5 file, then adding the resulting .z64 to CC).
Released one of the worlds and got the items in game properly.
Sent an effect through CC, and also got the effect properly.
=> OoT: Allow Crowd Control support for Ocarina of Time (Bizhawk)

MultiServer.py, docs/network protocol.md
Alternative / generic solution for https://github.com/ArchipelagoMW/Archipelago/pull/3117
Upside of this one being that clients do not need to change to support the new EnergyLink protocol.
Tested: Ran `MultiServer.py --log_network`, connected with a client that sends datastorage Set operations, verified that outgoing SetReply packets contain `slot: 1`
=> MultiServer: Add slot to SetReply packets

CommonClient.py, worlds/alttp/Client.py, worlds/factorio/Client.py
check_locations, a method that filters location checks before potentially bothering to send stuff over the wire
once with Factorio.
Also included is LttP which hopefully someone tests at some point, though it should be fairly safe if Factorio worked.
=> CommonClient: implement check_locations to send missing locations only

worlds/pokemon_emerald/client.py
Utilizes #4484 for Emerald. Benefits from shortening the list of sent locations to just missing.
Ran a game with the network logged, picked up a few locations, closed everything down, collected a few locations offline before rejoining to trigger it sending multiple locations at once. Saw the server acknowledge the locations and saw that it was only receiving the missing ones.
=> Pokemon Emerald: Use new `check_locations` helper

Generate.py, settings.py
https://github.com/ArchipelagoMW/Archipelago/pull/3028 added timestamps to all logging output.
Then, https://github.com/ArchipelagoMW/Archipelago/pull/4266 made this optional via an arg and added a setting for it for MultiServer.py. This effectively *turned off* timestamping for Generate.py again, because the default for the new arg is `False`.
This PR now aims to do the same thing 4266 did but for Generate.py, adding a CLI arg & setting to GeneratorOptions that allows turning on timestamps.
Also, adds `log_level` as a setting to GeneratorOptions, for parity with MultiServer.
=> Core: Make log time an optional arg & setting for Generate.py as well

worlds/ffmq/__init__.py
FFMQ's `collect_item` previously returned names (modified state) for non-progression items and did not handle `remove` properly. This fixes both of these things.
This was tested using a fixed version of https://github.com/ArchipelagoMW/Archipelago/pull/2062 following Qwint's deepcopy comment. FFMQ failed the tests before these changes and succeeds after them.
=> FFMQ: Fix collect_item

worlds/smz3/__init__.py
Moves the changes to `non_local_items` from `create_items` to `generate_early`. The primary motivation for this is a future PR requiring that local/non_local options not be changed after `generate_early`, which helps to cleanup some of the code in `Main.py`
Local generations with items in non_local_items with and without Keysanity enabled to see that items were properly removed. Also just printing the frozenset in `generate_early` and `create_items` to see that they were identical with various random yamls
=> SMZ3: Move non_local_items Changes Earlier

worlds/tunic/__init__.py
It wasn't creating `fill_locations` with only 1 player, so it would crash around there since it couldn't find `fill_locations`.
Test gen.
=> TUNIC: Fix failure in 1-player grass

Main.py, docs/entrance randomization.md, docs/world api.md, test/benchmark/locations.py, test/general/__init__.py, test/general/test_entrances.py, test/general/test_items.py, test/general/test_locations.py, test/general/test_reachability.py, worlds/AutoWorld.py, worlds/kh1/Regions.py, worlds/kh1/__init__.py
There is a lot of history for this, but basically, for Item Plando (using the upcoming [rewrite](https://github.com/ArchipelagoMW/Archipelago/pull/3046)) and Generic Entrance Randomizer to work well together, there is a specific timing window that has to be satisfied. The easiest way to do this is to add a new `connect_entrances` world stage.
When entrance source/target regions have to be finalized is also currently undefined, which has lead to some minor debate. This should prevent this from being up for discussion in the future.
=> Core: Add connect_entrances world step/stage

docs/world api.md
Docs: Correct outdated documentation in world api.md about location ID uniqueness
Previously the docs stated that location IDs must be unique across all games, which is no longer the case
Discussion on Discord
=> Docs: Update outdated info in World API docs

worlds/tunic/__init__.py, worlds/tunic/grass.py
Currently, grass has its own location name group. Someone brought up that if they excluded Guard House 1, they'd assume that it would exclude the grass in there too, but currently they'd have to also exclude Guard House 1 Grass.
So, the grass should probably go in the group too.
Unit tests, no test gens yet because I am at work and am a very good employee.
=> TUNIC: Make grass go in the regular location name group too

worlds/hk/__init__.py
adds a .value to potentially fix a codepath where this value persists to slot data
reported by user
```
File "/Projects/APBeta/MultiServer.py", line 836, in server
await process_client_cmd(ctx, client, msg)
File "/Projects/APBeta/MultiServer.py", line 1984, in process_client_cmd
await ctx.send_msgs(client, [args])
File "/Projects/APBeta/MultiServer.py", line 325, in send_msgs
msg = self.dumper(msgs)
^^^^^^^^^^^^^^^^^
File "/Projects/APBeta/NetUtils.py", line 116, in encode
return _encode(_scan_for_TypedTuples(obj))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/json/encoder.py", line 200, in encode
chunks = self.iterencode(o, _one_shot=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/json/encoder.py", line 258, in …
```
=> HK: Save GrubHuntGoal by value

Fill.py
adds a retry to priority fill in case the one item per player optimization would cause the priority fill to fail to find valid placements
this is beneficial over just current main's turn it fully off because other multis need the optimization to have a reasonable time to finish
gen'd with a bunch of copies of the witness yaml in #3467 (after confirming just turning one_item_per_player back on and not adding the retry step caused the failures), though more testing of other configurations would be appreciated 
did not test the large-multi usecase to notice the speedup
=> Core: Add Retry to Priority Fill

worlds/factorio/__init__.py
Removes a print that is a leftover from debugging
Apparently this found a bug outside of Factorio, so it was far more successful than it should have been.
=> Factorio: remove debug print

worlds/tunic/options.py
Setting it too high can sometimes lead to a late gen failure due to not enough spots left for progression items. This can be reverted once fill can swap out swaps prefilled with filler.
I changed a number.
=> TUNIC: Reduce range end for local_fill option

test/general/test_entrances.py, worlds/alttp/Rules.py, worlds/factorio/__init__.py
Fixes https://github.com/ArchipelagoMW/Archipelago/issues/4527.
In https://github.com/ArchipelagoMW/Archipelago/pull/4420, we added a new step called connect_entrances.
The description of this step reads: "By the end of this step, all Entrances must be connected".
However, there are some worlds that are relying on other worlds not having any dangling entrances in set_rules (which is before connect_entrances).
The culprit here is get_all_state, which does region sweeps on all worlds.
Conveniently, get_all_state has an `allow_partial_entrances` kwarg.
So, this PR adds that arg to the two "offending" worlds, and adds a unit test to ensure that it is used.
=> Core: Fix worlds that rely on other worlds having their Entrances connected before connect_entrances, add unit test

worlds/ahit/docs/setup_en.md
Fixes a broken link to the AHIT Steam workshop mod that had double parentheses for some reason
By clicking the link
=> AHIT: Fix broken link in setup guide

MultiServer.py
* Significantly reduces the traffic (and syscalls and async task switches) for messages produced by !release and /release:
* **before:** single print compressed to 90-100 bytes on the wire \
90-100 bytes on the wire per print - 1000 item release with 300 clients = 28.5MB \
1 ws message per item per connected client - 1000 item release with 300 clients = 300k
* **after:** 140 prints compressed to 1300-2600 bytes on the wire \
9-18 bytes on the wire per print - 1000 items release with 300 clients = ~5MB \
1 ws message per 140 items per connected client - 1000 item release with 300 clients = 2.4k
* Sorts release by receiver and items, which
* makes the output a lot nicer to parse by humans that are looking for what they got
* allows for better compression in very specific cases, probably not …
=> MultiServer: optimize PrintJSON for !release

worlds/factorio/__init__.py, worlds/shivers/__init__.py
#4519 notes an issue where factorio is forcing a cache save on CollectionState before set_rules finishes and shivers uses cached state in pre_fill, so if factorio's slot runs before shivers's the shivers indirect connections are not registered for the state used in prefill which makes regions unreachable and fails to fill
this is not the only approach that fixes the problem, but both of these changes independently make sense to me
tested each of these changes individually with default yamls for both games, also confirmed slot order matters by moving the shivers yaml before the factorio yaml by renaming
=> Shivers: Stop using get_all_state cache to fix timing issue

CommonClient.py
adds docstring to make_gui describing what things you might want to change without dealing with kivy/kvui directly (there are better places to document those)
eyeballs
=> CC: Expand on make_gui docstring

worlds/kdl3/rules.py
There's just been an entire set of rules missing since the initial merge of KDL3 that only causes an issue on a single settings combination. This creates unbeatable worlds by not accounting for logical requirements for stage completion, which would block access to the level's boss.
```yaml
Kirby's Dream Land 3:
strict_bosses: "false"
open_world: "true"
ow_boss_requirement: 6
```
Watched the generated spheres no longer contain all 5 levels by sphere 5.
=> KDL3: Fix world access on non-strict open world

worlds/pokemon_emerald/locations.py, worlds/pokemon_emerald/options.py
Cleans up what was added in #4165 and adds sphere 1 fly locations as default-blacklisted options.
Generated and checked the free fly location in the debugger.
=> Pokemon Emerald: Clean up free fly blacklist

worlds/kh2/Client.py
Tested: No but I'm like 99% sure it's fine
=> KH2: Use int(..., 0) in Client

worlds/mm2/options.py, worlds/mm2/rules.py
Two issues:
* `plando_weakness` was completely nonfunctional due to not converting the strings found in the yaml to their int counterparts
* Picopico-kun and Boobeam Trap weakness special cases were not properly being checked as the case where they would occur would pass the earlier check for an insufficient weakness.
Seed 89649562947386879912 on a default yaml with `random_weakness: shuffled`. On current main, Atomic Fire is picked up before moving past Wily Stage 4, with this change Metal Blade is required instead.
Plando was tested with the following plando.
```yaml
plando_weakness:
Air Man:
Mega Buster: 0
Atomic Fire: 14
Air Shooter: 0
Bubble Lead: 0
Leaf Shield: 0
Quick Boomerang: 0
Crash Bomber: 0
Time Stopper: 0
Metal Blade: 0
```
=> MM2: fix plando and weakness special cases

MultiServer.py, NetUtils.py, docs/network protocol.md
Part of the 300 player sync performance problems, hopefully.
Also some minor typing.
Connecting with my demo clients with various tags and compression/no compression.
=> MultiServer: implement NoText and deprecate uncompressed Websocket connections

test/general/test_memory.py
With the growing number of worlds, GC becomes the bottleneck and slows down the test.
It's not easy to track down actual time difference, because the GC run may also clear other tests' memory.
pytest
=> Tests: massively improve the memory leak test performance

worlds/stardew_valley/test/mods/TestMods.py
This removes one test that generate one world for each trap option, plus the magic mod. 
The magic mod does not add or remove any trap... Kaito said that a mana loosing trap was discussed at one point, maybe? If it comes, we can add the test again. 
Yes
N/A
=> Stardew Valley: Remove weird magic trap test?

worlds/stardew_valley/data/locations.csv
The slot machines added in the latest Luck Skill update were added to craftsanity, but turns out the last one requires a ginger island resource, so this makes it into a ginger island check
One of the shotgun tests ;)
=> Stardew Valley: Radioactive slot machine should be a ginger island check

worlds/stardew_valley/test/mods/TestModsFill.py
Black Sliver suggested this, from https://github.com/ArchipelagoMW/Archipelago/pull/4578
Adds two tests, that run the full base test suite including fill, for modded content without ginger island. One checks cooking recipes, the other checks crafting recipes, both have the related goal.
The new crafting test currently fails. It'll pass once https://github.com/ArchipelagoMW/Archipelago/pull/4578 is merged.
=> Stardew valley: Add Mod Recipes tests

settings.py
alternative to #4452
issue was an apworld that defined
```py
class mySettings(settings.Group):
pass
```
and added it as their world.settings type hint to register it, causing late crashes 
while the previous solution tried to crash the world early enough to not affect other worlds' settings, this pr instead aims to accept an empty Group as valid and to handle an empty dict type cache directly
export empty groups as an empty dict instead of crashing
made emerald null out their settings class
on an empty file exported as
```
pokemon_emerald_settings:
{}
```
`get_settings().pokemon_emerald_settings` returned the class which did not have attributes as expected
reverting emerald changes and re-saving the file populated the section as expected
```
pokemon_emerald_settings:
rom_file: "Pokemon - …
```
=> Settings: Handle empty Groups

worlds/ladx/__init__.py
This fixes the consistent generation error on minimal accessibility, which was caused by calling fill_restrictive with a state including `An Alarm Clock`, which is the victory item.
The solution makes the correct state to apply `fill_restrictive` with dungeons to.
I've tried several scenarios (see one of my comments), I also did 1000 generations on purely random settings without issues.
=> LADX: Fix generation error on minimal accessibility

kvui.py
Avoids users facing this issue: https://discord.com/channels/731205301247803413/731205301818359821/1335120260998758461
I saw it make a folder on windows next to the datapackage cache:
/Archipelago/Cache/datapackage
/Archipelago/kivy/mods
are now both valid folders in my local appdata.
=> kvui: set home folder to non-default

settings.py
Fixes #4595. Used Mysteryem's suggestion verbatim.
Deleted Jak's section in my host.yaml, ran the launcher, click "Open host.yaml." The section regenerated, this time with the correct docstring.
N/A
=> Core: Fix #4595 by using first type's docstring in a union type

worlds/kh2/Rules.py
All weapon slot locations use the logic of the Ultimate Mushroom Slot because the runtime variable of the loop (location) is not captured properly.
This also crashes because some weapon slots don't have an exclusion_table item defined. I don't really know what to do about that as I don't know anything about the game.
=> KH2: Fix lambda capture issue with weapon slot logic

settings.py
Add custom exception text for host.yaml failing parsing because 1) it's hard for people without the knowledge to notice host.yaml is the problem 2) it's very often unescaped \ characters from copy/pasting explorer paths on windows causing this exception to be thrown
by all means suggest a better import scheme and/or error text, I just wanted something down because i've had to handle this support question too many times
mucked up my host.yaml and ran get_settings()
=> Settings: add error message to identify host.yaml parsing failures

test/general/test_state.py
Ensures worlds leave state in a state where get_all_state works correctly on default settings.
locally, on which it passes for everything currently in main. However, based on https://discord.com/channels/731205301247803413/1336559625356705863/1336559625356705863, it should guard main from this failing if it gets merged first.
=> Test: ensure get_all_state() does not error in between steps

LttPAdjuster.py
mocks worlds[1].random in addition to per slot randoms now that lttp code is moved to using that
fixes a crash a user reported because `apply_rom_settings` was passed in a multiworld but that multiworld didn't have a worlds dict
I made sure making an instance from a python shell returned what i think it should, but did not test running the adjuster
=> Lttp Adjuster: mock world.random 

CommonClient.py
an invalid version rejection isn't going to change by attempting again
changed my utils version to trigger the connection rejection and saw it not reconnect
=> CC: don't try to reconnect on invalid version

worlds/stardew_valley/content/vanilla/base.py, worlds/stardew_valley/options/options.py, worlds/stardew_valley/options/presets.py
- Powdermelon growth season fixed to winter, it was mistakenly set as summer
- Fixed several option tooltips that were inconsistent, unclear, or otherwise improved
- Fixed one preset that had exclude ginger island yet was enabling walnutsanity
Unit tests, and also ran the webhost locally to look at my changes
=> Stardew Valley: Fixed Powdermelon and option inconsistencies

docs/world api.md
it wasn't right
it's right now
=> Docs: clean up create_item/event example

WebHostLib/static/assets/faq/en.md
"Archipelago supports multi-game multiworld." should be "Archipelago supports multi-game multiworlds."
=> Add missing plural in faq on website

worlds/celeste64/docs/guide_en.md, worlds/sa2b/docs/setup_en.md
- Updates the Linux portion of the setup guide to have the user download the .NET Desktop Runtime through the Mod Manager rather than needing to maintain a link to the correct version.
- Refactors the Linux setup guide a bit to be a bit nicer and clearer.
- Updates the .NET Desktop Runtime link at the top of the page to point to .NET 8, since I didn't change the Windows part of the guide to suggest downloading .NET through SAModManager.
- Also added a small Linux and Steam Deck setup guide for Celeste 64 to this. I figured this being in the same PR would be okay since they have the same maintainer. I can split it out into a separate PR if desired.
Tested via reading the rendered markdown on Github:
=> Docs: Update SA2B Linux and Steam Deck Setup Guide + Add Celeste 64 Linux Setup Guide

entrance_rando.py, test/general/test_entrance_rando.py
uses itempool count vs unfilled location count instead of counting prog_items values which could have custom counters
using #4402 with limited_movement + ER causes unreachable transitions with a shard counter in prog_items, before this change it errors after this change it generates successfully
=> GER: Use Itempool Count for Minimal handling

WebHostLib/customserver.py
Alternative to #4647 that keeps the static datapackage optimization but disables it if an old game was detected.
Wasn't
=> customserver: ignore static datapackage optimization for old games

worlds/tunic/combat_logic.py, worlds/tunic/er_rules.py, worlds/tunic/items.py, worlds/tunic/test/test_combat.py
Primarily, this fixes the Gun being missed from the combat_items list, since that had caused a failure where the gun was collected and the logic got weird afterwards. Testing with the failure seed treble provided, just that one-line change fixed the seed.
Other than that, I did the following:
- Very slightly refactored check_combat_reqs to remove a very unnecessary check for if you have magic, when we're already doing a changeover to "what if you didn't have your melee weapon?" down below.
- Changed the combat requirements for one location from a boss name to a non-boss name, since that location shouldn't strictly require a sword
- Added a new test to make sure the cache is actually working properly
Unit tests
=> TUNIC: Fix Gun being missing from combat_items, and some misc combat logic changes

MultiServer.py
Fixes https://github.com/ArchipelagoMW/Archipelago/issues/4654?notification_referrer_id=NT_kwDOA3N8G7QxNDgzMDI4MTQ3MDo1NzkwMDA1OQ#issuecomment-2661594964
There are two things going on here:
Problem 1: `get_hint` doesn't check that hint.finding_player == finding_player. This being necessary seems strange initially, but basically, each hint is present in both the finding player's **and** the receiving player's hint store.
Problem 2: The call to `get_hint` uses a variable from a different scope, in a way that I don't think was intended.
Barely, just tested that it resolves the issue at hand, not whether it breaks anything else, and had a cursory glance at the other two usages of `get_hint` to see if they still make sense.
=> MultiServer: Fix hinting an item that someone else already hinted in their slot not resolving correctly

worlds/factorio/Options.py
prevents < 1 item counts in starting items
```
starting_items:
burner-mining-drill: 0
raw-fish: 50
stone-furnace: 4
schema.SchemaError: amount of starting items has to be a positive integer
```
=> Factorio: prevent invalid starting items count

.github/workflows/ctest.yml, test/cpp/CMakeLists.txt
* gtest (the test runner/lib) now links to libc dynamically on windows (`/MD`). This updates the CMakeLists.txt to link dynamically
* updates cmake version in CMakeLists.txt to get rid of a warning
* also fixes a typo that would make changes to CMakeLists.txt not triggering the workflow run
CI
=> CI: fix native tests toolchain on windows

worlds/dark_souls_3/docs/setup_en.md
This adds a link to the new map tracker and adds information on
troubleshooting common issues that have come up in the Discord.
=> DS3: Update setup documentation

worlds/noita/items.py
It was trying to delete the Greed Die from the filler pool when it wasn't in there to begin with.
This just sets the weight to 0, which should be much safer.
Test gen.
=> Noita: Fix bug with Traps disabled in 1-player games

entrance_rando.py
This fixes the fact that the passed `exits` parameter is completely ignored during ER.
* When finding placeable exits, rather than iterating all unpaired blocked connections, we instead iterate the unpaired requested exits and check if they are blocked.
* When performing speculative sweep, it now ensures that one of the requested exits is available after the placement, rather than any exit.
I think this fix is really hard to unit test well without being overly dependent on implementation details and the provided seed. We would need to somehow know that the non-requested entrances are directly passed up (rather than just getting lucky they didn't get randomly chosen). From a practical perspective, there is a world in development facing this issue which can confirm the fix. The existing …
=> Core: Only consider requested exits during ER placement and speculative sweep

worlds/mm2/rules.py
Just minor seed bleed caused by not copying the inner lists within the weapon_damage dict.
Put a debugger on a MM2 generation with shuffled weaknesses, watched static `weapon_damage` not change after `world.weapon_damage` was set.
=> MM2: fix seed bleed from shuffled weaknesses

worlds/messenger/__init__.py, worlds/messenger/rules.py, worlds/messenger/test/test_shop_chest.py
For some reason i was doing max(1, required_seals) in the rules, but not when creating items, making it possible for someone to have 0 required seals at the time of item creation (causing them to all be filler), but then they were still required for the completion condition.
debugging, same way it was found, but also added a test :)
=> The Messenger: do max on the initial math instead of doing it later

worlds/tunic/er_rules.py, worlds/tunic/rules.py
Adds lantern as a requirement for a chest in a lit section of an otherwise dark area. It didn't originally require lantern as it seemed easy enough to navigate to through a short dark section, but players requested it be changed.
Test gens
=> TUNIC: Update logic for chest in fortress dark area

worlds/stardew_valley/content/vanilla/base.py, worlds/stardew_valley/logic/logic.py, worlds/stardew_valley/strings/fruit_tree_names.py
There was a conflict with the rules of the Tea Sapling that was probably introduced with the 5.x.x update when Craftsanity was added. The previous rule was not removed when the proper crafting rules were introduced. This would create an additional option in the logic to obtain the Tea Sapling, which would only require Wood and Fiber, without considering access to the actual recipe. 
Simply removing the rule fixes the issue.
Looking at the `/explain_item Tea Sapling` with the removed rule. Notice the part with `Has Wood (item) & Has Fiber (item)` is no longer there.
N/A
=> Stardew Valley: Fix a logic bug where the Tea Sapling would be considered available without having the recipe

worlds/_bizhawk/context.py
Right now, order matters if a world client wants to use `CommonContext.seed_name` to validate that the player is connecting to the right seed. The connection to the emulator must be made (and the world client must read the seed name from the emulator) before the player connects to the server, otherwise `CommonContext.seed_name` will still be `None` when `RoomInfo` is received, so no validation happens, and then the world client can't retroactively check, because the seed name isn't stored anywhere.
So this just catches the seed name and stores it on the context so that a world client can do its own validation if the connection to the server has already been made.
Wasn't
=> BizHawkClient: Store seed name sent by the server for clients to check

Utils.py
#4054 forgot that plando texts also got a NamedTuple added, so they also need to be added to the inclusion list.
Attempted to generate LttP with plando texts on WebHost, fails without this change.
=> Core: fix pickling plando texts

.github/workflows/build.yml, .github/workflows/release.yml
This fail happened:
https://github.com/ArchipelagoMW/Archipelago/actions/runs/13755483960/job/38487067285?pr=3736
This is because of a new version of PyGObject releasing on PyPi which has a dependency which is incompatible with Debian 20 and 22, you can read more about it here:
https://github.com/beeware/toga/issues/3143
=> Band-aid Linux Build breaking with the release of PyGObject 3.52.1

worlds/pokemon_rb/rock_tunnel.py
This pull request fixes (as of yet unreported) issues with the optional randomization of Rock Tunnel's layout in Pokémon Red and Blue.
The randomization feature was designed to create a cave layout, which - like in the base game - creates one linear path through the tunnel, using every ladder connecting the two floors.
Currently, the function occasionally creates the following on the bottom floor:
- Rocks with their top half missing (see screenshot below)
- Gaps in the walls, connecting all four ladders
- Rocks cutting off one ladder from the other three (happens rarely)
According to my tests, those are the only issues with the randomization; they are now fixed.
- Python code to mass verify that seeds produce valid caves (i.e.: no incomplete rocks, one path through)
- Python code to print …
=> Pokémon R/B: Fix Rock Tunnel B1F randomization

worlds/landstalker/Constants.py, worlds/landstalker/Hints.py, worlds/landstalker/Items.py, worlds/landstalker/Locations.py, worlds/landstalker/__init__.py, worlds/landstalker/data/world_node.py, worlds/landstalker/data/world_path.py, worlds/landstalker/data/world_region.py, worlds/landstalker/data/world_teleport_tree.py, worlds/landstalker/docs/landstalker_setup_en.md
This PR fixes a bunch of small issues encountered during the last few months with Landstalker:
- rare generation issues revealed by the AP Fuzzer tool (https://discord.com/channels/731205301247803413/1342273269713080380)
- cases of duplicate entrance names when using a specific set of options
- some endgame locations not being properly removed when playing with a short goal
- a fix regarding dynamic shop prices (using spheres) where it could be wrong if progression balancing occured (changes by @Exempt-Medic)
- etc...
Ran a few seeds with the fixes done, all working fine.
Ran a large AP Fuzzer batch to ensure there were no more issues.
=> Landstalker: Several small fixes

worlds/oot/data/LogicHelpers.json, worlds/oot/data/World/Overworld.json
In Zora's Domain, there are 3 beehives that only appear as Child Link. The current logic checks if Child Link has access to the area and if Child Link or Adult Link can break beehives. The problem is that these beehives do not appear to Adult Link, so if Child Link has access to the area and Adult Link can break beehives, but Child Link cannot, these 3 locations are still considered to be in logic even though they would be unobtainable.
Example can be seen in [this async](https://archipelago.gg/sphere_tracker/rz5YP6RBTYuAaxhkPhiRvw) where the player Me555 has access to the location "ZD In Front of King Zora Beehive 1" in Sphere 3, but based on the player's settings, could only be obtained with the "Boomerang" which was obtained in Sphere 5. 
You can also look at [this …
=> OOT: Have beehives that only appear as a child not be in logic if only adult can break beehives

worlds/messenger/options.py, worlds/messenger/transitions.py
The connection plando works by having the user pass in the names of the regions, rather than the names of the entrances. Two of the connections actually use special names since they share the same parent region, so this adds special handling for those two connections, so they don't crash. This also makes it so that if the user specifies a one-way exit, it must also be a one-way entrance, and vice versa, because GER can't properly resolve these being uneven currently
Generated with minimal yaml with a few different plando connection combinations to check all the various edge cases.
=> The Messenger: fix some transition plando issues

worlds/cvcotm/__init__.py, worlds/cvcotm/docs/en_Castlevania - Circle of the Moon.md, worlds/cvcotm/docs/setup_en.md, worlds/cvcotm/rom.py
@dontjoome some time ago managed to dump and test the Wii U VC version of Circle of the Moon to see if it worked, but it did not, and we determined that the reason why is because of code being shifted around into different places from where the patches expect things to be. The exact conversation can be found in the game's thread in future-game-design in the Archipelago Discord server. Due to the testing results, it now needs to be clarified that the VC version is completely unsupported, at least for now. The docs have been updated where they previously said VC was untested, and all usages of the VC ROM's hash are commented out so it should no longer be accepted (they can be easily uncommented back in if later needed).
Ensured the removal of the VC hash did not break anything by genning, …
=> CVCotM: Clarify the Wii U VC version is unsupported

AdventureClient.py, CommonClient.py, FF1Client.py, LinksAwakeningClient.py, MMBN3Client.py, MultiServer.py, OoTClient.py, SNIClient.py, UndertaleClient.py, WargrooveClient.py, Zelda1Client.py, worlds/_bizhawk/context.py, worlds/ahit/Client.py, worlds/factorio/Client.py, worlds/kh1/Client.py, worlds/kh2/Client.py, worlds/sc2/Client.py, worlds/zillion/client.py, worlds/zork_grand_inquisitor/client.py
This PR fixes a crash related to colorama when trying to log non-ascii characters as seen in https://discord.com/channels/731205301247803413/1339934780283682846 and https://discord.com/channels/731205301247803413/1323760193917685842. If your world was using colorama.init() that call has also been replaced.
Originally tested with the changes just in CommonClient.py and location/item names containing é from the Pokemon Platinum manual did not cause the client to freeze up. When compared with the regular unmodified 0.5.1 text client, it did not have the freezing problem. When the client freezes it spams the log with error messages leading to very large log files. I also tested this on the main branch with and without the change and I saw a noticeable difference.
=> Core/Various Worlds: Fix crash/freeze with unicode characters

worlds/sc2/docs/en_Starcraft 2.md, worlds/sc2/docs/fr_Starcraft 2.md, worlds/sc2/docs/setup_en.md, worlds/sc2/docs/setup_fr.md
Added the following to SC2 documentation:
- Description that the order of the missions can also be randomized
- Explicit mention of AP collect and what it does. It is a recurring question in SC2 channel.
- Issue resulting from mission order progress being tied to Victory location. Mostly prevalent due to AP collect on goal. 
I used a writing assistant to check the text and hosted the website locally to make sure that the rendering was okay.
None
=> Docs: SC2 - Add a description of mission order and the impact of collect on a SC2 world

WebHostLib/templates/weightedOptions/weightedOptions.html
Currently it says "This option is not supported", which is meant to mean "You cannot edit this option on webhost because no one wrote something to let you do that".
I think it would be better if it said "This option cannot be modified here". It's less confusing, mostly.
Reading.
=> Webhost: Update text for options you can't modify on webhost

CommonClient.py, MultiServer.py, WebHostLib/customserver.py, requirements.txt
updates websockets
Just a bit locally
=> Core: update websockets

.github/workflows/ctest.yml
This pins github actions where the repo is neither `actions` nor `github` to make supply chain attacks less likely.
CI; until the actions change, this will run the same code as before.
=> CI: pin some actions

Options.py
Adds the player ID int to the .csv file produced when running with --csv_output. Stems from discussion here: https://discord.com/channels/731205301247803413/1347003627180523602
Created a multiworld with 20 players, half Lingo and half LttP (somewhat arbitrarily). Gave the yaml files random names so the player IDs wouldn't be in game order, and viewed the output to confirm it was still default sorted by game, but contained the player IDs as well.
It doesn't.
=> Options: Add a column for player ID to --csv_output

worlds/messenger/rules.py
The rule is *technically* wrong but not very egregious. The self-locking being done on Corrupted Future when transition shuffle is definitely wrong though, since the entrance to that region can go anywhere. The other self-locking rules are still correct for transition shuffle, as the one leading to key of strength is not currently shuffled.
Had a seed where this was causing playthrough failure. Logically I know this is the correct fix but not really sure how to efficiently test it, since the failing seed potentially had other issues.
=> The Messenger: fix corrupted future rule

CommonClient.py, MultiServer.py, WebHostLib/customserver.py, requirements.txt
Reverts ArchipelagoMW/Archipelago#4732
This broke BizhawkClient, and likely more, due to the removal of `socket.closed` (to my understanding)
https://discord.com/channels/731205301247803413/731214280439103580/1351637766596722731
I think we should still do this upgrade of course, but it needs more testing next time
=> Revert "Core: update websockets"

worlds/alttp/Rom.py
Fixes a crash in generation when a player who is generating a game that has alttp, but has chosen to not install the sprites, so as a result, "data/sprites/alttpr" and/or "data/sprites/custom" are missing from the data directory.
Also made sure the base link sprite gets loaded, if it was not loaded, as a result of either the directories completely missing, or the file "data/sprite/custom/link.apsprite" is missing.
Ran repeated generations with and without the directories present.
=> [ALttP] Don't crash generation if sprite paths don't exist

worlds/hk/docs/setup_en.md
This adds redirect links to the setup instructions for Hollow Knight which use Lumafly's custom URL scheme to install mods
Read it, clicked the links on my branch to make sure they worked
=> Hollow Knight: Include Lumafly links to install mods

worlds/civ_6/Container.py
uses AutoPatchRegister on civ's APContainer to automatically register its output file and handle webhost using the handler to read the bytes
the BytesIO cutout is for a part of WebHostLib/upload.py which calls the constructor of the proper handler with the bytes, and then immediately calls read() to grab the player id, I'm not married to this particular handling of it, but without some handling the constructor fails
generated solo games on localhost and downloaded the patches
=> Civ6: Use AutoPatchRegister to make patch downloadable on webhost

BaseClasses.py, entrance_rando.py, test/general/test_entrance_rando.py
When calling `disconnect_entrance_for_randomization`, the target name of the created target was assumed to be the child region name. This is frequently not a useful assumption as the chosen name will end up in pairings and not be useful to the client which knows nothing about the region structure. Furthermore, it is currently not possible to access the created ER target at all to correct the bad assumption.
To resolve this, I added a `vanilla_target_name` attribute to `Entrance`. This is well-aligned with the typical programming model for ER where entrances are initialized from data and then ER happens much later; this way the data can just be updated instead of trying to keep track of it up until the disconnect call to pass as a parameter. This attribute is currently optional in all …
=> Core: Allow and require user-provided target name when splitting 1-way entrances for GER

test/general/test_patches.py
Adds a test that ensures that every registered `APPatch` has a game name that matches the name of a `World`. This is a test because if these two do not match up, then the patch will not show up as a downloadable file in a Webhost room.
Open to adjustments as I'm not quite sure this test is in the right file, or things I may have missed which might make the test clearer.
Tested on https://github.com/cjmang/Archipelago/tree/gstla which had a slight typo in their patch name. Results in
```
SubTest failure: Traceback (most recent call last):
File "C:\Users\deamo\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
yield
File "C:\Users\deamo\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 539, in subTest
yield
File …
```
=> Core: Add a test that checks all registered patches matches the name of a registered world

worlds/ladx/__init__.py
Fix for this bug report:
https://discord.com/channels/731205301247803413/1354129616670953572
Where LADX was failing generation over KH1's unconnected entrances during create_items
Using this solution:
https://discord.com/channels/731205301247803413/1354129616670953572/1354135524868362250
Generated with the yamls in the bug report thread
=> LADX: fix for unconnected entrances in other worlds

worlds/factorio/Client.py, worlds/factorio/__init__.py
ensures the number coming from lua scope as basis for energy link is an int, so it doesn't end up changing energy link to a float.
The way factorio works, this should only be a problem if increment is > max_int, then it should be a float in json, but supposedly this happened: https://discord.com/channels/731205301247803413/1010929117748809758/1353846406816862228
Wasn't.
=> Factorio: ensure increment is int

worlds/tunic/er_rules.py, worlds/tunic/rules.py
Atoll to Library rule:
Add laurels/orb requirement, so you aren't punished for enemy rando
Add sword/gun/wand requirement, so you can deal with the frogs at the northwest fuse
Swamp to Cathedral rule:
Add sword requirement for dealing with the bird and ghosts near the second fuse, it costs too much mana to reasonably require the magic weapons instead
Test gens
=> TUNIC: Update swamp and atoll fuse logic with weaponry

kvui.py
With the addition of the hint search bar, the type of the child of the TabbedPanel changed from HintLog to HintLayout. As HintLayout does not implement `fix_heights`, HintLog's `fix_heights` was never being reached. This simply implements `fix_heights` on HintLayout to call HintLog's `fix_heights`.
Manually by connecting to an AP server, hinting every item, and then attempting to rapidly scroll down the menu.
=> kvui: Fix hint tab formatting regression

worlds/cv64/rom.py
Fixes the following locations:
- Castle Center: Far-left near-side lizard locker: Used to contain a free guaranteed PermaUp if the Permanent Powerups option was enabled and the Lizard Locker Items option was disabled, because I completely forgot about it at the time. Using that combination of settings now replaces it with a Red jewel(L) just like all the other regular unrandomized PowerUps.
- Clock Tower: Final room entrance slab - Items 1 and 2: This was unwittingly introduced by https://github.com/ArchipelagoMW/Archipelago/pull/4277 removing the entire if check for the Multi Hit Breakables option. This particular 3HB is weird because the IDs for the items it drops (normally two 500 GOLDs) are in the exact same address space pointed at by the other 3HB in this room, Renon's final offers …
=> CV64: Fix some unrandomized locations containing unintended items on specific settings

worlds/LauncherComponents.py
Removes an unnecessary global, it caused a flake8 test failure: https://github.com/ArchipelagoMW/Archipelago/actions/runs/14185069387/job/39738807731?pr=4226
https://discord.com/channels/731205301247803413/1214608557077700720/1356480632737366056
Launched some clients through the launcher
=> Launcher: Remove an unnecessary global

worlds/pokemon_emerald/CHANGELOG.md
#4686 still had its changelog edits in the version that just got released. Moves it to a new apworld version.
=> Pokemon Emerald: Fix Changelog

CommonClient.py
When running the Archipelago Factorio Client with the `--nogui` flag, and then trying to connect, the connection commands try to update the UI, which doesn't exist when we start with `--nogui`
```
Task exception was never retrieved
future: <Task finished name='connecting' coro=<CommonContext.connect() done, defined at CommonClient.py:476> exception=AttributeError("'NoneType' object has no attribute 'update_hints'")>
File "CommonClient.py", line 478, in connect
File "CommonClient.py", line 416, in disconnect
AttributeError: 'NoneType' object has no attribute 'update_hints'
```
I ran the project from git with this change, and was then able to start the factorio client with `python FactorioClient.py --nogui`, and then was able to run the `/connect` command …
=> CommonClient: Fix crash when connecting to a server when using nogui

worlds/pokemon_rb/regions.py
When creating a Pokemon RB world with ER, it creates a state for the purposes of guaranteeing a valid ER placement. However, this state does not have the flag added in 0.6.0 to allow for entrances being disconnected. This causes a generation failure when combined with a world that has it's entrances disconnected for later randomization with GER. This PR sets `allow_partial_entrances` to true on this state.
Generating along-side a world with disconnected entrances; specifically the 2.0.0 release of the Crystalis APWorld with the options `shuffle_houses` and `shuffle_areas` both set to true.  Said APWorld can be found here: https://github.com/Ars-Ignis/Archipelago/releases/tag/v2.0.0
I also ran all unit tests.
=> Pokemon Red/Blue: Set allow_partial_entrances to true when building a state for ER

WebHostLib/misc.py, WebHostLib/options.py, WebHostLib/static/assets/gameInfo.js, WebHostLib/static/assets/tutorial.js, worlds/alttp/__init__.py, worlds/aquaria/__init__.py, worlds/clique/__init__.py, worlds/dlcquest/__init__.py, worlds/ffmq/__init__.py, worlds/oot/__init__.py, worlds/sc2/__init__.py
Some web pages don't use the usual 404 redirect page. They either use a JS-generated page like `tutorial` and `game-info`, or they throw an unformatted 500 error like `player-options` and `weighted-options`.
I added some `abort(404)` calls for those pages if the game name is not supported by Archipelago.
Ran WebHost locally, tried to go to pages for Inscryption 2, a game that does not exist yet.
Before:
After:
=> WebHost: Standardize some 404 redirects

Fill.py
moves state.remove() to after the check to see if the location was already checked to not make prog_items go negative
have a seed for my unsupported world that runs into an assert that a collect override never goes negative that generates fine with this branch
=> Core: make accessibility_corrections only state.remove if the location was collected

worlds/tunic/er_scripts.py
UT support for ER works by turning the entrance pairs sent in slot data into plando connections. Part of this fails if the APWorld does not have https://github.com/ArchipelagoMW/Archipelago/pull/3761 in it if the game was generated with #3761 in it.
So, just slapping in a longer error message to catch this issue in case that doesn't get into 0.6.1 or whatever the next version will be.
=> TUNIC: Error message in the spot that UT errors at if you have an old APWorld

Generate.py
If a player's name includes a sequence like `{1}`, with any number, this would crash the generator with a standard library error that is confusing for some players. Sequences like `{a}`, with any string, would work fine due to a clever subclassing of `dict`, which would dynamically insert the key surrounded by curly braces into the dict for any unknown key.
This PR subclasses `string.Formatter` as opposed to `dict` and overrides the default behavior by making the value fall back to the key or index surrounded by curly braces. This solution handles more cases more directly.
Generate with the following YAML before and after applying this commit:
```yaml﻿
name: Player{1}
description: nonexistent integer
game: A Link to the Past
requires:
version: 0.5.0 # Version of Archipelago required for …
```
=> Core: Handle integer arguments in player names gracefully

docs/network protocol.md
Adds a bit of text to specify that the `cause` for a DeathLink packet can be an empty string.
Reading
=> Docs: Include that DeathLink cause can be an empty string

CommonClient.py
Stops writing the data_package to the _persistent_storage.yaml, which is just wasted I/O since all new data packages will be loaded from the checksum cache.
Existing entries there are still loaded so that data packages that happen to be in there are still being used. This is still somewhat likely to happen for games that changed data package only once since the checksum cache was added.
Ctrl+Shift+F for current_cache.
=> Clients: stop updating datapackage in persistent_storage

worlds/dlcquest/Items.py, worlds/dlcquest/__init__.py
fix: Start inventory item would make a miss number of item from the number of location under certain condition
https://discord.com/channels/731205301247803413/1349141593692704829
Test where run and the world that failed to have the same number of location and item now work properly, other worlds with different item were tested
=> DLC Quest Bug Fix more item then location non existing start inventory

BaseClasses.py
Without implementing `__iter__` directly, calling iter() on a Region.Register on Python 3.12 would return a new generator implemented as follows:
```py
def __iter__(self) -> int:
i = 0
try:
while True:
v = self[i]
yield v
i += 1
except IndexError:
return None
```
This was determined by disassembling the returned generator with dis.dis() and then constructing a function that disassembles into the same bytecode.
The iterator returned by `iter(self._list)` is faster than this generator, so using it slightly improves generation performance on average.
Iteration of Region.Register objects is used a lot in `CollectionState.update_reachable_regions` in both of the private _update methods that get called. The performance gain here will vary depending on how many regions a world has and how many …
=> Core: Improve iteration speed of Region.Register objects

worlds/cvcotm/client.py
When a DeathLink was sent by a CotM player, other players that were connected to that same CotM slot would not receive it. This PR fixes that.
Connected two separate instances of the same CotM slot to the same localhosted server (connected with their own BizHawk Client instances), got Nathan killed in one instance, and made sure the other Nathan got killed as well while the first one did not get killed again upon respawning.
=> CVCotM: Fix DeathLinks sent by a different instance of the same slot not being received.

Fill.py
The base state passed to fill_restrictive should be as maximal as possible otherwise fill_restrictive has to repeatedly re-sweep and collect from advancement locations that were reachable from before fill_restrictive has placed a single item.
This is not added within fill_restrictive itself because it is common for fills to be performed using a partial 'all_state', which is already a maximum exploration state.
With --skip_output generation of every template yaml with no progression balancing, except FF, KH and Shivers, this prevented repeatedly re-sweeping 576 advancement locations in every sweep within progression fill, reducing the generation time from 124s to 113s for me (8.8% reduction, averaged over 5 generations each).
Generated seeds with `python -O .\Generate.py --skip_output …
=> Core: Pass maximum exploration states in distribute_items_restrictive

BaseClasses.py
`Location` does not override `__eq__` so should not override `__hash__` to begin with.
With this patch, this makes operations on sets of locations slightly faster because they will use `object.__hash__` rather than `Location.__hash__`.
`object.__hash__` is about 4 to 5 times faster than `Location.__hash__` for me. Generation often uses sets of locations, so this slightly speeds up generation.
The only place I could find that was hashing locations directly was `WitnessLocationHint.__hash__`, but it has implemented a matching `__eq__`, so is fine.
For security reasons, Python randomizes its hash seed each time it is started, so the result of the `hash()` function is nondeterministic and can't have been used by worlds for anything that needed to be deterministic and can't have been used to …
=> Core: Remove Location.__hash__ for faster generation

MultiServer.py, docs/network protocol.md
Several people have expressed that they would like it if there were a set type on datastorage.
This PR makes use of some free real estate by extending the `update` command to also work on lists (which currently raises an Exception). The effect is that only elements that weren't already present in the list are added, effectively making it act as a set as long as you only ever use `update`.
=> MultiServer Extend datastore "update" operation to work on lists as well, acting as a pseudo "set union".

MultiServer.py
The docs say want_reply needs to be True for a reply to be made. In reality not providing an argument also sends the reply. Not following these specs may lead to useless network usage and maybe some clients could be experiencing issues receiving packets they didn't ask for
I expect this to be a breaking change for some clients that rely on the reply being sent without them asking for one, but I'm putting that PR mainly so that the issue is not forgotten
It wasn't
=> Core: Made want_reply follow the specs in the docs

docs/world api.md
The rules claimed that a world could do everything in `generate_basic`, but rules *must* be finished by the end of `set_rules`, so this is not the case.
Reading
=> Docs: Remove false claim that rules can be set in generate_basic

worlds/soe/patch.py
Remove deprecated use of Utils.get_options() from SoE World.
The call to `user_path()`, or `get_base_rom_path()` in general, is not really required anymore with the settings API, but I tried to make the change as minimal as possible.
Resolves SoE for #4811 
* Generated with .sfc missing -> Cancel -> Gen stops with readable error
* Generated with .sfc missing -> Selected sfc -> Gen succeeds
* Generated with .sfc existing -> Gen succeeds
* Launcher -> Open Patch with .sfc missing -> Cancel -> Launching stops with readable error in MsgBox
* Launcher -> Open Patch with .sfc missing -> Selected sfc -> Patching + launching succeeds
* Launcher -> Open Patch with .sfc existing -> Patching + launching succeeds
=> SoE: remove use of deprecated Utils.get_options()

worlds/lingo/items.py
Some progression items are additionally marked as useful now, which some clients use to indicate that the item is particularly important. The affected items are:
- "Crossroads - Roof Access", which almost always provides access to a large number of locations.
- The five colors that are the most prevalent across puzzles.
- "Sunwarps", which unlocks all sunwarps at once. This tends to grant access to multiple regions, and is required for the Pilgrimage goal.
- The panel doors that are required for roof access in panels mode door shuffle. These may block victory depending on the selected goal, and even if they don't, they provide access to a large number of locations via the roof.
pytest, test generation, played with a client that recognizes proguseful items.
=> Lingo: Mark some items as ProgUseful

Launcher.py, data/client.kv, data/launcher.kv, kvui.py
* Removed now unused imports from Launcher
* Moved ImageIcon and ImageButton to use ApAsyncImage for compatibility with apworlds
* Adjusted image size in the Launcher from 40x40 to 48x48. This is already larger than the size in previous versions, and a docs update is soon to follow.
* Expose `dynamic_scheme_contrast` to user.kv, allowing users to set high contrast.
* ScrollBox's default scroll_type was set to only content, so the scrollbar in Launcher was nonfunctional.
* Adjusted the spacing of the title of a component when a description is present to be closer to the center.
* Launcher now scrolls to the top automatically when changing between filters
Manually.
=> Core: post-KivyMD cleanup

worlds/lingo/__init__.py
This allows the tracker to see whether postgame is shuffled in the player's world, and if it's not, allows it to hide locations/paintings accordingly.
Test generation with tracker.
=> Lingo: Add "shuffle_postgame" flag to slot data

.github/workflows/analyze-modified-files.yml
This disables an added check in flake8 that does not really fit the goal of the github action and currently throws a lot of errors.
Going forward we should think about which flake8 warnings we want to have mandatory since probably all uses here are wrong or basically dead code.
CI
❌ -> ✅
=> CI: ignore F824

worlds/tww/randomizers/Dungeons.py
Wind Waker collects nonprogression into state via world.collect.
This is something we're trying to phase out: https://github.com/ArchipelagoMW/Archipelago/pull/3786
I made the minimal possible change to make TWW compatible with that PR.
The alternative solution is to check for `item.advancement` before calling the world collect directly.
Unit test is the known flake8 issue
=> Wind Waker: Don't collect nonprogression

LinksAwakeningClient.py
Stops using the soon to be deprecated Utils.get_options
https://github.com/ArchipelagoMW/Archipelago/pull/4811
`LinksAwakeningWorld.settings` seems preferable to `settings.get_settings().ladx_options` since its one less thing to change for the ladx beta (which has a different game name)
Ran a patch file through the ladx client a few times, while fiddling with `host.yaml`
=> LADX: Stop using Utils.get_options

.github/workflows/build.yml, .github/workflows/release.yml
GitHub has removal of the Ubuntu 20.04 image scheduled for April 15th 2025, at which point the CI actions using it would fail.
On top of that, Ubuntu 20.04 LTS support will reach EOL May 1st 2025, at which point we should not use it to bundle anything anymore.
We want to stick to the oldest available image to use the oldest possible libc as dependency, so this changes affected actions to use Ubuntu 22.04. If this is a problem for some users, such as Debian oldstable, we could build on a different image (not a GitHub image), however that involves some work, so we should first make this change and see if anyone reports problems.
CI Output -> AppImage -> Launcher -> Generate, Browse Files and Text Client
on Arch Linux and Ubuntu 24.04 VM
=> CI: update action ubuntu build runners to 22.04

worlds/pokemon_rb/regions.py
Fixes the early code to set aside a PC item so it respects the item rules needed so that items that do not work in this location are not placed there.
Generating default yaml with seed 6133628608690033011 and observing Marsh Badge placed on main, Poke Ball on this branch.
=> Pokemon Red and Blue PC Item fix

worlds/sc2/ClientGui.py
Fixes the missing tooltip on hovering on mission buttons after KivyMD switch
Booted a client, joined a world, overed over a mission button
=> SC2 Client: Fix missing mission tooltip after KivyMD switch

worlds/lingo/items.py, worlds/lingo/locations.py, worlds/lingo/utils/pickle_static_data.py
This fixes some flake8 failures, and has no other effect.
Test generation, pytest, flake8.
=> Lingo: Removed unnecessary "global" keywords

BaseClasses.py
fix item links yet again (this time for the webhost sphere tracker)
https://discord.com/channels/731205301247803413/1358879618580480090/1359648039148585101
gen'd this yaml before and after and saw it crash sphere tracker before and not crash after
also inspected multidata["spheres"] and saw no `None` after the change
=> Webhost: Fix Sphere Tracker crashing on item links

worlds/mlss/Rules.py
With Chuckle Bean digspots disabled, the `Bowser's Castle Wendy & Larry Hallway Digspot` location does not exist, but `Rules.set_rules` was not checking for this when the `Goal` was set to `Emblem Hunt` and was trying to set rules on this location anyway, crashing generation.
Generated before, both locally and on the website, with the default options changed to the `Goal` set to `Emblem Hunt` and `Chuckle Beans` set to `None` and observed the crash, and then generated with this PR and observed successful generation.
Zipped example yaml:
[EmblemNoDigspot.zip](https://github.com/user-attachments/files/19688653/EmblemNoDigspot.zip)
I don't really know MLSS, I just stopped the crashing.
```
Uncaught exception
File …
```
=> MLSS: Fix generation error with emblem hunt and no digspots

worlds/factorio/Options.py
Fixes that since https://github.com/ArchipelagoMW/Archipelago/pull/4421 any world_gen floats  are written as None into the mod. None loads the global of the name None, which is not defined, so it loads nil, when nil is given in the table Factorio defaults to default world settings.
No longer None in this text.
=> Factorio: fix FloatRanges writing effectively nil into the mod

worlds/dlcquest/test/TestOptionsLong.py, worlds/dlcquest/test/__init__.py
Specifically requested by @black-sliver on #4762 
Two tests were long, so I introduced a similar system to Stardew's, to skip them in the main pipeline but keep them accessible for local work
Ran the test suite, test is skipped
=> DLC Quest - Skip two long tests in the main pipeline

worlds/hk/docs/setup_en.md, worlds/hk/docs/setup_pt_br.md
reformats the whitespace in hk docs to preemptively be prepared for the change in md parsing in #4074
(and deleted an extra period in the pt_br version)
webhost in current and in 4074 and :eyes:
=> HK: fix docs whitespace

worlds/stardew_valley/__init__.py
#4239 refactored buildings, but introduced iteration of a set when precollecting the building items into start inventory.
This patch sorts the new `building_progression.starting_buildings` set before iterating it, to ensure the items are precollected in a deterministic order.
The iteration order of sets varies between separate Python processes due to set order being partially based on the hashes of the objects in the set and because each Python process uses a random hash seed by default.
I ran the determinstic generation tests in #4410 and Stardew Valley passes the tests with this change.
=> Stardew Valley: Precollect building items in deterministic order

test/worlds/__init__.py
In #4762, the first instance of an entire module being skipped was added. The test collection does not account for an entire module being skipped, and thus started crashing with the following error `TypeError("'ModuleSkipped' object is not iterable")`.
Running unittests locally, and seeing that they were actually collected and ran.
=> Unittests: fix world unittests with unittest module

Launcher.py, data/launcher.kv
Adds a fuzzy search box to the Launcher main screen. Current notable behavior:
- Search bar is anchored to the top of the screen at all times.
- ~~Only starts searching when 3 or more characters are entered.~~
- Refreshes current filter (shows/un-hides relevant cards) when backspaced to 0 characters.
- ~~Uses `Utils.get_fuzzy_results` as opposed to "substring" or "startswith" options.~~
- ~~Hides cards with a search score < 25.~~
- ~~Sorts results by search score.~~
Played around with Launcher, PyCharm debugging. Could always use more testing.
https://github.com/user-attachments/assets/6d483740-a66e-4225-bf56-b9fbdf28e7b5
=> Launcher: Add search box

kvui.py
Alternative to #4894 that fixes the root problem, we were accidentally throwing args and kwargs into args.
Opened Text Client, saw that localhost was being set properly as the default text for the connect bar.
=> kvui: fix kwargs on ResizableTextField and ImageButton

worlds/zillion/__init__.py, worlds/zillion/client.py, worlds/zillion/gen_data.py, worlds/zillion/id_maps.py, worlds/zillion/logic.py, worlds/zillion/options.py, worlds/zillion/test/TestGoal.py, worlds/zillion/test/TestOptions.py
some cleaning:
- https://docs.astral.sh/ruff/rules/missing-trailing-comma/
- Underscore at the end of a variable name is the standard way to avoid shadowing built-ins.
- (Underscore at the beginning means "unused" for local variables.)
a generation
=> Zillion: some code cleaning

test/general/test_entrance_rando.py
A `type[X]` annotation should not be used if all you're doing with it is calling it to get an instance of that type.
This is because `__init__` signatures regularly don't follow the base class `__init__` signature.
You can see that this is the case with many subclasses in AP. Most of the subclasses of `Region` in supported worlds would crash if passed to this function.
I know this is just for tests, so it wasn't made to work with all of those subclasses. But it should usually be safe to copy patterns from unit tests into application code.
If this `type[Region]` pattern were copied into core code, it would be bad.
just unit tests
=> Tests: Don't use `type` as `Callable`

worlds/mm2/rules.py, worlds/mm2/test/test_weakness.py
Probably the cause of most MM2 weakness failures. `max` compares against the first value of a tuple if given a list of tuples, which meant it would always give the last weapon in the list, rather than the weapon with the greatest excess energy.
This PR also includes a refactor to the weakness tests to now test `shuffled` boss weaknesses, as it has been the cause of several bugs in the past.
StrictRandomWeaknessTests with seed 94073898902878149535 produces a mathematically impossible world generation. The test no longer fails once this change is made.
=> MM2: fix invalid weakness failsafe and refactor weakness tests

worlds/cv64/client.py
Some DeathLink-related things, mainly:
- When a DeathLink was sent by a CV64 player, other players that were connected to that same CV64 slot would not receive it. This PR fixes that.
- Sent death messages now include the in-game area the death occurred at, much like CotM's implementation.
- Added handling for when another game includes a death cause message that is just a blank string, i.e. Super Mario World. There should be no more blank in-game death message textboxes.
- Stopped the client from spam-sending goal packets after goal completion.
Connected two separate instances of the same CV64 slot to the same localhosted server (connected with their own BizHawk Client instances), got the player killed in one instance, and made sure the other player got killed as well while the first one …
=> CV64: Some DeathLink adjustments

MultiServer.py
Basically, hints for itemlink worlds' locations get stored in ctx.hints under
1. the location's player
2. **every individual player** that is participating in the itemlink.
Right now, the updatehint code tries to replace and resend the hint under the itemlinked player, which doesn't work.
=> MultiServer.py: Another Hint Priority + Item Links bug oh boy

worlds/AutoWorld.py
print both world source paths in case of conflict
https://discord.com/channels/731205301247803413/1214608557077700720/1351573247468241049
=> Core: print both world source paths in case of conflict

worlds/tunic/__init__.py
Plando from pool doesn't make new items anymore, so this code isn't doing anything but taking up space.
Test gens with some plando.
=> TUNIC: Rip out code that dealt with plando from pool making new items

worlds/lingo/__init__.py, worlds/lingo/player_logic.py
In some circumstances, Lingo will attempt to force a random "good" item onto a specific sphere 1 check, in order to make early progression easier. The code for this used to have a block copied from The Witness in order to handle the situation where a potential good item was plando'd "from pool" onto another location.
This PR removes the plando check and moves the actual item placement into `fill_hook` (inspired by #3041). The eligible good items are still calculated in `generate_early`, but one is not chosen at this point. Because of this, all of the eligible good items remain in the "real items" list and the sphere 1 location remains in the "real locations" list. By the time `fill_hook` gets called, plando has been resolved, meaning any "from pool" placements will have caused eligible …
=> Lingo: Rework early good items

MultiServer.py
Part of #4811 
Also switches from getitem to getattr for top level access to get proper type deduction for `as_dict`. Still uses dict access from that point on though.
Also makes the import lazy, which might be an improvement for customserver once Utils does not directly import settings anymore.
MultiServer still spins up
=> MultiServer: import get_settings from the correct module

setup.py
uses sha256 instead of sha1 for the RFC 3161 timestamp server. Without this change, AP cannot currently be signed with the cert I have. However, that cert will fail at the end of April, hopefully I have a new one by then, but that is hinging on a coworker.
locally.
=> Setup: use sha256 for timestamp server

inno_setup.iss
Usually, whenever something gets renamed, removed etc. it is as far as I remember, always forgotten to remove old files from existing installations, which is then fixed in a follow up PR. No more! - this now cleans all .exe from the install directory, and offers nuking /lib*
locally on windows 10
=> Setup: offer the default-on option to clean /lib folder on update

docs/world api.md
Update the comment to note that your world's `create_item` is used for start inventory and item links too, not just plando.
This seems to be an occasional issue in APWorlds where they'll effectively default items as filler and only call them progression as needed, so a little clarity here might help.
=> Docs: Update comment for create_item in world api.md

worlds/alttp/ItemPool.py
In  some very restricted settings, StopIteration may be raised and  generation aborted in the changed section. Now it doesn't crash and  continues, which should  be fine, as health is optional.
I did not.
=> LttP: make progression health optional

worlds/lingo/options.py
The OptionCounter type makes trap_weights visible on the WebHost, so this PR does that.
Looked at the webhost and it was fine. pytest, test generations to make sure the weighting is still applied and that settings all values to zero still errors.
=> Lingo: Use OptionCounter for trap_weights

worlds/overcooked2/__init__.py
OC2 was not properly counting progression items that were also classified as useful and/or trap.
Generations using multiclass items and seeing `total_progression_count` increase.
=> OC2: Account for Multiclass Items in Progression Balancing

worlds/tww/Options.py, worlds/tww/__init__.py
As referenced in #4931, The Wind Waker currently fails at generation.
This is due to `yaml.safe_dump` being used when creating the output APTWW file and it not being able to serialize the `OptionCounter` introduced in #3756. A few fixes were suggested, but in the end, I decided to change the output file to only include options used during patching, so as to also cut down on the file size. The means that the options that use `OptionCounter` (`start_inventory` and `start_inventory_from_pool`) are no longer included in the APTWW file.
I've also left a comment to also remind myself and future collaborators of the reasoning.
Generated a TWW world, patched using the resulting APTWW file, and checked a single location in-game, all of which worked fine.
N/A
=> TWW: Fix generation failure with output file

worlds/stardew_valley/__init__.py
Now that #2965 is merged, I want to use it!
`rule` and `item` are always passed to Stardew's `create_event_location`, so default are not required.
Gen and check that events are still there. (plus run the tests)
N/A
=> Stardew Valley: Replace event creation stardew code with add_event

.github/workflows/build.yml, .github/workflows/release.yml
* Adds windows build to release.yml
This can be disabled by changing a single boolean.
* Adds build attestation to release.yml
* Ensures fixed job order in release.yml (this was jank before)
* Adds build attestation to build.yml
This allows users to verify the origin (action, repo, commit) of a file.
It's also possible to find an attestation just from the file hash,
so this may or may not improve security in the future.
Skips attestation for builds that are triggered automatically.
Per github doc:
> You should not sign:
> * Frequent builds that are just for automated testing.
> [...]
Looking at CI.
Here is a run of the new release action with Windows builds enabled:
https://github.com/black-sliver/Archipelago/actions/runs/14720916838
Here is a run of the new build action that was …
=> CI: add optional windows release build and build attestation

worlds/alttp/Rules.py, worlds/alttp/test/dungeons/TestSwampPalace.py
Removes a lower key requirement for Swamp Palace West when a Hookshot is collected. Collecting an item should never make locations unreachable that are reachable without it.
We'll see if the unit tests pass :)
=> ALTTP: Swamp Palace West logic fix

worlds/sm/variaRandomizer/rom/rom.py
FakeROM instances were being created with default arguments, which included a mutable default argument data dictionary, so all FakeROM instances would be writing to and reading the same dictionary, resulting in broken patch data in multiworlds with more than one Super Metroid world.
This PR removes the mutable default argument to ensure that each FakeROM instance has its own data dictionary.
https://github.com/ArchipelagoMW/Archipelago/blob/6613c296523185ffd4ea9c37c4c6ffe21e797935/worlds/sm/variaRandomizer/rom/rompatcher.py#L58
https://github.com/ArchipelagoMW/Archipelago/blob/6613c296523185ffd4ea9c37c4c6ffe21e797935/worlds/sm/variaRandomizer/rom/rom.py#L92-L95
I have not tested it beyond generating. I have set up a test room of 20 Big Async filler Super Metroid yamls, generated with this …
=> SM: Fix FakeROM instances sharing the same data dictionary

Generate.py
handles MarkedYAMLError for generate like settings does
shares a lot of code with #4531 but needed tweaks based on what data we have
ran through some common yaml issues like tab characters (inserted in the default two space yamls) and mixing of datatypes and looked at the generate output
=> Generate: Better yaml parsing error messaging

Options.py
Cleans up the method signature, reduces nesting by a level, fixes a mistake in the docstring, makes some wording in the docstring less ambiguous, and also adds return docs
used my eyes. ran generation calling as_dict and added in things that tripped the errors.
=> Options: Cleanup CommonOptions.as_dict

CommonClient.py, test/programs/test_common_client.py
removes code that was apparently supposed to be removed in 0.6.0
minimally. unittests caught a test of the old API, which I removed.
=> CommonClient: rip out old global name lookup

Main.py
Makes it so that the Archipelago datapackage is always present, even if no spectator slots are, as the Server is "playing" Archipelago
with https://github.com/ArchipelagoMW/Archipelago/pull/4881
=> Core: always embed Archipelago

worlds/generic/docs/mac_en.md
For some time there has been encouragement to use the launcher instead of directly running the individual client files. This is a step in that direction.
It wasn't. It's a classic Snake docs update.
As an aside, I know that there's currently a method to play the GB/GBC/GBA rom games using mGBA instead of Bizhawk, but until that lua is in the repository, I don't plan on updating this document to reflect that method.
=> [Docs] Direct mac users to Launcher.py

worlds/messenger/docs/setup_en.md
Fixes indentation that was all over the place for some reason. Also removes the now irrelevant save backup section. Client has had proper save management for a while now this is just leftover.
Checked that all the indentations were 4 characters instead of whatever was going on before. Checked the other documents but they were already correct.
=> The Messenger: fix indentation in setup guide

worlds/terraria/Rules.dsv
The Leading Landlord achievement was discovered to be impossible to obtain in the secret getfixedboi seed, so removed it when getfixedboi is enabled.
I generated some worlds with different settings and checked to make sure the achievement is properly included/excluded based on settings.
=> Terraria: Fix inaccessible Leading Landlord achievement when getfixedboi is enabled

Launcher.py
Clicking "Generate Template Options" generates template options (yay) and then tries to open a file browser. When I did this in WSL to simplify some testing it threw an exception. Ideally when we don't have a file browser we just get back the path to the folder.
`python3 Launcher.py` and click "Generate Template Options" in WSL, i.e. a linux environment, without xdg-open, gnome-open, or kde-open.
=> Launcher: warn if there is no file browser

LinksAwakeningClient.py, worlds/ladx/ItemTracker.py
This makes sure the tracker's fake items that are linked to checks have access to `slot_data` if necessary.  Items without a condition get handled right away, but otherwise have to wait until `slot_data` is available. It should fix [this issue](https://discord.com/channels/731205301247803413/1090819435893362768/1362169782354313539), where getting the seashell mansion check in seashell hunt mode makes the seashell count wrong.
I tested various combinations of connection timing between Magpie, the emulator, and the AP server along with save scumming the seashell mansion check.
=> LADX: improve fake tracker items

worlds/mmbn3/__init__.py
The newly added check "Help With Rehab - Bonus" was not properly checking for Beach Area access to be completed, even though the original job reward was.
Generated a seed, added SubPET to inventory to access SciLab. Checked Universal Tracker to see that the "Help With Rehab - bonus" check was not in logic. Added PETCase to access Beach area, checked again, and confirmed the job is now in-logic.
=> [MMBN3] Adds beach access to "Help with Rehab" job bonus reward check

worlds/dark_souls_3/Locations.py
The `static` fields of `US: Homeward Bone - tower village, right at start`and `US: Homeward Bone - foot, drop overlook` were the same, and because of that, the [static randomizer](https://github.com/nex3/SoulsRandomizers/tree/archipelago-server) placed both of those items to `US: Homeward Bone - tower village, right at start`.
Reference (annotations.txt):
[`US: Homeward Bone - tower village, right at start`](https://github.com/nex3/SoulsRandomizers/blob/1c9d91334717240bbb937a236272eb3a00a784f4/dist/Base/annotations.txt#L2074C1-L2079C20)
[`US: Homeward Bone - foot, drop overlook`](https://github.com/nex3/SoulsRandomizers/blob/1c9d91334717240bbb937a236272eb3a00a784f4/dist/Base/annotations.txt#L2211C1-L2216C12)
Run 3 tests and checked them manually. Same YAML, item plando was used.
Before: …
=> DS3: Fixes "US: Homeward Bone - foot, drop overlook" location

worlds/messenger/__init__.py, worlds/messenger/portals.py, worlds/messenger/subclasses.py, worlds/messenger/transitions.py
Currently messenger attempts to guarantee the player has access to at least a few locations with empty state during GER, but as this reduces the amount of valid entrances significantly GER gets hung up on it not being able to connect stuff and throws a fit. This forces all of the validation to be done during portal shuffle every time with disconnected entrances, so that all entrance connections can just be valid. If portal shuffle is disabled this is irrelevant since one of the starting portals guarantees reaching some locations.
Ran a bunch of generations with the option combination that keeps throwing test failures.
=> The Messenger: do all empty state validation during portal shuffle

docs/tests.md
Adds naming convention for files, class names and function names.
Deprecates putting stuff into `__init__.py`.
This may be relevant for test discovery in the future.
See discussion in #4969 
Reading.
=> Docs: tests: add naming / file naming conventions

Fill.py
This removes redundant location counting when swapping in `fill_restrictive`.
`prev_state` starts off as a copy of `swap_state` and then `swap_state` collects `item_to_place`. Collecting an item must never reduce accessibility (otherwise generation can break horribly), so it is guaranteed that `swap_state` will always be able to reach at least as many locations as `prev_state`, so `new_loc_count >= prev_loc_count` is always `True`.
As a sideeffect of this change, this fixes generation of Pokemon Emerald with locally shuffled Badges/HMs when there are worlds with unconnected entrances present in the multiworld e.g. KH1. This is because this location counting did not respect `single_player_placement=True` and counted reachable locations across the entire multiworld.
Fixes #4834 as a …
=> Core: Remove redundant reachable location counting in swap

worlds/zillion/patch.py
fixes some of the inheritance structure that was broken by https://github.com/ArchipelagoMW/Archipelago/pull/4331
generated a patch file and applied it
=> Zillion: fix `read_contents` to be compatible with base class

worlds/adventure/Rom.py
As of https://github.com/ArchipelagoMW/Archipelago/pull/4331, APContainer.read_contents returns the manifest. It was missed by both Berserker and I that Adventure overrides this function and needs to be slightly changed as a result.
=> Adventure: Update AdventureDeltaPatch.read_contents to return the manifest as required by #4331

worlds/dark_souls_3/__init__.py
The DS3 static randomizer uses the relative ordering of location names to map between Archipelago's notion of location IDs and the static randomizer's. Treating unrandomized locations as excluded can break this behavior by removing some locations from the list, causing further locations to be incorrectly assigned.
The only reason this wasn't a bigger problem up to this point was that location order only matters on a per-region and per-item basis. That means this only causes problems in practice when a single region has multiple locations with the same default item, and some of those locations are randomized while others are not. Since exclusions (and thus randomization) are usually done based on item types, we managed to dodge this bullet for a long time.
I tested this with a few manual …
=> DS3: Don't make unrandomized items into events

Utils.py
An alternative approach to #4926
Tested by using unicode characters in the Text Client in frozen and unfrozen builds on both Windows and Macos
=> core: Reconfigure stdout to utf8

Utils.py
#5017 introduced a problem when sys.stdout was overridden with something that does not have reconfigure - such as subprocess capture in an IDE during test execution.
Reported on Discord here: <https://discord.com/channels/731205301247803413/731214280439103580/1374884066100379659>
Just reading and watching CI not fail. Hope people that can easily repro the problem test it a bit more.
=> core: don't reconfigure stdout if it's fake

worlds/LauncherComponents.py
wargroove component (and client) moved to apworld so this is unnecessary (and crashes setup)
running local setup.py now (it finished and ran clean)
=> Wargroove: Cleanup script_name component in LauncherComponents 

OoTClient.py, worlds/oot/__init__.py
Replace usage of `Utils.get_options` and `settings.get_settings()` in Ocarina of Time with the newer settings API from `OOTWorld`.
Resolves https://github.com/ArchipelagoMW/Archipelago/pull/4811 for Ocarina of Time.
Generated a patched file and client functions.
=> OoT: Stop using Utils.get_options

Generate.py
Removes the forced naming in weights files, leaving a fallback for if one isn't specified.
Breakpointed with custom names and no names in both various game yamls and a weights yaml.
=> Generate: don't force player name for weights files

MinecraftClient.py, worlds/minecraft/__init__.py
The Minecraft Client uses `Utils.get_options`, which is deprecated. This changes the client to instead use the settings API.
As a debatably positive side-effect, the `java` option is no longer hidden in `host.yaml` and now has a docstring.
Resolves #4811 for Minecraft.
Ensured the client functions properly by letting it perform automated setup and spin up a Forge server.
N/A
=> Minecraft: Stop using Utils.get_options

BaseClasses.py, worlds/AutoWorld.py, worlds/messenger/__init__.py
Abstracts state.prog_items for directly modifying state like all the other state helpers already do.
Put it in the base implementation and messenger and break point checked.
=> Core: add state add/remove helpers

worlds/ahit/Locations.py, worlds/ahit/Rules.py
It's been brought up a few times now by different people that Rush Hour could probably logically require Dweller Mask by default.
This PR adds the Dweller Mask logic requirement for Normal Logic Difficulty only.
Skipping the need to use Dweller Mask is probably on about the same level as some Moderate Logic Difficulty tricks, so the Dweller Mask requirement has not been added to Moderate Logic or any higher difficulties.
Without Dweller Mask:
- Skipping the Dweller platforms in front of the generator in Pink Paw Station requires one of:
a. Single jump + wall climb + double jump
b. Double jump dive cancel from the top of a bench
c. Double jump dive cancel from the top of the lamp
d. The Empress sometimes shoots this generator without the player going all the way up to it, but I don't know …
=> AHiT: Add Dweller Mask requirement to normal logic Rush Hour

MultiServer.py
as brought up here https://discord.com/channels/731205301247803413/731214280439103580/1362929155657957519 it might be good to give leeway to existing Seeds
no
=> Core: only raise min_client_version for new gens

setup.py
When LD_LIBRARY_PATH is not set, the old code would also add the current working directory to LD_LIBRARY_PATH, which is bad. (Potentially picking up libs from an unexpected folder.)
Looking at a debug print of it inside the AppImage with both LD_LIBRARY_PATH set and empty when launching.
The changed line was tested with both bash and dash.
See also Discord around here: <https://discord.com/channels/731205301247803413/731214280439103580/1375219855795421295>
=> Linux/AppImage: avoid adding cwd to LD_LIBRARY_PATH

worlds/stardew_valley/content/vanilla/pelican_town.py
This book is only sold from year 2. https://stardewvalleywiki.com/Animal_Catalogue
Now there is a `16% progression item` required, accounting for year 2.
N/A
=> Stardew Valley: Make animal catalog logically year 2

worlds/messenger/__init__.py
Makes portal shuffle continuously attempt to shuffle until it satisfies the condition. There's plenty of valid combinations for this, but the tests have been getting incredibly unlucky and this keeps failing. in actual practice, it very rarely fails, so i don't foresee this having any observable negative impact on players.
wasn't i need sleep
=> The Messenger: more generous portal validation

worlds/stardew_valley/data/craftable_data.py
A player using Universal Tracker noticed that the statue was in logic in winter, because it did not have the proper moss ingredient in its recipe. I added the moss
Bug Report: https://discord.com/channels/731205301247803413/1090823633099833464/1375636325775966228
Recipe: https://stardewvalleywiki.com/Statue_Of_Blessings
Unit tests, not much more to do here
=> Stardew Valley: Added moss to statue of blessings recipe

data/lua/connector_bizhawk_generic.lua
BizHawk has added new core options between versions and even changed the key for at least one system, so the current script can crash on a `PREFERRED_CORES` request (which is not useful for most clients, hence rare). The get config function appears to start reaching into C# territory, hence the original implementation, but this should be able to loop all the keys and send them to the client. And then the client can decide how to actually interpret it.
Ran the command via python in a client on BizHawk 2.7, 2.8, 2.9.1, and 2.10 to see that it returned a correct output.
=> BizHawkClient: Fix script to list all cores instead of explicit mapping

WebHostLib/requirements.txt
Flask 3.1.1 is a security update. Afaik we don't use the impacted feature, but AP's Flask *could* be configured to use it, so we should update.
=> Webhost: update Flask to 3.1.1

worlds/cvcotm/__init__.py, worlds/cvcotm/aesthetics.py, worlds/cvcotm/docs/en_Castlevania - Circle of the Moon.md, worlds/cvcotm/docs/setup_en.md
Adds the Nerf Roc Wing option value to slot_data so that @BowserCrusher's [PopTracker pack](https://github.com/BowserCrusher/Circle-of-the-Moon-AP-Tracker) can auto-enable it. Also changes the tracker links in the docs to instead point to its new maintainer's release page.
In addition, adds Harmony of Dissonance max ups to the `other_game_item_appearances` dict so that max ups for HoD players will show up as those max ups in CotM.
Connected and verified that `nerf_roc_wing` was in `ctx.slot_data`, verified the new PopTracker links were working on a local webhost, and also made sure the HoD max ups were showing up as the CotM max ups in-game.
=> CVCotM: Add Nerf Roc Wing to Slot Data and HoD max ups to other_game_item_appearances

worlds/tww/Options.py, worlds/tww/__init__.py
This PR limits the slot data for TWW to only necessary items. Complies with #5039.
Generated a seed and played through it for a bit. Checked that everything still worked, particularly the tracker. Cross-referenced the [tracker code](https://github.com/Mysteryem/ww-poptracker) to see which slot data items were being referenced.
N/A
=> TWW: Remove unnecessary items from slot data

worlds/timespinner/Locations.py, worlds/timespinner/Regions.py
Some more testing courtesy of participants in the upcoming Timespinner 2v2 tournament have revealed this old issue, possibly made more obvious by changes in #4803 (which this is going to conflict with) - a warp to the Caves of Banishment Maw-side entrance when both Maw and Lake Serene are flooded can still show progression through Caves back up into the Sirens side even though no items in the area are in logic. The connection logic between these two regions is straight up wrong. The equivalent logic upstream just checks to see if the region is flooded (the key omission that led to an unwinnable seed during testing).
Generated a large quantity of seeds and looked for seeds that met the conditions described above to ensure that only items within Caves of Banishment were in logic in those …
=> Timespinner: fix connection logic from Maw cave entrance to Maw

worlds/jakanddaxter/__init__.py, worlds/jakanddaxter/docs/en_Jak and Daxter The Precursor Legacy.md, worlds/jakanddaxter/docs/setup_en.md, worlds/jakanddaxter/options.py, worlds/jakanddaxter/regions.py, worlds/jakanddaxter/rules.py, worlds/jakanddaxter/test/test_trades.py
- Cleans up a few missed references in the setup guide.
- Refactors Options class to use metaclass and decorators to enforce friendly limits on multiple levels.    
- Templates generated from the website, even ones with `random` should not fail generation because the website will only allow values inside the friendly limits. 
- _Uploaded_ yamls to the website with `random`, should also now respect friendly limits without the need for `random-range` shenanigans.
- _Uploaded_ yamls to the website, or yamls that are used to generate locally, that have hard-defined values outside the friendly limits, will be clamped/dragged/massaged into those limits (with logged warnings).
- Removed an early completion goal that was playing havoc with fill. Not enough people seem to use this goal, so its …
=> Jak and Daxter: Post-merge Polish

Options.py
```yaml
plando_items:
- items: ["Shapers", "Shapers", "Shapers", "Shapers"]
```
This block currently only grabs one "Shapers" item and not four because `locations` and `location` are undefined and the default of `["Everywhere"]` is truthy, setting `count` to 1.
The block shown above now adds four copies of the item instead of one. It only sets the `count` to 1 if `location` was actually provided and then sets it to the default value.
=> Plando Items: Fix `count` with empty `locations`/`location`

worlds/dkc3/Regions.py
A couple of Entrance access rules were checking for being able to reach a Location, but a Location first checks for being able to reach its parent Region, so it needs to be registered that access to that parent Region can give access to the Entrance.
I added the contents of the `TestImplemented.test_explicit_indirect_conditions_spheres` test from `test_implemented.py` to the end of the generator and ran `--skip_output` generations of DKC3 using https://github.com/Eijebong/Archipelago-fuzzer
Before these changes, the test added to the end of the generator would frequently fail with (the raised error type is custom for ease of searching error logs):
```
Main.main.<locals>.IndirectConditionError: Sphere 2 created with explicit indirect conditions did not contain the same locations as sphere …
```
=> DKC3: Add missing indirect conditions

Launcher.py, Utils.py
There are cases where LD_LIBRARY_PATH is set, which can break system binaries if a library exist in any directory listed in LD_LIBRARY_PATH but is older than the one shipped with the system. This removes the LD_LIBRARY_PATH env variable when executing system programs.
Specifically this happens with the AppImage that sets LD_LIBRARY_PATH to Archipelago/lib when run on SteamDeck and using kdeopen. That bug was reported somewhere on Discord.
Used Launcher -> Browse Files, Open host.yaml, Open Path, Various Clients
on both source and AppImage
=> Launcher/Utils: reset LD_LIBRARY_PATH for system EXEs

worlds/factorio/Client.py, worlds/factorio/__init__.py
allows forwarding args from launcher
.\Launcher.py "Factorio Client"
.\Launcher.py "Factorio Client" -- --rcon-port 12121
.\Launcher.py "Factorio Client" -- --help
=> Factorio: revamp args parsing and passing

worlds/shapez/test/__init__.py
shapez has been raising fill errors in restrictive preset-based unittests every now and then since it got merged (see [here](https://discord.com/channels/731205301247803413/1259157584783478814/1380211280110948422) for details).
This removes those unittests and adds a small comment regarding other unittests.
No tests (pun intended)
No changes
=> shapez: Remove preset unittests

.github/workflows/label-pull-requests.yml
This attempts to fix a recent trend in failures with the labeler job, such as seen here: 
https://github.com/ArchipelagoMW/Archipelago/actions/runs/15431953364/job/43431278325?pr=5080
The cause of the change in behavior is unknown, though it is speculated to be either a change in the gh cli (not inferring the repo from the PR URL, if it ever did that) or in the actions runners' default environment configuration (removing GH_REPO, if it ever had that). Either way, it seems that we should be able to, at least theoretically, resolve the issue by manually specifying the repo. The env variable is easier as it can be set at the workflow level, but could also set it with a cli flag instead if desired.
Testing actions is literally the worst thing ever to exist on this planet so I have given up …
=> CI: Add GH_REPO environment variable to labeler

worlds/saving_princess/__init__.py
launch_subprocess takes the Callable not the result of the Callable
i opened the client and then used the launcher while it waited for me to select my data files (instead of it currently hanging in that situation)
=> saving princess: fix use of subprocess helpers

worlds/alttp/test/options/test_dungeon_fill.py, worlds/stardew_valley/test/regions/TestEntranceClassifications.py, worlds/stardew_valley/test/regions/TestRegionConnections.py
use name strings for subtest args instead of full objects
ran the tests locally and gh will do the same
=> LTTP/SDV: use .name when appropriate in subtests

worlds/sa2b/GateBosses.py, worlds/sa2b/Rules.py
- Fixed King Boom Boo being able to appear in multiple boss gates
- `Final Rush - 16 Animals (Expert)` no longer requires `Sonic - Bounce Bracelet`
- `Dry Lagoon - 5 (Standard)` now requires `Rouge - Pick Nails`
- `Sand Ocean - Extra Life Box 2 (Standard/Hard/Expert)` no longer requires `Eggman - Jet Engine`
- `Security Hall - 8 Animals (Expert)` no longer requires `Rouge - Pick Nails`
- `Sky Rail - Item Box 8 (Standard)` now requires `Shadow - Air Shoes` and `Shadow - Mystic Melody`
- `Cosmic Wall - Chao Key 1 (Standard/Hard/Expert)` no longer requires `Eggman - Mystic Melody`
- `Cannon's Core - Pipe 2 (Expert)` no longer requires `Tails - Booster`
- `Cannon's Core - Gold Beetle` no longer requires `Tails - Booster` nor `Knuckles - Hammer Gloves`
Generations and spoiler checking
=> SA2B: Logic Fixes

worlds/shivers/__init__.py
Shivers cannot generate with LADX or with plando or anything else that utilizes get_pre_fill_items.
A typo that used to exist in Shivers (compelte instead of complete) was inside the plando items rewrite, and worked correctly. But the Shivers typo was later fixed and the plando rewrite was not.
Generating with LADX and plando
=> Shivers: Fix get_pre_fill_items

Fill.py
When unfolding location groups, plando could add in locations from a group that didn't match the player the group came from. So if multiple worlds had identical location names, they could get added as expected locations when they shouldn't be, and the behavior depended upon the player order.
Using these two files, where Emerald includes this plando block:
```yaml
plando_items:
- item: Pearl
location: Pokedex
world: null
force: true
```
And seeing that before this change, the `Pokedex` location group would expand and include Pokemon Red/Blue's locations (which happen to have the same name as Emerald's), if Emerald resolved before R/B. This would happen despite the fact that "Pokedex" is not a valid group name in Red/Blue.
The resolved locations were check by just doing …
=> Plando Items: Fix Location Groups Unfolding

Fill.py
"Exception: Cannot place item to ['2', '1', '0']'s world as that world does not exist."
&rarr;
"Exception: Cannot place item to 0's world as that world does not exist."
Generating with an item plando block that used `world: ["2", "1", "0"]` with players named "2" and "1".
=> Plando Items: Better Warning for Nonexisting Worlds

AdventureClient.py
Part of https://github.com/ArchipelagoMW/Archipelago/pull/4811
Replaces Utils.get_settings with settings.get_settings in AdventureClient.  The incorrect death_link check I think I should address separately.
Generated and ran a couple adventure MWs.
=> AdventureClient: Replace Utils.get_settings with settings.get_settings

worlds/shapez/docs/de_shapez.md, worlds/shapez/docs/en_shapez.md
The shapesanity cheat sheet, which is uesd on the game's info page, is included in the apworld. The webhost shows it by accessing the file on the GitHub repo. This is to make the webhost use the AP main repo instead of the maintainer's repo.
👀 
This should prevent graphical changes if my repo goes down one day for some reason
=> shapez: Change link to shapesanity cheat sheet

worlds/pokemon_rb/docs/setup_en.md, worlds/pokemon_rb/docs/setup_es.md
This is replacing the link to the Pokémon RB Tracker made by Coveleski & me to a new branch just maintained by me.
Coveleski and I have split, I have no control of the old branch, he hasn't written in the AP servers in ~6 months, the old version has several major bugs that this fork of mine fixes. I am one of the original authors but the whole thing is also MIT-licensed.
With Support from Alchav & GerbilJames (this was already discussed), I will also overhaul the tracker to implement many of the features other Pokémon-Trackers have, such as Auto-Map-Tabbing, Pokémon-Tracking, Encounter Tracking and maybe even ER-Tracking.
I am also submitting a PR to BlackSliver's Community Pack List to make the old pack update to this new fork, as well as hoping to get the pins changed in the #pokemon-rb …
=> Pokémon RB: Use new link for a new tracker

worlds/pokemon_rb/client.py
Allows the Pokemon Red & Blue client to send bounce messages when the player changes maps in game, this allows trackers to automatically change maps
Verified that the bounce messages are sent with the correct map ID by running the multiserver locally with debug logging enabled
N/A
=> Pokemon RB: Client: Send bounce messages with current map ID

worlds/wargroove/Client.py
This fixes the crashes found in the communication thread for the Wargroove 1 client. It also keeps the communication thread alive.
I hard coded an exception and it was caught. The thread was verified to still be running. I started the client normally and it functioned as intended.
=> Wargroove communication thread fix

worlds/tww/randomizers/ItemPool.py
This PR fixes a bug in swordless mode where swords were being placed into the item pool. This was because the swords remained in the useful items pool in the old code and were thus potentially added after progression items were placed.
Fixes #5102.
Generated a spoiler log before and after the change with swordless mode and ensured no swords were placed. Checked the other sword modes as well to ensure swords were placed correctly for those as well.
N/A
=> TWW: Fix swords in swordless mode

worlds/stardew_valley/data/craftable_data.py
It was discovered today that the slot machine level requirements are 2-4-6-8, not 2-4-4-4. I suspect it was a bad copy paste job originally.
The mod data can be found here: https://github.com/Pet-Slime/StardewValley/blob/master/LuckSkillCode/ContentPatcher/%5BCP%5D%20LuckSkill/Data/CraftingData.json
Not much. It still passes tests, but I didn't make a new one, as this is an arbitrary value and the test would have to be just as arbitrary
=> Stardew Valley: Fixed luck level requirements for slot machines

docs/world api.md, worlds/AutoWorld.py
Typos in the docs. This prevented me from finding the code for `get_pre_fill_items` during a dev chat on Discord.
:eyes: and Ctrl+Shift+F
=> Docs: fix 'get_pre_fill_items' being typo'd as 'get_prefill_items'

Main.py, NetUtils.py, test/general/test_implemented.py
converts slot data and er hint info into base structures that json well (int, float, str, dict, tuple).
I generated with Factorio and loaded the .archipelago into multiserver
=> Core: ensure slot_data and er_hint_info are only base data types

worlds/factorio/Options.py
MapGenSettings.html is now its own page, so the previous link just went to the top of concepts.html.
Navigating to that URL
=> Factorio: Fix link to world_gen documentation

worlds/dlcquest/Items.py
start inventory error with lfod
https://discord.com/channels/731205301247803413/1392654857940373654
fixing a crash if you ask for some lfod only item  in start inventory
Previous gen that crash don't anymore and the fix was already test in basic campaign I forgot to copy it to lfod.
=> DLC Quest Bug Fix Start inventory lfod

worlds/tunic/ut_stuff.py
I feel like it should just auto-detect stuff like this, but whatever. At least it doesn't crash without this line in.
Fixes it so breakables actually show up on the map.
Genning game on 0.6.1, connecting latest UT to it, connecting latest poptracker, observing the hover text for a pot location.
=> TUNIC: Fix missing line for UT stuff

Utils.py, docs/network protocol.md
moves uuid caching to appdata and uuid generation to be a random uuid instead of getnode's hardware address driven identifier and updates docs to point to the shared cache
obviously if we want to alter the specifics (like how we generate or where we cache it) of this we can, but I think as-is this makes the most sense with how uuid is intended to be used
ran the function without a file, with the file but without the uuid in it, and with a custom value in the file and got appropriate values back.
=> Core: Update UUID handling to be more easily sharable between libraries

worlds/hk/__init__.py
explicitly adds white palace filler to exclusions so they won't be valid filler names when the area is excluded
fyi this is harder to do in the rewrite so may just be removed instead
lightly, generated a game that had good chances to generate totem fillers and didn't see any palace totems outside of palace
=> HK: explicitly exclude palace items as well

WebHostLib/__init__.py, WebHostLib/api/generate.py, WebHostLib/api/room.py, WebHostLib/api/user.py, test/hosting/webhost.py
update the id formatter to use staticmethods to not fake the unused self arg, and then use the formatter for the user session endpoints
found testing #4887
the user session responses have unusable ids that cause the id parser on webhost to error out with a `ValueError: bytes is not a 16-char string`
this also refactors the formatter class to use the staticmethod decorator like it's already being used
```py
import requests
s = requests.Session()
s.get("http://localhost/session/a66f6a05-5c23-4473-8cc0-f9b2c70c27bb")
api_base = "http://localhost/api"
get_rooms_response = s.get(f"{api_base}/get_rooms")
assert get_rooms_response.status_code == 200, "get_rooms failed"
rooms = get_rooms_response.json()
first_room = rooms[1]["room_id"]
room_status_response = …
```
=> WebHostLib: Properly format IDs in API responses 

worlds/sm/Options.py, worlds/sm/__init__.py
Purely cosmetic changes to the options page (which also affects the default auto-generated YAML).
Adds more explanation to some options. For example, there is now a brief description of difficulty presets, VARIA tweaks explains what it does, etc. Most descriptions I added are from the VARIA website, reworded a bit to balance descriptiveness and conciseness.
This also groups the options into categories, of which I created 7. These are also roughly based on VARIA's groupings. This may make the somewhat-dense options page a bit more approachable. At least I think it looks nicer!
There are a few fixes for typos and grammar as well.
Finally, this removes the unused "Option" import in Options.py. Its removal doesn't seem to have affected anything.
Any feedback or suggestions on how to improve …
=> SM: Improve options descriptions, categorize options

worlds/raft/__init__.py
In #4782 a line wasn't refactored properly, causing generation errors if `filler_item_types` is set to `duplicates` or `both`
https://github.com/ArchipelagoMW/Archipelago/blob/a948697f3a2387d13862a194690c39af8da2dbd8/worlds/raft/__init__.py#L95
https://github.com/ArchipelagoMW/Archipelago/blob/eba757d2cd468182f4d0500ab87c45d379b225d2/worlds/raft/__init__.py#L96
Generations before and after with `filler_item_types` set to all three values.
=> Raft: Fix filler_item_types TypeError introduced in #4782

Dockerfile, ModuleUpdate.py
Prevents `ModuleUpdate` from processing unnecessarily during container image runtime, by adding an environment variable as an additional check for `_skip_update`.
As an additional benefit, this fixes `aarch64` image support, where `dolphin-memory-engine` (not required for AP web hosting) is not packaged for said architecture.
The flag is set to `true` in the `Dockerfile`
Built new images for both `x86_64` and `aarch64` using these changes and deployed using the steps laid out in docs.
=> fix(env): Prevent module update during container runtime

worlds/alttp/__init__.py
ALttP's `pre_fill` makes a state and that state performs a sweep, picking up pre-placed items, such as a plando'ed Moon Pearl. The sweep it performed before the Crystals/Pendants are removed the state, so the fill performed afterwards is invalid/incorrect.
https://discord.com/channels/731205301247803413/1395423424515670030
```yaml
plando_items:
- item: Moon Pearl
location: Master Sword Pedestal
force: true
```
=> ALttP: Fix `pre_fill` State Sweeping Too Early

MultiServer.py, docs/network protocol.md
Supercedes https://github.com/ArchipelagoMW/Archipelago/pull/4316
Basically, this is supposed to supercede the concept of LocationScouts with create_as_hint in general, and have additional functionality.
Thanks to Jarno458 and EmilyV99 for their reviews on https://github.com/ArchipelagoMW/Archipelago/pull/4316, as well as Scipio's, alwaysintreble's and EmilyV99's (again) reviews on https://github.com/ArchipelagoMW/Archipelago/pull/3523. I apologize that your review work is lost, finding the right design is an iterative process that can only be done with reviewers' help :)
One question I anticipate is:
The code looks really similar to LocationScouts, so what was wrong with the original PR that allowed off-world LocationScouts?
The difference here is that this PR doesn't send back a …
=> MultiServer: CreateHints command (Allows clients to hint own items in other worlds)

.github/workflows/build.yml
Fixes Linux build by switching to new appimagetool. The old downloads are dead now.
Since this does not have versions anymore, we check the sha256 and require manual intervention if it changed.
We also specify a specific runtime version (again, with sha256).
In the future we should look for a way to get reproducible appimages instead of just disallowing the build.
The built AppImage's Launcher works on my ubuntu22.04 VM and also tested the command line interface (i.e. start SNIClient directly).
I did not test any other system, but we don't have an alternative runtime anyway.
Also tested a couple of error cases in CI on my fork:
If the hash of either the appimagetool or runtime is unexpected, it errors in "Install build-time dependencies".
If the commandline for sha256sums was wrong, it'd …
=> CI: switch to new appimagetool

setup.py
Downgrades integrated SNI to v0.0.100 to work around problems with v0.0.101 on Linux.
While we could use a different version on Windows and Linux for this specific issue, I think it's generally better to use the same version across all users to avoid needing version information when a problem is reported.
Seeing the correct version of SNI getting downloaded. Tested both with "v0.0..100" and "latest".
=> setup: Downgrade bundled SNI to 0.0.100

worlds/ladx/LADXR/patches/aesthetics.py
Preserves newline characters within Marin text options rather than breaking it into separate options.
Generated and tested the rom to see that text with linebreaks works.
=> LADX: fix marin text splitting

docs/world api.md
We don't need to suggest this `exclude` method anymore because `start_inventory_from_pool` exists and should, in many cases, be used instead.
👀
=> Docs: Don't Suggest `exclude` in `create_items`

AdventureClient.py, MMBN3Client.py, OoTClient.py, Zelda1Client.py
While debugging unrelated problems, I noticed that the OoTClient was constantly outputting "Attempting to connect to N64" and "Connection Refused, Trying Again" messages at a rate of 3-4 thousand per second. Since this was on Linux, all of those also ended up in my system log, i.e. written to disk. Which is, let's just call it, "not great".
This only affects the case where the emulator / Lua connection isn't running yet, because the connect timeout doesn't apply if the port is closed.
It wasn't. I'm opening this PR mainly in order to ask whether this was just never considered, or somehow isn't a problem for anybody else. I can't be the only one who doesn't enjoy 2x 4k messages/second ending up on their disk, and this code is ancient. Either nobody noticed (which is fine!), or there's a …
=> Various: Make clients wait a second between emulator connection attempts

worlds/subnautica/__init__.py, worlds/subnautica/options.py
Adds a new option that keeps tanks in inventory effectively empty.
Also forces an update of the client.
locally, with the new client https://github.com/Berserker66/ArchipelagoSubnauticaModSrc/releases/tag/1.9.0
=> Subnautica: add empty tanks option

worlds/dark_souls_3/__init__.py
Previously only the DLC regions and entrances weren't being created, but the DLC and NGP locations that were not in those regions would still get created, even though they were disabled. In the NGP case, this actually means they were fully inaccessible. This changes the behavior to not create any DLC or NGP locations if those are disabled by the options.
Generations with enabled and disabled NGP and DLC to see that locations were no longer being created when they weren't supposed to be.
It's worth noting that this just _happens_ to work out since none of the DLC and NGP locations that are not already in DLC regions are required by any parts of the logic outside of DLC and NGP locations and regions. That is to say, the DLC regions and the NGP locations are entirely self-contained when it …
=> DS3: Don't Create Disabled Locations

BaseClasses.py
`self.unreachables` is a set, so its iteration order changes depending on the Python process' random internal hash seed.
This change sorts the unreachable advancement locations before outputting them to the spoiler. Comparing spoilers generated with the same seed can be a simple method to check that a multiworld is generating deterministically (while ignoring the playthrough because playthrough is deliberately nondeterministic). The unreachable advancement locations were being written to the spoiler in a nondeterministic order.
Note that unreachable advancement locations are currently only written when the playthrough is enabled.
I generated a fixed seed with minimal accessibility and an early goal twice and observed that the order of the unreachable progression items/locations was the …
=> Core: Sort unreachable advancement locations written to the spoiler

.github/workflows/build.yml, .github/workflows/release.yml
Updates the hashes of appimage runtime.
If the next update happens in less than 6 Months, I think I'll fork it just to add tags, so we can upgrade at our own pace without breaking CI.
* Gave it a quick spin in an ubuntu vm.
* Downloaded the runtime, checked the gpg signature against what's in their repo, compared sha256sums.
```sh
gpg -o appimage-signing-pubkey.gpg --dearmor signing-pubkey.asc
gpg --no-default-keyring --keyring ./appimage-signing-pubkey.asc --verify runtime-x86_64.sig
```
=> CI: update appimage runtime

WebHostLib/misc.py
Tutorial changed to use the actual markdown filename, so URLs indexed by search engines are wrong now.
This replaces the old URL scheme with permanent redirects, updating search indices when being crawled the next time.
As a side note: I think if we implement proper multi-language support, it should be `/tutorials/<lang>/...` or `/<lang>/tutorials/...`, so I don't think we need to change back the tutorial route at this point.
Clicking the broken sitemap links locally.
=> WebHost: redirect old tutorials to new URL

worlds/osrs/Locations.py, worlds/osrs/LogicCSV/LogicCSVToPython.py, worlds/osrs/LogicCSV/locations_generated.py, worlds/osrs/Options.py, worlds/osrs/Rules.py, worlds/osrs/__init__.py
the OSRS UT integration had some limits when task categories weren't set to maximum possible tasks, 
In fixing this, some gen failures were identified and fixed/added OptionError exceptions where relevant
Also fixes problem with get_filler_item_name
Tested using the new UT fuzzer integration
=> [OSRS] Fix UT integraiton and various gen failures 

Dockerfile, ModuleUpdate.py, setup.py
setuptools ~~70.3.0~~ 65 seems to not work for us.
See whatever is happening here <https://discord.com/channels/731205301247803413/731214280439103580/1407239379814191164>;
cx_freeze has a requirement on setuptools, so we don't want to enforce the absolute latest version.
```bash
pip uninstall setuptools
pip install setuptools==65.5
python ModuleUpdate.py
```
and see it upgrade setuptools to 80.9.0
```bash
python setup.py
```
and see it downgrade setuptools to 75.8.0
=> Core: require setuptools>=75

Fill.py
Fixes an issue introduced in https://github.com/ArchipelagoMW/Archipelago/pull/4610
If there are regular progression items and deprioritized items, and there is no way to fill the priority locations with only regular progression, deprioritized progression will be used instead. If that also doesn't work, it crashes. So far, so good.
But: If there are regular progression items and *no* deprioritized items, it *doesn't* crash, because the place it would crash (the final attempt using allow_partial = True) never happens. Which is wrong. So this fixes that
=> Core: Fix Priority Fill *not* crashing when it should, in cases where there is no deprioritized progression

entrance_rando.py
Currently, on densely packed regions with a lot of interconnectivity, regions are added several times to the queue, which leads to exponential times
Say we have 0 >1, 0>2, 0>3, 1>2,1>3 and 2>3. 0 will add 1, 2, 3 to the queue, then 1 on explore will add 2 and 3, then 2 will add 3 twice to the queue and now 3 is explored 4 times in this minimal example
On my Tilesanity branch, GER was still initializing after 10 minutes. After this fix, it was done in a second
=> Core: Improved GER's caching of visited nodes during initialization

WebHostLib/options.py, WebHostLib/templates/playerOptions/macros.html, WebHostLib/templates/weightedOptions/macros.html
Say we have an option like this:
```
class AllowedTricks(OptionSet):
valid_keys = {"Sword Skip", "Shield Skip", "XD Skip"}
default = {"Shield Skip"}
```
On WebHost, this will be displayed as three checkboxes.
If any of them are checked, the option exports correctly to yaml when clicking the "Export Yaml" button.
However, if none of them are selected, the allowed_tricks option will be **missing from the generated yaml entirely**.
This is because unchecked checkboxes are not sent as POST data, which means the generate_yaml endpoint will not be aware of the existence of the option at all.
This however causes an issue - When an option is not present in the yaml, it will be treated as its **default value**.
So even though the user manually unchecked "Shield Skip", since the option is now …
=> WebHost: Ensure that OptionSets and OptionLists get exported to yaml, even when nothing is selected

worlds/timespinner/Items.py, worlds/timespinner/Options.py
v1.35.0 of the Timespinner randomiser added Spider Traps; this adds corresponding support into the apworld. (https://github.com/Jarno458/TsRandomizer/pull/174 will need to land upstream before this works completely)
Generated some worlds to confirm placement of the new trap.
N/A
=> Timespinner: add support for spider traps from new client release

WebHostLib/api/tracker.py
- Fixes a crash on `GET /api/tracker/<tracker>` caused by writing to a non-existent key.
- Previously wrote to `activity_timers[team]["player_timers"][player - 1]["time"]`
- The structure actually uses `{"team": team, "players": [...]}`  
- ✅ Replaced `"player_timers"` with `"players"` when assigning timestamps.
- Timestamps remain timezone-aware (UTC) via `datetime.fromtimestamp(ts, timezone.utc)`.
- **No schema change**: the response shape is unchanged; the `"time"` fields now populate correctly instead of raising an exception.
```diff
- activity_timers[team]["player_timers"][player - 1]["time"] = datetime.fromtimestamp(timestamp, timezone.utc)
+ activity_timers[team]["players"][player - 1]["time"] = datetime.fromtimestamp(timestamp, timezone.utc)
```
- Reproduced the bug before the fix …
=> WebHost: fix activity_timers in API tracker.py

docs/running from source.md
update docs since 3.13 is supported
=> Docs: Update max py version to 3.13

MultiServer.py
add check to status arg that it's a valid and known hintstatus
spun up multiserver, ran a createhints with status of `"0"`, `0`, missing, and `9999` and saw the invalid values error properly back to the client
also added a return to the other InvalidPacket response as it was probably intended
=> MultiServer: Validate CreateHints status arg

worlds/heretic/docs/setup_en.md
They did it again. As of August 7th, 2025, Heretic was merged with Hexen and provided a new game ID on Steam, rendering the old one defunct. This PR updates the old URL to the new one. Luckily for us, they treated this new remaster just like Doom + Doom II and retained the original DOS version's data files.
Reading
=> Heretic: Update Steam URL

Generate.py, Main.py, WebHost.py, WebHostLib/generate.py, WebHostLib/lttpsprites.py, worlds/bumpstik/Items.py, worlds/meritous/Items.py
lazy import or try/catch some lttp imports, as well as remove the alttp.EntranceRandomizer call in generate/webhost and replace it with the literal defaults already being used
could also potentially come with a full deletion of `alttp.EntranceRandomizer`, but I didn't know if there was still a usecase for it that didn't have test coverage
ran unit tests, someone should gen lttp to make sure the patch files still work
also ran unit test with #5338 merged in and saw only the one expected error for the item group test noted in that ticket that uses lttp by game name, but nothing attempted to import the world that wasn't caught
=> Core: Remove lttp module requirement from generation

worlds/sc2/docs/setup_en.md, worlds/sc2/docs/setup_fr.md
Updates the docs how to launch SC2 Client under Linux to follow the client migration away from the custom exe
Launched the client using AppImage
No
=> SC2: Update docs for Linux launch script to follow the core client migration

CommonClient.py
When using a game that the matching apworld is installed for, the datapackage is not loaded by the methods used by the changed /items, /missing and /locations commands, claiming that the package was not loaded. This has lead to ample confusion, especially of devs who thought their datapackage was broken.
Alternative to https://github.com/ArchipelagoMW/Archipelago/pull/5349 that refuses to go down the rabbithole of continuing to use two ways to retrieve datapackage in parallel and unifies the approach across commonclient instead.
locally, made sure the removed method had 0 uses left
=> CommonClient: fix /items, /locations and /missing not working if the datapackage is local

worlds/dark_souls_3/detailed_location_descriptions.py
Use a safe yaml loader in the locations help generator script in DS3.
It's unexpected that this script can execute code from nex3's github if it would get compromised, but also it's best practice to not use an unsafe loader if not required, especially when the data comes from the internet.
Wasn't
=> DS3: use yaml.safe_load

WebHostLib/misc.py
https://discord.com/channels/731205301247803413/731213907380666488/1416427397993070715
In essence, setting Room.last_activity in parallel is bad. This reduces the chance of that happening to near enough zero that it should be effectively fixed.
I only tested regular spinup still works, I did not set up a swarm to test if the bug is truely fixed, though it should be,
=> WebHost: fix Internal Server Error if parallel access to /room/* happens

worlds/tunic/ut_stuff.py
Just adds the new name to the poptracker location list. There was no need to remove the old one, since it just sorta works with both, and would break back compat.
Launched UT and sent the location
=> TUNIC: Update name of a chest in the UT poptracker map integration

worlds/stardew_valley/rules.py, worlds/stardew_valley/test/rules/TestTravelingMerchant.py
I discovered, during a rebase of the 7.x.x branch, that main had a flaky traveling merchant test.
It is fixed in the [7.x.x PR](https://github.com/ArchipelagoMW/Archipelago/pull/5432), and it would be better for me to merge it, instead of this, but obviously pushing through a 15k lines PR for such a small fix is unreasonable, so I cherry picked it in its own PR instead so it can get merged faster. I'll deal with the conflicts later.
The issue was simply that, depending on which cached worlds the test was grabbing (order of tests), it could land on settings that would invalidate its assumptions. Plus, the fact that, at 1000 cost, you only need to have pierre and start outside of winter to invalide the shipping bin, so I also increased the price a bit.
Ran the tests a couple times, not …
=> Stardew Valley: Fixed Traveling merchant flaky test

worlds/factorio/Client.py
The ability to reconnect the Factorio RCON client when it times out without needing to restart the Factorio client.
Game watcher no longer dies when RCON client connection is lost, it just waits for it to be restored.
Do things in factorio that causes the factorio server to take so long to process a request that the RCON client connection times out,  then when the factorio server is done processing whatever it was processing, issue /rcon_reconnect to the factorio ap client.
=> [Factorio]: Allow to reconnect a timed out RCON client connection.

worlds/jakanddaxter/test/test_trades.py
The test `TradesCostEverythingTest` fails randomly more often than we would like, which impacts other developers, worlds, and their unit tests. Examples [A](https://github.com/agilbert1412/Archipelago/actions/runs/17387737657/job/49356833708), [B](https://github.com/ArchipelagoMW/Archipelago/actions/runs/17415447817/job/49442655388?pr=5166), and [C](https://github.com/ArchipelagoMW/Archipelago/pull/5461).
These are fill errors due to being unable to place 20 Power Cells in Jak's first hub area. Under default options, this failure is extremely rare. However, this test increases the likelihood of failure because nearly all Orb items are marked as Progression during this test. Core is now flooded with more Orbs than Cells, and it cannot pick enough cells to put in hub 1.
Power Cells are not …
=> Jak and Daxter: close Power Cell loophole in trades test

worlds/sc2/options.py, worlds/sc2/test/test_base.py, worlds/sc2/test/test_custom_mission_orders.py, worlds/sc2/test/test_generation.py, worlds/sc2/test/test_item_filtering.py, worlds/sc2/test/test_rules.py, worlds/sc2/test/test_usecases.py
Following today's great big discussion on sc2 performance, an older topic was brought up relating to our default options. In particular, the default options for included campaigns list all campaigns (3 main campaigns + 1 mission pack + 3 subcampaigns that come with bigger campaigns). Of these, only 1 main campaign and 2 subcampaigns are actually free-to-play; the rest must be purchased before use.
It turns out that changing the default to only the free-to-play main campaign (Wings of Liberty) brings generation time for 5 default yamls from ~70s to around 10s. Doing all free campaigns (WoL+Prophecy+Prologue) is similarly fast, though would have an unbalanced pool of 25 terran missions to 9 protoss, so I'm making that non-default. Considering the developer experience (many core unit tests …
=> Sc2: [performance] change default options

LinksAwakeningClient.py, worlds/ladx/LADXR/generator.py, worlds/ladx/LADXR/patches/bank3e.py
Regarding this bug report: https://discord.com/channels/731205301247803413/1395843213436125194
We store 100 player names on the rom for displaying on picking up or receiving items. Any slot higher than 100 is treated as if it were slot 100.
We actually already had the generic "another world" in the 101st slot, so this change caps the name slot to 101 instead of 100.
Generated, fuzzed, patched, made sure the rom works. Generated a game with 200 Yacht Dices.
=> LADX: use generic slot name for slots 101+

Utils.py
Alternative to https://github.com/ArchipelagoMW/Archipelago/pull/5310 which tackles the problem at a slightly deeper level, as well as reduces the amount of needless writes to disk, so it may be worthwhile in its own right.
similar to 5310, via debugger to see if the if fires as desired
as far as I could see, all values support equality tests, and to be fair, values not supporting that are pretty rare, but it is technically a new limitation
=> Core: only store persistent changes if there are changes

worlds/sc2/item/item_tables.py, worlds/sc2/locations.py, worlds/sc2/rules.py
* Fixing any_units allowing unupgraded zerg mercs for the first unit when further down zerg mercs were listed again requiring upgrades to count as viable
* Fixing Shoot the Messenger lacking anti-air hard rules; the rough guideline is that locations requiring the player to kill something in the air should have a hard rule for AA (and shuttles qualify)
* Adding an addendum to each any_units rule to require that faction's `any_anti_air` in the first 5 units
Fixing a minor issue reported recently: the symptom was that a Reaver upgrade item was being sorted as a Scout item under `/received`. This data is also used for item culling, so I'd expect it would result in the item being culled if Scout was culled rather than Reaver.
Ran unit tests. Mostly by inspection.
None
=> SC2: any_unit and item parent bugfixes

WebHost.py
filter world types at top of webhost so worlds that aren't loadable in webhost are "uninstalled"
could also add more requirements if there are other known issues
alternatively webhost should have it's own register that it pulls from AutoWorld and filters down, but then every single file in webhostlib would need to be retargeted to use the other register
idk if the filter() is better or even looks better than a comprehension tbh
commented out the world.web declaration of a world and confirmed they were dropped from the /tutorial page (and that the page loaded at all)
=> Webhost: Ignore Invalid Worlds in Webhost

Main.py
Adds padding for world version added to the printout in #5484 since currently it gets shifted for version strings of different lengths and also has no space after the first bar (which I think was unintentional anyway since it wasn't in [this message](https://discord.com/channels/731205301247803413/731214280439103580/1420629227023110195)).
This does happen to raise the line length for core games from a perfect 80 columns to 83, although that was already broken by Muse Dash having an extra char in version and being 81 (and just like what the names/counts happened to be anyway).
Also do we like that the longest game's one doesn't have a space before the colon? That was already the case before the version was there but I think it looks kinda bad.
Looking at the output when generating.
```
... …
```
=> Core: Pad version string in world printout

worlds/civ_6/docs/setup_en.md
Further updating the Civ VI setup instructions based on what issues people have had since they were updated. Notable change to list the zip method first as multiple people have had issues with the associate the patch file with archipelago. Added a connecting to game section as multiple people have tried connecting to the game with the text client.
Tested on a local webhost.
=> Civilization VI: Update for the setup instructions

worlds/aquaria/docs/setup_en.md, worlds/aquaria/docs/setup_fr.md
Modifications of the game documentation to add some new information about the latest Aquaria client.
Also, a bug happens where there is not sound when running on the Steam Deck. So adding the workaround to fix it.
It is documentation. No test required... I think.
=> Aquaria: Updating documentation to add latest clients informations

Fill.py
There is a limit to the number of times an item can be swapped to prevent swapping going on potentially forever. Swapping an item with a copy of itself is assumed to be a pointless swap, and was wasting possible swaps in cases where there were multiple copies of an item being placed.
This swapping behaviour was noticed from debugging solo LADX generations that was wasting swaps by swapping copies of the same item.
This patch adds a check that if the `placed_item` and `item_to_place` are equal, then the location is skipped and no attempt to swap is made.
If worlds do intend to have seemingly equal items to actually have different logical behaviour, those worlds should override `__eq__` on their Item subclasses so that the item instances are not considered equal.
Generally, …
=> Core: Don't waste swaps by swapping two copies of the same item

Options.py, Utils.py, setup.py, worlds/Files.py, worlds/__init__.py
Cleans up a couple uses of `Version(*tuplize_version(...))`, which is redundant, an unused import and var, and an unneeded base parameter in `int`.
Running generation to make sure it doesn't somehow break it.
=> Core: Cleanup unneeded use of `Version`/`tuplize_version`

MultiServer.py, NetUtils.py, WebHostLib/customserver.py, test/benchmark/compression/benchmark.py
Improves Multiserver and customserver performance.
* Client/Endpoint can use slots, which saves some bytes and makes attribute access typically faster (not bench-marked this time).
* The changed compression settings should save ~16KB per connection. Performance (CPU) is similar, transferred data is somewhere between +1% and +15% depending on the kind of payload. Since we are at -90% from plain transfer, that difference is actually small in absolute numbers.
* Added benchmark for compression settings, which also lists some more details.
Side note: while the savings in total memory usage are quite small, saving memory also improves cache performance under heavy load.
Connecting to MultiServer and not getting a compression warning.
=> Multiserver: slight optimizations
