- WebHostLib/static/assets/tutorial/minecraft/minecraft_en.md
slightly updated pull request that specifies the Java edition of minecraft to help avoid confusion.
> Mincraft Tutorial

- WebHostLib/static/assets/tutorial/minecraft/minecraft_en.md
new changes to tutorial, fix some grammar and reflect the change in the /connect command.
> minecraft setup tutorial changes.

- WebHostLib/static/assets/tutorial/minecraft/minecraft_en.md
added the explanations back in and manually warping them to look good on the web site.
> re-added stuff

- MultiServer.py
The world is bigger than just Hyrule.
fix remaining command to look for items from all games.
> !remaining fix

- WebHostLib/static/assets/tutorial/minecraft/minecraft_en.md
fix pointing them to the correct default settings  yaml.
> tutorial changes

- worlds/subnautica/Rules.py
Range 940 -> 950
Y-axis is considered in the distance check.
> Adjust radiation rules to match code

- ModuleUpdate.py
-f: force update
-y: skip question to run pip
> ModuleUpdater: add -f and -y switches

- worlds/factorio/data/mod_template/control.lua
* check for resources inside collision box for first half of tries
* minor code clean-up
> Factorio: avoid ores when spawning silo

- .github/workflows/unittests.yml
Expected to need multiple attempts to get it working, so I made a branch. Nailed it though.
> Install all modules for unittests.yml

- MinecraftClient.py
- host.yaml
Uses the setup changes from #48
> Minecraft client

- BaseClasses.py
- worlds/alttp/Dungeons.py
- worlds/alttp/EntranceShuffle.py
- worlds/alttp/OverworldGlitchRules.py
- worlds/alttp/Rules.py
- worlds/alttp/__init__.py
> ALttP generation fixes

- BaseClasses.py
> set get_all_cache properly

- BaseClasses.py
- worlds/alttp/Dungeons.py
- worlds/alttp/Rules.py
- worlds/alttp/__init__.py
Should improve this async's generation rate considerably, since there is a beatable-only world.
> Fix for beatable-only key placement

- WebHostLib/static/assets/tutorial/ror2/setup_en.md
- worlds/alttp/Shops.py
- worlds/ror2/Items.py
- worlds/ror2/Locations.py
- worlds/ror2/Options.py
- worlds/ror2/Rules.py
- worlds/ror2/__init__.py
Removed the scraps only preset, added links to the RoR2 tutorial, and added functional progression logic to RoR2.
> RoR2: Add logic and increase item pool max.

- WebHostLib/static/assets/tutorial/archipelago/setup_en.md
- WebHostLib/static/assets/tutorial/tutorials.json
Previous PR got mangled when I updated my fork
> Add a general archipelago setup tutorial

- worlds/minecraft/Locations.py
- worlds/minecraft/Rules.py
A Furious Cocktail is bad so let's just get rid of it
> Minecraft logic update

- worlds/oot/EntranceShuffle.py
- worlds/oot/Options.py
- worlds/oot/__init__.py
I have solved the generation issues and have achieved a very low failure rate, so we should be able to have all forms of ER now. I promise this is the last PR I'm making before 0.2.0.
> OoT ER: Interior and Overworld Entrance Shuffle

- worlds/oot/__init__.py
set internal value of shuffle_interior_entrances to False instead of 'off'
> OoT: fixed glitched not rolling

- WebHostLib/static/assets/tutorial/secret-of-evermore/multiworld_en.md
easier to set up with SNI 0.0.59 :)
> SoE: update tutorial for 0.2.1

- SNIClient.py
still need to do and test the other end
> SNIClient: add #server= to url for soe/wasm client

- WebHostLib/static/assets/tutorial/zelda3/msu1_en.md
List assembled for use in competitive Zelda restreams.  Permission sought and granted by author Amarith via DM.
> Add known safe MSU-1 list

- Options.py
- worlds/minecraft/Options.py
- Fixed auto-generated yaml template defaults
- Fixed `starting_items` spoiler log error
> Pre-0.2.1 Minecraft bug fixes

- MinecraftClient.py
This fixes the critical security issue recently found in Minecraft.
> Minecraft client: update Forge to 1.17.1-37.1.1

- WebHostLib/static/assets/gameInfo/en_Final Fantasy.md
- WebHostLib/static/assets/supermetroidTracker.js
- WebHostLib/static/styles/supermetroidTracker.css
- WebHostLib/templates/supermetroidTracker.html
- WebHostLib/tracker.py
Adds an item and location tracker based on the TimeSpinner and OOT trackers.
The tracker uses the VARIA Randomizer location database for sorting locations. Sprites are referenced from the VARIA Randomizer/Solver's main website.
> [WebHost] Add Super Metroid support to Web Tracker

- worlds/alttp/Dungeons.py
- worlds/alttp/ItemPool.py
- worlds/alttp/Options.py
This adds a "Start With" option for dungeon items in ALTTP, replacing those items in the item pool with junk items
> Add "Start With" option to ALTTP dungeon items

- docs/network protocol.md
to hopefully prevent people from creating their own clients
> [Docs] Added links to client implementations

- worlds/timespinner/Locations.py
After my community pointed me at my mistake i was confusing this location with a different one
> [Timespinner] Fixed logic of journal

- WebHostLib/static/assets/gameInfo/en_Ocarina of Time.md
Changed Ocarina of Time to Zelda's Letter since that's what other world items look like here.
> Minor fix for OoT game info

- worlds/oot/Rules.py
- worlds/oot/__init__.py
This should fix issues where dungeon items were incorrectly filled onto Song from Impa, as well as prevent future bad starting inventories.
> Starting item safeguards

- worlds/alttp/Shops.py
Ensure shop prices are a multiple of 5 after price modifier
> LTTP shop price modifier tweak

- WebHostLib/static/assets/tutorial/timespinner/setup_en.md
- Game executable names for Linux and Mac were wrong
- Fixed some typos and changed grammar and semantics in some places
> Corrected typos and wrong information

- worlds/oot/Rules.py
I don't know how this one slipped past me tbh but at least it's easy to fix.
> Fix skip_child_zelda with song shuffle: songs

- worlds/factorio/Options.py
- worlds/factorio/data/mod_template/control.lua
Attenuate evolution trap increases based on game's current evolution_factor to improve difficulty slider scaling. See drive.google.com/file/d/1RBBZV3XRmvgwOTXJhr6aQJIaTatJc2WF
> Factorio - Attenuate evolution trap increases

- WebHostLib/templates/timespinnerTracker.html
- WebHostLib/tracker.py
- worlds/timespinner/Locations.py
Added Talaria Attachment to tracker if QuickSeed is enbled
Added new locations ids to tracker
Added new chest & logic for Ancient pyramid
Made tracker change available locations based on flags
Made tracker only show items that are progression based on selected flags
> [Timespinner] Updated tracker + Ancient Pyramid logic

- WebHostLib/static/assets/gameInfo/en_VVVVVV.md
- WebHostLib/static/assets/tutorial/tutorials.json
- WebHostLib/static/assets/tutorial/v6/setup_en.md
- worlds/v6/Items.py
- worlds/v6/Locations.py
- worlds/v6/Options.py
- worlds/v6/Regions.py
- worlds/v6/Rules.py
- worlds/v6/__init__.py
As VVVVVV is open source, I just forked it and added support [here](https://github.com/N00byKing/VVVVVV/tree/archipelago) (Branch `archipelago`). Clone incl. submodules!
~~Compilation requires C++11 and `cmake`. (Most?) Dependencies are bundled.
In the `desktop_version` folder, create a folder `build` and run `cmake ..`, followed by `make`.
Copy the `data.zip` containing assets from an existing Steam/GOG installation of the game. As these are copyrighted, I can't redistribute them.
Run with `./VVVVVV -v6mw_name <Username> -v6mw_ip <IP>` and, if required add `-v6mw_passwd <Password>`~~
Installation as follows (Windows):
- Download `v6ap_win.zip` from [here](https://github.com/N00byKing/VVVVVV/actions/workflows/ci.yml?query=branch%3Aarchipelago)
- Unzip the v6ap_win.zip where you have …
> Add VVVVVV to Archipelago

- worlds/v6/Options.py
- worlds/v6/Regions.py
- worlds/v6/Rules.py
Causes Generation Issues, though I dont know why.
Also raise DoorCost max to 5
> V6: Remove "The Final Level" Region

- worlds/sm64ex/__init__.py
Please dont hurt me
Text from Wikipedia
> sm64ex: Remove placeholder text

- worlds/ror2/Locations.py
- worlds/ror2/Options.py
- worlds/ror2/__init__.py
Increased max total locations from 100 to 500
Increased max number of revives from 10 to 50
Increased max weight for all item groups from 100 to 500
> Increase Location count and Item pool count

- worlds/v6/Options.py
- worlds/v6/Rules.py
- worlds/v6/__init__.py
I feel like there's either problems with my understanding of python, or with the generator.
DoorCost of 4 is logically possible and does generate, but only with 40% chance of success.
The Logic for V6 is pretty small, and I don't really see any errors. My Code also doesn't introduce any random elements which could cause the generator to only fail sometimes, as far as i know.
I don't know what's going wrong, so for now limit DoorCost back to 3.
> v6: Mitigate Generation Problems

- worlds/sm64ex/Locations.py
- worlds/sm64ex/Regions.py
- worlds/sm64ex/Rules.py
- worlds/sm64ex/__init__.py
> sm64ex: More name changes

- worlds/sm64ex/Items.py
- worlds/sm64ex/Options.py
- worlds/sm64ex/__init__.py
> sm64ex: Add Option to limit stars, replace with junk

- MultiServer.py
- WebHostLib/static/assets/tutorial/archipelago/commands_en.md
`send_multiple` is same as `send` but allows for specific quantites
> Add send_multiple command

- worlds/v6/Options.py
- worlds/v6/Regions.py
- worlds/v6/Rules.py
- worlds/v6/__init__.py
Needs testing.
Builds available [here](https://github.com/N00byKing/VVVVVV/actions/workflows/ci.yml?query=branch%3Aap_test)
The Instructions for normal V6 apply, more specifically the launch options.
> v6: Add Area Randomizer

- worlds/sm/Options.py
Adding documentation to Super Metroid game options.
> [SM]Update Options.py

- worlds/sm64ex/Items.py
- worlds/sm64ex/Locations.py
- worlds/sm64ex/Options.py
- worlds/sm64ex/Regions.py
- worlds/sm64ex/Rules.py
- worlds/sm64ex/__init__.py
For Course Rando: Python is the same as #249, but the Game Code is much more unstable, so needs some tests as well.
Progressive Keys should be pretty stable.
> sm64ex: Add Course Randomizer and Progressive Keys

- worlds/sm/__init__.py
Item is named "No Energy" not "NoEnergy"
> [SM] Fix "No Energy" bugs

- test/minecraft/TestMinecraft.py
- worlds/minecraft/Rules.py
- worlds/minecraft/__init__.py
didn't get this in time for 0.2.5 but it wouldn't have affected the async anyway, I suppose.
> Minecraft updates

- worlds/subnautica/locations.json
> [Subnautica] I guess someone had todo it

- worlds/oot/ColorSFXOptions.py
- worlds/oot/Options.py
Honestly do not know how this happened but not all the `displayname` attributes got renamed, so it broke the adjuster.
> Fix OoTAdjuster

- WebHostLib/downloads.py
- WebHostLib/static/assets/tutorial/sm64ex/setup_en.md
- WebHostLib/static/assets/tutorial/v6/setup_en.md
- WebHostLib/templates/macros.html
- WebHostLib/upload.py
- worlds/sm64ex/__init__.py
- worlds/v6/__init__.py
Both output functions are the same except for the file ending
> v6,sm64ex: Add support for offline singeplayer seeds

- worlds/archipidle/Rules.py
- worlds/archipidle/__init__.py
Prevents overwrite of the global item pool
> Fix generation issues with ArchipIDLE

- data/lua/FF1/ff1_connector.lua
I don't want to allow versions for perpetuity because there have been enough breaking changes historically I would rather test them first. On the bright side the text looks nicer on the newer version :)
> Adding in support for bizhawk 2.8

- Options.py
> Options: implement item name groups for item sets options

- Options.py
should look a bit nicer to the humans for whom this output is created.
> Options: sort values when displaying OptionSet

- MultiServer.py
TK may not be installed alongside python on some systems, like minimal linux installations.
> MultiServer: try to import tkinter, then provide some feedback

- Main.py
- worlds/AutoWorld.py
- worlds/factorio/__init__.py
Only used by Factorio and that use predates start_location_hints, which works perfectly fine for this purpose.
> Core: remove sending_visible

- BaseClasses.py
- Main.py
- Options.py
- worlds/alttp/EntranceShuffle.py
- worlds/alttp/ItemPool.py
- worlds/factorio/Technologies.py
Core: add some more types to State and add count() method
> Core: use assert correctly

- worlds/v6/Rules.py
> V6: fix area cost always referencing last area cost, instead of current index

- .github/workflows/release.yml
Add release action and some comments
> CI: add release action

- WebHostLib/static/assets/tutorial/ArchipIDLE/guide_en.md
- WebHostLib/static/assets/tutorial/tutorials.json
- Added ArchipIDLE setup guide
- Corrected ChecksFinder tutorial listing so it will receive a theme if one is set
- Corrected tutorial listing for LttP MSU tutorial
> Add ArchipIDLE Setup Guide

- WebHostLib/templates/islandFooter.html
Just when you thought 2021 was over.
> Webhost - Update copyright year

- .github/workflows/unittests.yml
- ModuleUpdate.py
- test/programs/TestGenerate.py
- test/programs/data/OnePlayer/test.yaml
* allows ModuleUpdate to be run outside of local_dir
* adds windows-latest to the unittest matrix
> CI: add Generate.py tests

- inno_setup.iss
> Setup: fix apparently forgotten file endings

- .github/workflows/build.yml
set setuptools to 60.x until the issue is resolved
change retention to 7 days
> CI: add windows build action

- BaseClasses.py
- worlds/alttp/__init__.py
- worlds/factorio/Mod.py
- worlds/minecraft/__init__.py
- worlds/oot/__init__.py
- worlds/sm/__init__.py
- worlds/sm64ex/__init__.py
- worlds/smz3/__init__.py
- worlds/soe/__init__.py
- worlds/v6/__init__.py
Thanks Windows for your bad filesystem.
> Added filesafe player name function and updated generator functions to use it.

- Utils.py
https://github.com/ArchipelagoMW/Archipelago/pull/398
and
https://github.com/ArchipelagoMW/Archipelago/pull/401
should happen first.
> Core: update version

- WebHostLib/static/styles/userContent.css
- WebHostLib/templates/userContent.html
Fixed the styling of the user-content page
> [WebHost] Fix /user-content styles

- WebHostLib/static/assets/player-settings.js
- WebHostLib/static/assets/weighted-settings.js
- Fixed a bug causing the player-settings page to fail to update with new JSON data is fetched
- Minor optimization to player-settings hash calculation
- Minor optimization for weighted-settings hash calculation
> Hash comparison fix for player-settings pages

- worlds/hk/Options.py
By allowing pickle to find the options
> HK: Fix web gen

- WebHostLib/__init__.py
- WebHostLib/templates/check.html
- WebHostLib/templates/checkResult.html
- WebHostLib/templates/islandFooter.html
- WebHostLib/templates/siteMap.html
- Add `/sitemap` to the WebHost
- Fixed styles on `/mysterycheck` pages
> Add a /sitemap to the WebHost

- Fill.py
- worlds/hk/__init__.py
fixes Ijwu/Archipelago.HollowKnight#46
> HK: don't progression balance "Currency"-like progression items

- WebHostLib/static/assets/tutorial/Archipelago/advanced_settings_en.md
Just a small sample of what you can do with item_links
> Documentation: Added example of item_links

- worlds/alttp/Shops.py
LttP: refactor price type rando code
> LttP: fix retro allowing arrows in "P" price shuffle in shops

- worlds/sm64ex/Rules.py
Rule changes after discussions on Discord
> sm64ex: Rule updates

- worlds/oot/__init__.py
@espeon65536 looks good to you?
> OoT: prevent connection from outdated clients

- BaseClasses.py
just a little more progress on more thorough typing
I stopped at the point CollectionState got into purely LTTP stuff.
> add some typing info to CollectionState

- MultiServer.py
Server options no longer expire on restart :)
> Remove outdated disclaimer

- WebHostLib/static/assets/tutorial/Factorio/setup_en.md
looks like someone forgot to capatlize this when we swiched case on everything.
> Broken Factorio setup image

- MultiServer.py
- Options.py
- Utils.py
- requirements.txt
GPL -> BSD2Clause and should be faster though I haven't tested it myself and just trusted people on the internet.
Jellyfish also allows us access to many more algorithms should they be any better. Trying out Jaro distance now instead of Levenshtein.
> Fuzzy: replace thefuzz with jellyfish

- worlds/witness/WitnessLogic.txt
Found another one, and it's one that can 100% definitely create impossible seeds so I'm hoping to sneak it in quickly before 0.3.2 RC1 :D
> Witness: Logic Fix

- .github/workflows/release.yml
Change to oldest available container to maximize compatibility
> CI: build release AppImage on ubuntu-18.04

- CommonClient.py
- FF1Client.py
- FactorioClient.py
- OoTClient.py
- SNIClient.py
- kvui.py
Also gets rid of:
```
DeprecationWarning: There is no current event loop
loop = asyncio.get_event_loop()
```
by no longer using that function (Warning starts with Py 3.10)
> Clients: centralize UI and input behaviour

- worlds/ff1/docs/multiworld_en.md
Simple docs update to remove outdated information
> Updating docs to remove reference to the AP preset

- Main.py
- WebHostLib/api/generate.py
- WebHostLib/generate.py
Was just tested with a 15 world MW on testserver.
(Squash on this one)
> Webhost serialize fixes

- worlds/timespinner/Options.py
Also makes DamageRando setting compatible with older yamls that still use booleans
> [Timespinner] Make DamageRandoOverrides a bit easier to work with

- docs/api.md
- worlds/alttp/docs/multiworld_en.md
- worlds/generic/docs/plando_en.md
- worlds/generic/docs/setup_en.md
- worlds/generic/docs/triggers_en.md
- worlds/generic/docs/using_website_en.md
- worlds/sm/docs/multiworld_en.md
- worlds/smz3/docs/multiworld_en.md
- worlds/soe/docs/multiworld_en.md
- worlds/timespinner/docs/setup_en.md
- worlds/witness/docs/setup_en.md
> Docs: fix broken links/images across various guides. add tutorials documentation to api.md

- Fill.py
Fill: speed up Counter creation by skipping intermediary list creation
> Fill: fix type-crash on unfilled having either str or Location

- worlds/timespinner/Options.py
Adds new setting defined in https://github.com/JarnoWesthof/TsRandomizer/pull/79
> [Timespinner] Add Show Item Drops in Bestiary

- worlds/minecraft/Locations.py
- worlds/minecraft/Options.py
- worlds/minecraft/Rules.py
- worlds/minecraft/__init__.py
really getting these in last minute lol
> MC: add 1.18.2 advancements

- Launcher.py
- Starcraft2Client.py
@TheCondor07 looks good to you?
> SC2: more cleanup and fix setup compile

- worlds/archipidle/__init__.py
It's an April Fool's joke. Don't include it on the site unless it's April.
> Make ArchipIDLE hidden unless the current month is April

- worlds/sc2wol/Items.py
Construct item name groups from the "Type" variable passed into ItemData
> [SC2] Item name groups and item game name fix

- worlds/sc2wol/docs/setup_en.md
Just changes to the set-up page for Starcraft 2, no code changes.
> SC2: Better set-up instructs and a section for those having issues

- Starcraft2Client.py
Turns out this was easy.... and should have likely been included from the beginning.
> SC2: Launch game in fullscreen mode.

- worlds/meritous/Items.py
- worlds/meritous/Regions.py
- worlds/meritous/__init__.py
This change designates four key Artifacts as progression items. It also sets a theme and bug report page in the WebWorld.
> Meritous: Minor logic change

- setup.py
cx_Freeze on windows implements hooks to include some DLLs, on linux we don't have them and thus libssl and libcrypto are missing from the AppImage.
After hours of searching it does not look like you can instruct cx_Freeze to simply include a system DLL that is dlopened (rather than compile-time linked), so we resolve "hard-coded" DLL names through dlconfig to files and copy them.
I also did not find documentation on how to extend cx_Freezes finder from a script, so we simply use include_files now (which was broken for whatever reason).
> Appimage: include libssl

- worlds/minecraft/Items.py
- worlds/minecraft/Locations.py
- worlds/minecraft/Rules.py
- worlds/minecraft/__init__.py
Adds minecraft 1.19 advancements.
> Minecraft 1.19

- Options.py
- WebHostLib/options.py
- WebHostLib/static/assets/player-settings.js
- WebHostLib/static/assets/weighted-settings.js
- WebHostLib/static/styles/player-settings.css
- worlds/hk/Options.py
Allows Ranges with special named values in a cutoff section.
Could use WebHost menu integration.
Might be possible to make it a cross-child of Choice and Range, but that attempt turned out very messy, so I opted for this solution.
> Options: introduce SpecialRange

- ChecksFinderClient.py
- kvui.py
> ChecksFinder Client refactored to import CommonClient components.

- worlds/soe/Options.py
Open for discussion, but from what I've seen 50 is too high if evermore is mixed with other games.
20 gave usable results, 30 may be a good middle ground.
> SoE: change default prog balancing to 30

- worlds/factorio/Technologies.py
> Factorio: more condensed raw_recipes creation

- worlds/ff1/Items.py
Classifies some items as Useful: the Tail, which is used to upgrade your classes, and all the weapons and armor that are classified as "Legendary" or "Uber" in the FF1 Randomizer
> FF1 - classify some items as useful

- .github/workflows/build.yml
- .github/workflows/release.yml
Test builds are here: https://github.com/black-sliver/Archipelago/actions/runs/2544831394
> CI: update enemizer and sni

- SNIClient.py
- Utils.py
* don't fail SNIClient when Tk is missing
* add "native" Linux messageboxes
* show error when patching fails
> UX: More errors

- worlds/timespinner/__init__.py
The German tutorial link pointed to the English version
> Fix broken link

- BaseClasses.py
- WebHost.py
- worlds/archipidle/__init__.py
- worlds/oot/__init__.py
attempt to clean up the history. should we merge this as is?
> Rename author to authors for consistency

- worlds/factorio/__init__.py
- worlds/factorio/data/mod_template/data-final-fixes.lua
Had a dream about this today, and decided to make it reality.
> Allow potentially all rocket-part ingredients to be fluids.

- BaseClasses.py
This falls under somewhat spicy optimization
> Core: skip second sanity check when pushing an item into a location (-O)

- WebHostLib/options.py
* this applies to yaml and webhost
* this allows overwriting common options from the world
> Put common options first

- worlds/ror2/Options.py
- worlds/ror2/__init__.py
Added a YAML option for 'FinalStageDeath', a toggle for 'death on the final boss stage counts as a win'. Defaults to On.
Sister PR to: https://github.com/Ijwu/Archipelago.RiskOfRain2/pull/10
> RoR2: FinalStageDeath

- worlds/ror2/Options.py
- worlds/ror2/docs/en_Risk of Rain 2.md
Having played Risk of Rain 2 with a few people new to Archipelago, there are several pitfalls and misunderstandings that seem to come up a lot, so I have attempted to clarify them.
- How multiplayer works
- Victory conditions (this is updated assuming the fixes from #766 are in effect)
- Seems pretty common for people to think that clearing all the location checks is required to win, maybe because it appears in the objective list.
- Compatibility with other mods
- The fact that you need to change "Item Weight Presets" to "No" or else your adjustments to the item frequencies won't apply
> Improve Risk of Rain 2 docs

- playerSettings.yaml
removes vendor option from hints, adds scam setting, and adds P option to shop shuffle.
> LTTP yaml update

- WebHostLib/models.py
- WebHostLib/templates/hostRoom.html
WebHost: attempt to improve wording of server resume
WebHost: reduce default room timeout to 1 hour
> WebHost: reduce server uptime

- worlds/hk/Options.py
Fixed max charm and max geo cost display names.
> HK - Fix typos in option names

- worlds/witness/Options.py
- worlds/witness/WitnessItems.txt
- worlds/witness/WitnessLogic.txt
- worlds/witness/__init__.py
- worlds/witness/items.py
- worlds/witness/settings/Disable_Unrandomized.txt
Logic fixes
Better option order & tooltips
Item groups for Lasers, Symbols & Doors
> The Witness: Small changes in response to beta tests

- OoTClient.py
- data/lua/OOT/oot_connector.lua
- worlds/oot/LogicTricks.py
Minor maintenance update. The only real change is the crash fix for deathlink, everything else is very minor.
> OOT updates

- worlds/generic/docs/advanced_settings_en.md
- worlds/sm64ex/Locations.py
- worlds/sm64ex/Options.py
- worlds/sm64ex/Regions.py
- worlds/sm64ex/Rules.py
- worlds/sm64ex/__init__.py
This adds an option to randomize both the normal courses as well as the secret courses throughout the game.
~However, there's a problem: I keep getting fill errors for what should be totally fine seeds.
If someone could take a look that'd be great~
EDIT: Now includes logic fixes as well for Big Star Doors, Options for setting MIPS Costs
> sm64ex: Various Features

- SNIClient.py
addresses https://github.com/ArchipelagoMW/Archipelago/issues/789
> SNIClient: fix program not exiting if SNI does not exist nor is running

- WebHostLib/stats.py
built on top of changes from https://github.com/ArchipelagoMW/Archipelago/pull/825
> WebHost: games played per day plot per game on stats page

- README.md
- docs/running from source.md
Resolving Issue #796 
Would be good if someone could test and document the VS setup step(s) on a clean install/vm.
If someone wants to add a section for their individual Linux distro, feel free to PR that in.
> Doc: move Running from source from wiki to docs

- WebHostLib/__init__.py
- WebHostLib/templates/macros.html
Unfortunately conflicts with https://github.com/ArchipelagoMW/Archipelago/pull/834 and as DKC3 doesn't actually use APDeltaPatch it would not get picked up by this.
> WebHost: make a deeply buried if tree for games a bit more automatic

- worlds/hk/__init__.py
> HK: Add bug report link

- setup.py
Latest cx_freeze breaks tkinter/tcl on linux
> setup.py: downgrade cx_freeze

- NetUtils.py
- docs/network protocol.md
While technically a breaking change. i dont believe its used anywhere so recommend to just secretly merge
Related discord discussion: https://discord.com/channels/731205301247803413/731214280439103580/1004450658096775188
> [Core] Colorama fix

- BaseClasses.py
- worlds/alttp/Items.py
- worlds/alttp/Rom.py
- worlds/alttp/SubClasses.py
- worlds/alttp/__init__.py
- worlds/archipidle/__init__.py
- worlds/hk/__init__.py
- worlds/meritous/Items.py
- worlds/oot/Items.py
- worlds/sa2b/Items.py
- worlds/sm/__init__.py
- worlds/smz3/__init__.py
Moved all non-common members away from BaseClasses.Item, changed how the alttp credit texts work, fixed / cleaned up / type-hinted some worlds
Feedback is welcome
> Core: cleanup Item classes

- worlds/spire/__init__.py
> StS: Add a description for the game.

- BaseClasses.py
- worlds/alttp/Shops.py
- worlds/alttp/SubClasses.py
This is just cleanup and has virtually no performance impact.
> Core: cleanup BaseClasses.Location

- CommonClient.py
A client change from https://github.com/ArchipelagoMW/Archipelago/pull/757 that would be good to release ahead of time.
> Clients: prepare for removal of players key in RoomInfo

- CommonClient.py
By popular demand, this makes /received work again.
Closes #887
> TextClient: receive all items

- Utils.py
- test/utils/TestSIPrefix.py
999.999 would give 1000.00 instead of 1.00k
Also adds a couple of tests :-)
> Utils: SI: fix rounding problems

- worlds/sm64ex/__init__.py
Typos can be bad.
Did the change here instead of the client for consistency.
> sm64ex: Fix Secound Floor Door Cost

- worlds/subnautica/Locations.py
- worlds/subnautica/__init__.py
- worlds/subnautica/docs/en_Subnautica.md
fixes https://github.com/ArchipelagoMW/Archipelago/issues/913 and https://github.com/ArchipelagoMW/Archipelago/issues/911
New client that can send the check at https://github.com/Berserker66/ArchipelagoSubnauticaModSrc/releases/tag/1.1.1
> Subnautica: fix 2 logic/locations bugs and add a bit of docs

- WebHostLib/tracker.py
Fixes https://github.com/ArchipelagoMW/Archipelago/issues/779
> Webhost: prevent tracker crashes with LttP key itemlinks

- worlds/minecraft/Rules.py
I put the noteblock requirement logic on the wrong allay advancement. this fixes that.
> MC: Fix allay advancement logic

- worlds/factorio/data/mod_template/data.lua
I have accidentally mass-produced a whole bunch of energy bridges, and supplied them to the rocket silo, not realizing what I was doing, because of them looking exactly like the accumulators I was supposed to be making instead.
> Make the energy bridge a different color.

- WebHostLib/README.md
I'm trying to explain the intent of the "style lockdown" and what it actually means.
Little changes like adding a button or a couple new select elements are perfectly fine. Tweaks to styles specific to a PR's content are also probably not a problem. For example, if you build a new page which needs two side by side tables and you need to write a CSS file specific to your page, that is perfectly reasonable. 
The PRs that I reject are primarily ones which change the overall look and feel of the website. It is valuable to maintain a consistent design throughout. Therefore there are a couple files which I guard closely, but could be convinced to make tweaks with designer approval. These closely guarded files are:
- `globalStyles.css`
- `islandFooter.css`
- `landing.css`
- `markdown.css`
- …
> Explaining the "Style Lockdown"

- WebHostLib/options.py
- test/webhost/TestFileGeneration.py
Test: verify file webhost file creations work to some degree
WebHost: fix some file creation paths
> Test: verify file webhost file creations work to some degree

- WebHostLib/customserver.py
> WebHost: fix error on save

- worlds/subnautica/__init__.py
Makes https://github.com/Berserker66/ArchipelagoSubnauticaModSrc/releases/tag/1.2.0 required.
> Subnautica: increment client version

- Options.py
Which lead to a connect failure in Raft
Not at all
> Options: fix corner case where Toggle.value and Toggle.__int__ would be bool

- Launcher.py
add ModuleUpdate to launcher
not
> Launcher: add ModuleUpdate

- Generate.py
- Main.py
- worlds/alttp/EntranceRandomizer.py
- worlds/alttp/__init__.py
remove game-specific arguments from Generate
ran LttP generation a few times, with and without Enemizer
> Core: remove game-specific arguments from Generate

- worlds/sm64ex/Locations.py
- worlds/sm64ex/__init__.py
Another typo...
Location ID was duplicated
> sm64ex: Fix a Location

- test/general/TestIDs.py
catches https://github.com/ArchipelagoMW/Archipelago/pull/979 early
I ran it once on main and got the expected failure
> Tests: verify that a world doesn't use the same ID multiple times

- worlds/minecraft/docs/en_Minecraft.md
Added list of recipes that are shuffled and which item group they are in for player reference.
> Minecraft: Added shuffled recipe list to en_Minecraft.md

- .github/ISSUE_TEMPLATE/bug_report.yaml
label name was changed so this is an update to that new label
🙃
> templates: fix bug report label

- worlds/subnautica/Creatures.py
> Subnautica: add some more missed aggressive creatures

- WebHostLib/requirements.txt
- requirements.txt
> Core: update modules

- worlds/sa2b/__init__.py
Just fixing the spelling of a character's name in a single string.
> SA2B: Fix Single Typo

- Starcraft2Client.py
https://discord.com/channels/731205301247803413/763938462092886067/1016084690526027927
On an 0.3.4 Async once.
> SC2: fix Launching Mission: text pulling the unshuffled ID.

- MultiServer.py
> MultiServer: save goal completion flag

- CommonClient.py
- FF1Client.py
- MultiServer.py
- SNIClient.py
- Starcraft2Client.py
FF1 fix PR with "cleaned" history with a commit per author for rebasing.
Continuation of https://github.com/ArchipelagoMW/Archipelago/pull/1005
> FF1 client fixes

- worlds/subnautica/Items.py
- worlds/subnautica/__init__.py
add Ultra High Capacity Tank, normalizes both Seamoth and Prawn to required plus 1 Fragments and correct Bench Fragments to Bench, Bench Fragments do not exist in vanilla.
Mod to go with it:
https://github.com/Berserker66/ArchipelagoSubnauticaModSrc/releases/tag/1.2.1
> Subnautica: fix missed item and correct other item pool counts to fit it

- Starcraft2Client.py
- worlds/sc2wol/Items.py
Fixes https://github.com/TheCondor07/Starcraft2ArchipelagoData/issues/7
Connected to a regular multiworld with full inventory to confirm everything still shows up as normal, then used !getitem Marine twice on a fresh one to confirm it no longer turns into a Medic.
@TheCondor07 looks good to you?
> SC2: fix bitflag overflow when multiple instances of an Item are acquired

- Starcraft2Client.py
When both client and game are running, closing the client would hang it until the user decides to close the game. This now closes the game freeing both applications.
twice on windows
> SC2: fix client freezing on exit while SC2 is running

- Options.py
- docs/world api.md
- test/webhost/TestFileGeneration.py
- worlds/alttp/Options.py
- worlds/factorio/Options.py
- worlds/hk/Options.py
- worlds/oot/Options.py
- worlds/sm/Options.py
- worlds/sm64ex/Options.py
- worlds/sm64ex/__init__.py
- worlds/smz3/Options.py
- worlds/soe/Options.py
- worlds/timespinner/Options.py
https://github.com/ArchipelagoMW/Archipelago/pull/1021
by running the Tests
> Core: auto alias

- worlds/sm64ex/Rules.py
> sm64ex: Fix WDW 1Up Block Logic

- worlds/alttp/ItemPool.py
> Alttp: only check item.type for own items with retro_cave

- docs/apworld specification.md
- docs/world api.md
Clarifying when a relative and absolute import should be used and why.
Read it.
> doc: update use of relative/absolute imports

- MultiServer.py
- WebHostLib/customserver.py
Change dict to defaultdict coming from webhost and add some typing. Should fix https://discord.com/channels/731205301247803413/731214280439103580/1020798966499135628
Wasn't. Hoping someone else will test.
> WebHost: CustomServer: use defaultdicts

- Generate.py
- Options.py
when option is missing from the player yaml,
Using this in #893 and tested there.
> core: fix options with "random" as default value not generating

- docs/world api.md
- test/general/TestReachability.py
Adds Ocarina of Time's unreachable regions to the region reachability test.
run unittest
> Test region access

- inno_setup.iss
> Windows: update VC Redistributable to 14.32.31332 from 14.29.30037

- Generate.py
I made a bug that I could've swore I tested properly...
non_local_items
> Core: fix unweighted options for meta files

- BaseClasses.py
- CommonClient.py
- NetUtils.py
- Options.py
- Patch.py
- Utils.py
- WebHostLib/options.py
- WebHostLib/upload.py
- docs/running from source.md
- test/general/TestReachability.py
- worlds/AutoWorld.py
- worlds/generic/Rules.py
Documentation and typing that would have helped my development of a new game.
(Everything here is something I ran into when trying to add a new game to AP.)
Unit tests, and mypy type checking with my game module.
n/a
> some typing and docs in various parts of the interface

- docs/network protocol.md
when implementing it, the meaning of the changed sentence was unclear
> Doc: network protocol: clarify want_reply

- WebHostLib/misc.py
- WebHostLib/static/assets/faq/faq_en.md
> Docs: AP discord fell to level 2, so the custom invite link no longer works.

- worlds/sm64ex/docs/setup_en.md
Adapt docs to how it works now
Well i sure hope plaintext changes dont break anything
> sm64ex: Document new connection status notifications

- worlds/__init__.py
- set sys.modules so it can be imported with worlds.*
- overwrite `__package__` so it can reference ..generic
- fix deprecation warning
> APWorld: make it behave more like a regular world

- WebHostLib/options.py
apparently tests can fail due to yamls from another branch when switching, this should clean them out correctly.
> WebHost: clear yaml template folder before populating it

- worlds/sm64ex/docs/setup_en.md
Added a few clarifications addressing issues that seemed to come up often in the Discord:
- Added bolded note that one must use a new file with each new seed
- Added troubleshooting section for when one didn't use a new file
- Worded compilation step 8 more explicitly
- Added link to compilation options list
- Added link to TextClient for using commands
The whole file could do with a do-over, fixing spelling and word capitalization. However, as there are other open pull requests for this file (#768 and possibly #1025), I kept changes to a minimum for now in favor of PR compatibility.
> Docs/sm64ex: address common questions

- worlds/sm64ex/__init__.py
> sm64ex: Update min client version

- worlds/generic/Rules.py
makes add_rule behave like set_rule if no rule was ever set
just unittests
> Core: make add_rule set if it finds an empty rule

- Fill.py
reduced memory use
just unittests
> Fill: create minimal excluded location rule only once

- README.md
> Hylics 2: add to readme

- worlds/oot/EntranceShuffle.py
- worlds/oot/__init__.py
Fixes a few longstanding issues in the ER algorithm to significantly improve generation rate. In particular, we place the most problematic entrances earlier in order to ensure they are viable, and skip taking some shortcuts that weren't actually logically safe.
Generated 50 seeds on max ER, zero failures. Hopefully that wasn't just luck, but this is a randomizer so it's hard to tell.
> OoT: ER algorithm improvements

- inno_setup.iss
> [Pokemon R/B] Fix inno_setup mistake

- WebHost.py
- WebHostLib/__init__.py
- WebHostLib/api/__init__.py
- WebHostLib/api/generate.py
- WebHostLib/api/user.py
- WebHostLib/autolauncher.py
- WebHostLib/check.py
- WebHostLib/customserver.py
- WebHostLib/downloads.py
- WebHostLib/generate.py
- WebHostLib/landing.py
- WebHostLib/misc.py
- WebHostLib/models.py
- WebHostLib/options.py
- WebHostLib/stats.py
- WebHostLib/tracker.py
- WebHostLib/upload.py
mostly using PyCharm#s optimize import on the folder, with manual removal of remaining instances of import *
visiting a few pages
> WebHost: optimize imports

- Main.py
- test/general/TestFill.py
- worlds/generic/Rules.py
memory consumption going through the roof
only a bit on 2 players without item groups, but probably about to unleash this on some async attempts.
> Locality: rewrite for linear memory consumption, from quadratic

- worlds/alttp/__init__.py
fix ganons tower trash fill deleting items that did not fit
Not yet, hoping @black-sliver is about to do it though.
> LttP: fix ganons tower trash fill deleting items that did not fit

- Fill.py
Should fix the generator spending very large amounts of time cramming an item into a priority location that will never fit.
About to be against the async gen
> Fill: Priority locks when placing and does not swap.

- BaseClasses.py
fix duplicate event pickups
About to be, basically
Credit for breaking it goes to alchav and me, as I did not spot the problem when approving it.
Credit for figuring out the problem goes to espeon.
> Fill: fix duplicate event pickups

- worlds/factorio/docs/setup_en.md
> [Factorio] Minor fix for typo on setup doc

- worlds/alttp/EntranceShuffle.py
- worlds/alttp/__init__.py
Inverted Big Bomb Shop indirect connection rule
running generate with LttP
> LttP: fix Inverted Big Bomb Shop indirect connection rule

- test/worlds/test_base.py
- test/worlds/zillion/TestGoal.py
- test/worlds/zillion/__init__.py
previous fix was incorrect
around 15000 runs of Zillion unit tests
> Zillion: fix unit tests

- worlds/subnautica/__init__.py
potential conflict with plando placing items into Subnautica sphere 1
not, I have trust
> Subnautica: don't override plando during pre_fill

- Main.py
> Logging: we now need 9 digits for IDs

- worlds/overcooked2/Logic.py
- Some seeds are more difficult than intended because of some blunt  3-star logic, this PR fixes it.
`TestOvercooked2.py`
> Overcooked! 2: Slightly relax 3-star logic

- docs/style.md
There was some confusion regarding annotation of local variables. This tries to clarify it a bit.
i read it
> Doc: Clarify annotations in style guide

- worlds/dark_souls_3/data/items_data.py
- worlds/dark_souls_3/data/locations_data.py
Dark Souls III
an items ID and location ID
by br00ty after finding the correct ID
> DS3: fix shield item/location

- worlds/rogue_legacy/Regions.py
- worlds/rogue_legacy/Rules.py
See title. Done after #931 was merged to maintain naming consistency.
Generated. Still worked.
N/A
> Rogue Legacy: Rename `world` to `multiworld` in local variables and function signatures.

- worlds/alttp/ItemPool.py
Triforce pieces were creating duplicate items instead of individual instances
generating
> LTTP: fix triforce piece duping

- FactorioClient.py
On Windows, the Factorio server is currently hard-quit (the process is killed) when FactorioClient is closed. If the user hadn't manually saved the game and not all players had left the server (which triggers a save), progress since the last save may be lost.
Worse, there have been reports of players even losing/corrupting their existing savegame. I have not been able to reproduce this (although it happened to me once), but I can imagine this sequence of events taking place:
- The player closes their Factorio client, disconnecting from the Factorio server.
- The Factorio server triggers a save due to the last player leaving the server.
- The player closes their FactorioClient, killing the Factorio server process during saving, corrupting the save.
[It should be noted that a user savvy …
> FactorioClient: Fix saving on exit on Windows

- docs/contributing.md
> Docs: fix broken link in contributing.md

- FactorioClient.py
- worlds/factorio/Technologies.py
> Factorio: make client use CommonClient location lookup for technologies

- BaseClasses.py
> Core: more useful error for entrance without region

- worlds/bk_sudoku/__init__.py
Fixed setup link
By trying the url on the :24242 port
> Sudoku: Fixed setup link

- WebHostLib/customserver.py
- WebHostLib/models.py
- WebHostLib/templates/hostRoom.html
prevent infinite spinup loop of Rooms
By making set_save fail
From:
To only a single message.
Also:
> WebHost: prevent infinite spinup loop of Rooms

- PokemonClient.py
- worlds/pokemon_rb/__init__.py
- worlds/pokemon_rb/locations.py
- worlds/pokemon_rb/options.py
- worlds/pokemon_rb/rom.py
Generated patches are now against the base rom instead of base-patched rom, and applied to base rom instead of base-patched rom. This will allow patching compatibility between versions.
Location ID range starts at same ID as the Item ID range now.
Changed some option defaults to be more sync-friendly
Generating a patch, applying it, connecting to a server and collecting locations
> [Pokémon Red and Blue] more improvements

- WebHostLib/templates/options.yaml
- worlds/hk/Options.py
- worlds/minecraft/Options.py
- worlds/oot/ColorSFXOptions.py
- worlds/oot/Options.py
- worlds/overcooked2/Options.py
- worlds/raft/Options.py
- worlds/sa2b/Options.py
- worlds/sc2wol/Options.py
- worlds/sm/Options.py
- worlds/sm64ex/Options.py
- worlds/smw/Options.py
- worlds/timespinner/Options.py
See title.
~~Removed old and new examples.~~
Edited output:
```yaml
progression_balancing:
#
random: 0
random-low: 0
random-high: 0
disabled: 0 # equivalent to 0
normal: 50 # equivalent to 50
extreme: 0 # equivalent to 99
accessibility:
locations: 0
items: 50
minimal: 0
```
N/A
> Templates: Remove auto wordwrap, fix manual indentation, and reformat docstrings for world options in main.

- worlds/factorio/__init__.py
add rocket-silo as required technology
not
> Factorio: add rocket-silo as required technology

- worlds/witness/__init__.py
Add required_client_version to WitnessWorld (0, 3, 6).
_Hahahaha I can't believe I got away without doing this for so long_
(The clients already support this)
> The Witness Add required_client_version to WitnessWorld

- WebHostLib/__init__.py
- WebHostLib/generate.py
- worlds/factorio/__init__.py
Webhost generation time limit
with 1 second to trigger it, and with a long time to see it not trigger
> Webhost time limit

- worlds/overcooked2/__init__.py
> OC2 - Fix typo in game description

- worlds/ff1/docs/multiworld_en.md
Fixing location as it is no longer in the beta tab
No testing required
> Docs: Updating FFR Docs for new Archipelago setting location on finalfantasyrandomizer.com

- worlds/witness/WitnessLogicExpert.txt
Adding many missed symbol requirements to WitnessLogicExpert.txt to prevent broken seeds
> The Witness - Fixes for broken expert seeds (Credit: IHNN)

- worlds/spire/Options.py
See title.
Just a tool-tip change to match in-game behavior. No testing needed.
N/A
> Slay the Spire: Correct tool tip for `heart_run` to match actual behavior.

- WebHostLib/static/styles/themes/dirt.css
- WebHostLib/static/styles/themes/grass-flowers.css
- WebHostLib/static/styles/themes/grass.css
- WebHostLib/static/styles/themes/ice.css
- WebHostLib/static/styles/themes/jungle.css
- WebHostLib/static/styles/themes/ocean.css
- WebHostLib/static/styles/themes/party-time.css
- WebHostLib/static/styles/themes/stone.css
Locally, in Firefox and Chrome.
> Web/Style: Fix code block padding

- setup.py
update cx-Freeze
On Py 3.10 on Win10
> Core: update cx-Freeze

- worlds/alttp/Rom.py
- worlds/alttp/__init__.py
make xxtea only required for race generation
> LttP: make xxtea only required for race generation

- Utils.py
datetime-tag log files and delete old ones
with generate on its own and a webhost generate -> host cycle
> Core: datetime-tag log files and delete old ones

- BaseClasses.py
- worlds/alttp/Dungeons.py
streamline Multiworld.get_*_locations calls
a bit wtih unittests and LttP gen
> Core: streamline Multiworld.get_*_locations calls

- WebHostLib/generate.py
- WebHostLib/stats.py
- worlds/AutoWorld.py
- worlds/__init__.py
adds some typing. I was trying to add some data package stats, that project fell flat but I might as well add the typing info I added when I was working on it.
Not
> Docs datapackage typing

- playerSettings.yaml
- worlds/alttp/Options.py
The yaml parsing that changed yes and no yaml parsing broke the alias's and default template for this
generated yes and no a few times
> lttp: fix open pyramid settings parsing

- Utils.py
logs additional system info that may be relevant to errors
by running stuff and getting results like `Archipelago (0.3.6) logging initialized on Windows-10-10.0.19044-SP0 running Python 3.10.8`
> Core: log additional system info that may be relevant to errors

- Fill.py
- Main.py
- worlds/alttp/__init__.py
- worlds/subnautica/Options.py
- worlds/subnautica/__init__.py
https://discord.com/channels/731205301247803413/1046469997750386698
by running it against the failing yaml set
> Core: Fill fix local logic conflict

- worlds/witness/docs/setup_en.md
Updating urls to github repo, after repo was transferred
Not at all
> [Witness, Docs] Updated link to repository owner

- worlds/overcooked2/__init__.py
- worlds/overcooked2/docs/en_Overcooked! 2.md
- Increase amount of time required to complete final level
- Add table to documentation to guide new players on what difficulty setting they should use
- Checked JSON output
- Checked WebHost.py
> [OC2] Difficulty Adjustment/Documentation

- worlds/witness/rules.py
Faulty entrance logic fixed, where PP3 exit door is required no matter what for PP2, but was not always checked.
> The Witness: Fix Expert PP2 Access Logic

- worlds/subnautica/__init__.py
tell users to update
the client update itself was tested in the Zelda 1 betatest game alongside. The increment of 5 to 6 was not.
> Subnautica: prompt users to update

- WebHostLib/requirements.txt
update webhost modules
accessing /stats
> WebHost: update modules

- worlds/factorio/__init__.py
fix revealed tech tree hinting old location names
only genning to spoiler so far, not ingame
> Factorio: fix revealed tech tree hinting old location names

- worlds/timespinner/Locations.py
- worlds/timespinner/Options.py
- worlds/timespinner/Regions.py
Say your prayers, little one, don't forget, my son
To include everyone
I tuck you in, warm within, keep you free from sin
Til the Sandman, he comes
Sleep with one eye open
Gripping your pillow tight
Exit light
Enter night
Take my hand
We're off to never-never land
Something's wrong, shut the light, heavy thoughts tonight
And they aren't of Snow White
Dreams of war, dreams of liars, dreams of dragons' fire
And of things that will bite, yeah
leep with one eye open
Gripping your pillow tight
Exit light
Enter night
Take my hand
We're off to never-never land
Yeah-hah
Now, I lay me down to sleep (Now, I lay me down to sleep)
Pray the Lord my soul to keep (Pray the Lord my soul to keep)
If I die before I wake (If I die before I wake)
Pray the Lord my soul to take (Pray the Lord my soul to take) …
> Timespinner: Enter Sandman flag

- MultiServer.py
attempt to make nothing found message clearer
No, actually
> Server: attempt to make nothing found message clearer

- worlds/ror2/docs/setup_en.md
Change the mod link for Risk of Rain 2
Updating the mod required a new team on thunderstore
> RoR2: Change risk of rain mod download page link

- meta.yaml
meta.yaml still uses on/off progression balancing
nothing really, it's not super testable
> Update meta.yaml to numeric progression balancing

- WebHostLib/api/generate.py
- test/webhost/TestAPIGenerate.py
!aginahbot generate
~~Not yet~~ Unittest included
> WebHost: restore old silent ignore of mimetypes in json getting

- WebHostLib/generate.py
- worlds/AutoWorld.py
Makes misplacement like in https://github.com/ArchipelagoMW/Archipelago/pull/1222/files less likely as it should raise a warning that one is writing to a ClassVar via instance.
not
> Docs: add ClassVar marker to World class

- Utils.py
- test/general/TestHostYAML.py
- test/webhost/TestDocs.py
- test/webhost/TestFileGeneration.py
verify and fix host.yaml/Utils.py match
It is a test.
> Tests: verify and fix host.yaml/Utils.py match

- docs/apworld specification.md
fixed broken link
In github ui
> Docs: Fixed link on apworld docs

- setup.py
- worlds/rogue_legacy/Rules.py
- worlds/rogue_legacy/__init__.py
Title.
Built, Installed, Ran test generation.
N/A
> Rogue Legacy: Remove relative imports and move to .apworld.

- Main.py
- MultiServer.py
- docs/network protocol.md
embeds custom datapackage into .archipelago
Set SC2 to data_version 0, generated, deleted its folder, then ran server with .archipelago generated earlier.
> Core: embed custom datapackage into .archipelago

- worlds/subnautica/Options.py
give Early Seaglide a display name
no
> Subnautica: give Early Seaglide a display name

- docs/world api.md
remove another remote_items leftover
no
> Docs: remove another remote_items leftover

- BaseClasses.py
- Main.py
- Utils.py
- WebHostLib/generate.py
- host.yaml
moves create_playthrough under Spoiler as method
moves paths to level 3 spoiler
running generate on the various levels
> Core: move create_playthrough under Spoiler as method & split it

- WebHostLib/templates/sc2wolTracker.html
Bug fix for a few items on the SC2WoL web tracker
Untested, very simple fix.
> WebHost: Bugfix for SC2WoL tracker

- worlds/smw/Regions.py
Some Dragon Coin logic was pointed out as erroneous. This has been resolved.
Many Generations
> SMW: Adjust Butter Bridge 2 - Dragon Coins logic

- WebHostLib/tracker.py
LttP specific slot tracker
not, but the bug was found in the :24242 logs
> WebHost: fix LttP tracker crash

- worlds/oot/EntranceShuffle.py
no one plays closed forest which is why this got missed
> oot: repair closed forest + dungeon ER

- Utils.py
> Generate: fix default utils options

- WebHost.py
- test/webhost/TestAPIGenerate.py
prevents Generations being queued up to real DB in testing mode.
> Tests: make sure DB overwrite actually takes

- NetUtils.py
https://discord.com/channels/731205301247803413/1056946329114398781
hopefully soon by @Jarno458
> Network: allow sending frozenset

- worlds/subnautica/__init__.py
fix early seaglide option, so it can actually be turned off
no
> Subnautica: fix early seaglide

- CommonClient.py
client commits from https://github.com/ArchipelagoMW/Archipelago/pull/1340, should be safe to merge ahead of time.
> Clients auto ssl

- worlds/sa2b/__init__.py
- worlds/sa2b/docs/setup_en.md
This PR adds a Linux section to the SA2B setup guide.
I myself used these steps on both my Steam Deck and my Linux desktop, and I have also helped several others on the Discord with setup using the same steps. The change was verified on the site by running it locally.
> SA2B: Add Linux section to setup guide

- worlds/zillion/requirements.txt
minor terrain logic update: standing on a moving walkway requires 2 columns of standing space
https://github.com/beauxq/zilliandomizer/commit/23d938daa5aaeaa3ec2255c50f2729b33a9e7f87
a new unit test in zilliandomizer package
ran zilliandomizer unit tests
AP ModuleUpdate.py
ran AP unit tests
> Zillion: minor terrain logic update

- worlds/alttp/Client.py
attempt at preventing ghost location checks in LttP
https://discord.com/channels/731205301247803413/1054434028645797928
> LttP: attempt at preventing ghost location checks

- test/general/TestLocations.py
Tests
I ran it against the commit where I was doing this :X
> Tests: write a test to check for dupe locations

- worlds/subnautica/Options.py
correct doc string placement for early seaglide
no
> Subnautica: correct doc string placement for early seaglide

- test/TestBase.py
- worlds/alttp/Items.py
- worlds/alttp/Rules.py
- worlds/alttp/test/options/TestOpenPyramid.py
I wrote a method to check whether pyramid should be open or not but forgot to use it on the entrance rule
checked spoiler
> LTTP: fix open pyramid for real this time

- CommonClient.py
- MultiServer.py
- NetUtils.py
- WebHostLib/static/assets/faq/faq_en.md
- WebHostLib/templates/generate.html
- docs/adding games.md
- docs/network protocol.md
- worlds/generic/docs/commands_en.md
- worlds/generic/docs/setup_en.md
- worlds/generic/docs/using_website_en.md
- worlds/meritous/docs/setup_en.md
- worlds/witness/Options.py
release_mode inconsistencies, which can lead to a crash
hopefully soon
> Server: fix release_mode

- BaseClasses.py
- worlds/alttp/Rom.py
Hint tiles in game telling you that your item is with an item link, instead of telling you where that item actually is.
Rolling ALttP games with item links on and checking the results.  
debugging screenshot as I didn't feel like going to actual hint tiles to check.
> ALttP: Fix hint tile hints being potentially useless with item links.

- setup.py
gives the module updater install prompt to users running setup first thing
not
> Setup: add moduleupdater prompt to setup.py

- worlds/overcooked2/Options.py
- default difficulty is too hard for the average player coming in, I made it easier by default
- doesn't need to be
> [OC2] Decrease default difficulty

- MultiServer.py
- docs/network protocol.md
adds 3 new opperations to datastorage that allows adding and removing of elemdns from list and dicts.
localy with a beta version of Slay the Spire that uses them.
> MultiServer: Data Storage Additions

- setup.py
updates cx_Freeze to 6.14.1
not yet, but will probably after work - where we are also testing this
> Setup: new cx-Freeze just dropped

- CommonClient.py
- setup.py
Should allow textclient to disconnect from a slot and then connect to a different slot or multiworld even when the game of that slot changes.
about to post this to be tested
> Textclient game reset

- WebHostLib/static/assets/faq/faq_en.md
Berserker has frequently corrected, that each player's game is a single world, inside a larger seed; not that each player's game is a seed.
> Docs: FAQ: change "seeds" to "a world" where world is the right term.

- worlds/AutoWorld.py
- worlds/witness/__init__.py
- worlds/witness/hints.py
- worlds/zillion/__init__.py
> Core: Rename the missed slot_seeds.

- Main.py
- MultiServer.py
- Utils.py
prepare server for removal of names in multidata
ran a generation and hosted it
> Core: prepare server for removal of names in multidata

- test/general/TestImplemented.py
- test/general/TestItems.py
- test/general/TestLocations.py
- test/general/TestReachability.py
- test/general/__init__.py
- worlds/ff1/__init__.py
> Tests: add a test that created items and locations exist in the datapackage

- worlds/factorio/docs/en_Factorio.md
To the best of my knowledge, the EnergyLink feature was not documented anywhere, with the exception of the short blurb on the option.
> Docs/Factorio: Document EnergyLink

- worlds/subnautica/__init__.py
move code to be a better example
unittests and one test gen
> Subnautica: move code to be a better example

- docs/style.md
A note to style guide that worlds should be consistent
By reading it :-)
> Style Guide: add world consistency

- docs/world api.md
documentation for world documentation i.e. setup and game_info, and world level tests since neither of these were documented.
> Docs: document world docs and tests

- worlds/smw/Aesthetics.py
- worlds/smw/Rom.py
smw currently fails to generate due to using multiworld random instead of slot random
it wasn't
> SMW: change random in generate_output to use slot random

- worlds/AutoWorld.py
> Docs: add docstrings to the World class

- README.md
> Docs: More games more fun

- README.md
the order of games listed in the readme
by checking the commit history
> Readme: fix order

- Main.py
count the world types
running the code
> Core: count the world types

- Launcher.py
https://discord.com/channels/731205301247803413/1080285334585212938
By verifying that *.apl2ac files were displayed in the "Open Patch" file selection dialogue and confirming that the game was successfully patched and launched with SNIClient when selecting that file.
> launcher: add .apl2ac support

- test/TestBase.py
I thought this was in the new reachability tests already oops.
> Tests: test that the game is beatable for WorldTestBases

- CommonClient.py
- Generate.py
- Main.py
- WebHostLib/static/assets/tracker.js
- WebHostLib/templates/macros.html
- worlds/factorio/Technologies.py
This is a small collection of minor mistakes in the codebase I ran across during my exploits, which didn't fit in any of my other PRs.
I've been sitting on these for months and since I've become mostly inactive it seemed like it was time to commit them.
> Misc collected fixes

- worlds/stardew_valley/logic.py
- worlds/stardew_valley/test/TestOptions.py
- worlds/stardew_valley/test/__init__.py
Fix generation issue with Master Angler goal and vanilla tools
Unit tested in the dev branch, I just cherry-picked here since the dev branch is not up-to-date with the last PR
> Stardew Valley: Fix generation issue with Master Angler goal and vanilla tools

- worlds/subnautica/Locations.py
- worlds/subnautica/Rules.py
If you look at the old code, you will find it tries to calculate the distance on the axis X, Y and Y again.
asserts and prints that are stripped from this PR
> Subnautica: fix exported radiation logic

- worlds/alttp/Options.py
ran webhost and checked the changes
also pulled in and tested with #823
> LTTP: add option `__doc__`s

- worlds/witness/WitnessLogicExpert.txt
Tfw your previous "fix" actually made it even worse
> The Witness - Expert logic bug (could lead to broken seeds)

- setup.py
> Setup: update cx-Freeze

- worlds/pokemon_rb/rules.py
> Pokemon: apply rename of location_item_name

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/unittests.yml
* get rid of a bunch of warnings by updating actions/setup-python and actions/checkout
* skip downloading SNI. This is part of setup.py now
* don't run unit tests for files that do not concern the unit tests
* run the build action when setup.py changes to see if the build still suceceds
https://github.com/black-sliver/Archipelago/actions
> CI: update stuff

- worlds/spire/__init__.py
Fix STS using `multiworld.slot_seeds` which has been renamed
Generating and observing no error
> STS: update slot_seeds to per_slot_randoms

- worlds/factorio/Mod.py
- worlds/factorio/Options.py
- worlds/factorio/__init__.py
- worlds/factorio/data/mod/LICENSE.md
- worlds/factorio/data/mod/lib.lua
- worlds/factorio/data/mod_template/control.lua
- worlds/factorio/data/mod_template/data.lua
Energy Link:
* Transfer and Storage increased by 10X
* Cost of building increased by roughly 10X
* This is a way to address their effect on performance, as users now need a tenth of them to get the same throughput, it also differentiates them from Accumulators 
5 new Traps:
* Teleport Trap
* Grenade Trap
* Cluster Grenade Trap
* Artillery Trap
* Atomic Rocket Trap
Max Evolution Trap count was changed from 25 -> 10. 
When max science is lower than min science, the two are now swapped. 
New option: Ingredients Offset
* When creating random recipes, use this many more or less ingredients in the new recipe.
> Factorio: content update

- Launcher.py
- inno_setup.iss
- setup.py
- worlds/LauncherComponents.py
- worlds/__init__.py
- worlds/factorio/__init__.py
makes the launcher more dynamic, so stuff like apworld can hook into it
* showcases a bit on Factorio
adds Launcher to windows installation
makes world folders optional, logging any exceptions and moving on.
A bit on windows
We should have a way to register Clients and to make Clients launchable as either executable or function. But time is running low for next release to make and test all that.
> Launcher: dynamic Launcher

- README.md
- inno_setup.iss
> Kingdom Hearts 2: Fixed inno_setup and fixed readme.md

- worlds/tloz/docs/multiworld_en.md
Added 'Optional Software' to instructions for setting up Z1
Added links to download poptracker pack
myself
> TLoZ: Update instructions

- README.md
It was missed somewhere, I guess.
> Add LADX to Readme.md

- WebHostLib/templates/multiTracker.html
- WebHostLib/tracker.py
add Status to MultiTracker
currently the only way to see if a slot is actually completed is to have at least one LttP world and see if those worlds have a triforce.
locally
> WebHost: add Status to MultiTracker

- worlds/pokemon_rb/__init__.py
- worlds/pokemon_rb/rom.py
Fixes typo causing crashes.
Skips sweeping for events when placing non-advancement items. This can waste a lot of time, especially with HK games present.
Clicking generate, not seeing any explosions
> Pokemon R/B: A fix and an improvement

- test/TestBase.py
- worlds/messenger/Options.py
- worlds/messenger/Rules.py
- worlds/messenger/SubClasses.py
- worlds/messenger/__init__.py
- worlds/messenger/test/TestAccess.py
- worlds/messenger/test/TestLogic.py
- worlds/messenger/test/TestNotes.py
- worlds/messenger/test/TestShopChest.py
A hard and challenging logic mode which require speedrunning tricks. Also adds even more limited logic to No Logic following known OOB strats.
Had someone with knowledge of all the tricks read over it, and unit tests.
> The Messenger: Add more difficult logic options

- worlds/ladx/Options.py
- worlds/ladx/__init__.py
Fixes the missing main description for LADX. 
Adds missing help text for various yaml options.
No code changed, just ran build_exe and generate.py
> LADX: Fixup missing descriptions

- worlds/sa2b/Options.py
An option display name was incorrect. No more.
I read it.
> Fix SA2B Option Display Name

- worlds/messenger/Rules.py
- worlds/messenger/docs/en_The Messenger.md
- worlds/messenger/test/TestLogic.py
Was updating the tracker and noticed a missing location rule. Also added a known issue I forgot to write down.
> The Messenger: Fix a missing location rule and missing known issue

- worlds/AutoWorld.py
> Core: add an everywhere location group

- worlds/tloz/docs/multiworld_en.md
> TLOZ: Fix Broken Links to Player Settings Page

- worlds/kh2/Items.py
the medal item had the wrong memory address
I gave myself the medal
> fixes medal being shadow archive memory address

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/unittests.yml
- ModuleUpdate.py
- setup.py
* Tries to fix missing pkg_resources in both setup.py and ModuleUpdate.py
* Checks for pip availability before running pip and prints (a hopefully useful) error
* Remove (now, hopefully) unused steps from CI
* Some minor cleanup for flake8 and mypy
CI
> ModuleUpdate/Setup: install pkg_resources, check pip, typing and cleanup

- test/general/TestLocations.py
explicitly make sure there is no double use of location Name or ID
yes
@KonoTyran might be in a good position to also test this.
> Test: explicitly make sure there is no double use of location Name or ID

- worlds/kh2/OpenKH.py
- worlds/kh2/Options.py
Options:
Fixed the option to actually have valid keys
Openkh:
changed the | operator to .union
I tried invalid and valid keys in the yamls and it worked the way it was intended
> Fixed Blacklist and python 3.8 support

- worlds/archipidle/Items.py
- worlds/archipidle/Rules.py
- worlds/archipidle/__init__.py
This is just increasing the number of items in the ArchipIDLE pool to 200.
Locally, and in secret.
> Update ArchipIDLE item count to 200, and add a few more items

- worlds/stardew_valley/__init__.py
- worlds/stardew_valley/docs/setup_en.md
Improvements to documentation files. The main game description is re-written, and the install instructions page had a broken link that is now fixed
It's only documentation
> Stardew Valley: Improve Documentation for 0.3.9

- WebHostLib/options.py
Title. Weighted settings random doesn't appear after this yet
Looking at the webhost
> Webhost: add Toggle options back to player settings and remove random

- worlds/messenger/docs/setup_en.md
The mod is still backwards compatible but it is no longer possible to have both installed at the same time and have it function correctly.
read it.
> The Messenger/Docs: Have users explicitly remove old version

- MultiServer.py
> Multiserver: location name groups fix

- worlds/kh2/Options.py
- worlds/kh2/docs/en_Kingdom Hearts 2.md
reworded and updated options descriptions
I ran it on a local webhost and it looks a lot better
> KH2: updated the docs for options and faq

- MultiServer.py
- WebHostLib/customserver.py
MultiServer: compat fix if checksum is not present
nope
> MultiServer: compat fix if checksum is not present

- worlds/smw/Options.py
Copy/paste error.
I read it this time.
> Fix SMW Option Tooltip

- worlds/overcooked2/Options.py
- worlds/overcooked2/docs/setup_en.md
> [OC2] Spelling Mistakes 🐝

- worlds/messenger/Constants.py
- worlds/messenger/Regions.py
- worlds/messenger/Rules.py
- worlds/messenger/__init__.py
- worlds/messenger/docs/en_The Messenger.md
- worlds/messenger/docs/setup_en.md
- worlds/messenger/test/TestAccess.py
- worlds/messenger/test/TestLogic.py
A logic bug and some small PEP8 consistency cleanup. Also more clear and explicit documentation.
Read it and had to modify my unit tests.
> The Messenger: some miscellaneous cleanup. Also found a logic bug. oops.

- worlds/subnautica/Items.py
- worlds/subnautica/Options.py
- worlds/subnautica/__init__.py
* bundles together items that are mostly decorative
* removes item pool option, as this is a cleaner way to address the same problem
> Subnautica: group items and removal of item pool option

- Fill.py
Fixes a `ZeroDivisionError` that is generated while calculating percentages for logging purposes during progression balancing phase when all locations in a given world are locked (e.g. all locations are set as priority).
Error before fix:
```
Creating World.
Creating Items.
Calculating Access Rules.
Running Item Plando
Running Pre Main Fill.
Filling the world with 461 items.
Balancing multiworld progression for 3 Players.
Uncaught exception
File "C:\Users\Phar\PycharmProjects\archipelago\Generate.py", line 643, in <module>
main()
File "C:\Users\Phar\PycharmProjects\archipelago\Generate.py", line 226, in main
callback(erargs, seed)
File "C:\Users\Phar\PycharmProjects\archipelago\Main.py", line 251, in main
balance_multiworld_progression(world)
File …
```
> Core: Fix ZeroDivisionError if a world is contained 100% locked locations.

- worlds/archipidle/__init__.py
- worlds/archipidle/docs/en_ArchipIDLE.md
Update ArchipIDLE's documentation and create items in `create_items` func.
Generated a game locally and sent a few items.
> [ArchipIDLE] Update documentation and item pool generation

- Utils.py
- WebHostLib/templates/macros.html
- WebHostLib/upload.py
Fixes upload of bare `.archipelago` file.
Fixes lack of datapackage stripping from said file.
Fixes broken download button for said upload's patches
Uploaded both a .zip and a .archipelago file to a local webhost.
> Fix upload of .archipelago file

- docs/apworld specification.md
https://discord.com/channels/731205301247803413/731214280439103580/1094655639600508999
> Doc: apworlds have to be all lower case

- worlds/alttp/Client.py
Title
I walked around for a bit and grabbed locations while connected and disconnected and made sure they all showed correctly
> LTTP: use server for counting locations instead of having 249/216

- worlds/sc2wol/Locations.py
- worlds/sc2wol/__init__.py
Removes extraneous space from location "Piercing the Shroud: Brutalisk "
Generated once.
> SC2: Removed extra space from location

- worlds/stardew_valley/logic.py
- worlds/stardew_valley/requirements.txt
- worlds/stardew_valley/test/TestLogic.py
- worlds/stardew_valley/test/TestOptions.py
Removed Pytest as a requirement for all stardew valley code
Ran all the tests in the project after uninstalling pytest locally
> Stardew Valley: Removed Pytest Requirement from everything

- worlds/kh2/Locations.py
Fixes the non-deterministic behavior from using a set instead of a list for random location 
I genned the same seed 3 times and it was identical
> KH2: Fixed Non Deterministic Generation

- worlds/ladx/Tracker.py
Adds support for https://github.com/kbranch/Magpie/wiki/sendFull-command
Connected the tracker, pressed the "send all items/checks" button
> LADX: Support magpie tracker's sendfull button

- worlds/ladx/Items.py
See title. Not sure why I marked it like this.
> LADX: Fix useless item being marked as progression

- worlds/kh2/__init__.py
Fixing the keyblade index out of list error
I genned 2 seeds on the webhost and 3 locally and all worked as intended
> KH2: Init Cleanup and Keyblade Fix

- worlds/kh2/__init__.py
> KH2: Fix validAbilitys

- worlds/kh2/__init__.py
If the player has more mcguffins required than in the pool
I roll with said fix
> KH2: fixed lucky emblem required>lucky emblem amount

- worlds/dlcquest/Options.py
- worlds/dlcquest/docs/en_DLCQuest.md
- worlds/dlcquest/docs/setup_en.md
> Fix documentation error

- worlds/stardew_valley/data/bundle_data.py
- worlds/stardew_valley/docs/setup_en.md
- worlds/stardew_valley/rules.py
- worlds/stardew_valley/test/TestBundles.py
- worlds/stardew_valley/test/TestData.py
- worlds/stardew_valley/test/TestGeneration.py
- Typo in the documentation
- Logic error for help wanted quests
Generated several worlds with the same yamls that caused errors, they no longer do.
Ran all the tests
> Stardew Valley: Fix a logic bug and a documentation typo

- BaseClasses.py
document has_all and has_any
please do proofread
> Docs: has_all and has_any

- worlds/alttp/requirements.txt
update xxtea to 3.0.0
generated with race:1 and opened a chest
> LttP: update xxtea to 3.0.0

- worlds/stardew_valley/options.py
Settings page had errors and bad formatting in the descriptions
Ran the webhost locally to look at the changes
> Stardew Valley: Fix Mistake and Formatting in settings page

- worlds/clique/docs/en_Clique.md
- worlds/clique/docs/guide_en.md
Less obnoxious docs for Clique.
I read the English and it read good.
> Clique: Better, less-obtuse, docs for Clique.

- worlds/ladx/Items.py
- worlds/ladx/__init__.py
> LADX: no pre fill

- worlds/sc2wol/Items.py
- worlds/sc2wol/LogicMixin.py
Fixes some issues with typos and oversights logic generation in SC2
Rebalancing
Adds Vultures to Advanced  tactics as train killers
Drops Firebats from basic unit pool and moves Goliaths from advanced tactics to standard
I've generated a game
> Sc2wol logic update

- worlds/kh2/OpenKH.py
- worlds/kh2/__init__.py
- worlds/kh2/test/TestSlotData.py
__init__:
- Added exception for if the player has too many excluded abilities on keyblades.
- Fixed Action Abilities only on keyblades from breaking.
- Added proper support for ability quantity's instead of 1 of the ability 
- Moved filling the localitems slot data to init instead of generate_output so I could easily unit test it
TestSlotData:
- Checks if the "localItems" part of slot data is filled. This is used for keeping track of local items and making sure nothing dupes
I genned and played over 4 seeds and ran unit tests
> KH2: New Unit Test and better keyblade fill

- BaseClasses.py
- worlds/factorio/Mod.py
- worlds/factorio/Shapes.py
- worlds/factorio/__init__.py
improves cleanliness
running Generate
> Factorio: remove tech_tree_layout_prerequisites from core

- worlds/sc2wol/docs/setup_en.md
Docs: Supplementing StarCraft 2 setup guide with instructions to run on macOS.
Supplementing StarCraft 2 setup guide with instructions to run on macOS.
I ran through the setup process for running clients on macOS I wrote several months ago, and confirmed that the key features (downloading maps, loading maps, sending/receiving items) all worked on macOS as is.
> StarCraft 2 macOS documentation

- Utils.py
- worlds/alttp/Bosses.py
- worlds/alttp/Client.py
- worlds/alttp/Dungeons.py
- worlds/alttp/EntranceShuffle.py
- worlds/alttp/InvertedRegions.py
- worlds/alttp/ItemPool.py
- worlds/alttp/Items.py
- worlds/alttp/OverworldGlitchRules.py
- worlds/alttp/Rom.py
- worlds/alttp/Shops.py
- worlds/alttp/StateHelpers.py
- worlds/alttp/SubClasses.py
- worlds/alttp/UnderworldGlitchRules.py
- worlds/alttp/__init__.py
fix that collect can bypass requirements for ganon ped goal
* may contain traces of pep8
https://discord.com/channels/731205301247803413/827141303330406408/1100566103098409020
> LttP: fix that collect can bypass requirements for ganon ped goal

- worlds/LauncherComponents.py
Reformatting comment to comply with PEP format
> Correcting minor formatting error

- worlds/ladx/__init__.py
1. Implements `get_pre_fill_items` for LADX
2. Fixes issues with filling with more exotic mixed dungeon item fill types
Generated a couple of times
> LADX: Rework dungeon item fill 

- WebHostLib/misc.py
- WebHostLib/templates/hostRoom.html
adds a log download link
clicking on it when the file exists and when it not exists.
> WebHost: offer room owner log download link

- worlds/noita/docs/en_Noita.md
- worlds/noita/docs/setup_en.md
Fixing some information in the docs to make them more accurate. And also including a link to the poptracker pack.
Docs changes
> Noita - Docs updates

- worlds/AutoWorld.py
probably nothing, was just looking for some low-hanging-fruit todo items
ran generate once.
> Core: call stages in sorted order

- KH2Client.py
Fixed the item syncing when receiving an item while not connected to the server.
Also ran pycharms linter
I did /send to my slot while not disconnected and received the item when I connected to my slot
> KH2:Item Syncing Fix

- worlds/noita/docs/en_Noita.md
Added specifics about the number of checks in the pool.
Math
> Docs: Add location count specifics to Noita

- LttPAdjuster.py
- Main.py
- OoTAdjuster.py
- worlds/adventure/__init__.py
- worlds/alttp/Rom.py
- worlds/dkc3/Rom.py
- worlds/sm/__init__.py
- worlds/smw/Rom.py
Define `__all__` in Main.py to make clear what it is and fix imports.
> Main: add __all__ and change wrong imports

- worlds/alttp/Shops.py
Makes shop shuffle deterministic when two LttP players have it on.
Just once, got the same spoiler log.
> LttP: deterministic shop_shuffle

- .github/workflows/analyze-modified-files.yml
https://discord.com/channels/731205301247803413/731214280439103580/1109523465314242742
By pushing a new branch to a repository where this change was already applied
> CI: treat all files as modified on new branches

- worlds/sm/Options.py
I changed the link in the description of Objectives. I tested it by copying the new link and pasting into a browser.
> [SM] Minor update to link in Options.py

- worlds/ror2/Options.py
- worlds/ror2/docs/en_Risk of Rain 2.md
The docs never got updated to when I changed how obliteration worked with final stage death.
ran webhost
> RoR2: Victory Conditions Doc Update

- docs/world api.md
https://discord.com/channels/731205301247803413/731214249828941884/1113994843316826282
markdown preview
> docs: Fix typo in world api.md

- WebHostLib/customserver.py
removes no longer used imports from customserver
running the webhost
> WebHost: remove some unused imports

- WebHostLib/customserver.py
> Webhost: reenable ping on webhost multi server

- worlds/witness/static_logic.py
- worlds/witness/utils.py
Make Witness world work as an apworld.
This mostly meant replacing "open" statemenets with "pkgutil.get_data"
> Witness: apworld support

- worlds/witness/utils.py
The file diff is self-explanatory...
Yikes, I swear I ran like 15 generations with a random yaml, I got so unlucky
> The Witness: Fixed seeds not generating with vanilla logic

- WebHostLib/generate.py
found generator_options keyerror on line 109 in the server logs, so fixing that
nope
> WebHost: fix dict lookup exceptions

- README.md
Docs: Added DOOM 1993 to the list of games in the root README.md
> Docs: Added DOOM 1993 to the list of games in the root README.md

- setup.py
Creating the _speedups.pyd in-place proved problematic because Windows won't delete files that are in use. We now build it manually and copy to the destination lib/ dir to avoid this.
Running setup.py build_exe
> Setup: don't build speedups in-place, copy instead

- NetUtils.py
- _speedups.pyx
- test/netutils/TestLocationStore.py
... to pure python implementation.
Title
Running phar's seed and running tests after changing expected outcome of tests.
> MultiServer: Allow games with no locations, add checks to pure python implementation.

- Main.py
- WebHostLib/tracker.py
removes "names", as was planned around 0.4.0
minimally, please test too
> Core: remove "names" from multidata

- worlds/ror2/Regions.py
Title
ran https://github.com/ArchipelagoMW/Archipelago/pull/1935 and noticed two stages were in the wrong spot
> RoR2: fix event exits for dlc stages

- worlds/witness/hints.py
Basically, some people requested this and I thought it was already the case. Lol
> The Witness: Add Quarry Stoneworks Control Room Left to the hint pool

- docs/apworld specification.md
- docs/world api.md
This fixes some mistakes and inconsistencies in "world api.md".
> docs: clean up world api.md a bit

- WebHostLib/templates/islandFooter.html
Nothing quite like updating the copyright year more than half a year into the year.
Number go up. brrr
wow
> WebHost: Update copyright year in footer.

- worlds/dkc3/__init__.py
Move Generate Basic earlier to pass tests
A few generations
> DKC3: Move item creation earlier

- worlds/generic/docs/setup_en.md
Adding some text regarding generating template yamls, since this section only discusses exporting from the website. The main purpose is to show how to generate template yamls for non-main apworlds.
2 hours, closed notebook, 45 questions open-ended. Partial credit awarded _only if work is shown_.
N/A
> Docs: Slight doc update regarding yaml template generation

- worlds/mmbn3/Rom.py
- worlds/pokemon_rb/rom.py
- worlds/tloz/Rom.py
Same issue as #1986, I just missed these two the first time. Went through and confirmed this issue isn't made anywhere else.
Generated a game with the changes, confirmed output was correctly made.
> MMBN3, Pokemon RB: Fix Incorrect Import

- worlds/musedash/__init__.py
- Changes all instances of `self.multiworld.random` to `self.random`
- Uses the newer entrance functions to clean up entrance connection
Note: Will deal with `get_filler_item_name` at another time as using it will require some additional work for which I don't have the time atm.
Several local generations.
N/A
> Muse Dash: Update code to use some newer API

- worlds/witness/__init__.py
Incredibly sorry for missing this, that should've stuck out to me way more.
> Witness: Yeah let's not sort the entire multiworld's itempool lol

- WebHostLib/templates/multiFactorioTracker.html
- WebHostLib/tracker.py
Fixes <=0.4.0 IDs that were still in the multitracker
quickly
> Factorio: fix multitracker ID misalignment

- worlds/messenger/docs/en_The Messenger.md
- worlds/messenger/docs/setup_en.md
Documents a bug someone found that I can't fix and removes workaround code for another thing I was ignorant of.
📖
> The Messenger: Update Docs for latest release

- docs/world api.md
Review of #1958 showed that documentation of item classifications could be improved.
> docs: mention all item classifications

- worlds/factorio/__init__.py
Ensure that people don't use an old client that is known to be incompatible.
Not
> Factorio: update required_client_version

- worlds/hk/__init__.py
A typo :)
Tbh I didn't but I can guarantee you that LEFTSLASH is much more likely to actually exist than LFFTSLASH
> HK: Fix typo in LEFTSLASH

- worlds/pokemon_rb/__init__.py
- worlds/pokemon_rb/rom.py
- worlds/pokemon_rb/rules.py
Fixes imports and patch file loading to work in apworlds
running setup to build EXEs, running generate w/ Pokémon Red and Blue game, patching game w/ client
> Pokemon RB: apworld fixes

- worlds/witness/__init__.py
Medic has come about as close to writing code for this randomizer as they could without actually doing so, literally sending me the line that's wrong and telling me how I need to change it, for bugs it would've taken weeks to find on our own.
I think that should count, so. Yeah :P
> Witness: Add Exempt-Medic to the in-game credits hint

- worlds/musedash/MuseDashData.txt
Adds a couple more songs from the Cosmic Radio Update.
Couple Generations + Tests
> Muse Dash: Add songs from Cosmic Radio Update

- worlds/sc2wol/docs/setup_en.md
- worlds/sm64ex/docs/en_Super Mario 64.md
Docs: removed an extraneous sentence from SC2 setup guide and corrected a misspelling in SM64 info doc.
Making bits of documentation easier to read
Looking at the rendered markdown.
> Docs, SM64, SC2: Minor Documentation Updates

- worlds/dark_souls_3/docs/en_Dark Souls III.md
Rewrites the DS3 game page to be more in line with current settings and better describe certain mechanics.
> DS3: Update game page

- worlds/pokemon_rb/__init__.py
Adds more data to slot_data for tracker purposes.
Generated a game and ensured it didn't crash.
> Pokémon R/B: More slot data for trackers

- Utils.py
- WebHostLib/requirements.txt
- requirements.txt
updates some versions
just some clicking around on a local webhost for now
> Core: update versions

- kvui.py
https://discord.com/channels/731205301247803413/1138588937007407154
https://discord.com/channels/731205301247803413/1138588937007407154/1151982943242293368
> kvui: remove custom DPI scaling on windows

- requirements.txt
New fish of the jelly kind.
I had this installed since it came out. So maybe it was.
> Core: update jellyfish

- NetUtils.py
https://discord.com/channels/731205301247803413/731214280439103580/1154874595057352877
renaming _speedups.pyx and then doing
```python
import NetUtils
```
> Speedups: fix file date check when frozen

- worlds/terraria/__init__.py
according to https://github.com/ArchipelagoMW/Archipelago/pull/2116 this data is unused.
it wasn't
> Terraria: remove unused data

- BaseClasses.py
- worlds/AutoWorld.py
offer API hook to modify Group World creation
> Core: offer API hook to modify Group World creation

- test/TestBase.py
- worlds/messenger/Rules.py
- worlds/messenger/test/TestLogic.py
two locations in glacial peak were missing their rules for hard logic. Reliant on #2233
Unit tests and a lot of debug stepping
> The Messenger: fix rules for two glacial peak locations

- kvui.py
silently fail to disable DPI awareness on Windows
Nope and can't.
> kvui: silently fail to disable DPI awareness on Windows

- WebHostLib/misc.py
caches misc page template results
clicking around a bit, did not do any benchmarking
> WebHost: cache static misc pages

- WebHostLib/requirements.txt
updates ponyorm to 0.7.17
barely on 3.11
> WebHost: update ponyorm

- WebHostLib/templates/viewSeed.html
> WebHost: fix indentation

- WebHostLib/templates/multiFactorioTracker.html
nothing really, just makes the Factorio tracker cleaner in case of copy pasting
yes, but merely with a single factorio world
> WebHost/Factorio: use "better" jinja practices in web tracker

- test/TestBase.py
> Tests: add can_reach_region method to WorldTestBase

- Utils.py
Adds win32 gui support for messagebox
> Utils: support messagebox on windows without dependencies

- worlds/ff1/__init__.py
creates items in `create_items()`
generated a few hundred seeds
@jtoyoda
> FFR: create items in the correct place

- CommonClient.py
just a bit  cleaner when this gets copy pasted, as it inherits the parent tags
I added  a new tag to the base Context and it propagated.
> CommonClient: inherit Context tags

- worlds/pokemon_rb/docs/setup_en.md
- worlds/pokemon_rb/docs/setup_es.md
Change recommended Bizhawk version to 2.9 in the Pokémon R/B Setup Guide
My eyes, and Google Translate
> Docs: Recommend Bizhawk Version 2.9.1 for Pokémon R/B

- worlds/overcooked2/__init__.py
I bug good
generated and played a session. Also wrote a unit test in a forthcoming PR
> OC2: fix mistakes when moving to new options api

- worlds/generic/docs/advanced_settings_en.md
Added suggested change regarding BK mode from Issue #2295
Previewed changes in viewer to make sure PEP8 followed and looks correct
> Docs: Added Note Explaining BK and fix typo in advanced settings

- worlds/alttp/Items.py
make Triforce Piece progression_skip_balancing in LttP
nope
> LttP: make Triforce Piece progression_skip_balancing

- worlds/messenger/__init__.py
- worlds/messenger/subclasses.py
Speed up generation for large multiworlds by not forcing a recache for every player
I trust in my ability to not mess this up
> The Messenger: speed up generation for large multiworlds

- worlds/oot/__init__.py
Also includes some extra optimizations in case this is used on async before I finish the prefill optimizations.
Tests will fail because of alttp, oot tests should succeed now
> Fix OoT in new region cache

- worlds/tloz/docs/multiworld_en.md
Oops, we never had the required version of the game in the setup guide. This fixes that.
Ran the webhost to make sure my change took.
N/A
> TLOZ: Update setup doc to include what version of TLOZ is required

- worlds/musedash/MuseDashData.txt
- worlds/musedash/__init__.py
Adds the new songs from Muse Dash 3.10.0 and also adjusts a song name to the new spelling. (New pack is not a separate DLC so it isn't needed to be added to the list.)
Using Tests.
> Muse Dash: Apply new songs and name changes from Muse Dash 3.10.0

- Main.py
> Core: Running item Plando dot

- worlds/alttp/Rom.py
- worlds/alttp/__init__.py
As per community preference votes in https://discord.com/channels/731205301247803413/827141303330406408/1170064904573693962 adds the bottle refill to spoiler log and removes the fart in a bottle return. (Empty Bottle)
> LttP: write fairy bottle fill to spoiler and prevent fart in a bottle

- CommonClient.py
Reduces UserError cases
It wasn't
> CommonClient: make IncompatibleVersion more explicit.

- BaseClasses.py
Fixes item links groups not existing in the region manager, and collection state.
Wasn't
> Core: fix item links around core changes

- Utils.py
> Core: Increment Archipelago Version

- Fill.py
hopefully https://discord.com/channels/731205301247803413/1153540697031442544
it wasn't
> Plando: verify from_pool type

- worlds/alttp/Options.py
removes a line of code.
Not bothering with the initial plan, at least today.
> LttP: remove extra default = False

- inno_setup.iss
deletes old files that may still exist in user installations.
It wasn't, was hoping @Alchav would
> Pokemon: delete old files

- worlds/pokemon_emerald/README.md
Going to continue to keep track of these so there's a throughline after worlds are out of core and I'm back to making releases separate from AP releases.
👀
> Pokemon Emerald: Bump apworld version number

- worlds/musedash/MuseDashData.txt
- worlds/musedash/Presets.py
- worlds/musedash/__init__.py
Add presets to Muse Dash. Also includes an update for songs included in v3.11.0
Running tests and a local webhost to double check presets.
> Muse Dash: Presets and Song Updates

- WebHostLib/static/assets/player-options.js
https://discord.com/channels/731205301247803413/1179193651251920916/1179193651251920916
> WebHostLib: fix NamedRange in options presets

- WebHostLib/templates/supportedGames.html
title. muust've missed this with find all
clicked the buttons
> Webhost: fix options page redirects

- worlds/kh2/Regions.py
- worlds/kh2/__init__.py
title
ran tests and generated a seed
> KH2: Fix events in datapackage

- worlds/kh2/Client.py
- worlds/kh2/Rules.py
- worlds/kh2/__init__.py
Changes the finished_game to new variable so now it only checks the game's memory and if it has sent the finished flag before
Fixed ag2 not requiring 1 of each black magic
Fix hitlist if you exclude summon level 7 and have summon levels option turned off
Put my self into wincon, deleted apsave and restarted the server. Connected and it didnt send out wincon
> KH2: RC1 Bug Fixes

- worlds/hk/__init__.py
removes unused code so this game can actually pass #2386
wasn't but it just removes a line that might as well have just been `if True`
> Hollow Knight: remove unused option check

- worlds/pokemon_rb/client.py
Absolute import of locations_data in client.py is breaking the win7 build.
> Pokémon R/B: Fix import

- WebHostLib/templates/hostRoom.html
> Webhost: open graph support for /room

- BaseClasses.py
ports variable renames from https://github.com/ArchipelagoMW/Archipelago/pull/1764
in the original PR
> Core: make update_reachable_regions local variables more wordy

- worlds/sm64ex/Rules.py
Backported from #2569
Generating
> sm64ex: Fix randomizing Courses and Secrets separately

- worlds/witness/__init__.py
o_o I did NOT know this was here.
> The Witness: Fix an instance of multiworld.random being used

- worlds/factorio/Options.py
Makes it less likely that people kill themselves via pollution and gives them some healing items they may not even know about.
nope
> Factorio: "improve" default start items

- WebHostLib/templates/islandFooter.html
Happy new year AP.
Title.
Wasn't.
2️⃣0️⃣2️⃣4️⃣
> WebHost: Copyright update time.

- worlds/kh2/docs/setup_en.md
updating the docs to be in line with the new update that the openkh mod manager had for the main randomizer
I read it
> KH2: setup guide update to reflect main rando

- worlds/kh2/docs/en_Kingdom Hearts 2.md
- worlds/kh2/docs/setup_en.md
updates the link to the new logic sheet and update list of bounties/whats randomized to reflect the features of the next update.
I read it
> KH2: Update docs and logic sheet to reflect 4.4

- worlds/kh2/Rules.py
terra was missing logic that reflects the game's logic for the fight to show up. 
rolled a seed and it didnt break
> KH2: Fix Terra logic

- worlds/kh2/Options.py
fixing relative import
changed it and genned a seed
> KH2: Fix relative import

- worlds/sc2wol/Client.py
Allows UI to stay responsive
locally
> SC2: run download_data via concurrent.futures

- worlds/dlcquest/__init__.py
- worlds/dlcquest/docs/fr_DLCQuest.md
- worlds/dlcquest/docs/setup_fr.md
Docs: add Translate FR guide for DLCQuest
> Docs: add FR guide for DLCQuest

- test/benchmark/__init__.py
adds a benchmark test to measure time taken in access rules of locations
https://discord.com/channels/731205301247803413/731214280439103580/1171242783349149746
> Test: add location access rule benchmark

- worlds/witness/Options.py
- worlds/witness/WitnessItems.txt
[Bonk](https://www.youtube.com/watch?v=6Ydqj-DU2qo)
(Also changed the weights of existing traps a bit)
Tested:
Mostly client side, using !getitem
> The Witness: Bonk Trap

- worlds/witness/Options.py
Add Death Link Amnesty
Tested:
Once again, this was more client testing than anything, with seeds with different death link & death link amnesty values
> The Witness: Death Link Amnesty

- BaseClasses.py
- worlds/alttp/SubClasses.py
yanks a bit more LttP out of core
with LttP
I found one other use of _hint_text, but that's attached to OoT Regions, so should not be related.
> LttP: move _hint_text to SubClasses

- worlds/stardew_valley/docs/en_Stardew Valley.md
- worlds/stardew_valley/docs/setup_en.md
> Docs: fixed typo in Stardew Valley setup guide

- worlds/witness/hints.py
It's another one of these yay
Also modified one joke hint because it was a bit too close to looking like an actual error.
> The Witness: Junk hints for Shivers, Mystic Quest and Heretic

- worlds/musedash/MuseDashCollection.py
- worlds/musedash/MuseDashData.txt
- worlds/musedash/Options.py
Updates song list to include the new songs from 4.0.0.
Tests and some generations.
> Muse Dash: Add support for Muse Dash 4.0.0 Songs

- worlds/kh2/Logic.py
Fixing final form logic thinking you can level it where you cannot
ran the tests
> KH2: Fix Final Form logic softlock

- worlds/AutoWorld.py
fix comment that did more harm than good
no
no
> Core: fix comment that did more harm than good

- worlds/tunic/__init__.py
- worlds/tunic/er_data.py
- worlds/tunic/er_scripts.py
Adds better support for the Universal Tracker (see its channel in the future game design section).
This does absolutely nothing regarding standard gen, just adds some checks for an attribute that only exists when UT is being used.
Testing with and without UT with gens with various settings to make sure it works regardless of UT status, and regardless of options used.
N/A
> TUNIC: Universal Tracker Support Update

- BaseClasses.py
Fixes a debug printout: "Calculated final sphere A, containing B of C progress items."
Reading.
> [Generation] Fix sphere calculation debug message

- worlds/AutoWorld.py
provide convenience getters on World class
with Subnautica (not included here)
> Core: provide convenience getters on World class

- worlds/dkc3/Locations.py
- worlds/dkc3/Options.py
- worlds/dkc3/Regions.py
- worlds/dkc3/Rom.py
- worlds/dkc3/Rules.py
- worlds/dkc3/__init__.py
- Removes all cases of `world: MultiWorld` in this World.
- Updates to the new Option access API
- Implement `extend_hint_information`
Note: this does not include any functionality changes or player-facing bug fixes. Maybe someday...
Many gens with different settings. Test playthrough.
> DKC3: Long-overdue World code cleanup

- docs/world api.md
> Docs: mention that IDs for items and locations can overlap

- docs/network protocol.md
in markdown preview window in github
> Fixed broken hyperlink

- worlds/pokemon_emerald/docs/rom changes.md
Adds a detailed list of changes made to the game via the base patch that a player might be interested in knowing. Something to link to if someone asks or is curious, but contains many small things that don't really _need_ to be covered by the game page and would probably just clutter it up.
Reading
> Pokemon Emerald: Add exhaustive list of ROM changes

- Options.py
- worlds/messenger/options.py
title
where else would i put it. tested to make sure it assigned correctly.
> Options: add a DeathLinkMixin dataclass to easily standardize death_link

- worlds/Files.py
https://github.com/ArchipelagoMW/Archipelago/pull/2887
I made this variable for more compatible and safer type narrowing, and then I didn't use it for the type narrowing.
looked at it more carefully this time
> Core: fix mistake in PR 2887

- worlds/tunic/docs/en_TUNIC.md
- worlds/tunic/docs/setup_en.md
Updating the setup guide with new links for the randomizer mod repo and BepInEx version, based on an upcoming change to the client mod.
A few other miscellaneous wording changes.
Reading
> TUNIC: Update setup guide and game page docs

- docs/contributing.md
Add my expectations to contributing.md that reviews should state what was reviewed.
Reading. Not a native speaker.
> Docs: Add review expectations to contributing.md

- worlds/witness/options.py
Accidentally made Witness non .apworld compliant
> The Witness: Fix absolute world import

- worlds/witness/__init__.py
```            
for hint in generated_hints:
hint = generated_hints.pop(0)
```
lmao
> The Witness: Fix... I don't know how to explain this one

- data/client.kv
- kvui.py
allow sorting hints in the hint tab
> kvui: allow sorting hints in the hint tab

- worlds/dkc3/CHANGELOG.md
Adds a changelog markdown file to the DKC3 World.
I read it, and tossed it into a markdown renderer.
> DKC3: Add CHANGELOG.md

- Utils.py
> Core: increment version

- worlds/sa2b/CHANGELOG.md
Adds a changelog markdown file to the SA2B World.
I read it, and tossed it into a markdown renderer.
> SA2B: Add CHANGELOG.md

- worlds/witness/hints.py
> The Witness: Add junk hint for Zork: Grand Inquisitor

- worlds/sm64ex/Options.py
- worlds/sm64ex/Regions.py
- worlds/sm64ex/Rules.py
- worlds/sm64ex/__init__.py
Fixes WebHost generation, and uses the new options API to do so.
WebHost and local generations
> sm64ex: New Options API and WebHost fix

- requirements.txt
> requirements.txt: _ instead of - to make PyCharm happy

- worlds/stardew_valley/data/villagers_data.py
- worlds/stardew_valley/logic/logic.py
`test_given_mod_names_when_generate_paired_with_entrance_randomizer_then_basic_checks` fails because
<details><summary>Assert all locations are accessible</summary>
<p>
```
AssertionError: False is not true : (Reach Location Complete Crafts Room & Reach Location Complete Pantry & Reach Location Complete Fish Tank & Reach Location Complete Bulletin Board & Reach Location Complete Vault & Reach Location Complete Boiler Room) -> False
Reach Location Complete Crafts Room -> False
(Received 9 Foraging Level & Has Fiddlehead Fern & Has Fiddlehead Fern & Reach Region Wizard Tower & Reach Region Wizard Tower & Received 3 [Has Dandelion -> Received Spring, Has Purple Mushroom -> (Reach Region The Mines - Floor 95 | Reach Region Skull Cavern Floor 25 | (Received Mushroom Boxes & Reach Region …
```
> Stardew Valley: Fix generation fail with SVE and entrance rando when Wizard Tower is in place of Sprite Spring

- worlds/smw/docs/en_Super Mario World.md
Updates SMW's Game Page documentation to include v2.0 features.
I read it.
> SMW: Update World Doc for v2.0 Features

- worlds/shorthike/docs/en_A Short Hike.md
Fixes incorrect information about the save slots in the docs of A Short Hike.
> A Short Hike: Fix incorrect info in docs

- README.md
Removed the section mentioning Windows-only installers.
I read it
> README: Remove outdated information about launchers

- worlds/tunic/er_scripts.py
Remove some unused stuff that got left in after a merge. Also change an if to an elif because that's probably faster?
Test gens with ladder shuffle on and entrance rando off, as that is the case where the function is called. Also test gens with all random settings as a just-in-case.
N/A
> TUNIC: Minor refactor of the vanilla_portals function

- worlds/factorio/Client.py
fix attempting to create savegame with not filename safe characters
https://discord.com/channels/731205301247803413/1204642920221638677
> Factorio: fix attempting to create savegame with not filename safe characters

- worlds/smz3/Options.py
Fixing typos on option tooltips
> SMZ3: Fixing minor typos on options

- Generate.py
removes now unused stuff in Generate.py
Not yet, I'm in Generate for another PR and ran into this. Will test it together with the change I actually wanted to do.
> Core: remove now unused stuff in Generate.py

- worlds/yoshisisland/__init__.py
A typo: "randomizerand"
Reading
> Yoshi Island: Typo Fix

- worlds/sc2/PoolFilter.py
https://discord.com/channels/731205301247803413/1227239356272607262
Sorts campaigns that are subjects to goal selection prior picking the one containing the goal
The game still successfully generates
No
> SC2: Fix possible non-determinism in goal selection

- worlds/tunic/__init__.py
- worlds/tunic/er_rules.py
- worlds/tunic/er_scripts.py
- worlds/tunic/test/__init__.py
- worlds/tunic/test/test_access.py
Ran mypy, cleaned up some of the items it called out. Mostly adding return values to things.
Ran unit tests, ran gen.
N/A
> TUNIC: Some cleanup

- worlds/subnautica/__init__.py
- worlds/subnautica/items.py
- worlds/subnautica/options.py
adds a new option to control filler items
also adds some cleanup that I missed in the cleanup PR.
by making a few spoiler logs, the client should be unaffected by this, so I didn't start it up.
> Subnautica: filler items distribution

- worlds/sc2/docs/en_Starcraft 2.md
- worlds/sc2/docs/setup_en.md
Fix documentation title
Documentation-only
nothing important, just text changes
> SC2 Documentation: Fix the page titles

- worlds/ffmq/docs/setup_en.md
Update setup doc for FFMQ to reflect the new compatibility with v1.0 rom
Look at the text in the github preview window
> FFMQ: Update setup doc to reflect new requirements

- worlds/kh2/OpenKH.py
- worlds/kh2/Options.py
- worlds/kh2/__init__.py
- worlds/kh2/docs/setup_en.md
Update to the docs to reflect the removal of the qol stuff from the companion mod and moved into the qol mod.
Fixed the bug that caused the generation to crash if someone excluded keyblade slots.
Added the seed name to the randomizer seed so you can see which seed is which in the mod manager
Fixed some grammar in the cor skip logic option description
ran the tests, generated with a yaml that excluded locations and read the setup guides
> KH2: Docs updates and Excluded Locations Bugfix

- worlds/doom_ii/Rules.py
- worlds/doom_ii/__init__.py
- worlds/doom_ii/docs/setup_en.md
- Added info in doc on which folder to find your WAD file in your steam library
- renamed variables world -> multiworld
Generated locally.
> DOOM II: var world->multiworld fix and minor doc fix

- docs/CODEOWNERS
Changing ChecksFinder code owner to me
it was not
> CODEOWNERS: Update owner for ChecksFinder

- worlds/generic/docs/advanced_settings_en.md
Adds links to /check from the advanced yaml guide
reading it and clicking the links
> Docs: Mention /check in the advanced yaml guide

- worlds/tunic/docs/en_TUNIC.md
Just some edits that have been bugging me. Wish I could fix the issue with that large gap before the starts of lists.
Reading, viewing webhost
N/A
> TUNIC: Minor edits to game page

- worlds/witness/data/WitnessItems.txt
- worlds/witness/data/WitnessLogic.txt
- worlds/witness/data/WitnessLogicExpert.txt
- worlds/witness/data/WitnessLogicVanilla.txt
- worlds/witness/data/settings/Door_Shuffle/Complex_Doors.txt
Couple more door item names that didn't fit the correct naming scheme.
> The Witness: More door renames

- worlds/factorio/requirements.txt
sets factorio-rcon-py to tested compatible versions
yes
> Factorio: fix client compatibility with Windows 7/Python 3.8

- MultiServer.py
- SNIClient.py
- Utils.py
- worlds/alttp/Rom.py
- worlds/factorio/Client.py
switches get_options to get_settings in stuff I'm responsible for.
Manually. If I was allowed to just do it for all worlds I could have PyCharm do it and check it for me.
> Core/SNIClient/LttP/Factorio: switch to get_settings

- CommonClient.py
just a few type annotations that were missing
maybe
> Core: some `CommonContext` typing

- worlds/pokemon_emerald/docs/setup_en.md
- worlds/pokemon_emerald/docs/setup_es.md
It's updating the Link for the poptracker pack for Pokémon Emerald as the old maintainer dropped support and the pack was no longer functioning correctly with 0.4.5. This new pack was developed by three people, Seto, Vyneras and me, palex00 and is also pinned in the Discord Channel now. It's the definitive pack.
It's a text document. I read it.
> Updating Poptracker-Pack-Link for Pokémon Emerald as the old one was no longer maintained and did not work with 0.4.5

- worlds/wargroove/Options.py
- worlds/wargroove/__init__.py
Switched Wargroove to use the new options API
I generated a game, ran the server on it, connected the Wargroove client to it, did a /release, verified that the client showed the correct multipliers for the various options. I ran this test multiple times for different option values.
> Wargroove: Switched to options API.

- worlds/witness/data/WitnessLogic.txt
- worlds/witness/data/WitnessLogicExpert.txt
- worlds/witness/data/WitnessLogicVanilla.txt
Another thing that cannot possibly matter right now, but who knows about the future
> The Witness: Fix Monastery Entry Right Requirement

- WebHostLib/customserver.py
Hopefully nothing. But maybe a recent rollback occured due to multi-hosting the same room and an outdated shadow version writing to DB? Unknown if that was the reason, but this should remove the possibility.
Ran it, nothing more.
> WebHost: re-introduce per-Room Locker

- worlds/factorio/requirements.txt
2.1.1 didn't work with py3.8, 2.1.2 fixes that
Not yet.
> Factorio: update factorio-rcon

- WebHostLib/templates/playerOptions/macros.html
- WebHostLib/templates/weightedOptions/macros.html
[Issue 3373](https://github.com/ArchipelagoMW/Archipelago/issues/3373)
LocationSets with default values were not working.
Generations, looking at WebHost, and exporting yamls.
> WebHost: Fixing default values for LocationSets

- worlds/tunic/docs/setup_en.md
Adds some linux-specific instructions to the setup guide
Had someone with linux tell us what they thought we should add
N/A
> TUNIC: Update setup guide with some linux instructions

- worlds/musedash/MuseDashData.txt
Its that time of the month again. Update song list to 4.3.0
Using tests. And a local generation
> Muse Dash: Update Song List to Muse Dash 4.3.0

- worlds/generic/docs/advanced_settings_en.md
- worlds/generic/docs/triggers_en.md
Went to fix some changes in the triggers guide and accidentally opened the wrong file, made some small changes to two files now.
Reading
> Docs: Update trigger guide and advanced yaml guide

- worlds/musedash/MuseDashData.txt
- worlds/musedash/Options.py
Once again, another song update.
I will make another PR for option changes, which will adjust how dlc's are shown, which will depend on this PR. (CHUNITHM is a "time limited" dlc and with the option changes, I can finally put all the long running time limited dlcs in the list.)
Running tests.
> Update to Muse Dash 4.4.0

- worlds/hk/GodhomeData.py
- worlds/hk/__init__.py
apparently this is required? and noone knew?
generated once and didn't play it
> HK: adds Godtuner for GH Flower Quest Goal

- worlds/hk/Options.py
Some expected default settings are not on account of python tomfoolery.
Wasn't
> Hollow Knight: Add missing comma

- worlds/witness/data/settings/EP_Shuffle/EP_Easy.txt
> The Witness: Put Treehouse Both Orange Bridges EP on the normal EPs exclusion list

- worlds/zillion/requirements.txt
There was a bug that made lots of flashing terrain if a game over happened in certain places.
(And this could be dangerous for people sensitive to flashing lights.)
There was also a bug with a bad sound effect after a game over.
diff: https://github.com/beauxq/zilliandomizer/commit/1dd2ce01c9d818caba5844529699b3ad026d6a07
generated a game and got a game over in one of the affected places
> Zillion: fix some game over bugs

- worlds/tunic/docs/setup_en.md
Setup guide is now more explicit on which version of bepinex to download.
Also added a link to poptracker under the map tracker link.
Reading
N/A
> TUNIC: Update setup guide

- WebHostLib/templates/weightedOptions/macros.html
> Documentation: Fixing subject-verb agreement in NamedRange special value description

- AdventureClient.py
- worlds/adventure/Options.py
- worlds/adventure/Regions.py
- worlds/adventure/Rules.py
- worlds/adventure/__init__.py
Adventure: Update to use new options api
Remove deprecated options calls
Generated adventure multiworlds with random settings, checked logs for errors, and played a couple of them to confirm different settings were applied.
N/A
> Adventure: Update to use new options api

- worlds/messenger/options.py
- worlds/shorthike/Rules.py
- worlds/yugioh06/client_bh.py
- worlds/yugioh06/opponents.py
messenger, yugi and shorthike loading on 3.8 build
On cx freeze 7.0.0 on python 3.8 on win10
> Various: fix absolute imports in worlds

- docs/CODEOWNERS
Announcement Post: https://discord.com/channels/731205301247803413/959203442570715176/1249823352755978240
TL;DR I am stepping down as maintainer, and @qwint is stepping up.
N/A
N/A
> CODEOWNERS: Replace @ThePhar with @qwint as Hollow Knight maintainer.

- WebHost.py
removes files like https://archipelago.gg/tutorial/Starcraft%202%20Wings%20of%20Liberty/setup/en
(I have since manually deleted the file, so it may not show up anymore.)
locally, saw the folder poof.
> WebHost: delete old docs files

- worlds/pokemon_rb/docs/setup_en.md
- worlds/pokemon_rb/docs/setup_es.md
The old tracker did not have any logic update since 0.4.3 and the maintainer is unreachable. This is a from-the-grounds-up new tracker developed by Coveleski and me, palex00. It will be maintained.
> Pokemon Red/Blue: Replaces link to R&B Poptracker with a new one

- docs/CODEOWNERS
Per request: https://discord.com/channels/731205301247803413/1214608557077700720/1250714693136547920
World is still considered active, but may become inactive if a future update breaks compatibility with no maintainer to take on world maintenance.
If anyone is interested in taking on responsibility for maintenance, a list of known bugs is compiled here: https://docs.google.com/spreadsheets/d/1inhmXSQk9UvDKjiBrfwFGVDDFt2ZnkdsmpIJmRQFUeA/edit?gid=0#gid=0
N/A
N/A
> CODEOWNERS: Remove @zig-for as world maintainer for LADX.

- worlds/tunic/docs/en_TUNIC.md
Adds more tips to the game info page, and links to the tunic rando site since it has even more tips and such
Reading
N/A
> TUNIC: Update game info page with more tips

- worlds/zillion/__init__.py
- worlds/zillion/options.py
- worlds/zillion/requirements.txt
a new map generation feature
zilliandomizer package diff https://github.com/beauxq/zilliandomizer/compare/v0.7.1...v0.8.0
A few players played a few games in the single player randomizer.
At least one playthrough of an AP seed.
> Zillion: new map generation feature

- worlds/generic/docs/setup_en.md
Lastest Release -> Latest Release
Technically it's correct currently, buuuuuut
ASTM A370
no
> Docs: Lastest -> Latest

- worlds/subnautica/__init__.py
A couple days ago an update of the Subnautica mod was released, I have received no bug reports about and it establishes compatiblity with overlapping IDs. So I think it's time to enforce the update.
I tested it in the big async, it was posted publicly for testing as well. It found two bugs in MultiClient.Net that have since been fixed.
> Subnautica: increase minimum client version

- worlds/yugioh06/boosterpacks.py
- worlds/yugioh06/structure_deck.py
Fixes non-deterministic bug involving sets not being sorted.
Generated several games and compared the order of booster packs and structure decks in the spoiler log.
> YGO06: fixes non-deterministic bug

- worlds/bomb_rush_cyberfunk/Locations.py
> Bomb Rush Cyberfunk: Fix final graffiti location being unobtainable

- worlds/hk/__init__.py
removes the delete from remove (because it's a counter so -1 does just fine) to fix hk for #2062
ran a local copy of the failing test in 2062 modified for current main
> HK: fix remove issues failing collect/remove test

- docs/apworld_dev_faq.md
Adds a bit of text explaining the value in `early_local_items`, adds alternative ways to handle the restrictive start fill errors, and adds alternatives to the `while` loop for creating filler items.
Reading
> Docs: Expanding on the answers in the FAQ

- WebHostLib/tracker.py
Disclaimer: I don't know what this does and I'm not about to go read through everything to figure out what it all does. All I know is that this is a very clear typo. If it's not, please feel free to close this.
It wasn't. I don't even know what this file does. I think it's the multitracker?
N/A
> Webhost: Fix typo in tracker.py

- worlds/ffmq/Client.py
Fixes a bug with reset protection that renders the client unusable.
Connecting and sending checks.
> FFMQ: Fix reset protection

- worlds/pokemon_rb/options.py
Title, also:
https://discord.com/channels/731205301247803413/1230990819217899550/1230990819217899550
Generations
> Pokemon R/B: Removing Floats from NamedRange

- worlds/clique/Items.py
- worlds/clique/Locations.py
- worlds/clique/Options.py
- worlds/clique/Rules.py
- worlds/clique/__init__.py
Phar needed someone to do it, so I did it.
Also I added `start_inventory_from_pool` because I want more people to know it exists, so if it's in the game people sometimes reference when making a new world, that increases the chances that someone actually uses it.
Some test gens. Made sure it still worked.
N/A
> Clique: Update to new options API

- docs/network protocol.md
Adding documentation for the `HintGame` tag (and cleaning up tag docs)
n/a
> Docs: Update 'tag' documentation

- worlds/minecraft/ItemPool.py
- worlds/minecraft/Options.py
- worlds/minecraft/Rules.py
- worlds/minecraft/Structures.py
- worlds/minecraft/__init__.py
- worlds/minecraft/test/TestOptions.py
- worlds/minecraft/test/__init__.py
Updating mineraft to the new options system, as well as stopped using per slot randoms in favor of self.random
game generated, and output valid APMC file
> Update Minecraft to new options system.

- worlds/osrs/__init__.py
Missed this in my review of OSRS.
> OSRS: Purge the "world: MultiWorld" evil

- worlds/kh1/Rules.py
Makes some ceiling division in the puppy logic human readable.  No functional change.
Generated a few games and confirmed the results.
N/A
> Kingdom Hearts: Make Ceiling Division Human-Readable

- worlds/ahit/Regions.py
Once a thug shop rolled 0 as the number of items it should have, all remaining iterations would do nothing because neither the `count == -1` condition nor the `count >= 1` condition would be met. This caused all remaining thug shops to have zero items. This also caused the item counts of remaining thug shops to be absent from slot data, which was how this issue was found.
I found the old code confusing and, rather than try to figure out how to fix it, I opted to rewrite it. With the new code, a local variable dictionary tracks the number of created locations for each thug and no more locations are created for a thug once their number of locations equals the number of shop items that thug rolled.
An AHiT yaml was used that had `NyakuzaThugMinShopItems: 0` and print statements were added to …
> AHIT: Fix thug shops having 0 items after the first shop that rolls 0 items

- WebHostLib/requirements.txt
Updates webhost dependencies
werkzeug: looks safe, fixes a regression that doesn't matter for us, fixes potential DoS
pony: fixed just meta data
flask-limiter: bug fix for conditional limits
bokeh: bug fixes and new features, migration guide does not list anything
CI and looking at changelogs
> WebHost: update dependencies

- docs/world maintainer.md
ESL, feel free to make suggestions for how to phrase this better
> Docs: Specify process for adding a world maintainer to an existing world

- docs/CODEOWNERS
https://discord.com/channels/731205301247803413/1214608557077700720/1253206955879694336
Espeon might come back, but still, this world acts as unmaintained right now, so we should make this change, and then change it back if/when he's back.
@espeon65536 Just so you're aware of this change as well
> CODEOWNERS: Move OoT to "unmaintained"

- WebHostLib/templates/userContent.html
Webhost: Fixed typo ("no" to "not")
> Webhost: Fixed typo in userContent.html

- worlds/rogue_legacy/Options.py
- worlds/rogue_legacy/Regions.py
- worlds/rogue_legacy/Rules.py
- worlds/rogue_legacy/__init__.py
- worlds/rogue_legacy/test/__init__.py
Updates Rogue Legacy to the options API per #3284 . 
Unittests + a generation confirming that the "RLWorld assigned options through option_definitions" did not occur. Could not play a seed to test fully.
> Rogue Legacy: Update to Options API

- worlds/witness/__init__.py
The newest release of the Witness client connects with 0.5.1
https://github.com/NewSoupVi/The-Witness-Randomizer-for-Archipelago/releases/tag/7.0.0p10
> The Witness: Bump Required Client Version

- docs/CODEOWNERS
I've already discussed this with @Marechal-L and gotten his approval.
> Add myself as a world maintainer for DS3

- Utils.py
Technically neither of those things
wasn't.
> Core: update version number

- worlds/hk/docs/setup_en.md
https://discord.com/channels/731205301247803413/959203442570715176/1283969471932923965
> HK: XBox doesn't exist

- worlds/mmbn3/__init__.py
Entrances to SciLab_Cyberworld and Yoka_Cyberworld had logic for being able to reach SciLab_Overworld, but did not register this indirect condition.
Entrances to Beach_Cyberworld had logic for being able to reach Yoka_Overworld, but did not register this indirect condition.
Entrances to Undernet and Secret_Area had logic for having a high enough explore score, but explore score is calculated based on the accessibility of a number of regions and no indirect conditions were being registered for these regions.
I wrote a test (#3924) to sweep in spheres once as normal and then a second time with `world.explicit_indirect_conditions = False`. When all required indirect conditions are present with `world.explicit_indirect_conditions = True`, the spheres in both sweeps should always be the same. …
> MMBN3: Add missing indirect conditions

- worlds/yugioh06/__init__.py
- worlds/yugioh06/rules.py
Fixes a slotdata oversight for universal tracker.
Also assigns "low deck bonus" and "extremely low deck bonus" their proper difficulty.
Generated a game
> YGO06: slotdata fix

- worlds/witness/rules.py
I merged https://github.com/ArchipelagoMW/Archipelago/pull/3617 but then Exempt-Medic reminded me that there was some dead code I was gonna remove. So yea
Also changed two `isinstance(tuple)` to `isinstance(SimpleItemRepresentation)` (the actual NamedTuple class that they would be)
> The Witness: Remove some unused code

- worlds/osrs/Options.py
closes #3946 , adds display names to OSRS options
Web Host run locally, confirmed display names added.
> [OSRS] Adds display names to Options

- worlds/messenger/docs/en_The Messenger.md
- worlds/messenger/docs/setup_en.md
This new feature got added and The Messenger already supports it as part of the feature but i forgor to update docs.
> The Messenger: add webhost auto connection steps to guide

- worlds/stardew_valley/data/items.csv
Someone asked for a resource pack of cinder shards, so I provided it
Unit Tests
> Stardew Valley: Add Cinder Shard resource pack

- worlds/AutoWorld.py
Noticed this could be made clearer when someone else linked there.
It wasn't
> Core: update World method comment

- worlds/kdl3/__init__.py
Wasn't, this is the same fix as #3175
> KDL3: Fix webhost not giving a patch

- worlds/pokemon_emerald/CHANGELOG.md
Adds #3939 and #3900 to the changelog.
> Pokemon Emerald: Update changelog

- worlds/kh2/__init__.py
This is adding several of the options to slot data so the upcoming shiny new KH2 Poptracker Pack can use them
I generated on Source with this new apworld, connected to the room made with this change and verified with a Debug poptracker pack that the new slot data is present
N/A
> [KH2] Adds more options to slot data

- worlds/timespinner/__init__.py
> Timespinner: Two typos

- worlds/minecraft/Structures.py
Minecraft's connections plando was broken as a result of #3765.
This fixes it.
Ran a gen using plando connections. Everything worked as expected.
> Minecraft: Fix plando connections

- worlds/aquaria/docs/setup_en.md
- worlds/aquaria/docs/setup_fr.md
> [Aquaria] Adds Poptracker Pack to the Aquaria Setup Guides 

- Launcher.py
Title. This wasn't a thing already somehow.
`py Launcher.py`
> Core: Add Version string to Launcher title

- worlds/lufia2ac/test/__init__.py
> Lufia 2: Update tests to bases.py

- worlds/ladx/test/__init__.py
> LADX: Update tests to use bases.py

- worlds/pokemon_emerald/test/__init__.py
- worlds/pokemon_emerald/test/test_warps.py
> Pokemon Emerald: Update tests to use bases.py

- worlds/checksfinder/__init__.py
Reducing fluff in setup guide intro and changing writer of the guide from mewlif to me (as the stuff from mewlif was basically removed in previous changes)
by running webhost from source
> Checksfinder: clean up setup guide intro and change ownership

- worlds/factorio/data/mod_template/control.lua
Fixes Satellite goal for Factorio 2.0
You no longer check the rocket itself for the satellite, but instead, you check if the rocket has a cargo pod attached.  If so, the check that for the satellite.
Finish a seed set to satellite goal to completion.
> [Factorio] Fix satellite goal

- docs/CODEOWNERS
Since Chandler is unavailable, I can be the maintainer since I designed the client, as Chandler and I were a team
> docs: Add @BrandenEK as codeowner

- worlds/factorio/data/mod_template/control.lua
Make Energy Link Bridges more UPS friendly than ever before,  Also make them work on multiple surfaces, as the check for the bridges is now event based rather than doing a surface scan.   The main way this improves UPS is either when there is a large number of bridges, or when the surface that is scanned for the bridges is super large.
Playing on some live games.
> [Factorio] energy link bridge improvements

- worlds/kh1/Rules.py
Adjusts a few logic rules for some missed scenarios that may cause unreachable (or at least difficult-to-reach) locations.  These issues were brought to my attention by Goblin God.
Goblin God and I ran a recent 100% seed to confirm the changes were being taken into account.
> Kingdom Hearts: Minor Logic Fixes

- worlds/witness/options.py
Who let me get away with this lmao
> The Witness: Rename "Panel Hunt Settings" to "Panel Hunt Options"

- worlds/smz3/Options.py
Original PR that I accidentally closed by deleting the branch associated with it - https://github.com/ArchipelagoMW/Archipelago/pull/3689
Reopened in the hopes of getting it added, since it's a nice thing to have so you don't find duplicates of stuff out in the wild.
> SMZ3: Add Start Inventory From Pool

- worlds/hk/Options.py
adds a specific error message for invalid plando charm costs
> HK: better error messaging for charm plando

- .github/workflows/build.yml
> CI: fix naming of windows build action

- docs/CODEOWNERS
As stated [here](https://github.com/ArchipelagoMW/Archipelago/pull/4240#issuecomment-2508618526) and [on Discord](https://discord.com/channels/731205301247803413/1214608557077700720/1312154267716419715), just making it official
By mocking the pointless "This CODEOWNERS file contains errors" warning that GitHub shows
> CODEOWNERS: id Tech 1 co-ownership (adding myself as owner)

- WebHostLib/templates/templates.html
Removes a script that as far as I can tell, is unused on this page.
locally
> WebHost: delete unused script tag

- worlds/hk/Items.py
adds item group for progressive dreamnail,
will be obsolete after item rename
wasn't
> HK: add item group for dream nail(s)

- worlds/hk/Options.py
- worlds/hk/__init__.py
See title
Running unittests and generation
> HK: Remove unused variables and imports

- worlds/adventure/Locations.py
- worlds/adventure/Regions.py
- worlds/adventure/Rom.py
Removes unused variables and parameters in various locations.
Running unittests and generation
> Adventure: Remove unused variables

- WebHostLib/templates/hostRoom.html
- WebHostLib/templates/macros.html
https://discord.com/channels/731205301247803413/731214280439103580/1312526939571097662
Checking the Text Client link having a port now on localhost.
> WebHost: fix host room not updating (ports in) slot table

- .github/workflows/scan-build.yml
Updates to the latest version of scan-build
CI
> CI: update scan-build to v19

- NetUtils.py
- _speedups.pyx
- _speedups.pyxbld
- test/netutils/test_location_store.py
see title
plus a bit of cleanup
Tests
> Core: fix exceptions coming from LocationStore

- worlds/noita/items.py
Reclassifies the Greed Die from filler to trap, because let's face it: they kill ya more often than anything else
Test gen
> Noita: Make greed die a trap

- BaseClasses.py
- Fill.py
- docs/network protocol.md
- docs/world api.md
- worlds/generic/docs/advanced_settings_en.md
If you want context: Take a day off, and read the last day of messages in #ap-core-dev.
> Core: Reword item classification definitions to allow for progression + useful

- worlds/shivers/Options.py
Follow on PR from https://github.com/ArchipelagoMW/Archipelago/pull/4018#issuecomment-2564009838
This PR just cleans up the options as suggested to me by @Exempt-Medic
> Shivers: Follow on PR to cleanup options

- LICENSE
- WebHostLib/templates/islandFooter.html
2024 -> 2025
and
2022 -> 2025
No, I'm confident in replacing text successfully.
> Core: it's 2025

- worlds/shivers/Items.py
- worlds/shivers/__init__.py
This just fixes spelling error, and affects nothing but my ego. Laughable I messed up the spelling two PRs ago yet it wasn't caught until after the latest PR got merged.
Thank you @Exempt-Medic for pointing this spelling error out
> Shivers: Fix spelling error in naming

- worlds/kh2/docs/setup_en.md
Updating Documentation
I read it
> Kh2 Doc updates

- worlds/tunic/er_rules.py
- worlds/tunic/rules.py
Adding Dagger and Gun to the logic for the check here, since you can use either to hit the switch as well as the other stuff already considered in logic.
Test gen.
> TUNIC: Logic for Beneath the Vault Bridge Switch

- worlds/subnautica/__init__.py
a typo and removal of a logger instance that is no longer used
I ran AP, which triggers the imports/code
> Subnautica: fix typo and remove no longer used logger

- test/general/test_items.py
PR to #2062 
reorganizes collect/remove tests to just make a new CollectionState instead of copying it every iteration
ran them, updated ffmq to not fail them, saw them not fail (used #4433)
> Tests: Use new CollectionState in collect/remove test instead of attempting to clean up a reused state

- docs/CODEOWNERS
I would like to become the maintainer for LADX.
I know the game well, I'm pretty comfortable in the code base at this point, I've already made various fixes/enhancements, and the community seems to be on board with the idea.
> Codeowners: @threeandthreee as LADX maintainer

- worlds/factorio/data/mod_template/control.lua
https://discord.com/channels/731205301247803413/1316750465219956776/1316750465219956776
> Factorio: fix Evolution Trap crashing bound server

- MultiServer.py
update InvalidPacket text for location scouts
no
> MultiServer: update InvalidPacket text for location scouts

- worlds/tloz/docs/multiworld_en.md
Sptions -> Options
It wasn't, I can't read
> TLoZ: Fix typo in setup guide

- pytest.ini
This allows having failing tests in CI in worlds_disabled and allows moving worlds there to disable tests.
> pytest: only check tests/ and worlds/

- worlds/tunic/options.py
I just didn't like the current order mostly. I think it's a little more organized this way with its _flow_
The unit tests that auto-run after the PR is submitted
> TUNIC: Reorder options

- worlds/_bizhawk/context.py
adds typing to bizhawk component launch
wasn't
> Bizhawk: adds typing to bizhawk component launch

- worlds/_bizhawk/__init__.py
- worlds/_bizhawk/client.py
- worlds/_bizhawk/context.py
Cleans up the typing in the `_bizhawk` files now that we've dropped 3.8.
Launched the client.
> BizHawkClient: Use built-ins for typing

- worlds/tunic/__init__.py
Woops, mostly.
it is an if statement
> TUNIC: Fix hero relics not being prog if hex quest is on in combat logic

- worlds/hk/Options.py
- worlds/hk/__init__.py
- worlds/hk/test/__init__.py
- worlds/hk/test/test_grub_count.py
some stuff ruff and pycodestyle complained about
left extractor stuff alone, regions.py could be deleted but I didn't bother
left some annoying lines that go over 120 untouched
also changed some list(generator) to list comprehensions
ran the tests
> HK: some stuff ruff and pycodestyle complained about

- worlds/noita/options.py
People have been asking more frequently about this, so putting it in the option descriptions will give it more visibility.
> Noita: Add clarification to check option descriptions

- docs/network protocol.md
Fixes mentioned ID range in docs.
Eyes.
> Docs: fix lower limit of valid IDs in network protocol.md

- worlds/tunic/options.py
Bugs were discovered, since we're already in RC phase I doubt the fixes will be merged in time, so adding this label since that's probably the correct thing to do here.
> TUNIC: Call Combat Logic experimental

- worlds/kh2/Rules.py
Fix the lambda's logic 
ran the tests
> Fix the lambda's logic 

- worlds/ahit/Options.py
> [AHIT] Fix small options issue

- worlds/shivers/docs/en_Shivers.md
- worlds/shivers/docs/setup_en.md
Updates the links to point to the new organization for Shivers repos.
Also slight updates on the guides.
Clicked the links
N/A
> Shivers: Update shivers links and guides

- entrance_rando.py
Move speculative sweep membership checks to a set. This saves cycles if speculative sweep is called more than once and loses very minimal cycles otherwise.
I also took this opportunity to pull all the initialization logic up before the nested function defs. This isn't strictly necessary but I keep getting annoyed by it when debugging things and have touched initialization logic in this PR, so I'm leaving it better than I found it.
Existing unit tests. No functional changes to test.
> Core: Do speculative sweep membership checks against a set

- worlds/witness/__init__.py
- worlds/witness/player_items.py
To support this: https://github.com/ArchipelagoMW/Archipelago/pull/4481
I'm not actually sure I agree with that PR, but there is no reason for me not to do this.
> The Witness: Move local_items code earlier

- worlds/alttp/Rom.py
Fixes the dungeon_counters option when the values on and off are selected.   "on" was being treated like "off", and off was being treated like "default".
Temporary logging.info statements in each of the if/elif/else statements, along with yamls picking each of the possible combinations.
> Fix dungeon counter options.

- worlds/tunic/items.py
> TUNIC: Add another alias for ladders

- worlds/oot/__init__.py
It's extremely out of date, and has caused issues here: https://discord.com/channels/731205301247803413/1349099273115140148
Wasn't, I hope I know how comments work in python
> OoT: Remove spanish setup guide

- worlds/messenger/options.py
Title. Missed this because I almost never look at spoilers :sweat:
Generated a game and checked the spoiler.
> The Messenger: add display names to the plando options

- LinksAwakeningClient.py
> Stop ladx from spamming location checks

- worlds/witness/data/utils.py
Really don't want this one to be spoiled :P I've done a lot of private tests, including bigger async multiworlds and stuff, so I'm pretty confident this feature doesn't need the RC testing
Again, don't look at this if you don't wanna spoil yourself
@ core: Feel free to just merge this after approving, no need to wait for me to be around to click myself
> The Witness: Make sure the 2025 April Fools feature does not go live with RC3

- worlds/witness/__init__.py
The new client releases already report this and it will be very necessary that people switch over.
> The Witness: Bump Required Client Version to 0.6.0

- worlds/sa2b/Rules.py
Fixes a typo in an 11th-hour logic fix that was not sufficiently tested.
Actually testing the logic this time.
> SA2B: Fix critical typo

- worlds/musedash/MuseDashCollection.py
- worlds/musedash/MuseDashData.py
Adds the Muse Dash Legend songs. 
With tests.
> Muse Dash; Update Song List to Muse Dash Legend.

- worlds/ffmq/__init__.py
prevents the ffmq website from gaining control of systems running ffmq ap generations
Currently on prod. If I messed up and it's broken I consider that still an improvement.
> FFMQ: fix remote code execution

- worlds/tunic/docs/en_TUNIC.md
As titled.
Since people ask about it sometimes, it makes sense to put that death link exists here somewhere in the docs.
And Trap Link is new, so I want more people to know it exists.
> TUNIC: Note Death Link and Trap Link in-game toggles on Game Info page

- docs/adding games.md
There are a few common features that new world developers tend to miss, and adding them here would formalize them as requirements.
Additionally, I reorganized the document with a few new subheadings, hopefully that breaks the information from one big bullet point list into several smaller ones.
I'm open to any/all of this information being moved, changed, dropped, etc. Leaving as draft for discussion.
PyCharm's MD renderer.
N/A
> Additional detail and organization to adding games.md

- worlds/stardew_valley/options/options.py
Added a "have" to "Very Cheap: Buildings will have an 80% discount"
Added capitalization where it was inconsistent.
Looking at the fixed text.
> Stardew Valley: Fix minor grammatical issues

- worlds/witness/options.py
> The Witness: Option tooltip clarifications

- BaseClasses.py
> Core: add an is_event property to Item to match the one on Location

- worlds/adventure/__init__.py
https://github.com/ArchipelagoMW/Archipelago/issues/4563
Comparing generations before and after.
@JusticePS
> Adventure: Set Victory Condition Earlier

- WebHostLib/customserver.py
today's outage from occuring again
locally once with file and without file, didn't test the day tick-over
> WebHost: update cert file daily in customserver.py

- docs/apworld_dev_faq.md
add faq section for debugging corrupted metadata
made some corrupted metadata files to confirmed the causes/messages, but some of the descriptions should be double checked
> Doc: Add FAQ section for corrupted metadata debugging

- docs/adding games.md
Add completion condition requirement to world section, update icon size recommendation after the kivymd update (see https://github.com/ArchipelagoMW/Archipelago/pull/4815).
Proofread.
N/A
> Update to adding games.md based on kivymd

- docs/adding games.md
https://discord.com/channels/731205301247803413/1214608557077700720/1360925703021006959
:eyes:
> Doc: fix parse_yaml in adding games.md

- WebHostLib/templates/userContent.html
adds a blurb and link to user content pointing users to /session along with a why
http://localhost/user-content and clicked on the new link
> Webhost: add link to new session page

- WebHostLib/api/user.py
fixes get_players call in api/get_seeds
opened up http://localhost/api/get_seeds and it didn't crash
> Webhost: fix get_seeds api endpoint

- worlds/alttp/Rom.py
fixes LttP so it works with other games again
https://discord.com/channels/731205301247803413/731214280439103580/1363126411904160037
> LttP: fix generation if other games are involved

- worlds/checksfinder/docs/en_ChecksFinder.md
Changing description of locations to match current implementation of the game
was not
> Checksfinder: Fix the last remnant of outdated game description

- Launcher.py
tweaks the launcher header docstring to better represent current functionality
eyeballs
> Launcher: Update header docstring

- worlds/bomb_rush_cyberfunk/docs/setup_en.md
Was missing a step for manual install.
> BRC: Update setup guide

- worlds/kh2/docs/setup_en.md
Corrected some minor typos and added a clarification to the "common pitfalls" section.
I looked at the md in context and nothing broke
N/A
> Docs: Update worlds/kh2/docs/setup_en.md

- worlds/tunic/__init__.py
Makes UT work with that option.
Probably was backporting stuff and messed it up. Please merge https://github.com/ArchipelagoMW/Archipelago/pull/3761 at some point so I don't have to keep backporting stuff when issues arise.
> TUNIC: Fix UT issue with fewer shops option

- worlds/alttp/ItemPool.py
https://discord.com/channels/731205301247803413/1347270089979990046
with a print
> LttP: increase gen rate of pedestal goal with limited rupee pool

- worlds/AutoWorld.py
- worlds/factorio/__init__.py
the occasional test failure, hopefully
with unittests and looking if a spoiler with itemlink everything looks plausible
> Factorio: implement custom filler items

- worlds/tww/Options.py
- worlds/tww/docs/en_The Wind Waker.md
- worlds/tww/docs/setup_en.md
This is a small cleanup of TWW documentation, fixing some typos and modifying some things for grammar or clarity.
Edit: In addition, the description of one option is updated for clarity.
Read though the docs a couple times, double-checked the links.
N/A
> TWW: Documentation cleanup

- worlds/factorio/Client.py
- worlds/factorio/__init__.py
- worlds/factorio/settings.py
prevents users from opening infinite Factorio Clients
locally a bit
> Factorio: client cleanup and prevent process bomb

- docs/apworld_dev_faq.md
Just reread it and decided that the first entry felt a little abrupt, and the second one said settings instead of options.
> Docs: Minor wording changes in apworld_dev_faq.md

- worlds/subnautica/rules.py
updates Subnautica to use World API instead of MultiWorld API in several places in rules
I believe (one test gen and local unittests, actually)
> Subnautica: use less multiworld API

- worlds/noita/__init__.py
- worlds/noita/events.py
- worlds/noita/items.py
- worlds/noita/locations.py
- worlds/noita/regions.py
- worlds/noita/rules.py
- Use less imports from typing, using the lowercase versions instead
- Replace some old helpers with world helpers or other code
- Use more world helpers instead of the multiworld versions
Test gens, ran unit tests.
> Noita: Modernization refactor

- worlds/lufia2ac/test/__init__.py
- worlds/lufia2ac/test/bases.py
- worlds/lufia2ac/test/test_custom_item_pool.py
- worlds/lufia2ac/test/test_goal.py
> lufia2ac: rearrange tests to comply with new conventions

- worlds/stardew_valley/test/TestMonstersanity.py
Soft conflict from previous PRs, the import was wrong in a new file
Ran the tests, they now pass
> Stardew Valley: Fixed import bases

- CommonClient.py
adds docstrings (or moves comments to docstrings) and update typing for various ctx attributes
👀
> CommonClient: Add docs for attributes

- worlds/oot/docs/setup_de.md
- worlds/oot/docs/setup_en.md
- worlds/oot/docs/setup_fr.md
Updated setup guides to suggest Bizhawk version 2.10 and specify a US version of the ROM. I do not speak French of German, but got help from the translators thread in Discord.
> Update OOT Guides

- worlds/tww/__init__.py
This PR updates the class for the TWW patch file to the correct class (cf. #4331), fixing a generation issue.
Generated a seed and hosted a room with it with the webhost, downloaded the patch file, and successfully patched an ISO with it.
N/A
> TWW: Update patch class

- worlds/soe/docs/multiworld_en.md
Update docs - The client does not depend on Animation Frame anymore, so it can be backgrounded.
:eyes:
> SoE: remove outdated info from guide

- worlds/civ_6/docs/en_Civilization VI.md
- worlds/civ_6/docs/setup_en.md
This updates the information and setup pages for Civilization VI in an attempt to clarify things and make setting up the game easier for users. The setup page especially had many changes with the info page having minor changes.
The formatting was tested with local webhost and it seemed fine on my end.
None
> Civilization VI: Updated setup and info pages

- .github/workflows/build.yml
- test/hosting/__main__.py
- test/hosting/generate.py
- test/hosting/world.py
To allow https://github.com/ArchipelagoMW/Archipelago/pull/5177 to be merged
V6 seems like the simplest, most stable game after Clique in my estimation, always having exactly 20 locations & it doesn't look like it will receive more updates soon.
> Core: Replace Clique with V6 in unit tests

- docs/world api.md
- worlds/hk/__init__.py
- worlds/hk/docs/es_Hollow Knight.md
- worlds/hk/docs/setup_es.md
Adding a Spanish guide configuration for Hollow Knight
Markdown online test
> Docs: add spanish lenguage for HK

- worlds/tunic/test/__init__.py
- worlds/tunic/test/bases.py
- worlds/tunic/test/test_access.py
- worlds/tunic/test/test_combat.py
API Updates said that the test init should be empty, so now it's empty, and stuff got moved to bases.
Also used the opportunity to shuffle imports around and get rid of unused stuff.
Tests!
> TUNIC: Update tests per 0.6.2 api updates ping

- docs/webhost api.md
fix data types in webhost api doc now that #4944 is merged
👀
> Docs: Clean up SUUID in docs post 4944

- WebHostLib/templates/macros.html
https://github.com/ArchipelagoMW/Archipelago/issues/5212
locally once
> Factorio: fix rename of mod file leading to incompatibility with base game

- worlds/musedash/MuseDashData.py
- worlds/musedash/__init__.py
Updates to the Rhythm Master Collab. Also deprioritizes Music Sheets.
With Tests
> Muse Dash: Update to Rhythm Master Collab

- WebHostLib/stats.py
list unrecognized games as Other in stats on WebHost
locally a bit
> WebHost: list unrecognized games as Other in stats

- WebHostLib/__init__.py
slightly reduces the chances of future mistakes/reduces the code changes needed to make changes in the future/removes a line that could lead to git conflicts
locally, by visiting a couple pages and also printing the discovered modules to see it matches.
> WebHost: turn module discovery dynamic

- WebHostLib/misc.py
- WebHostLib/templates/siteMap.html
- test/general/__init__.py
- test/webhost/test_sitemap.py
/sitemap
a test for /index
test included
> WebHost: fix links on sitemap, switch to url_for and add test to prevent future breakage

- Utils.py
> Core: 0.6.4

- .github/workflows/build.yml
- .github/workflows/release.yml
Looked at the source code changes.
They don't provide any signature nor attestation, so I did not validate anything, however the release says the files were uploaded by github bot, so it should match what's in the repo.
Same as with the runtime: if this updates again within the next 6mo, I am gonna fork it.
CI
> CI: update appimagetool hash

- worlds/zillion/__init__.py
issue:
https://github.com/ArchipelagoMW/Archipelago/issues/4563
related:
https://github.com/ArchipelagoMW/Archipelago/pull/4565
played a game
> Zillion: move `completion_condition` definition earlier

- docs/apworld specification.md
adds doc for apworld manifest for #4516 
eyes after reading the code and utilizing the PR locally to get a better understanding of what needed to be documented
> Docs: for #4516 APWorld Manifest

- docs/world api.md
Did this on my phone while in the bathroom :)
> Docs: Add deprioritized to AP API doc

- worlds/musedash/MuseDashData.py
- worlds/musedash/__init__.py
- Adds support for Muse Radio FM106
- Changes an exception to an OptionError. As wanted by #5370
With tests. And this yaml file.
[Muse Dash.yaml](https://github.com/user-attachments/files/22046642/Muse.Dash.yaml)
> Muse Dash: Change Exception to Option Error and Update to Muse Radio FM106

- worlds/sc2/locations.py
- worlds/sc2/rules.py
Porting over the simple bugfixes and typhint fixes from PR #5423 now that it's been closed by Ziktofel.
Most changes are adding parentheses to call functions in boolean logic in locations.py; otherwise they were always evaluated as true. Also fixed several missing type annotations in rules.py and several incorrect ones. This was all done by just running mypy on locations.py, which lit up all these issues.
Additionally fixed a couple of logic issues with discussion from the other devs in the #sc2-dev thread. I tried to keep the changes conservative in the interest of not spawning another great debate; it's well-known the current logic is overly restrictive but loosening it up somehow always takes more discussion than anticipated. I tried to limit myself to situations where the composition …
> SC2: Logic bugfixes

- worlds/factorio/Client.py
> fix punctuation

- worlds/pokemon_rb/__init__.py
This does:
- Removes outdated slot data not needed anymore for the tracker
- Add two minor slot data so the poptracker pack can track better
- Wasn't
> Update slotdata for Pokémon RB

- worlds/bumpstik/archipelago.json
Add archipelago.json manifest to Bumper Stickers
n/a
n/a
> bumpstik: Create manifest

- worlds/witness/__init__.py
Self-explanatory
Tested:
Ctrl+Shift+F for each thing in slot_data on client side, these two didn't come up (also verified in my brain that it makes sense :D)
> The Witness: Remove two things from slot_data that nothing uses anymore

- worlds/kdl3/__init__.py
- worlds/kdl3/rules.py
- worlds/mm2/__init__.py
#4565 
Generated a multi with the two games
> KDL3, MM2: set goal condition before generate basic

- test/general/__init__.py
Some people have made unittest test cases where they set up multiworlds, and wanted to use setup_multiworld for it. However, if you want non-default options in your test, you have to set them after the fact, which is a bit dirty. So, this PR adds an `options` kwarg to setup_multiworld that lets you specify the options you want.
> Core: Add an "options" arg to setup_multiworld so that non-default options can be set in it

- WebHostLib/static/assets/faq/en.md
Someone came in thinking "I want to add a game to the Archipelago randomizer" meant making a randomizer game. I think this misinterpretation is very understandable. So this should be clarified.
> [Website docs] Update wording of "adding a game to archipelago" section

- worlds/shorthike/docs/setup_en.md
Adds a link to the mod installer and makes it clearer the instructions are on the readme there
> Short Hike: improve setup guide docs

- worlds/celeste64/LICENSE
- worlds/celeste64/archipelago.json
- worlds/celeste_open_world/LICENSE
- worlds/celeste_open_world/archipelago.json
- worlds/dkc3/LICENSE
- worlds/dkc3/archipelago.json
- worlds/sa2b/LICENSE
- worlds/sa2b/archipelago.json
- worlds/smw/LICENSE
- worlds/smw/archipelago.json
Adds APWorld manifests for my 5 games.
It wasn't.
> SA2B, DKC3, SMW, Celeste 64, Celeste (Open World): Manifest manifests
